In [1]:
import pandas as pd
from constants import DATA_PATH, EOS_FILE, SENTINEL_FILE

sentinel = pd.read_csv(DATA_PATH / SENTINEL_FILE)
eos = pd.read_csv(DATA_PATH / EOS_FILE)

In [2]:
sentinel = sentinel[sentinel['SM1 (%)'] != 50]
eos = eos[eos['SM1 (%)'] != 50]

In [3]:
from constants import X_cols_eos, X_cols_sentinel, y_col

X_sentinel = sentinel[X_cols_sentinel].values
X_eos = eos[X_cols_eos].values

y_sentinel = sentinel[y_col].values
y_eos = eos[y_col].values

In [4]:
import tensorflow as tf

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1778435050.742134 2605029 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1778435050.771032 2605029 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1778435051.495586 2605029 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

In [5]:
n_features = X_eos.shape[1]

models = {
#     "16, 1": tf.keras.Sequential([
#     # Input layer
#     tf.keras.Input(shape=(n_features, )),
#     tf.keras.layers.Dense(16, activation='relu'),
#     tf.keras.layers.Dense(1)
# ]),
#     "8, 1": tf.keras.Sequential([
#     # Input layer
#     tf.keras.Input(shape=(n_features, )),
#     tf.keras.layers.Dense(8, activation='relu'),
#     tf.keras.layers.Dense(1)
# ]),
#     "2, 1": tf.keras.Sequential([
#     # Input layer
#     tf.keras.Input(shape=(n_features, )),
#     tf.keras.layers.Dense(2, activation='relu'),
#     tf.keras.layers.Dense(1)
# ]),
#     "4, 1": tf.keras.Sequential([
#     # Input layer
#     tf.keras.Input(shape=(n_features, )),
#     tf.keras.layers.Dense(4, activation='relu'),
#     tf.keras.layers.Dense(1)
# ]),
    "16, Dropout, 8, Dropout": tf.keras.Sequential([
    # Input layer
    tf.keras.Input(shape=(n_features, )),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dropout(0.09),
    tf.keras.layers.Dense(8, activation='relu'),
    tf.keras.layers.Dropout(0.09),
    tf.keras.layers.Dense(1)
]),
    "16, Dropout": tf.keras.Sequential([
    # Input layer
    tf.keras.Input(shape=(n_features, )),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dropout(0.1),
    tf.keras.layers.Dense(1)
])
}

I0000 00:00:1778435052.372018 2605029 gpu_device.cc:2043] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 6157 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.9

In [6]:
from model_experiments import ConformalizedQuantileExperiment

eos_exp = ConformalizedQuantileExperiment(X_eos, y_eos, satellite="EOS-04")

eos_results = eos_exp.run_ann_tuning_experiment(models["16, Dropout, 8, Dropout"])

Results → /home/lmaosid/Desktop/major/experiments/classification_new_data/output/pi_estimation_uncensored
Results → /home/lmaosid/Desktop/major/experiments/classification_new_data/output/conformal_results_uncensored

=== Starting Tau Hyperparameter Tuning for EOS-04 ===

Running configuration: Low:0.01 - High:0.96

Upper model:   0%|          | 0/100 [00:00<?, ?epoch/s]

I0000 00:00:1778435053.594948 2605134 service.cc:153] XLA service 0x7f7e44032db0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1778435053.594970 2605134 service.cc:161]   StreamExecutor [0]: NVIDIA GeForce RTX 4060 Laptop GPU, Compute Capability 8.9 (Driver: 13.2.0; Runtime: 12.4.0; Toolkit: 12.5.0; DNN: 9.3.0)
I0000 00:00:1778435053.610657 2605134 dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
I0000 00:00:1778435053.709756 2605134 cuda_dnn.cc:461] Loaded cuDNN version 90300
I0000 00:00:1778435053.741388 2605134 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_1829__.19

I0000 00:00:1778435055.059871 2605134 device_compiler.h:208] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
I0000 00:00:1778435055.194882 2605127 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_1829__.19

Upper model:   0%|          | 0/100 [00:03<?, ?epoch/s, loss=17.3959, val_loss=15.9908]

Upper model:   1%|          | 1/100 [00:03<06:09,  3.73s/epoch, loss=17.3959, val_loss=15.9908]

Upper model:   1%|          | 1/100 [00:03<06:09,  3.73s/epoch, loss=17.3168, val_loss=15.9076]

Upper model:   2%|▏         | 2/100 [00:03<06:05,  3.73s/epoch, loss=17.2270, val_loss=15.8171]

Upper model:   3%|▎         | 3/100 [00:03<01:38,  1.02s/epoch, loss=17.2270, val_loss=15.8171]

Upper model:   3%|▎         | 3/100 [00:03<01:38,  1.02s/epoch, loss=17.1414, val_loss=15.7181]

Upper model:   4%|▍         | 4/100 [00:03<01:37,  1.02s/epoch, loss=17.0253, val_loss=15.6095]

Upper model:   5%|▌         | 5/100 [00:03<00:49,  1.90epoch/s, loss=17.0253, val_loss=15.6095]

Upper model:   5%|▌         | 5/100 [00:04<00:49,  1.90epoch/s, loss=16.9120, val_loss=15.4890]

Upper model:   6%|▌         | 6/100 [00:04<00:49,  1.90epoch/s, loss=16.7921, val_loss=15.3543]

Upper model:   7%|▋         | 7/100 [00:04<00:30,  3.01epoch/s, loss=16.7921, val_loss=15.3543]

Upper model:   7%|▋         | 7/100 [00:04<00:30,  3.01epoch/s, loss=16.6492, val_loss=15.2049]

Upper model:   8%|▊         | 8/100 [00:04<00:30,  3.01epoch/s, loss=16.4909, val_loss=15.0425]

Upper model:   9%|▉         | 9/100 [00:04<00:21,  4.32epoch/s, loss=16.4909, val_loss=15.0425]

Upper model:   9%|▉         | 9/100 [00:04<00:21,  4.32epoch/s, loss=16.3329, val_loss=14.8700]

Upper model:  10%|█         | 10/100 [00:04<00:20,  4.32epoch/s, loss=16.1520, val_loss=14.6877]

Upper model:  11%|█         | 11/100 [00:04<00:15,  5.77epoch/s, loss=16.1520, val_loss=14.6877]

Upper model:  11%|█         | 11/100 [00:04<00:15,  5.77epoch/s, loss=15.9515, val_loss=14.4945]

Upper model:  12%|█▏        | 12/100 [00:04<00:15,  5.77epoch/s, loss=15.7650, val_loss=14.2892]

Upper model:  13%|█▎        | 13/100 [00:04<00:12,  7.21epoch/s, loss=15.7650, val_loss=14.2892]

Upper model:  13%|█▎        | 13/100 [00:04<00:12,  7.21epoch/s, loss=15.5471, val_loss=14.0710]

Upper model:  14%|█▍        | 14/100 [00:04<00:11,  7.21epoch/s, loss=15.3005, val_loss=13.8369]

Upper model:  15%|█▌        | 15/100 [00:04<00:09,  8.63epoch/s, loss=15.3005, val_loss=13.8369]

Upper model:  15%|█▌        | 15/100 [00:04<00:09,  8.63epoch/s, loss=15.0545, val_loss=13.5878]

Upper model:  16%|█▌        | 16/100 [00:04<00:09,  8.63epoch/s, loss=14.7821, val_loss=13.3222]

Upper model:  17%|█▋        | 17/100 [00:04<00:08, 10.04epoch/s, loss=14.7821, val_loss=13.3222]

Upper model:  17%|█▋        | 17/100 [00:04<00:08, 10.04epoch/s, loss=14.5024, val_loss=13.0396]

Upper model:  18%|█▊        | 18/100 [00:04<00:08, 10.04epoch/s, loss=14.2147, val_loss=12.7394]

Upper model:  19%|█▉        | 19/100 [00:04<00:07, 11.01epoch/s, loss=14.2147, val_loss=12.7394]

Upper model:  19%|█▉        | 19/100 [00:04<00:07, 11.01epoch/s, loss=13.8945, val_loss=12.4247]

Upper model:  20%|██        | 20/100 [00:05<00:07, 11.01epoch/s, loss=13.5911, val_loss=12.0923]

Upper model:  21%|██        | 21/100 [00:05<00:06, 12.21epoch/s, loss=13.5911, val_loss=12.0923]

Upper model:  21%|██        | 21/100 [00:05<00:06, 12.21epoch/s, loss=13.2374, val_loss=11.7449]

Upper model:  22%|██▏       | 22/100 [00:05<00:06, 12.21epoch/s, loss=12.8731, val_loss=11.3846]

Upper model:  23%|██▎       | 23/100 [00:05<00:05, 13.09epoch/s, loss=12.8731, val_loss=11.3846]

Upper model:  23%|██▎       | 23/100 [00:05<00:05, 13.09epoch/s, loss=12.5087, val_loss=11.0126]

Upper model:  24%|██▍       | 24/100 [00:05<00:05, 13.09epoch/s, loss=12.1116, val_loss=10.6284]

Upper model:  25%|██▌       | 25/100 [00:05<00:05, 13.74epoch/s, loss=12.1116, val_loss=10.6284]

Upper model:  25%|██▌       | 25/100 [00:05<00:05, 13.74epoch/s, loss=11.6802, val_loss=10.2306]

Upper model:  26%|██▌       | 26/100 [00:05<00:05, 13.74epoch/s, loss=11.3178, val_loss=9.8211]

Upper model:  27%|██▋       | 27/100 [00:05<00:05, 14.10epoch/s, loss=11.3178, val_loss=9.8211]

Upper model:  27%|██▋       | 27/100 [00:05<00:05, 14.10epoch/s, loss=10.9348, val_loss=9.3991]

Upper model:  28%|██▊       | 28/100 [00:05<00:05, 14.10epoch/s, loss=10.5080, val_loss=8.9787]

Upper model:  29%|██▉       | 29/100 [00:05<00:04, 14.33epoch/s, loss=10.5080, val_loss=8.9787]

Upper model:  29%|██▉       | 29/100 [00:05<00:04, 14.33epoch/s, loss=10.1083, val_loss=8.5611]

Upper model:  30%|███       | 30/100 [00:05<00:04, 14.33epoch/s, loss=9.6426, val_loss=8.1402]

Upper model:  31%|███       | 31/100 [00:05<00:04, 14.79epoch/s, loss=9.6426, val_loss=8.1402]

Upper model:  31%|███       | 31/100 [00:05<00:04, 14.79epoch/s, loss=9.3075, val_loss=7.7182]

Upper model:  32%|███▏      | 32/100 [00:05<00:04, 14.79epoch/s, loss=8.8388, val_loss=7.2963]

Upper model:  33%|███▎      | 33/100 [00:05<00:04, 14.97epoch/s, loss=8.8388, val_loss=7.2963]

Upper model:  33%|███▎      | 33/100 [00:05<00:04, 14.97epoch/s, loss=8.4087, val_loss=6.8883]

Upper model:  34%|███▍      | 34/100 [00:05<00:04, 14.97epoch/s, loss=8.0843, val_loss=6.4856]

Upper model:  35%|███▌      | 35/100 [00:05<00:04, 14.53epoch/s, loss=8.0843, val_loss=6.4856]

Upper model:  35%|███▌      | 35/100 [00:06<00:04, 14.53epoch/s, loss=7.6179, val_loss=6.1015]

Upper model:  36%|███▌      | 36/100 [00:06<00:04, 14.53epoch/s, loss=7.2878, val_loss=5.7316]

Upper model:  37%|███▋      | 37/100 [00:06<00:04, 14.36epoch/s, loss=7.2878, val_loss=5.7316]

Upper model:  37%|███▋      | 37/100 [00:06<00:04, 14.36epoch/s, loss=6.9030, val_loss=5.3753]

Upper model:  38%|███▊      | 38/100 [00:06<00:04, 14.36epoch/s, loss=6.6762, val_loss=5.0352]

Upper model:  39%|███▉      | 39/100 [00:06<00:04, 14.64epoch/s, loss=6.6762, val_loss=5.0352]

Upper model:  39%|███▉      | 39/100 [00:06<00:04, 14.64epoch/s, loss=6.2122, val_loss=4.7154]

Upper model:  40%|████      | 40/100 [00:06<00:04, 14.64epoch/s, loss=5.8943, val_loss=4.4153]

Upper model:  41%|████      | 41/100 [00:06<00:03, 14.95epoch/s, loss=5.8943, val_loss=4.4153]

Upper model:  41%|████      | 41/100 [00:06<00:03, 14.95epoch/s, loss=5.5464, val_loss=4.1160]

Upper model:  42%|████▏     | 42/100 [00:06<00:03, 14.95epoch/s, loss=5.3308, val_loss=3.8288]

Upper model:  43%|████▎     | 43/100 [00:06<00:03, 14.85epoch/s, loss=5.3308, val_loss=3.8288]

Upper model:  43%|████▎     | 43/100 [00:06<00:03, 14.85epoch/s, loss=4.8292, val_loss=3.5584]

Upper model:  44%|████▍     | 44/100 [00:06<00:03, 14.85epoch/s, loss=4.6454, val_loss=3.3164]

Upper model:  45%|████▌     | 45/100 [00:06<00:03, 14.50epoch/s, loss=4.6454, val_loss=3.3164]

Upper model:  45%|████▌     | 45/100 [00:06<00:03, 14.50epoch/s, loss=4.4310, val_loss=3.0815]

Upper model:  46%|████▌     | 46/100 [00:06<00:03, 14.50epoch/s, loss=4.0553, val_loss=2.8486]

Upper model:  47%|████▋     | 47/100 [00:06<00:03, 14.25epoch/s, loss=4.0553, val_loss=2.8486]

Upper model:  47%|████▋     | 47/100 [00:06<00:03, 14.25epoch/s, loss=3.9052, val_loss=2.6214]

Upper model:  48%|████▊     | 48/100 [00:06<00:03, 14.25epoch/s, loss=3.5731, val_loss=2.4024]

Upper model:  49%|████▉     | 49/100 [00:06<00:03, 14.38epoch/s, loss=3.5731, val_loss=2.4024]

Upper model:  49%|████▉     | 49/100 [00:07<00:03, 14.38epoch/s, loss=3.4321, val_loss=2.1916]

Upper model:  50%|█████     | 50/100 [00:07<00:03, 14.38epoch/s, loss=3.2641, val_loss=2.0092]

Upper model:  51%|█████     | 51/100 [00:07<00:03, 14.62epoch/s, loss=3.2641, val_loss=2.0092]

Upper model:  51%|█████     | 51/100 [00:07<00:03, 14.62epoch/s, loss=2.9876, val_loss=1.8394]

Upper model:  52%|█████▏    | 52/100 [00:07<00:03, 14.62epoch/s, loss=2.8424, val_loss=1.6904]

Upper model:  53%|█████▎    | 53/100 [00:07<00:03, 14.49epoch/s, loss=2.8424, val_loss=1.6904]

Upper model:  53%|█████▎    | 53/100 [00:07<00:03, 14.49epoch/s, loss=2.7899, val_loss=1.5675]

Upper model:  54%|█████▍    | 54/100 [00:07<00:03, 14.49epoch/s, loss=2.6542, val_loss=1.4538]

Upper model:  55%|█████▌    | 55/100 [00:07<00:03, 14.21epoch/s, loss=2.6542, val_loss=1.4538]

Upper model:  55%|█████▌    | 55/100 [00:07<00:03, 14.21epoch/s, loss=2.3630, val_loss=1.3495]

Upper model:  56%|█████▌    | 56/100 [00:07<00:03, 14.21epoch/s, loss=2.2217, val_loss=1.2513]

Upper model:  57%|█████▋    | 57/100 [00:07<00:03, 14.16epoch/s, loss=2.2217, val_loss=1.2513]

Upper model:  57%|█████▋    | 57/100 [00:07<00:03, 14.16epoch/s, loss=2.1699, val_loss=1.1694]

Upper model:  58%|█████▊    | 58/100 [00:07<00:02, 14.16epoch/s, loss=2.1187, val_loss=1.1083]

Upper model:  59%|█████▉    | 59/100 [00:07<00:02, 13.98epoch/s, loss=2.1187, val_loss=1.1083]

Upper model:  59%|█████▉    | 59/100 [00:07<00:02, 13.98epoch/s, loss=2.0044, val_loss=1.0603]

Upper model:  60%|██████    | 60/100 [00:07<00:02, 13.98epoch/s, loss=1.8367, val_loss=1.0177]

Upper model:  61%|██████    | 61/100 [00:07<00:02, 14.08epoch/s, loss=1.8367, val_loss=1.0177]

Upper model:  61%|██████    | 61/100 [00:07<00:02, 14.08epoch/s, loss=1.9002, val_loss=0.9858]

Upper model:  62%|██████▏   | 62/100 [00:07<00:02, 14.08epoch/s, loss=1.8278, val_loss=0.9591]

Upper model:  63%|██████▎   | 63/100 [00:07<00:02, 14.29epoch/s, loss=1.8278, val_loss=0.9591]

Upper model:  63%|██████▎   | 63/100 [00:07<00:02, 14.29epoch/s, loss=1.8071, val_loss=0.9362]

Upper model:  64%|██████▍   | 64/100 [00:08<00:02, 14.29epoch/s, loss=1.7165, val_loss=0.9156]

Upper model:  65%|██████▌   | 65/100 [00:08<00:02, 14.51epoch/s, loss=1.7165, val_loss=0.9156]

Upper model:  65%|██████▌   | 65/100 [00:08<00:02, 14.51epoch/s, loss=1.6610, val_loss=0.8981]

Upper model:  66%|██████▌   | 66/100 [00:08<00:02, 14.51epoch/s, loss=1.6496, val_loss=0.8857]

Upper model:  67%|██████▋   | 67/100 [00:08<00:02, 15.01epoch/s, loss=1.6496, val_loss=0.8857]

Upper model:  67%|██████▋   | 67/100 [00:08<00:02, 15.01epoch/s, loss=1.6959, val_loss=0.8750]

Upper model:  68%|██████▊   | 68/100 [00:08<00:02, 15.01epoch/s, loss=1.4835, val_loss=0.8691]

Upper model:  69%|██████▉   | 69/100 [00:08<00:02, 15.41epoch/s, loss=1.4835, val_loss=0.8691]

Upper model:  69%|██████▉   | 69/100 [00:08<00:02, 15.41epoch/s, loss=1.5216, val_loss=0.8633]

Upper model:  70%|███████   | 70/100 [00:08<00:01, 15.41epoch/s, loss=1.5023, val_loss=0.8592]

Upper model:  71%|███████   | 71/100 [00:08<00:01, 15.65epoch/s, loss=1.5023, val_loss=0.8592]

Upper model:  71%|███████   | 71/100 [00:08<00:01, 15.65epoch/s, loss=1.5177, val_loss=0.8571]

Upper model:  72%|███████▏  | 72/100 [00:08<00:01, 15.65epoch/s, loss=1.4828, val_loss=0.8557]

Upper model:  73%|███████▎  | 73/100 [00:08<00:01, 16.19epoch/s, loss=1.4828, val_loss=0.8557]

Upper model:  73%|███████▎  | 73/100 [00:08<00:01, 16.19epoch/s, loss=1.4139, val_loss=0.8566]

Upper model:  74%|███████▍  | 74/100 [00:08<00:01, 16.19epoch/s, loss=1.3973, val_loss=0.8578]

Upper model:  75%|███████▌  | 75/100 [00:08<00:01, 16.33epoch/s, loss=1.3973, val_loss=0.8578]

Upper model:  75%|███████▌  | 75/100 [00:08<00:01, 16.33epoch/s, loss=1.4628, val_loss=0.8588]

Upper model:  76%|███████▌  | 76/100 [00:08<00:01, 16.33epoch/s, loss=1.4406, val_loss=0.8598]

Upper model:  77%|███████▋  | 77/100 [00:08<00:01, 16.74epoch/s, loss=1.4406, val_loss=0.8598]

Upper model:  77%|███████▋  | 77/100 [00:08<00:01, 16.74epoch/s, loss=1.3396, val_loss=0.8607]

Upper model:  78%|███████▊  | 78/100 [00:08<00:01, 16.74epoch/s, loss=1.4330, val_loss=0.8613]

Upper model:  79%|███████▉  | 79/100 [00:08<00:01, 16.84epoch/s, loss=1.4330, val_loss=0.8613]

Upper model:  79%|███████▉  | 79/100 [00:08<00:01, 16.84epoch/s, loss=1.5118, val_loss=0.8624]

Upper model:  80%|████████  | 80/100 [00:09<00:01, 16.84epoch/s, loss=1.3493, val_loss=0.8637]

Upper model:  81%|████████  | 81/100 [00:09<00:01, 16.62epoch/s, loss=1.3493, val_loss=0.8637]

Upper model:  81%|████████  | 81/100 [00:09<00:01, 16.62epoch/s, loss=1.4004, val_loss=0.8655]

Upper model:  82%|████████▏ | 82/100 [00:09<00:01, 16.62epoch/s, loss=1.3548, val_loss=0.8673]

Upper model:  83%|████████▎ | 83/100 [00:09<00:01, 15.95epoch/s, loss=1.3548, val_loss=0.8673]

Upper model:  83%|████████▎ | 83/100 [00:09<00:01,  9.06epoch/s, loss=1.3548, val_loss=0.8673]

Lower model:   0%|          | 0/100 [00:00<?, ?epoch/s]

I0000 00:00:1778435062.745600 2605127 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_7999__.19

I0000 00:00:1778435063.547139 2605134 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_7999__.19

Lower model:   0%|          | 0/100 [00:02<?, ?epoch/s, loss=0.1814, val_loss=0.1669]

Lower model:   1%|          | 1/100 [00:02<03:39,  2.21s/epoch, loss=0.1814, val_loss=0.1669]

Lower model:   1%|          | 1/100 [00:02<03:39,  2.21s/epoch, loss=0.1810, val_loss=0.1665]

Lower model:   2%|▏         | 2/100 [00:02<03:36,  2.21s/epoch, loss=0.1806, val_loss=0.1661]

Lower model:   3%|▎         | 3/100 [00:02<01:00,  1.61epoch/s, loss=0.1806, val_loss=0.1661]

Lower model:   3%|▎         | 3/100 [00:02<01:00,  1.61epoch/s, loss=0.1801, val_loss=0.1656]

Lower model:   4%|▍         | 4/100 [00:02<00:59,  1.61epoch/s, loss=0.1795, val_loss=0.1651]

Lower model:   5%|▌         | 5/100 [00:02<00:31,  3.01epoch/s, loss=0.1795, val_loss=0.1651]

Lower model:   5%|▌         | 5/100 [00:02<00:31,  3.01epoch/s, loss=0.1790, val_loss=0.1645]

Lower model:   6%|▌         | 6/100 [00:02<00:31,  3.01epoch/s, loss=0.1783, val_loss=0.1638]

Lower model:   7%|▋         | 7/100 [00:02<00:20,  4.63epoch/s, loss=0.1783, val_loss=0.1638]

Lower model:   7%|▋         | 7/100 [00:02<00:20,  4.63epoch/s, loss=0.1776, val_loss=0.1631]

Lower model:   8%|▊         | 8/100 [00:02<00:19,  4.63epoch/s, loss=0.1770, val_loss=0.1625]

Lower model:   9%|▉         | 9/100 [00:02<00:14,  6.37epoch/s, loss=0.1770, val_loss=0.1625]

Lower model:   9%|▉         | 9/100 [00:02<00:14,  6.37epoch/s, loss=0.1763, val_loss=0.1617]

Lower model:  10%|█         | 10/100 [00:02<00:14,  6.37epoch/s, loss=0.1755, val_loss=0.1610]

Lower model:  11%|█         | 11/100 [00:02<00:10,  8.16epoch/s, loss=0.1755, val_loss=0.1610]

Lower model:  11%|█         | 11/100 [00:02<00:10,  8.16epoch/s, loss=0.1746, val_loss=0.1602]

Lower model:  12%|█▏        | 12/100 [00:02<00:10,  8.16epoch/s, loss=0.1738, val_loss=0.1593]

Lower model:  13%|█▎        | 13/100 [00:02<00:08,  9.83epoch/s, loss=0.1738, val_loss=0.1593]

Lower model:  13%|█▎        | 13/100 [00:02<00:08,  9.83epoch/s, loss=0.1730, val_loss=0.1584]

Lower model:  14%|█▍        | 14/100 [00:03<00:08,  9.83epoch/s, loss=0.1721, val_loss=0.1575]

Lower model:  15%|█▌        | 15/100 [00:03<00:07, 11.43epoch/s, loss=0.1721, val_loss=0.1575]

Lower model:  15%|█▌        | 15/100 [00:03<00:07, 11.43epoch/s, loss=0.1713, val_loss=0.1565]

Lower model:  16%|█▌        | 16/100 [00:03<00:07, 11.43epoch/s, loss=0.1701, val_loss=0.1554]

Lower model:  17%|█▋        | 17/100 [00:03<00:06, 12.54epoch/s, loss=0.1701, val_loss=0.1554]

Lower model:  17%|█▋        | 17/100 [00:03<00:06, 12.54epoch/s, loss=0.1690, val_loss=0.1542]

Lower model:  18%|█▊        | 18/100 [00:03<00:06, 12.54epoch/s, loss=0.1685, val_loss=0.1531]

Lower model:  19%|█▉        | 19/100 [00:03<00:05, 13.66epoch/s, loss=0.1685, val_loss=0.1531]

Lower model:  19%|█▉        | 19/100 [00:03<00:05, 13.66epoch/s, loss=0.1678, val_loss=0.1519]

Lower model:  20%|██        | 20/100 [00:03<00:05, 13.66epoch/s, loss=0.1661, val_loss=0.1507]

Lower model:  21%|██        | 21/100 [00:03<00:05, 14.56epoch/s, loss=0.1661, val_loss=0.1507]

Lower model:  21%|██        | 21/100 [00:03<00:05, 14.56epoch/s, loss=0.1665, val_loss=0.1496]

Lower model:  22%|██▏       | 22/100 [00:03<00:05, 14.56epoch/s, loss=0.1660, val_loss=0.1487]

Lower model:  23%|██▎       | 23/100 [00:03<00:04, 15.43epoch/s, loss=0.1660, val_loss=0.1487]

Lower model:  23%|██▎       | 23/100 [00:03<00:04, 15.43epoch/s, loss=0.1665, val_loss=0.1479]

Lower model:  24%|██▍       | 24/100 [00:03<00:04, 15.43epoch/s, loss=0.1646, val_loss=0.1473]

Lower model:  25%|██▌       | 25/100 [00:03<00:04, 15.27epoch/s, loss=0.1646, val_loss=0.1473]

Lower model:  25%|██▌       | 25/100 [00:03<00:04, 15.27epoch/s, loss=0.1661, val_loss=0.1467]

Lower model:  26%|██▌       | 26/100 [00:03<00:04, 15.27epoch/s, loss=0.1647, val_loss=0.1462]

Lower model:  27%|██▋       | 27/100 [00:03<00:04, 15.86epoch/s, loss=0.1647, val_loss=0.1462]

Lower model:  27%|██▋       | 27/100 [00:03<00:04, 15.86epoch/s, loss=0.1648, val_loss=0.1459]

Lower model:  28%|██▊       | 28/100 [00:03<00:04, 15.86epoch/s, loss=0.1658, val_loss=0.1456]

Lower model:  29%|██▉       | 29/100 [00:03<00:04, 16.04epoch/s, loss=0.1658, val_loss=0.1456]

Lower model:  29%|██▉       | 29/100 [00:03<00:04, 16.04epoch/s, loss=0.1657, val_loss=0.1456]

Lower model:  30%|███       | 30/100 [00:04<00:04, 16.04epoch/s, loss=0.1642, val_loss=0.1455]

Lower model:  31%|███       | 31/100 [00:04<00:04, 16.51epoch/s, loss=0.1642, val_loss=0.1455]

Lower model:  31%|███       | 31/100 [00:04<00:04, 16.51epoch/s, loss=0.1653, val_loss=0.1455]

Lower model:  32%|███▏      | 32/100 [00:04<00:04, 16.51epoch/s, loss=0.1662, val_loss=0.1456]

Lower model:  33%|███▎      | 33/100 [00:04<00:04, 16.51epoch/s, loss=0.1662, val_loss=0.1456]

Lower model:  33%|███▎      | 33/100 [00:04<00:04, 16.51epoch/s, loss=0.1641, val_loss=0.1457]

Lower model:  34%|███▍      | 34/100 [00:04<00:03, 16.51epoch/s, loss=0.1638, val_loss=0.1455]

Lower model:  35%|███▌      | 35/100 [00:04<00:03, 16.74epoch/s, loss=0.1638, val_loss=0.1455]

Lower model:  35%|███▌      | 35/100 [00:04<00:03, 16.74epoch/s, loss=0.1637, val_loss=0.1450]

Lower model:  36%|███▌      | 36/100 [00:04<00:03, 16.74epoch/s, loss=0.1635, val_loss=0.1449]

Lower model:  37%|███▋      | 37/100 [00:04<00:03, 17.10epoch/s, loss=0.1635, val_loss=0.1449]

Lower model:  37%|███▋      | 37/100 [00:04<00:03, 17.10epoch/s, loss=0.1643, val_loss=0.1446]

Lower model:  38%|███▊      | 38/100 [00:04<00:03, 17.10epoch/s, loss=0.1650, val_loss=0.1448]

Lower model:  39%|███▉      | 39/100 [00:04<00:03, 16.53epoch/s, loss=0.1650, val_loss=0.1448]

Lower model:  39%|███▉      | 39/100 [00:04<00:03, 16.53epoch/s, loss=0.1624, val_loss=0.1443]

Lower model:  40%|████      | 40/100 [00:04<00:03, 16.53epoch/s, loss=0.1648, val_loss=0.1438]

Lower model:  41%|████      | 41/100 [00:04<00:03, 15.26epoch/s, loss=0.1648, val_loss=0.1438]

Lower model:  41%|████      | 41/100 [00:04<00:03, 15.26epoch/s, loss=0.1652, val_loss=0.1438]

Lower model:  42%|████▏     | 42/100 [00:04<00:03, 15.26epoch/s, loss=0.1649, val_loss=0.1439]

Lower model:  43%|████▎     | 43/100 [00:04<00:03, 15.76epoch/s, loss=0.1649, val_loss=0.1439]

Lower model:  43%|████▎     | 43/100 [00:04<00:03, 15.76epoch/s, loss=0.1617, val_loss=0.1439]

Lower model:  44%|████▍     | 44/100 [00:04<00:03, 15.76epoch/s, loss=0.1647, val_loss=0.1439]

Lower model:  45%|████▌     | 45/100 [00:04<00:03, 15.68epoch/s, loss=0.1647, val_loss=0.1439]

Lower model:  45%|████▌     | 45/100 [00:04<00:03, 15.68epoch/s, loss=0.1631, val_loss=0.1440]

Lower model:  46%|████▌     | 46/100 [00:05<00:03, 15.68epoch/s, loss=0.1636, val_loss=0.1439]

Lower model:  47%|████▋     | 47/100 [00:05<00:03, 15.93epoch/s, loss=0.1636, val_loss=0.1439]

Lower model:  47%|████▋     | 47/100 [00:05<00:03, 15.93epoch/s, loss=0.1622, val_loss=0.1437]

Lower model:  48%|████▊     | 48/100 [00:05<00:03, 15.93epoch/s, loss=0.1626, val_loss=0.1437]

Lower model:  49%|████▉     | 49/100 [00:05<00:03, 16.27epoch/s, loss=0.1626, val_loss=0.1437]

Lower model:  49%|████▉     | 49/100 [00:05<00:03, 16.27epoch/s, loss=0.1629, val_loss=0.1436]

Lower model:  50%|█████     | 50/100 [00:05<00:03, 16.27epoch/s, loss=0.1628, val_loss=0.1437]

Lower model:  51%|█████     | 51/100 [00:05<00:02, 16.37epoch/s, loss=0.1628, val_loss=0.1437]

Lower model:  51%|█████     | 51/100 [00:05<00:02, 16.37epoch/s, loss=0.1622, val_loss=0.1438]

Lower model:  52%|█████▏    | 52/100 [00:05<00:02, 16.37epoch/s, loss=0.1619, val_loss=0.1438]

Lower model:  53%|█████▎    | 53/100 [00:05<00:02, 16.17epoch/s, loss=0.1619, val_loss=0.1438]

Lower model:  53%|█████▎    | 53/100 [00:05<00:02, 16.17epoch/s, loss=0.1632, val_loss=0.1436]

Lower model:  54%|█████▍    | 54/100 [00:05<00:02, 16.17epoch/s, loss=0.1630, val_loss=0.1437]

Lower model:  55%|█████▌    | 55/100 [00:05<00:02, 16.30epoch/s, loss=0.1630, val_loss=0.1437]

Lower model:  55%|█████▌    | 55/100 [00:05<00:02, 16.30epoch/s, loss=0.1620, val_loss=0.1437]

Lower model:  56%|█████▌    | 56/100 [00:05<00:02, 16.30epoch/s, loss=0.1632, val_loss=0.1436]

Lower model:  57%|█████▋    | 57/100 [00:05<00:02, 16.00epoch/s, loss=0.1632, val_loss=0.1436]

Lower model:  57%|█████▋    | 57/100 [00:05<00:02, 16.00epoch/s, loss=0.1619, val_loss=0.1436]

Lower model:  58%|█████▊    | 58/100 [00:05<00:02, 16.00epoch/s, loss=0.1639, val_loss=0.1435]

Lower model:  59%|█████▉    | 59/100 [00:05<00:02, 16.03epoch/s, loss=0.1639, val_loss=0.1435]

Lower model:  59%|█████▉    | 59/100 [00:05<00:02, 16.03epoch/s, loss=0.1626, val_loss=0.1435]

Lower model:  60%|██████    | 60/100 [00:05<00:02, 16.03epoch/s, loss=0.1626, val_loss=0.1435]

Lower model:  61%|██████    | 61/100 [00:05<00:02, 16.55epoch/s, loss=0.1626, val_loss=0.1435]

Lower model:  61%|██████    | 61/100 [00:05<00:02, 16.55epoch/s, loss=0.1628, val_loss=0.1435]

Lower model:  62%|██████▏   | 62/100 [00:05<00:02, 16.55epoch/s, loss=0.1627, val_loss=0.1435]

Lower model:  63%|██████▎   | 63/100 [00:05<00:02, 16.79epoch/s, loss=0.1627, val_loss=0.1435]

Lower model:  63%|██████▎   | 63/100 [00:06<00:02, 16.79epoch/s, loss=0.1622, val_loss=0.1434]

Lower model:  64%|██████▍   | 64/100 [00:06<00:02, 16.79epoch/s, loss=0.1621, val_loss=0.1433]

Lower model:  65%|██████▌   | 65/100 [00:06<00:02, 16.78epoch/s, loss=0.1621, val_loss=0.1433]

Lower model:  65%|██████▌   | 65/100 [00:06<00:02, 16.78epoch/s, loss=0.1630, val_loss=0.1433]

Lower model:  66%|██████▌   | 66/100 [00:06<00:02, 16.78epoch/s, loss=0.1622, val_loss=0.1432]

Lower model:  67%|██████▋   | 67/100 [00:06<00:01, 16.62epoch/s, loss=0.1622, val_loss=0.1432]

Lower model:  67%|██████▋   | 67/100 [00:06<00:01, 16.62epoch/s, loss=0.1619, val_loss=0.1433]

Lower model:  68%|██████▊   | 68/100 [00:06<00:01, 16.62epoch/s, loss=0.1598, val_loss=0.1433]

Lower model:  69%|██████▉   | 69/100 [00:06<00:01, 16.37epoch/s, loss=0.1598, val_loss=0.1433]

Lower model:  69%|██████▉   | 69/100 [00:06<00:01, 16.37epoch/s, loss=0.1646, val_loss=0.1432]

Lower model:  70%|███████   | 70/100 [00:06<00:01, 16.37epoch/s, loss=0.1617, val_loss=0.1431]

Lower model:  71%|███████   | 71/100 [00:06<00:01, 15.65epoch/s, loss=0.1617, val_loss=0.1431]

Lower model:  71%|███████   | 71/100 [00:06<00:01, 15.65epoch/s, loss=0.1610, val_loss=0.1432]

Lower model:  72%|███████▏  | 72/100 [00:06<00:01, 15.65epoch/s, loss=0.1622, val_loss=0.1432]

Lower model:  73%|███████▎  | 73/100 [00:06<00:01, 15.92epoch/s, loss=0.1622, val_loss=0.1432]

Lower model:  73%|███████▎  | 73/100 [00:06<00:01, 15.92epoch/s, loss=0.1624, val_loss=0.1432]

Lower model:  74%|███████▍  | 74/100 [00:06<00:01, 15.92epoch/s, loss=0.1620, val_loss=0.1432]

Lower model:  75%|███████▌  | 75/100 [00:06<00:01, 15.94epoch/s, loss=0.1620, val_loss=0.1432]

Lower model:  75%|███████▌  | 75/100 [00:06<00:01, 15.94epoch/s, loss=0.1628, val_loss=0.1432]

Lower model:  76%|███████▌  | 76/100 [00:06<00:01, 15.94epoch/s, loss=0.1628, val_loss=0.1433]

Lower model:  77%|███████▋  | 77/100 [00:06<00:01, 15.93epoch/s, loss=0.1628, val_loss=0.1433]

Lower model:  77%|███████▋  | 77/100 [00:06<00:01, 15.93epoch/s, loss=0.1612, val_loss=0.1433]

Lower model:  78%|███████▊  | 78/100 [00:06<00:01, 15.93epoch/s, loss=0.1616, val_loss=0.1433]

Lower model:  79%|███████▉  | 79/100 [00:06<00:01, 16.11epoch/s, loss=0.1616, val_loss=0.1433]

Lower model:  79%|███████▉  | 79/100 [00:07<00:01, 16.11epoch/s, loss=0.1626, val_loss=0.1433]

Lower model:  80%|████████  | 80/100 [00:07<00:01, 16.11epoch/s, loss=0.1608, val_loss=0.1433]

Lower model:  81%|████████  | 81/100 [00:07<00:01, 16.49epoch/s, loss=0.1608, val_loss=0.1433]

Lower model:  81%|████████  | 81/100 [00:07<00:01, 11.43epoch/s, loss=0.1608, val_loss=0.1433]

1/6 ━━━━━━━━━━━━━━━━━━━━ 1s 215ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

1/6 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step

1/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step

1/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

  > CQR Calibration constant (Q): -0.1387

Running configuration: Low:0.015 - High:0.965

Upper model:   0%|          | 0/100 [00:00<?, ?epoch/s]

I0000 00:00:1778435070.878339 2605127 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_14605__.19

I0000 00:00:1778435071.656663 2605130 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_14605__.19

Upper model:   0%|          | 0/100 [00:02<?, ?epoch/s, loss=17.8018, val_loss=16.3682]

Upper model:   1%|          | 1/100 [00:02<03:33,  2.16s/epoch, loss=17.8018, val_loss=16.3682]

Upper model:   1%|          | 1/100 [00:02<03:33,  2.16s/epoch, loss=17.7345, val_loss=16.3080]

Upper model:   2%|▏         | 2/100 [00:02<03:31,  2.16s/epoch, loss=17.6742, val_loss=16.2518]

Upper model:   3%|▎         | 3/100 [00:02<00:58,  1.66epoch/s, loss=17.6742, val_loss=16.2518]

Upper model:   3%|▎         | 3/100 [00:02<00:58,  1.66epoch/s, loss=17.6155, val_loss=16.1988]

Upper model:   4%|▍         | 4/100 [00:02<00:57,  1.66epoch/s, loss=17.5594, val_loss=16.1498]

Upper model:   5%|▌         | 5/100 [00:02<00:30,  3.11epoch/s, loss=17.5594, val_loss=16.1498]

Upper model:   5%|▌         | 5/100 [00:02<00:30,  3.11epoch/s, loss=17.5123, val_loss=16.1030]

Upper model:   6%|▌         | 6/100 [00:02<00:30,  3.11epoch/s, loss=17.4700, val_loss=16.0562]

Upper model:   7%|▋         | 7/100 [00:02<00:19,  4.74epoch/s, loss=17.4700, val_loss=16.0562]

Upper model:   7%|▋         | 7/100 [00:02<00:19,  4.74epoch/s, loss=17.4125, val_loss=16.0058]

Upper model:   8%|▊         | 8/100 [00:02<00:19,  4.74epoch/s, loss=17.3534, val_loss=15.9498]

Upper model:   9%|▉         | 9/100 [00:02<00:13,  6.55epoch/s, loss=17.3534, val_loss=15.9498]

Upper model:   9%|▉         | 9/100 [00:02<00:13,  6.55epoch/s, loss=17.3013, val_loss=15.8885]

Upper model:  10%|█         | 10/100 [00:02<00:13,  6.55epoch/s, loss=17.2319, val_loss=15.8207]

Upper model:  11%|█         | 11/100 [00:02<00:10,  8.35epoch/s, loss=17.2319, val_loss=15.8207]

Upper model:  11%|█         | 11/100 [00:02<00:10,  8.35epoch/s, loss=17.1578, val_loss=15.7463]

Upper model:  12%|█▏        | 12/100 [00:02<00:10,  8.35epoch/s, loss=17.0760, val_loss=15.6647]

Upper model:  13%|█▎        | 13/100 [00:02<00:08, 10.09epoch/s, loss=17.0760, val_loss=15.6647]

Upper model:  13%|█▎        | 13/100 [00:02<00:08, 10.09epoch/s, loss=16.9916, val_loss=15.5753]

Upper model:  14%|█▍        | 14/100 [00:02<00:08, 10.09epoch/s, loss=16.8886, val_loss=15.4764]

Upper model:  15%|█▌        | 15/100 [00:02<00:07, 11.36epoch/s, loss=16.8886, val_loss=15.4764]

Upper model:  15%|█▌        | 15/100 [00:03<00:07, 11.36epoch/s, loss=16.7701, val_loss=15.3670]

Upper model:  16%|█▌        | 16/100 [00:03<00:07, 11.36epoch/s, loss=16.6660, val_loss=15.2473]

Upper model:  17%|█▋        | 17/100 [00:03<00:06, 12.43epoch/s, loss=16.6660, val_loss=15.2473]

Upper model:  17%|█▋        | 17/100 [00:03<00:06, 12.43epoch/s, loss=16.5297, val_loss=15.1168]

Upper model:  18%|█▊        | 18/100 [00:03<00:06, 12.43epoch/s, loss=16.3873, val_loss=14.9735]

Upper model:  19%|█▉        | 19/100 [00:03<00:05, 13.58epoch/s, loss=16.3873, val_loss=14.9735]

Upper model:  19%|█▉        | 19/100 [00:03<00:05, 13.58epoch/s, loss=16.2340, val_loss=14.8182]

Upper model:  20%|██        | 20/100 [00:03<00:05, 13.58epoch/s, loss=16.0679, val_loss=14.6485]

Upper model:  21%|██        | 21/100 [00:03<00:05, 14.43epoch/s, loss=16.0679, val_loss=14.6485]

Upper model:  21%|██        | 21/100 [00:03<00:05, 14.43epoch/s, loss=15.8728, val_loss=14.4628]

Upper model:  22%|██▏       | 22/100 [00:03<00:05, 14.43epoch/s, loss=15.6931, val_loss=14.2589]

Upper model:  23%|██▎       | 23/100 [00:03<00:05, 14.93epoch/s, loss=15.6931, val_loss=14.2589]

Upper model:  23%|██▎       | 23/100 [00:03<00:05, 14.93epoch/s, loss=15.4642, val_loss=14.0377]

Upper model:  24%|██▍       | 24/100 [00:03<00:05, 14.93epoch/s, loss=15.2340, val_loss=13.7980]

Upper model:  25%|██▌       | 25/100 [00:03<00:04, 15.61epoch/s, loss=15.2340, val_loss=13.7980]

Upper model:  25%|██▌       | 25/100 [00:03<00:04, 15.61epoch/s, loss=14.9743, val_loss=13.5408]

Upper model:  26%|██▌       | 26/100 [00:03<00:04, 15.61epoch/s, loss=14.6982, val_loss=13.2632]

Upper model:  27%|██▋       | 27/100 [00:03<00:04, 15.57epoch/s, loss=14.6982, val_loss=13.2632]

Upper model:  27%|██▋       | 27/100 [00:03<00:04, 15.57epoch/s, loss=14.4037, val_loss=12.9664]

Upper model:  28%|██▊       | 28/100 [00:03<00:04, 15.57epoch/s, loss=14.0889, val_loss=12.6468]

Upper model:  29%|██▉       | 29/100 [00:03<00:04, 16.01epoch/s, loss=14.0889, val_loss=12.6468]

Upper model:  29%|██▉       | 29/100 [00:03<00:04, 16.01epoch/s, loss=13.7751, val_loss=12.3073]

Upper model:  30%|███       | 30/100 [00:03<00:04, 16.01epoch/s, loss=13.4892, val_loss=11.9473]

Upper model:  31%|███       | 31/100 [00:03<00:04, 16.48epoch/s, loss=13.4892, val_loss=11.9473]

Upper model:  31%|███       | 31/100 [00:04<00:04, 16.48epoch/s, loss=13.0264, val_loss=11.5634]

Upper model:  32%|███▏      | 32/100 [00:04<00:04, 16.48epoch/s, loss=12.6706, val_loss=11.1599]

Upper model:  33%|███▎      | 33/100 [00:04<00:04, 16.39epoch/s, loss=12.6706, val_loss=11.1599]

Upper model:  33%|███▎      | 33/100 [00:04<00:04, 16.39epoch/s, loss=12.2225, val_loss=10.7475]

Upper model:  34%|███▍      | 34/100 [00:04<00:04, 16.39epoch/s, loss=11.8097, val_loss=10.3184]

Upper model:  35%|███▌      | 35/100 [00:04<00:04, 16.14epoch/s, loss=11.8097, val_loss=10.3184]

Upper model:  35%|███▌      | 35/100 [00:04<00:04, 16.14epoch/s, loss=11.3777, val_loss=9.8792]

Upper model:  36%|███▌      | 36/100 [00:04<00:03, 16.14epoch/s, loss=10.9404, val_loss=9.4288]

Upper model:  37%|███▋      | 37/100 [00:04<00:03, 16.56epoch/s, loss=10.9404, val_loss=9.4288]

Upper model:  37%|███▋      | 37/100 [00:04<00:03, 16.56epoch/s, loss=10.4956, val_loss=8.9676]

Upper model:  38%|███▊      | 38/100 [00:04<00:03, 16.56epoch/s, loss=9.9966, val_loss=8.5179]

Upper model:  39%|███▉      | 39/100 [00:04<00:03, 16.71epoch/s, loss=9.9966, val_loss=8.5179]

Upper model:  39%|███▉      | 39/100 [00:04<00:03, 16.71epoch/s, loss=9.5877, val_loss=8.0739]

Upper model:  40%|████      | 40/100 [00:04<00:03, 16.71epoch/s, loss=9.1080, val_loss=7.6273]

Upper model:  41%|████      | 41/100 [00:04<00:03, 16.75epoch/s, loss=9.1080, val_loss=7.6273]

Upper model:  41%|████      | 41/100 [00:04<00:03, 16.75epoch/s, loss=8.7259, val_loss=7.1871]

Upper model:  42%|████▏     | 42/100 [00:04<00:03, 16.75epoch/s, loss=8.2532, val_loss=6.7545]

Upper model:  43%|████▎     | 43/100 [00:04<00:03, 17.10epoch/s, loss=8.2532, val_loss=6.7545]

Upper model:  43%|████▎     | 43/100 [00:04<00:03, 17.10epoch/s, loss=7.9237, val_loss=6.3303]

Upper model:  44%|████▍     | 44/100 [00:04<00:03, 17.10epoch/s, loss=7.4786, val_loss=5.9235]

Upper model:  45%|████▌     | 45/100 [00:04<00:03, 17.36epoch/s, loss=7.4786, val_loss=5.9235]

Upper model:  45%|████▌     | 45/100 [00:04<00:03, 17.36epoch/s, loss=7.1126, val_loss=5.5297]

Upper model:  46%|████▌     | 46/100 [00:04<00:03, 17.36epoch/s, loss=6.7007, val_loss=5.1532]

Upper model:  47%|████▋     | 47/100 [00:04<00:03, 17.26epoch/s, loss=6.7007, val_loss=5.1532]

Upper model:  47%|████▋     | 47/100 [00:04<00:03, 17.26epoch/s, loss=6.3450, val_loss=4.8040]

Upper model:  48%|████▊     | 48/100 [00:04<00:03, 17.26epoch/s, loss=5.9119, val_loss=4.4782]

Upper model:  49%|████▉     | 49/100 [00:04<00:02, 17.36epoch/s, loss=5.9119, val_loss=4.4782]

Upper model:  49%|████▉     | 49/100 [00:05<00:02, 17.36epoch/s, loss=5.7618, val_loss=4.1706]

Upper model:  50%|█████     | 50/100 [00:05<00:02, 17.36epoch/s, loss=5.3736, val_loss=3.8714]

Upper model:  51%|█████     | 51/100 [00:05<00:02, 16.82epoch/s, loss=5.3736, val_loss=3.8714]

Upper model:  51%|█████     | 51/100 [00:05<00:02, 16.82epoch/s, loss=4.9611, val_loss=3.5943]

Upper model:  52%|█████▏    | 52/100 [00:05<00:02, 16.82epoch/s, loss=4.6790, val_loss=3.3362]

Upper model:  53%|█████▎    | 53/100 [00:05<00:02, 16.84epoch/s, loss=4.6790, val_loss=3.3362]

Upper model:  53%|█████▎    | 53/100 [00:05<00:02, 16.84epoch/s, loss=4.4357, val_loss=3.0858]

Upper model:  54%|█████▍    | 54/100 [00:05<00:02, 16.84epoch/s, loss=4.1457, val_loss=2.8410]

Upper model:  55%|█████▌    | 55/100 [00:05<00:02, 16.99epoch/s, loss=4.1457, val_loss=2.8410]

Upper model:  55%|█████▌    | 55/100 [00:05<00:02, 16.99epoch/s, loss=3.9603, val_loss=2.6045]

Upper model:  56%|█████▌    | 56/100 [00:05<00:02, 16.99epoch/s, loss=3.5190, val_loss=2.3772]

Upper model:  57%|█████▋    | 57/100 [00:05<00:02, 16.95epoch/s, loss=3.5190, val_loss=2.3772]

Upper model:  57%|█████▋    | 57/100 [00:05<00:02, 16.95epoch/s, loss=3.3309, val_loss=2.1641]

Upper model:  58%|█████▊    | 58/100 [00:05<00:02, 16.95epoch/s, loss=3.1770, val_loss=1.9709]

Upper model:  59%|█████▉    | 59/100 [00:05<00:02, 16.30epoch/s, loss=3.1770, val_loss=1.9709]

Upper model:  59%|█████▉    | 59/100 [00:05<00:02, 16.30epoch/s, loss=3.0655, val_loss=1.7950]

Upper model:  60%|██████    | 60/100 [00:05<00:02, 16.30epoch/s, loss=2.8656, val_loss=1.6414]

Upper model:  61%|██████    | 61/100 [00:05<00:02, 15.78epoch/s, loss=2.8656, val_loss=1.6414]

Upper model:  61%|██████    | 61/100 [00:05<00:02, 15.78epoch/s, loss=2.5704, val_loss=1.5105]

Upper model:  62%|██████▏   | 62/100 [00:05<00:02, 15.78epoch/s, loss=2.6118, val_loss=1.3925]

Upper model:  63%|██████▎   | 63/100 [00:05<00:02, 16.10epoch/s, loss=2.6118, val_loss=1.3925]

Upper model:  63%|██████▎   | 63/100 [00:05<00:02, 16.10epoch/s, loss=2.3902, val_loss=1.2830]

Upper model:  64%|██████▍   | 64/100 [00:05<00:02, 16.10epoch/s, loss=2.2466, val_loss=1.1809]

Upper model:  65%|██████▌   | 65/100 [00:05<00:02, 16.07epoch/s, loss=2.2466, val_loss=1.1809]

Upper model:  65%|██████▌   | 65/100 [00:06<00:02, 16.07epoch/s, loss=2.2467, val_loss=1.1025]

Upper model:  66%|██████▌   | 66/100 [00:06<00:02, 16.07epoch/s, loss=2.1890, val_loss=1.0364]

Upper model:  67%|██████▋   | 67/100 [00:06<00:02, 16.15epoch/s, loss=2.1890, val_loss=1.0364]

Upper model:  67%|██████▋   | 67/100 [00:06<00:02, 16.15epoch/s, loss=1.9846, val_loss=0.9827]

Upper model:  68%|██████▊   | 68/100 [00:06<00:01, 16.15epoch/s, loss=1.8117, val_loss=0.9374]

Upper model:  69%|██████▉   | 69/100 [00:06<00:01, 16.30epoch/s, loss=1.8117, val_loss=0.9374]

Upper model:  69%|██████▉   | 69/100 [00:06<00:01, 16.30epoch/s, loss=1.8209, val_loss=0.9023]

Upper model:  70%|███████   | 70/100 [00:06<00:01, 16.30epoch/s, loss=1.7050, val_loss=0.8742]

Upper model:  71%|███████   | 71/100 [00:06<00:01, 16.25epoch/s, loss=1.7050, val_loss=0.8742]

Upper model:  71%|███████   | 71/100 [00:06<00:01, 16.25epoch/s, loss=1.6819, val_loss=0.8481]

Upper model:  72%|███████▏  | 72/100 [00:06<00:01, 16.25epoch/s, loss=1.6808, val_loss=0.8285]

Upper model:  73%|███████▎  | 73/100 [00:06<00:01, 16.02epoch/s, loss=1.6808, val_loss=0.8285]

Upper model:  73%|███████▎  | 73/100 [00:06<00:01, 16.02epoch/s, loss=1.5845, val_loss=0.8100]

Upper model:  74%|███████▍  | 74/100 [00:06<00:01, 16.02epoch/s, loss=1.5145, val_loss=0.7936]

Upper model:  75%|███████▌  | 75/100 [00:06<00:01, 16.52epoch/s, loss=1.5145, val_loss=0.7936]

Upper model:  75%|███████▌  | 75/100 [00:06<00:01, 16.52epoch/s, loss=1.5565, val_loss=0.7795]

Upper model:  76%|███████▌  | 76/100 [00:06<00:01, 16.52epoch/s, loss=1.4581, val_loss=0.7684]

Upper model:  77%|███████▋  | 77/100 [00:06<00:01, 16.81epoch/s, loss=1.4581, val_loss=0.7684]

Upper model:  77%|███████▋  | 77/100 [00:06<00:01, 16.81epoch/s, loss=1.4496, val_loss=0.7602]

Upper model:  78%|███████▊  | 78/100 [00:06<00:01, 16.81epoch/s, loss=1.4608, val_loss=0.7547]

Upper model:  79%|███████▉  | 79/100 [00:06<00:01, 17.08epoch/s, loss=1.4608, val_loss=0.7547]

Upper model:  79%|███████▉  | 79/100 [00:06<00:01, 17.08epoch/s, loss=1.4046, val_loss=0.7506]

Upper model:  80%|████████  | 80/100 [00:06<00:01, 17.08epoch/s, loss=1.5042, val_loss=0.7480]

Upper model:  81%|████████  | 81/100 [00:06<00:01, 17.00epoch/s, loss=1.5042, val_loss=0.7480]

Upper model:  81%|████████  | 81/100 [00:06<00:01, 17.00epoch/s, loss=1.4569, val_loss=0.7474]

Upper model:  82%|████████▏ | 82/100 [00:07<00:01, 17.00epoch/s, loss=1.3587, val_loss=0.7469]

Upper model:  83%|████████▎ | 83/100 [00:07<00:00, 17.16epoch/s, loss=1.3587, val_loss=0.7469]

Upper model:  83%|████████▎ | 83/100 [00:07<00:00, 17.16epoch/s, loss=1.3966, val_loss=0.7465]

Upper model:  84%|████████▍ | 84/100 [00:07<00:00, 17.16epoch/s, loss=1.2549, val_loss=0.7461]

Upper model:  85%|████████▌ | 85/100 [00:07<00:00, 16.92epoch/s, loss=1.2549, val_loss=0.7461]

Upper model:  85%|████████▌ | 85/100 [00:07<00:00, 16.92epoch/s, loss=1.2964, val_loss=0.7484]

Upper model:  86%|████████▌ | 86/100 [00:07<00:00, 16.92epoch/s, loss=1.3692, val_loss=0.7516]

Upper model:  87%|████████▋ | 87/100 [00:07<00:00, 17.09epoch/s, loss=1.3692, val_loss=0.7516]

Upper model:  87%|████████▋ | 87/100 [00:07<00:00, 17.09epoch/s, loss=1.2771, val_loss=0.7549]

Upper model:  88%|████████▊ | 88/100 [00:07<00:00, 17.09epoch/s, loss=1.2801, val_loss=0.7591]

Upper model:  89%|████████▉ | 89/100 [00:07<00:00, 17.38epoch/s, loss=1.2801, val_loss=0.7591]

Upper model:  89%|████████▉ | 89/100 [00:07<00:00, 17.38epoch/s, loss=1.2764, val_loss=0.7639]

Upper model:  90%|█████████ | 90/100 [00:07<00:00, 17.38epoch/s, loss=1.1811, val_loss=0.7667]

Upper model:  91%|█████████ | 91/100 [00:07<00:00, 17.45epoch/s, loss=1.1811, val_loss=0.7667]

Upper model:  91%|█████████ | 91/100 [00:07<00:00, 17.45epoch/s, loss=1.2640, val_loss=0.7693]

Upper model:  92%|█████████▏| 92/100 [00:07<00:00, 17.45epoch/s, loss=1.2500, val_loss=0.7721]

Upper model:  93%|█████████▎| 93/100 [00:07<00:00, 17.45epoch/s, loss=1.2500, val_loss=0.7721]

Upper model:  93%|█████████▎| 93/100 [00:07<00:00, 17.45epoch/s, loss=1.2365, val_loss=0.7747]

Upper model:  94%|█████████▍| 94/100 [00:07<00:00, 17.45epoch/s, loss=1.2741, val_loss=0.7772]

Upper model:  95%|█████████▌| 95/100 [00:07<00:00, 17.38epoch/s, loss=1.2741, val_loss=0.7772]

Upper model:  95%|█████████▌| 95/100 [00:07<00:00, 12.26epoch/s, loss=1.2741, val_loss=0.7772]

Lower model:   0%|          | 0/100 [00:00<?, ?epoch/s]

I0000 00:00:1778435078.630271 2605134 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_21435__.19

I0000 00:00:1778435079.388095 2605127 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_21435__.19

Lower model:   0%|          | 0/100 [00:02<?, ?epoch/s, loss=0.2757, val_loss=0.2537]

Lower model:   1%|          | 1/100 [00:02<03:31,  2.14s/epoch, loss=0.2757, val_loss=0.2537]

Lower model:   1%|          | 1/100 [00:02<03:31,  2.14s/epoch, loss=0.2751, val_loss=0.2532]

Lower model:   2%|▏         | 2/100 [00:02<03:29,  2.14s/epoch, loss=0.2745, val_loss=0.2527]

Lower model:   3%|▎         | 3/100 [00:02<00:58,  1.66epoch/s, loss=0.2745, val_loss=0.2527]

Lower model:   3%|▎         | 3/100 [00:02<00:58,  1.66epoch/s, loss=0.2740, val_loss=0.2522]

Lower model:   4%|▍         | 4/100 [00:02<00:57,  1.66epoch/s, loss=0.2736, val_loss=0.2517]

Lower model:   5%|▌         | 5/100 [00:02<00:31,  3.04epoch/s, loss=0.2736, val_loss=0.2517]

Lower model:   5%|▌         | 5/100 [00:02<00:31,  3.04epoch/s, loss=0.2730, val_loss=0.2510]

Lower model:   6%|▌         | 6/100 [00:02<00:30,  3.04epoch/s, loss=0.2723, val_loss=0.2504]

Lower model:   7%|▋         | 7/100 [00:02<00:20,  4.64epoch/s, loss=0.2723, val_loss=0.2504]

Lower model:   7%|▋         | 7/100 [00:02<00:20,  4.64epoch/s, loss=0.2716, val_loss=0.2496]

Lower model:   8%|▊         | 8/100 [00:02<00:19,  4.64epoch/s, loss=0.2709, val_loss=0.2488]

Lower model:   9%|▉         | 9/100 [00:02<00:14,  6.15epoch/s, loss=0.2709, val_loss=0.2488]

Lower model:   9%|▉         | 9/100 [00:02<00:14,  6.15epoch/s, loss=0.2700, val_loss=0.2480]

Lower model:  10%|█         | 10/100 [00:02<00:14,  6.15epoch/s, loss=0.2691, val_loss=0.2471]

Lower model:  11%|█         | 11/100 [00:02<00:11,  7.87epoch/s, loss=0.2691, val_loss=0.2471]

Lower model:  11%|█         | 11/100 [00:02<00:11,  7.87epoch/s, loss=0.2682, val_loss=0.2461]

Lower model:  12%|█▏        | 12/100 [00:02<00:11,  7.87epoch/s, loss=0.2671, val_loss=0.2451]

Lower model:  13%|█▎        | 13/100 [00:02<00:09,  9.49epoch/s, loss=0.2671, val_loss=0.2451]

Lower model:  13%|█▎        | 13/100 [00:02<00:09,  9.49epoch/s, loss=0.2660, val_loss=0.2439]

Lower model:  14%|█▍        | 14/100 [00:03<00:09,  9.49epoch/s, loss=0.2646, val_loss=0.2426]

Lower model:  15%|█▌        | 15/100 [00:03<00:07, 11.05epoch/s, loss=0.2646, val_loss=0.2426]

Lower model:  15%|█▌        | 15/100 [00:03<00:07, 11.05epoch/s, loss=0.2633, val_loss=0.2412]

Lower model:  16%|█▌        | 16/100 [00:03<00:07, 11.05epoch/s, loss=0.2619, val_loss=0.2397]

Lower model:  17%|█▋        | 17/100 [00:03<00:06, 12.42epoch/s, loss=0.2619, val_loss=0.2397]

Lower model:  17%|█▋        | 17/100 [00:03<00:06, 12.42epoch/s, loss=0.2600, val_loss=0.2379]

Lower model:  18%|█▊        | 18/100 [00:03<00:06, 12.42epoch/s, loss=0.2584, val_loss=0.2361]

Lower model:  19%|█▉        | 19/100 [00:03<00:06, 13.42epoch/s, loss=0.2584, val_loss=0.2361]

Lower model:  19%|█▉        | 19/100 [00:03<00:06, 13.42epoch/s, loss=0.2564, val_loss=0.2341]

Lower model:  20%|██        | 20/100 [00:03<00:05, 13.42epoch/s, loss=0.2546, val_loss=0.2319]

Lower model:  21%|██        | 21/100 [00:03<00:05, 14.39epoch/s, loss=0.2546, val_loss=0.2319]

Lower model:  21%|██        | 21/100 [00:03<00:05, 14.39epoch/s, loss=0.2526, val_loss=0.2298]

Lower model:  22%|██▏       | 22/100 [00:03<00:05, 14.39epoch/s, loss=0.2511, val_loss=0.2275]

Lower model:  23%|██▎       | 23/100 [00:03<00:05, 14.88epoch/s, loss=0.2511, val_loss=0.2275]

Lower model:  23%|██▎       | 23/100 [00:03<00:05, 14.88epoch/s, loss=0.2490, val_loss=0.2252]

Lower model:  24%|██▍       | 24/100 [00:03<00:05, 14.88epoch/s, loss=0.2481, val_loss=0.2231]

Lower model:  25%|██▌       | 25/100 [00:03<00:04, 15.31epoch/s, loss=0.2481, val_loss=0.2231]

Lower model:  25%|██▌       | 25/100 [00:03<00:04, 15.31epoch/s, loss=0.2463, val_loss=0.2209]

Lower model:  26%|██▌       | 26/100 [00:03<00:04, 15.31epoch/s, loss=0.2462, val_loss=0.2190]

Lower model:  27%|██▋       | 27/100 [00:03<00:04, 15.94epoch/s, loss=0.2462, val_loss=0.2190]

Lower model:  27%|██▋       | 27/100 [00:03<00:04, 15.94epoch/s, loss=0.2460, val_loss=0.2174]

Lower model:  28%|██▊       | 28/100 [00:03<00:04, 15.94epoch/s, loss=0.2449, val_loss=0.2163]

Lower model:  29%|██▉       | 29/100 [00:03<00:04, 16.32epoch/s, loss=0.2449, val_loss=0.2163]

Lower model:  29%|██▉       | 29/100 [00:03<00:04, 16.32epoch/s, loss=0.2440, val_loss=0.2153]

Lower model:  30%|███       | 30/100 [00:03<00:04, 16.32epoch/s, loss=0.2433, val_loss=0.2145]

Lower model:  31%|███       | 31/100 [00:03<00:04, 16.57epoch/s, loss=0.2433, val_loss=0.2145]

Lower model:  31%|███       | 31/100 [00:04<00:04, 16.57epoch/s, loss=0.2422, val_loss=0.2140]

Lower model:  32%|███▏      | 32/100 [00:04<00:04, 16.57epoch/s, loss=0.2418, val_loss=0.2138]

Lower model:  33%|███▎      | 33/100 [00:04<00:04, 16.53epoch/s, loss=0.2418, val_loss=0.2138]

Lower model:  33%|███▎      | 33/100 [00:04<00:04, 16.53epoch/s, loss=0.2466, val_loss=0.2136]

Lower model:  34%|███▍      | 34/100 [00:04<00:03, 16.53epoch/s, loss=0.2432, val_loss=0.2137]

Lower model:  35%|███▌      | 35/100 [00:04<00:03, 16.91epoch/s, loss=0.2432, val_loss=0.2137]

Lower model:  35%|███▌      | 35/100 [00:04<00:03, 16.91epoch/s, loss=0.2433, val_loss=0.2141]

Lower model:  36%|███▌      | 36/100 [00:04<00:03, 16.91epoch/s, loss=0.2424, val_loss=0.2143]

Lower model:  37%|███▋      | 37/100 [00:04<00:03, 16.39epoch/s, loss=0.2424, val_loss=0.2143]

Lower model:  37%|███▋      | 37/100 [00:04<00:03, 16.39epoch/s, loss=0.2447, val_loss=0.2144]

Lower model:  38%|███▊      | 38/100 [00:04<00:03, 16.39epoch/s, loss=0.2441, val_loss=0.2142]

Lower model:  39%|███▉      | 39/100 [00:04<00:03, 16.14epoch/s, loss=0.2441, val_loss=0.2142]

Lower model:  39%|███▉      | 39/100 [00:04<00:03, 16.14epoch/s, loss=0.2447, val_loss=0.2141]

Lower model:  40%|████      | 40/100 [00:04<00:03, 16.14epoch/s, loss=0.2432, val_loss=0.2140]

Lower model:  41%|████      | 41/100 [00:04<00:03, 16.48epoch/s, loss=0.2432, val_loss=0.2140]

Lower model:  41%|████      | 41/100 [00:04<00:03, 16.48epoch/s, loss=0.2411, val_loss=0.2139]

Lower model:  42%|████▏     | 42/100 [00:04<00:03, 16.48epoch/s, loss=0.2440, val_loss=0.2138]

Lower model:  43%|████▎     | 43/100 [00:04<00:03, 16.74epoch/s, loss=0.2440, val_loss=0.2138]

Lower model:  43%|████▎     | 43/100 [00:04<00:03, 16.74epoch/s, loss=0.2421, val_loss=0.2136]

Lower model:  44%|████▍     | 44/100 [00:04<00:06,  9.19epoch/s, loss=0.2421, val_loss=0.2136]

1/6 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step

1/6 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step

1/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

1/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

  > CQR Calibration constant (Q): -0.0615

Running configuration: Low:0.02 - High:0.97

Upper model:   0%|          | 0/100 [00:00<?, ?epoch/s]

I0000 00:00:1778435084.170756 2605133 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26240__.19

I0000 00:00:1778435084.931633 2605134 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_26240__.19

Upper model:   0%|          | 0/100 [00:02<?, ?epoch/s, loss=17.6158, val_loss=16.2084]

Upper model:   1%|          | 1/100 [00:02<03:33,  2.15s/epoch, loss=17.6158, val_loss=16.2084]

Upper model:   1%|          | 1/100 [00:02<03:33,  2.15s/epoch, loss=17.5668, val_loss=16.1653]

Upper model:   2%|▏         | 2/100 [00:02<03:30,  2.15s/epoch, loss=17.5248, val_loss=16.1228]

Upper model:   3%|▎         | 3/100 [00:02<00:58,  1.65epoch/s, loss=17.5248, val_loss=16.1228]

Upper model:   3%|▎         | 3/100 [00:02<00:58,  1.65epoch/s, loss=17.4799, val_loss=16.0785]

Upper model:   4%|▍         | 4/100 [00:02<00:58,  1.65epoch/s, loss=17.4364, val_loss=16.0308]

Upper model:   5%|▌         | 5/100 [00:02<00:30,  3.09epoch/s, loss=17.4364, val_loss=16.0308]

Upper model:   5%|▌         | 5/100 [00:02<00:30,  3.09epoch/s, loss=17.3798, val_loss=15.9786]

Upper model:   6%|▌         | 6/100 [00:02<00:30,  3.09epoch/s, loss=17.3293, val_loss=15.9208]

Upper model:   7%|▋         | 7/100 [00:02<00:19,  4.74epoch/s, loss=17.3293, val_loss=15.9208]

Upper model:   7%|▋         | 7/100 [00:02<00:19,  4.74epoch/s, loss=17.2656, val_loss=15.8564]

Upper model:   8%|▊         | 8/100 [00:02<00:19,  4.74epoch/s, loss=17.2013, val_loss=15.7848]

Upper model:   9%|▉         | 9/100 [00:02<00:13,  6.54epoch/s, loss=17.2013, val_loss=15.7848]

Upper model:   9%|▉         | 9/100 [00:02<00:13,  6.54epoch/s, loss=17.1173, val_loss=15.7050]

Upper model:  10%|█         | 10/100 [00:02<00:13,  6.54epoch/s, loss=17.0340, val_loss=15.6160]

Upper model:  11%|█         | 11/100 [00:02<00:10,  8.37epoch/s, loss=17.0340, val_loss=15.6160]

Upper model:  11%|█         | 11/100 [00:02<00:10,  8.37epoch/s, loss=16.9268, val_loss=15.5164]

Upper model:  12%|█▏        | 12/100 [00:02<00:10,  8.37epoch/s, loss=16.8220, val_loss=15.4063]

Upper model:  13%|█▎        | 13/100 [00:02<00:08, 10.13epoch/s, loss=16.8220, val_loss=15.4063]

Upper model:  13%|█▎        | 13/100 [00:02<00:08, 10.13epoch/s, loss=16.7054, val_loss=15.2855]

Upper model:  14%|█▍        | 14/100 [00:02<00:08, 10.13epoch/s, loss=16.5875, val_loss=15.1538]

Upper model:  15%|█▌        | 15/100 [00:02<00:07, 11.56epoch/s, loss=16.5875, val_loss=15.1538]

Upper model:  15%|█▌        | 15/100 [00:03<00:07, 11.56epoch/s, loss=16.4328, val_loss=15.0097]

Upper model:  16%|█▌        | 16/100 [00:03<00:07, 11.56epoch/s, loss=16.2828, val_loss=14.8520]

Upper model:  17%|█▋        | 17/100 [00:03<00:06, 12.90epoch/s, loss=16.2828, val_loss=14.8520]

Upper model:  17%|█▋        | 17/100 [00:03<00:06, 12.90epoch/s, loss=16.1139, val_loss=14.6795]

Upper model:  18%|█▊        | 18/100 [00:03<00:06, 12.90epoch/s, loss=15.9232, val_loss=14.4920]

Upper model:  19%|█▉        | 19/100 [00:03<00:05, 13.66epoch/s, loss=15.9232, val_loss=14.4920]

Upper model:  19%|█▉        | 19/100 [00:03<00:05, 13.66epoch/s, loss=15.7464, val_loss=14.2893]

Upper model:  20%|██        | 20/100 [00:03<00:05, 13.66epoch/s, loss=15.5057, val_loss=14.0692]

Upper model:  21%|██        | 21/100 [00:03<00:05, 14.20epoch/s, loss=15.5057, val_loss=14.0692]

Upper model:  21%|██        | 21/100 [00:03<00:05, 14.20epoch/s, loss=15.2935, val_loss=13.8314]

Upper model:  22%|██▏       | 22/100 [00:03<00:05, 14.20epoch/s, loss=15.0279, val_loss=13.5772]

Upper model:  23%|██▎       | 23/100 [00:03<00:05, 14.84epoch/s, loss=15.0279, val_loss=13.5772]

Upper model:  23%|██▎       | 23/100 [00:03<00:05, 14.84epoch/s, loss=14.7139, val_loss=13.3053]

Upper model:  24%|██▍       | 24/100 [00:03<00:05, 14.84epoch/s, loss=14.4670, val_loss=13.0145]

Upper model:  25%|██▌       | 25/100 [00:03<00:04, 15.43epoch/s, loss=14.4670, val_loss=13.0145]

Upper model:  25%|██▌       | 25/100 [00:03<00:04, 15.43epoch/s, loss=14.1495, val_loss=12.7026]

Upper model:  26%|██▌       | 26/100 [00:03<00:04, 15.43epoch/s, loss=13.8427, val_loss=12.3696]

Upper model:  27%|██▋       | 27/100 [00:03<00:04, 16.08epoch/s, loss=13.8427, val_loss=12.3696]

Upper model:  27%|██▋       | 27/100 [00:03<00:04, 16.08epoch/s, loss=13.4788, val_loss=12.0149]

Upper model:  28%|██▊       | 28/100 [00:03<00:04, 16.08epoch/s, loss=13.1087, val_loss=11.6373]

Upper model:  29%|██▉       | 29/100 [00:03<00:04, 16.41epoch/s, loss=13.1087, val_loss=11.6373]

Upper model:  29%|██▉       | 29/100 [00:03<00:04, 16.41epoch/s, loss=12.7782, val_loss=11.2487]

Upper model:  30%|███       | 30/100 [00:03<00:04, 16.41epoch/s, loss=12.3867, val_loss=10.8487]

Upper model:  31%|███       | 31/100 [00:03<00:04, 16.77epoch/s, loss=12.3867, val_loss=10.8487]

Upper model:  31%|███       | 31/100 [00:03<00:04, 16.77epoch/s, loss=11.9404, val_loss=10.4348]

Upper model:  32%|███▏      | 32/100 [00:04<00:04, 16.77epoch/s, loss=11.4655, val_loss=10.0099]

Upper model:  33%|███▎      | 33/100 [00:04<00:03, 16.87epoch/s, loss=11.4655, val_loss=10.0099]

Upper model:  33%|███▎      | 33/100 [00:04<00:03, 16.87epoch/s, loss=11.0743, val_loss=9.5707]

Upper model:  34%|███▍      | 34/100 [00:04<00:03, 16.87epoch/s, loss=10.5977, val_loss=9.1212]

Upper model:  35%|███▌      | 35/100 [00:04<00:03, 16.31epoch/s, loss=10.5977, val_loss=9.1212]

Upper model:  35%|███▌      | 35/100 [00:04<00:03, 16.31epoch/s, loss=10.2741, val_loss=8.6765]

Upper model:  36%|███▌      | 36/100 [00:04<00:03, 16.31epoch/s, loss=9.7641, val_loss=8.2414]

Upper model:  37%|███▋      | 37/100 [00:04<00:03, 16.52epoch/s, loss=9.7641, val_loss=8.2414]

Upper model:  37%|███▋      | 37/100 [00:04<00:03, 16.52epoch/s, loss=9.4331, val_loss=7.8008]

Upper model:  38%|███▊      | 38/100 [00:04<00:03, 16.52epoch/s, loss=8.9183, val_loss=7.3630]

Upper model:  39%|███▉      | 39/100 [00:04<00:03, 15.84epoch/s, loss=8.9183, val_loss=7.3630]

Upper model:  39%|███▉      | 39/100 [00:04<00:03, 15.84epoch/s, loss=8.5553, val_loss=6.9275]

Upper model:  40%|████      | 40/100 [00:04<00:03, 15.84epoch/s, loss=8.1240, val_loss=6.4972]

Upper model:  41%|████      | 41/100 [00:04<00:03, 15.87epoch/s, loss=8.1240, val_loss=6.4972]

Upper model:  41%|████      | 41/100 [00:04<00:03, 15.87epoch/s, loss=7.7068, val_loss=6.0914]

Upper model:  42%|████▏     | 42/100 [00:04<00:03, 15.87epoch/s, loss=7.1605, val_loss=5.6970]

Upper model:  43%|████▎     | 43/100 [00:04<00:03, 15.91epoch/s, loss=7.1605, val_loss=5.6970]

Upper model:  43%|████▎     | 43/100 [00:04<00:03, 15.91epoch/s, loss=6.9785, val_loss=5.3128]

Upper model:  44%|████▍     | 44/100 [00:04<00:03, 15.91epoch/s, loss=6.6193, val_loss=4.9433]

Upper model:  45%|████▌     | 45/100 [00:04<00:03, 16.31epoch/s, loss=6.6193, val_loss=4.9433]

Upper model:  45%|████▌     | 45/100 [00:04<00:03, 16.31epoch/s, loss=6.2607, val_loss=4.6014]

Upper model:  46%|████▌     | 46/100 [00:04<00:03, 16.31epoch/s, loss=5.8677, val_loss=4.2774]

Upper model:  47%|████▋     | 47/100 [00:04<00:03, 16.58epoch/s, loss=5.8677, val_loss=4.2774]

Upper model:  47%|████▋     | 47/100 [00:04<00:03, 16.58epoch/s, loss=5.4538, val_loss=3.9710]

Upper model:  48%|████▊     | 48/100 [00:05<00:03, 16.58epoch/s, loss=5.1597, val_loss=3.6762]

Upper model:  49%|████▉     | 49/100 [00:05<00:03, 16.43epoch/s, loss=5.1597, val_loss=3.6762]

Upper model:  49%|████▉     | 49/100 [00:05<00:03, 16.43epoch/s, loss=4.8080, val_loss=3.4070]

Upper model:  50%|█████     | 50/100 [00:05<00:03, 16.43epoch/s, loss=4.6140, val_loss=3.1535]

Upper model:  51%|█████     | 51/100 [00:05<00:03, 16.20epoch/s, loss=4.6140, val_loss=3.1535]

Upper model:  51%|█████     | 51/100 [00:05<00:03, 16.20epoch/s, loss=4.2262, val_loss=2.9049]

Upper model:  52%|█████▏    | 52/100 [00:05<00:02, 16.20epoch/s, loss=3.9829, val_loss=2.6590]

Upper model:  53%|█████▎    | 53/100 [00:05<00:02, 16.47epoch/s, loss=3.9829, val_loss=2.6590]

Upper model:  53%|█████▎    | 53/100 [00:05<00:02, 16.47epoch/s, loss=3.8275, val_loss=2.4243]

Upper model:  54%|█████▍    | 54/100 [00:05<00:02, 16.47epoch/s, loss=3.5606, val_loss=2.1985]

Upper model:  55%|█████▌    | 55/100 [00:05<00:02, 16.67epoch/s, loss=3.5606, val_loss=2.1985]

Upper model:  55%|█████▌    | 55/100 [00:05<00:02, 16.67epoch/s, loss=3.3326, val_loss=1.9926]

Upper model:  56%|█████▌    | 56/100 [00:05<00:02, 16.67epoch/s, loss=2.9217, val_loss=1.8068]

Upper model:  57%|█████▋    | 57/100 [00:05<00:02, 16.63epoch/s, loss=2.9217, val_loss=1.8068]

Upper model:  57%|█████▋    | 57/100 [00:05<00:02, 16.63epoch/s, loss=2.8348, val_loss=1.6460]

Upper model:  58%|█████▊    | 58/100 [00:05<00:02, 16.63epoch/s, loss=2.6330, val_loss=1.5008]

Upper model:  59%|█████▉    | 59/100 [00:05<00:02, 16.87epoch/s, loss=2.6330, val_loss=1.5008]

Upper model:  59%|█████▉    | 59/100 [00:05<00:02, 16.87epoch/s, loss=2.5967, val_loss=1.3711]

Upper model:  60%|██████    | 60/100 [00:05<00:02, 16.87epoch/s, loss=2.3510, val_loss=1.2506]

Upper model:  61%|██████    | 61/100 [00:05<00:02, 16.77epoch/s, loss=2.3510, val_loss=1.2506]

Upper model:  61%|██████    | 61/100 [00:05<00:02, 16.77epoch/s, loss=2.3968, val_loss=1.1456]

Upper model:  62%|██████▏   | 62/100 [00:05<00:02, 16.77epoch/s, loss=2.1614, val_loss=1.0566]

Upper model:  63%|██████▎   | 63/100 [00:05<00:02, 16.98epoch/s, loss=2.1614, val_loss=1.0566]

Upper model:  63%|██████▎   | 63/100 [00:05<00:02, 16.98epoch/s, loss=2.0202, val_loss=0.9870]

Upper model:  64%|██████▍   | 64/100 [00:05<00:02, 16.98epoch/s, loss=2.1518, val_loss=0.9231]

Upper model:  65%|██████▌   | 65/100 [00:05<00:02, 17.19epoch/s, loss=2.1518, val_loss=0.9231]

Upper model:  65%|██████▌   | 65/100 [00:06<00:02, 17.19epoch/s, loss=1.8271, val_loss=0.8765]

Upper model:  66%|██████▌   | 66/100 [00:06<00:01, 17.19epoch/s, loss=1.7953, val_loss=0.8394]

Upper model:  67%|██████▋   | 67/100 [00:06<00:02, 16.25epoch/s, loss=1.7953, val_loss=0.8394]

Upper model:  67%|██████▋   | 67/100 [00:06<00:02, 16.25epoch/s, loss=1.7674, val_loss=0.8081]

Upper model:  68%|██████▊   | 68/100 [00:06<00:01, 16.25epoch/s, loss=1.7320, val_loss=0.7824]

Upper model:  69%|██████▉   | 69/100 [00:06<00:01, 16.48epoch/s, loss=1.7320, val_loss=0.7824]

Upper model:  69%|██████▉   | 69/100 [00:06<00:01, 16.48epoch/s, loss=1.5659, val_loss=0.7604]

Upper model:  70%|███████   | 70/100 [00:06<00:01, 16.48epoch/s, loss=1.5672, val_loss=0.7397]

Upper model:  71%|███████   | 71/100 [00:06<00:01, 16.63epoch/s, loss=1.5672, val_loss=0.7397]

Upper model:  71%|███████   | 71/100 [00:06<00:01, 16.63epoch/s, loss=1.5544, val_loss=0.7230]

Upper model:  72%|███████▏  | 72/100 [00:06<00:01, 16.63epoch/s, loss=1.6637, val_loss=0.7128]

Upper model:  73%|███████▎  | 73/100 [00:06<00:01, 16.72epoch/s, loss=1.6637, val_loss=0.7128]

Upper model:  73%|███████▎  | 73/100 [00:06<00:01, 16.72epoch/s, loss=1.6136, val_loss=0.7023]

Upper model:  74%|███████▍  | 74/100 [00:06<00:01, 16.72epoch/s, loss=1.3511, val_loss=0.6930]

Upper model:  75%|███████▌  | 75/100 [00:06<00:01, 16.62epoch/s, loss=1.3511, val_loss=0.6930]

Upper model:  75%|███████▌  | 75/100 [00:06<00:01, 16.62epoch/s, loss=1.4602, val_loss=0.6849]

Upper model:  76%|███████▌  | 76/100 [00:06<00:01, 16.62epoch/s, loss=1.4777, val_loss=0.6767]

Upper model:  77%|███████▋  | 77/100 [00:06<00:01, 16.22epoch/s, loss=1.4777, val_loss=0.6767]

Upper model:  77%|███████▋  | 77/100 [00:06<00:01, 16.22epoch/s, loss=1.4411, val_loss=0.6684]

Upper model:  78%|███████▊  | 78/100 [00:06<00:01, 16.22epoch/s, loss=1.3922, val_loss=0.6616]

Upper model:  79%|███████▉  | 79/100 [00:06<00:01, 16.07epoch/s, loss=1.3922, val_loss=0.6616]

Upper model:  79%|███████▉  | 79/100 [00:06<00:01, 16.07epoch/s, loss=1.2808, val_loss=0.6568]

Upper model:  80%|████████  | 80/100 [00:07<00:01, 16.07epoch/s, loss=1.3075, val_loss=0.6567]

Upper model:  81%|████████  | 81/100 [00:07<00:01, 15.23epoch/s, loss=1.3075, val_loss=0.6567]

Upper model:  81%|████████  | 81/100 [00:07<00:01, 15.23epoch/s, loss=1.3196, val_loss=0.6581]

Upper model:  82%|████████▏ | 82/100 [00:07<00:01, 15.23epoch/s, loss=1.2295, val_loss=0.6601]

Upper model:  83%|████████▎ | 83/100 [00:07<00:01, 15.12epoch/s, loss=1.2295, val_loss=0.6601]

Upper model:  83%|████████▎ | 83/100 [00:07<00:01, 15.12epoch/s, loss=1.1935, val_loss=0.6624]

Upper model:  84%|████████▍ | 84/100 [00:07<00:01, 15.12epoch/s, loss=1.2794, val_loss=0.6657]

Upper model:  85%|████████▌ | 85/100 [00:07<00:01, 14.74epoch/s, loss=1.2794, val_loss=0.6657]

Upper model:  85%|████████▌ | 85/100 [00:07<00:01, 14.74epoch/s, loss=1.2636, val_loss=0.6691]

Upper model:  86%|████████▌ | 86/100 [00:07<00:00, 14.74epoch/s, loss=1.2579, val_loss=0.6707]

Upper model:  87%|████████▋ | 87/100 [00:07<00:00, 15.41epoch/s, loss=1.2579, val_loss=0.6707]

Upper model:  87%|████████▋ | 87/100 [00:07<00:00, 15.41epoch/s, loss=1.2190, val_loss=0.6722]

Upper model:  88%|████████▊ | 88/100 [00:07<00:00, 15.41epoch/s, loss=1.2153, val_loss=0.6737]

Upper model:  89%|████████▉ | 89/100 [00:07<00:00, 16.00epoch/s, loss=1.2153, val_loss=0.6737]

Upper model:  89%|████████▉ | 89/100 [00:07<00:00, 16.00epoch/s, loss=1.1314, val_loss=0.6754]

Upper model:  90%|█████████ | 90/100 [00:07<00:00, 16.00epoch/s, loss=1.2439, val_loss=0.6773]

Upper model:  91%|█████████ | 91/100 [00:07<00:00, 16.40epoch/s, loss=1.2439, val_loss=0.6773]

Upper model:  91%|█████████ | 91/100 [00:07<00:00, 11.93epoch/s, loss=1.2439, val_loss=0.6773]

Lower model:   0%|          | 0/100 [00:00<?, ?epoch/s]

I0000 00:00:1778435091.879571 2605134 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_32850__.19

I0000 00:00:1778435092.680705 2605127 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_32850__.19

Lower model:   0%|          | 0/100 [00:02<?, ?epoch/s, loss=0.3587, val_loss=0.3300]

Lower model:   1%|          | 1/100 [00:02<03:45,  2.28s/epoch, loss=0.3587, val_loss=0.3300]

Lower model:   1%|          | 1/100 [00:02<03:45,  2.28s/epoch, loss=0.3574, val_loss=0.3287]

Lower model:   2%|▏         | 2/100 [00:02<03:43,  2.28s/epoch, loss=0.3558, val_loss=0.3273]

Lower model:   3%|▎         | 3/100 [00:02<01:01,  1.58epoch/s, loss=0.3558, val_loss=0.3273]

Lower model:   3%|▎         | 3/100 [00:02<01:01,  1.58epoch/s, loss=0.3542, val_loss=0.3257]

Lower model:   4%|▍         | 4/100 [00:02<01:00,  1.58epoch/s, loss=0.3523, val_loss=0.3237]

Lower model:   5%|▌         | 5/100 [00:02<00:31,  2.97epoch/s, loss=0.3523, val_loss=0.3237]

Lower model:   5%|▌         | 5/100 [00:02<00:31,  2.97epoch/s, loss=0.3503, val_loss=0.3210]

Lower model:   6%|▌         | 6/100 [00:02<00:31,  2.97epoch/s, loss=0.3474, val_loss=0.3180]

Lower model:   7%|▋         | 7/100 [00:02<00:20,  4.59epoch/s, loss=0.3474, val_loss=0.3180]

Lower model:   7%|▋         | 7/100 [00:02<00:20,  4.59epoch/s, loss=0.3443, val_loss=0.3149]

Lower model:   8%|▊         | 8/100 [00:02<00:20,  4.59epoch/s, loss=0.3412, val_loss=0.3115]

Lower model:   9%|▉         | 9/100 [00:02<00:14,  6.18epoch/s, loss=0.3412, val_loss=0.3115]

Lower model:   9%|▉         | 9/100 [00:02<00:14,  6.18epoch/s, loss=0.3375, val_loss=0.3078]

Lower model:  10%|█         | 10/100 [00:02<00:14,  6.18epoch/s, loss=0.3342, val_loss=0.3039]

Lower model:  11%|█         | 11/100 [00:02<00:11,  7.96epoch/s, loss=0.3342, val_loss=0.3039]

Lower model:  11%|█         | 11/100 [00:02<00:11,  7.96epoch/s, loss=0.3305, val_loss=0.2998]

Lower model:  12%|█▏        | 12/100 [00:02<00:11,  7.96epoch/s, loss=0.3273, val_loss=0.2954]

Lower model:  13%|█▎        | 13/100 [00:02<00:08,  9.75epoch/s, loss=0.3273, val_loss=0.2954]

Lower model:  13%|█▎        | 13/100 [00:03<00:08,  9.75epoch/s, loss=0.3233, val_loss=0.2909]

Lower model:  14%|█▍        | 14/100 [00:03<00:08,  9.75epoch/s, loss=0.3225, val_loss=0.2868]

Lower model:  15%|█▌        | 15/100 [00:03<00:07, 11.33epoch/s, loss=0.3225, val_loss=0.2868]

Lower model:  15%|█▌        | 15/100 [00:03<00:07, 11.33epoch/s, loss=0.3181, val_loss=0.2831]

Lower model:  16%|█▌        | 16/100 [00:03<00:07, 11.33epoch/s, loss=0.3167, val_loss=0.2801]

Lower model:  17%|█▋        | 17/100 [00:03<00:06, 12.54epoch/s, loss=0.3167, val_loss=0.2801]

Lower model:  17%|█▋        | 17/100 [00:03<00:06, 12.54epoch/s, loss=0.3162, val_loss=0.2781]

Lower model:  18%|█▊        | 18/100 [00:03<00:06, 12.54epoch/s, loss=0.3154, val_loss=0.2768]

Lower model:  19%|█▉        | 19/100 [00:03<00:05, 13.64epoch/s, loss=0.3154, val_loss=0.2768]

Lower model:  19%|█▉        | 19/100 [00:03<00:05, 13.64epoch/s, loss=0.3146, val_loss=0.2758]

Lower model:  20%|██        | 20/100 [00:03<00:05, 13.64epoch/s, loss=0.3180, val_loss=0.2760]

Lower model:  21%|██        | 21/100 [00:03<00:05, 13.93epoch/s, loss=0.3180, val_loss=0.2760]

Lower model:  21%|██        | 21/100 [00:03<00:05, 13.93epoch/s, loss=0.3151, val_loss=0.2767]

Lower model:  22%|██▏       | 22/100 [00:03<00:05, 13.93epoch/s, loss=0.3139, val_loss=0.2772]

Lower model:  23%|██▎       | 23/100 [00:03<00:05, 14.40epoch/s, loss=0.3139, val_loss=0.2772]

Lower model:  23%|██▎       | 23/100 [00:03<00:05, 14.40epoch/s, loss=0.3153, val_loss=0.2774]

Lower model:  24%|██▍       | 24/100 [00:03<00:05, 14.40epoch/s, loss=0.3148, val_loss=0.2774]

Lower model:  25%|██▌       | 25/100 [00:03<00:04, 15.05epoch/s, loss=0.3148, val_loss=0.2774]

Lower model:  25%|██▌       | 25/100 [00:03<00:04, 15.05epoch/s, loss=0.3144, val_loss=0.2774]

Lower model:  26%|██▌       | 26/100 [00:03<00:04, 15.05epoch/s, loss=0.3166, val_loss=0.2773]

Lower model:  27%|██▋       | 27/100 [00:03<00:04, 15.76epoch/s, loss=0.3166, val_loss=0.2773]

Lower model:  27%|██▋       | 27/100 [00:03<00:04, 15.76epoch/s, loss=0.3160, val_loss=0.2774]

Lower model:  28%|██▊       | 28/100 [00:03<00:04, 15.76epoch/s, loss=0.3121, val_loss=0.2772]

Lower model:  29%|██▉       | 29/100 [00:03<00:04, 16.38epoch/s, loss=0.3121, val_loss=0.2772]

Lower model:  29%|██▉       | 29/100 [00:04<00:04, 16.38epoch/s, loss=0.3161, val_loss=0.2769]

Lower model:  30%|███       | 30/100 [00:04<00:09,  7.45epoch/s, loss=0.3161, val_loss=0.2769]

1/6 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step

1/6 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step

1/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

1/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

  > CQR Calibration constant (Q): -0.2152

Running configuration: Low:0.025 - High:0.975

Upper model:   0%|          | 0/100 [00:00<?, ?epoch/s]

I0000 00:00:1778435096.698539 2605134 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_36885__.19

I0000 00:00:1778435097.465545 2605134 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_36885__.19

Upper model:   0%|          | 0/100 [00:02<?, ?epoch/s, loss=17.6198, val_loss=16.1917]

Upper model:   1%|          | 1/100 [00:02<03:48,  2.31s/epoch, loss=17.6198, val_loss=16.1917]

Upper model:   1%|          | 1/100 [00:02<03:48,  2.31s/epoch, loss=17.5491, val_loss=16.1220]

Upper model:   2%|▏         | 2/100 [00:02<03:46,  2.31s/epoch, loss=17.4759, val_loss=16.0491]

Upper model:   3%|▎         | 3/100 [00:02<01:03,  1.53epoch/s, loss=17.4759, val_loss=16.0491]

Upper model:   3%|▎         | 3/100 [00:02<01:03,  1.53epoch/s, loss=17.3995, val_loss=15.9742]

Upper model:   4%|▍         | 4/100 [00:02<01:02,  1.53epoch/s, loss=17.3213, val_loss=15.8944]

Upper model:   5%|▌         | 5/100 [00:02<00:33,  2.86epoch/s, loss=17.3213, val_loss=15.8944]

Upper model:   5%|▌         | 5/100 [00:02<00:33,  2.86epoch/s, loss=17.2272, val_loss=15.8032]

Upper model:   6%|▌         | 6/100 [00:02<00:32,  2.86epoch/s, loss=17.1225, val_loss=15.6853]

Upper model:   7%|▋         | 7/100 [00:02<00:21,  4.38epoch/s, loss=17.1225, val_loss=15.6853]

Upper model:   7%|▋         | 7/100 [00:02<00:21,  4.38epoch/s, loss=16.9875, val_loss=15.5359]

Upper model:   8%|▊         | 8/100 [00:02<00:20,  4.38epoch/s, loss=16.8199, val_loss=15.3611]

Upper model:   9%|▉         | 9/100 [00:02<00:15,  5.98epoch/s, loss=16.8199, val_loss=15.3611]

Upper model:   9%|▉         | 9/100 [00:02<00:15,  5.98epoch/s, loss=16.6410, val_loss=15.1555]

Upper model:  10%|█         | 10/100 [00:02<00:15,  5.98epoch/s, loss=16.4032, val_loss=14.9295]

Upper model:  11%|█         | 11/100 [00:02<00:11,  7.70epoch/s, loss=16.4032, val_loss=14.9295]

Upper model:  11%|█         | 11/100 [00:03<00:11,  7.70epoch/s, loss=16.1667, val_loss=14.6855]

Upper model:  12%|█▏        | 12/100 [00:03<00:11,  7.70epoch/s, loss=15.9228, val_loss=14.4237]

Upper model:  13%|█▎        | 13/100 [00:03<00:09,  9.44epoch/s, loss=15.9228, val_loss=14.4237]

Upper model:  13%|█▎        | 13/100 [00:03<00:09,  9.44epoch/s, loss=15.6324, val_loss=14.1429]

Upper model:  14%|█▍        | 14/100 [00:03<00:09,  9.44epoch/s, loss=15.3467, val_loss=13.8421]

Upper model:  15%|█▌        | 15/100 [00:03<00:07, 10.82epoch/s, loss=15.3467, val_loss=13.8421]

Upper model:  15%|█▌        | 15/100 [00:03<00:07, 10.82epoch/s, loss=15.0490, val_loss=13.5221]

Upper model:  16%|█▌        | 16/100 [00:03<00:07, 10.82epoch/s, loss=14.6677, val_loss=13.1787]

Upper model:  17%|█▋        | 17/100 [00:03<00:06, 12.17epoch/s, loss=14.6677, val_loss=13.1787]

Upper model:  17%|█▋        | 17/100 [00:03<00:06, 12.17epoch/s, loss=14.2961, val_loss=12.8111]

Upper model:  18%|█▊        | 18/100 [00:03<00:06, 12.17epoch/s, loss=13.9531, val_loss=12.4230]

Upper model:  19%|█▉        | 19/100 [00:03<00:06, 13.43epoch/s, loss=13.9531, val_loss=12.4230]

Upper model:  19%|█▉        | 19/100 [00:03<00:06, 13.43epoch/s, loss=13.4997, val_loss=12.0114]

Upper model:  20%|██        | 20/100 [00:03<00:05, 13.43epoch/s, loss=13.1040, val_loss=11.5812]

Upper model:  21%|██        | 21/100 [00:03<00:05, 14.52epoch/s, loss=13.1040, val_loss=11.5812]

Upper model:  21%|██        | 21/100 [00:03<00:05, 14.52epoch/s, loss=12.6599, val_loss=11.1357]

Upper model:  22%|██▏       | 22/100 [00:03<00:05, 14.52epoch/s, loss=12.2694, val_loss=10.6738]

Upper model:  23%|██▎       | 23/100 [00:03<00:05, 15.30epoch/s, loss=12.2694, val_loss=10.6738]

Upper model:  23%|██▎       | 23/100 [00:03<00:05, 15.30epoch/s, loss=11.7131, val_loss=10.1993]

Upper model:  24%|██▍       | 24/100 [00:03<00:04, 15.30epoch/s, loss=11.2538, val_loss=9.7083]

Upper model:  25%|██▌       | 25/100 [00:03<00:04, 15.70epoch/s, loss=11.2538, val_loss=9.7083]

Upper model:  25%|██▌       | 25/100 [00:03<00:04, 15.70epoch/s, loss=10.7700, val_loss=9.2048]

Upper model:  26%|██▌       | 26/100 [00:03<00:04, 15.70epoch/s, loss=10.2311, val_loss=8.7063]

Upper model:  27%|██▋       | 27/100 [00:03<00:04, 16.18epoch/s, loss=10.2311, val_loss=8.7063]

Upper model:  27%|██▋       | 27/100 [00:03<00:04, 16.18epoch/s, loss=9.7655, val_loss=8.2107]

Upper model:  28%|██▊       | 28/100 [00:04<00:04, 16.18epoch/s, loss=9.2982, val_loss=7.7076]

Upper model:  29%|██▉       | 29/100 [00:04<00:04, 16.10epoch/s, loss=9.2982, val_loss=7.7076]

Upper model:  29%|██▉       | 29/100 [00:04<00:04, 16.10epoch/s, loss=8.8169, val_loss=7.2048]

Upper model:  30%|███       | 30/100 [00:04<00:04, 16.10epoch/s, loss=8.2741, val_loss=6.6981]

Upper model:  31%|███       | 31/100 [00:04<00:04, 15.96epoch/s, loss=8.2741, val_loss=6.6981]

Upper model:  31%|███       | 31/100 [00:04<00:04, 15.96epoch/s, loss=7.8228, val_loss=6.2050]

Upper model:  32%|███▏      | 32/100 [00:04<00:04, 15.96epoch/s, loss=7.3350, val_loss=5.7391]

Upper model:  33%|███▎      | 33/100 [00:04<00:04, 16.23epoch/s, loss=7.3350, val_loss=5.7391]

Upper model:  33%|███▎      | 33/100 [00:04<00:04, 16.23epoch/s, loss=6.9413, val_loss=5.2758]

Upper model:  34%|███▍      | 34/100 [00:04<00:04, 16.23epoch/s, loss=6.4174, val_loss=4.8351]

Upper model:  35%|███▌      | 35/100 [00:04<00:04, 15.80epoch/s, loss=6.4174, val_loss=4.8351]

Upper model:  35%|███▌      | 35/100 [00:04<00:04, 15.80epoch/s, loss=5.9834, val_loss=4.4193]

Upper model:  36%|███▌      | 36/100 [00:04<00:04, 15.80epoch/s, loss=5.5727, val_loss=4.0235]

Upper model:  37%|███▋      | 37/100 [00:04<00:03, 15.84epoch/s, loss=5.5727, val_loss=4.0235]

Upper model:  37%|███▋      | 37/100 [00:04<00:03, 15.84epoch/s, loss=5.1719, val_loss=3.6526]

Upper model:  38%|███▊      | 38/100 [00:04<00:03, 15.84epoch/s, loss=4.8276, val_loss=3.3239]

Upper model:  39%|███▉      | 39/100 [00:04<00:03, 15.94epoch/s, loss=4.8276, val_loss=3.3239]

Upper model:  39%|███▉      | 39/100 [00:04<00:03, 15.94epoch/s, loss=4.3649, val_loss=3.0089]

Upper model:  40%|████      | 40/100 [00:04<00:03, 15.94epoch/s, loss=3.9625, val_loss=2.6981]

Upper model:  41%|████      | 41/100 [00:04<00:03, 15.98epoch/s, loss=3.9625, val_loss=2.6981]

Upper model:  41%|████      | 41/100 [00:04<00:03, 15.98epoch/s, loss=3.6587, val_loss=2.3987]

Upper model:  42%|████▏     | 42/100 [00:04<00:03, 15.98epoch/s, loss=3.5158, val_loss=2.1232]

Upper model:  43%|████▎     | 43/100 [00:04<00:03, 16.21epoch/s, loss=3.5158, val_loss=2.1232]

Upper model:  43%|████▎     | 43/100 [00:04<00:03, 16.21epoch/s, loss=3.1414, val_loss=1.8674]

Upper model:  44%|████▍     | 44/100 [00:05<00:03, 16.21epoch/s, loss=2.8876, val_loss=1.6503]

Upper model:  45%|████▌     | 45/100 [00:05<00:03, 16.48epoch/s, loss=2.8876, val_loss=1.6503]

Upper model:  45%|████▌     | 45/100 [00:05<00:03, 16.48epoch/s, loss=2.6556, val_loss=1.4575]

Upper model:  46%|████▌     | 46/100 [00:05<00:03, 16.48epoch/s, loss=2.4582, val_loss=1.2950]

Upper model:  47%|████▋     | 47/100 [00:05<00:03, 16.44epoch/s, loss=2.4582, val_loss=1.2950]

Upper model:  47%|████▋     | 47/100 [00:05<00:03, 16.44epoch/s, loss=2.2341, val_loss=1.1478]

Upper model:  48%|████▊     | 48/100 [00:05<00:03, 16.44epoch/s, loss=2.0231, val_loss=1.0197]

Upper model:  49%|████▉     | 49/100 [00:05<00:03, 16.73epoch/s, loss=2.0231, val_loss=1.0197]

Upper model:  49%|████▉     | 49/100 [00:05<00:03, 16.73epoch/s, loss=1.8878, val_loss=0.9200]

Upper model:  50%|█████     | 50/100 [00:05<00:02, 16.73epoch/s, loss=1.8161, val_loss=0.8493]

Upper model:  51%|█████     | 51/100 [00:05<00:02, 16.88epoch/s, loss=1.8161, val_loss=0.8493]

Upper model:  51%|█████     | 51/100 [00:05<00:02, 16.88epoch/s, loss=1.7413, val_loss=0.7993]

Upper model:  52%|█████▏    | 52/100 [00:05<00:02, 16.88epoch/s, loss=1.6064, val_loss=0.7551]

Upper model:  53%|█████▎    | 53/100 [00:05<00:02, 16.77epoch/s, loss=1.6064, val_loss=0.7551]

Upper model:  53%|█████▎    | 53/100 [00:05<00:02, 16.77epoch/s, loss=1.4787, val_loss=0.7152]

Upper model:  54%|█████▍    | 54/100 [00:05<00:02, 16.77epoch/s, loss=1.4199, val_loss=0.6869]

Upper model:  55%|█████▌    | 55/100 [00:05<00:02, 16.76epoch/s, loss=1.4199, val_loss=0.6869]

Upper model:  55%|█████▌    | 55/100 [00:05<00:02, 16.76epoch/s, loss=1.4109, val_loss=0.6649]

Upper model:  56%|█████▌    | 56/100 [00:05<00:02, 16.76epoch/s, loss=1.2791, val_loss=0.6488]

Upper model:  57%|█████▋    | 57/100 [00:05<00:02, 16.75epoch/s, loss=1.2791, val_loss=0.6488]

Upper model:  57%|█████▋    | 57/100 [00:05<00:02, 16.75epoch/s, loss=1.3011, val_loss=0.6353]

Upper model:  58%|█████▊    | 58/100 [00:05<00:02, 16.75epoch/s, loss=1.2644, val_loss=0.6224]

Upper model:  59%|█████▉    | 59/100 [00:05<00:02, 16.70epoch/s, loss=1.2644, val_loss=0.6224]

Upper model:  59%|█████▉    | 59/100 [00:05<00:02, 16.70epoch/s, loss=1.1671, val_loss=0.6099]

Upper model:  60%|██████    | 60/100 [00:05<00:02, 16.70epoch/s, loss=1.1257, val_loss=0.5982]

Upper model:  61%|██████    | 61/100 [00:05<00:02, 16.74epoch/s, loss=1.1257, val_loss=0.5982]

Upper model:  61%|██████    | 61/100 [00:06<00:02, 16.74epoch/s, loss=1.1059, val_loss=0.5908]

Upper model:  62%|██████▏   | 62/100 [00:06<00:02, 16.74epoch/s, loss=1.1400, val_loss=0.5882]

Upper model:  63%|██████▎   | 63/100 [00:06<00:02, 16.36epoch/s, loss=1.1400, val_loss=0.5882]

Upper model:  63%|██████▎   | 63/100 [00:06<00:02, 16.36epoch/s, loss=1.0669, val_loss=0.5875]

Upper model:  64%|██████▍   | 64/100 [00:06<00:02, 16.36epoch/s, loss=1.1018, val_loss=0.5907]

Upper model:  65%|██████▌   | 65/100 [00:06<00:02, 16.66epoch/s, loss=1.1018, val_loss=0.5907]

Upper model:  65%|██████▌   | 65/100 [00:06<00:02, 16.66epoch/s, loss=0.9452, val_loss=0.5938]

Upper model:  66%|██████▌   | 66/100 [00:06<00:02, 16.66epoch/s, loss=1.1091, val_loss=0.5967]

Upper model:  67%|██████▋   | 67/100 [00:06<00:01, 16.89epoch/s, loss=1.1091, val_loss=0.5967]

Upper model:  67%|██████▋   | 67/100 [00:06<00:01, 16.89epoch/s, loss=1.0301, val_loss=0.5997]

Upper model:  68%|██████▊   | 68/100 [00:06<00:01, 16.89epoch/s, loss=1.0277, val_loss=0.6025]

Upper model:  69%|██████▉   | 69/100 [00:06<00:01, 16.98epoch/s, loss=1.0277, val_loss=0.6025]

Upper model:  69%|██████▉   | 69/100 [00:06<00:01, 16.98epoch/s, loss=0.9461, val_loss=0.6040]

Upper model:  70%|███████   | 70/100 [00:06<00:01, 16.98epoch/s, loss=0.9711, val_loss=0.6063]

Upper model:  71%|███████   | 71/100 [00:06<00:01, 17.28epoch/s, loss=0.9711, val_loss=0.6063]

Upper model:  71%|███████   | 71/100 [00:06<00:01, 17.28epoch/s, loss=0.9946, val_loss=0.6084]

Upper model:  72%|███████▏  | 72/100 [00:06<00:01, 17.28epoch/s, loss=0.9698, val_loss=0.6102]

Upper model:  73%|███████▎  | 73/100 [00:06<00:01, 17.13epoch/s, loss=0.9698, val_loss=0.6102]

Upper model:  73%|███████▎  | 73/100 [00:06<00:01, 17.13epoch/s, loss=0.9320, val_loss=0.6119]

Upper model:  74%|███████▍  | 74/100 [00:06<00:02, 10.98epoch/s, loss=0.9320, val_loss=0.6119]

Lower model:   0%|          | 0/100 [00:00<?, ?epoch/s]

I0000 00:00:1778435103.322040 2605131 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_42560__.19

I0000 00:00:1778435104.116067 2605134 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_42560__.19

Lower model:   0%|          | 0/100 [00:02<?, ?epoch/s, loss=0.4557, val_loss=0.4190]

Lower model:   1%|          | 1/100 [00:02<03:38,  2.20s/epoch, loss=0.4557, val_loss=0.4190]

Lower model:   1%|          | 1/100 [00:02<03:38,  2.20s/epoch, loss=0.4536, val_loss=0.4168]

Lower model:   2%|▏         | 2/100 [00:02<03:35,  2.20s/epoch, loss=0.4514, val_loss=0.4145]

Lower model:   3%|▎         | 3/100 [00:02<01:00,  1.61epoch/s, loss=0.4514, val_loss=0.4145]

Lower model:   3%|▎         | 3/100 [00:02<01:00,  1.61epoch/s, loss=0.4490, val_loss=0.4122]

Lower model:   4%|▍         | 4/100 [00:02<00:59,  1.61epoch/s, loss=0.4467, val_loss=0.4098]

Lower model:   5%|▌         | 5/100 [00:02<00:31,  3.01epoch/s, loss=0.4467, val_loss=0.4098]

Lower model:   5%|▌         | 5/100 [00:02<00:31,  3.01epoch/s, loss=0.4442, val_loss=0.4074]

Lower model:   6%|▌         | 6/100 [00:02<00:31,  3.01epoch/s, loss=0.4417, val_loss=0.4049]

Lower model:   7%|▋         | 7/100 [00:02<00:20,  4.57epoch/s, loss=0.4417, val_loss=0.4049]

Lower model:   7%|▋         | 7/100 [00:02<00:20,  4.57epoch/s, loss=0.4390, val_loss=0.4023]

Lower model:   8%|▊         | 8/100 [00:02<00:20,  4.57epoch/s, loss=0.4364, val_loss=0.3995]

Lower model:   9%|▉         | 9/100 [00:02<00:14,  6.20epoch/s, loss=0.4364, val_loss=0.3995]

Lower model:   9%|▉         | 9/100 [00:02<00:14,  6.20epoch/s, loss=0.4333, val_loss=0.3966]

Lower model:  10%|█         | 10/100 [00:02<00:14,  6.20epoch/s, loss=0.4307, val_loss=0.3934]

Lower model:  11%|█         | 11/100 [00:02<00:11,  7.99epoch/s, loss=0.4307, val_loss=0.3934]

Lower model:  11%|█         | 11/100 [00:02<00:11,  7.99epoch/s, loss=0.4271, val_loss=0.3901]

Lower model:  12%|█▏        | 12/100 [00:02<00:11,  7.99epoch/s, loss=0.4240, val_loss=0.3866]

Lower model:  13%|█▎        | 13/100 [00:02<00:09,  9.64epoch/s, loss=0.4240, val_loss=0.3866]

Lower model:  13%|█▎        | 13/100 [00:03<00:09,  9.64epoch/s, loss=0.4208, val_loss=0.3831]

Lower model:  14%|█▍        | 14/100 [00:03<00:08,  9.64epoch/s, loss=0.4186, val_loss=0.3794]

Lower model:  15%|█▌        | 15/100 [00:03<00:07, 11.10epoch/s, loss=0.4186, val_loss=0.3794]

Lower model:  15%|█▌        | 15/100 [00:03<00:07, 11.10epoch/s, loss=0.4141, val_loss=0.3755]

Lower model:  16%|█▌        | 16/100 [00:03<00:07, 11.10epoch/s, loss=0.4110, val_loss=0.3716]

Lower model:  17%|█▋        | 17/100 [00:03<00:06, 12.30epoch/s, loss=0.4110, val_loss=0.3716]

Lower model:  17%|█▋        | 17/100 [00:03<00:06, 12.30epoch/s, loss=0.4088, val_loss=0.3677]

Lower model:  18%|█▊        | 18/100 [00:03<00:06, 12.30epoch/s, loss=0.4054, val_loss=0.3642]

Lower model:  19%|█▉        | 19/100 [00:03<00:06, 13.35epoch/s, loss=0.4054, val_loss=0.3642]

Lower model:  19%|█▉        | 19/100 [00:03<00:06, 13.35epoch/s, loss=0.4040, val_loss=0.3609]

Lower model:  20%|██        | 20/100 [00:03<00:05, 13.35epoch/s, loss=0.4010, val_loss=0.3579]

Lower model:  21%|██        | 21/100 [00:03<00:05, 14.42epoch/s, loss=0.4010, val_loss=0.3579]

Lower model:  21%|██        | 21/100 [00:03<00:05, 14.42epoch/s, loss=0.3989, val_loss=0.3558]

Lower model:  22%|██▏       | 22/100 [00:03<00:05, 14.42epoch/s, loss=0.3970, val_loss=0.3539]

Lower model:  23%|██▎       | 23/100 [00:03<00:05, 15.10epoch/s, loss=0.3970, val_loss=0.3539]

Lower model:  23%|██▎       | 23/100 [00:03<00:05, 15.10epoch/s, loss=0.3974, val_loss=0.3521]

Lower model:  24%|██▍       | 24/100 [00:03<00:05, 15.10epoch/s, loss=0.3976, val_loss=0.3511]

Lower model:  25%|██▌       | 25/100 [00:03<00:04, 15.76epoch/s, loss=0.3976, val_loss=0.3511]

Lower model:  25%|██▌       | 25/100 [00:03<00:04, 15.76epoch/s, loss=0.4001, val_loss=0.3509]

Lower model:  26%|██▌       | 26/100 [00:03<00:04, 15.76epoch/s, loss=0.3993, val_loss=0.3508]

Lower model:  27%|██▋       | 27/100 [00:03<00:04, 16.14epoch/s, loss=0.3993, val_loss=0.3508]

Lower model:  27%|██▋       | 27/100 [00:03<00:04, 16.14epoch/s, loss=0.3976, val_loss=0.3511]

Lower model:  28%|██▊       | 28/100 [00:03<00:04, 16.14epoch/s, loss=0.3992, val_loss=0.3512]

Lower model:  29%|██▉       | 29/100 [00:03<00:04, 16.58epoch/s, loss=0.3992, val_loss=0.3512]

Lower model:  29%|██▉       | 29/100 [00:03<00:04, 16.58epoch/s, loss=0.3957, val_loss=0.3510]

Lower model:  30%|███       | 30/100 [00:04<00:04, 16.58epoch/s, loss=0.3949, val_loss=0.3507]

Lower model:  31%|███       | 31/100 [00:04<00:04, 16.89epoch/s, loss=0.3949, val_loss=0.3507]

Lower model:  31%|███       | 31/100 [00:04<00:04, 16.89epoch/s, loss=0.3970, val_loss=0.3506]

Lower model:  32%|███▏      | 32/100 [00:04<00:04, 16.89epoch/s, loss=0.3970, val_loss=0.3502]

Lower model:  33%|███▎      | 33/100 [00:04<00:03, 17.16epoch/s, loss=0.3970, val_loss=0.3502]

Lower model:  33%|███▎      | 33/100 [00:04<00:03, 17.16epoch/s, loss=0.3962, val_loss=0.3501]

Lower model:  34%|███▍      | 34/100 [00:04<00:03, 17.16epoch/s, loss=0.3941, val_loss=0.3499]

Lower model:  35%|███▌      | 35/100 [00:04<00:03, 17.03epoch/s, loss=0.3941, val_loss=0.3499]

Lower model:  35%|███▌      | 35/100 [00:04<00:03, 17.03epoch/s, loss=0.3918, val_loss=0.3495]

Lower model:  36%|███▌      | 36/100 [00:04<00:03, 17.03epoch/s, loss=0.3971, val_loss=0.3489]

Lower model:  37%|███▋      | 37/100 [00:04<00:03, 17.17epoch/s, loss=0.3971, val_loss=0.3489]

Lower model:  37%|███▋      | 37/100 [00:04<00:03, 17.17epoch/s, loss=0.3966, val_loss=0.3489]

Lower model:  38%|███▊      | 38/100 [00:04<00:03, 17.17epoch/s, loss=0.3924, val_loss=0.3489]

Lower model:  39%|███▉      | 39/100 [00:04<00:03, 17.31epoch/s, loss=0.3924, val_loss=0.3489]

Lower model:  39%|███▉      | 39/100 [00:04<00:03, 17.31epoch/s, loss=0.3949, val_loss=0.3484]

Lower model:  40%|████      | 40/100 [00:04<00:03, 17.31epoch/s, loss=0.3907, val_loss=0.3478]

Lower model:  41%|████      | 41/100 [00:04<00:03, 16.71epoch/s, loss=0.3907, val_loss=0.3478]

Lower model:  41%|████      | 41/100 [00:04<00:03, 16.71epoch/s, loss=0.3969, val_loss=0.3472]

Lower model:  42%|████▏     | 42/100 [00:04<00:03, 16.71epoch/s, loss=0.3954, val_loss=0.3470]

Lower model:  43%|████▎     | 43/100 [00:04<00:03, 16.68epoch/s, loss=0.3954, val_loss=0.3470]

Lower model:  43%|████▎     | 43/100 [00:04<00:03, 16.68epoch/s, loss=0.3905, val_loss=0.3465]

Lower model:  44%|████▍     | 44/100 [00:04<00:03, 16.68epoch/s, loss=0.3961, val_loss=0.3469]

Lower model:  45%|████▌     | 45/100 [00:04<00:03, 16.22epoch/s, loss=0.3961, val_loss=0.3469]

Lower model:  45%|████▌     | 45/100 [00:04<00:03, 16.22epoch/s, loss=0.3920, val_loss=0.3470]

Lower model:  46%|████▌     | 46/100 [00:04<00:03, 16.22epoch/s, loss=0.3943, val_loss=0.3464]

Lower model:  47%|████▋     | 47/100 [00:04<00:03, 16.36epoch/s, loss=0.3943, val_loss=0.3464]

Lower model:  47%|████▋     | 47/100 [00:05<00:03, 16.36epoch/s, loss=0.3938, val_loss=0.3463]

Lower model:  48%|████▊     | 48/100 [00:05<00:03, 16.36epoch/s, loss=0.3932, val_loss=0.3461]

Lower model:  49%|████▉     | 49/100 [00:05<00:03, 16.30epoch/s, loss=0.3932, val_loss=0.3461]

Lower model:  49%|████▉     | 49/100 [00:05<00:03, 16.30epoch/s, loss=0.3886, val_loss=0.3457]

Lower model:  50%|█████     | 50/100 [00:05<00:03, 16.30epoch/s, loss=0.3904, val_loss=0.3452]

Lower model:  51%|█████     | 51/100 [00:05<00:02, 16.46epoch/s, loss=0.3904, val_loss=0.3452]

Lower model:  51%|█████     | 51/100 [00:05<00:02, 16.46epoch/s, loss=0.3918, val_loss=0.3449]

Lower model:  52%|█████▏    | 52/100 [00:05<00:02, 16.46epoch/s, loss=0.3917, val_loss=0.3451]

Lower model:  53%|█████▎    | 53/100 [00:05<00:02, 16.10epoch/s, loss=0.3917, val_loss=0.3451]

Lower model:  53%|█████▎    | 53/100 [00:05<00:02, 16.10epoch/s, loss=0.3908, val_loss=0.3449]

Lower model:  54%|█████▍    | 54/100 [00:05<00:02, 16.10epoch/s, loss=0.3909, val_loss=0.3442]

Lower model:  55%|█████▌    | 55/100 [00:05<00:02, 16.51epoch/s, loss=0.3909, val_loss=0.3442]

Lower model:  55%|█████▌    | 55/100 [00:05<00:02, 16.51epoch/s, loss=0.3949, val_loss=0.3436]

Lower model:  56%|█████▌    | 56/100 [00:05<00:02, 16.51epoch/s, loss=0.3925, val_loss=0.3433]

Lower model:  57%|█████▋    | 57/100 [00:05<00:02, 16.77epoch/s, loss=0.3925, val_loss=0.3433]

Lower model:  57%|█████▋    | 57/100 [00:05<00:02, 16.77epoch/s, loss=0.3885, val_loss=0.3427]

Lower model:  58%|█████▊    | 58/100 [00:05<00:02, 16.77epoch/s, loss=0.3883, val_loss=0.3422]

Lower model:  59%|█████▉    | 59/100 [00:05<00:02, 16.78epoch/s, loss=0.3883, val_loss=0.3422]

Lower model:  59%|█████▉    | 59/100 [00:05<00:02, 16.78epoch/s, loss=0.3890, val_loss=0.3420]

Lower model:  60%|██████    | 60/100 [00:05<00:02, 16.78epoch/s, loss=0.3900, val_loss=0.3421]

Lower model:  61%|██████    | 61/100 [00:05<00:02, 16.26epoch/s, loss=0.3900, val_loss=0.3421]

Lower model:  61%|██████    | 61/100 [00:05<00:02, 16.26epoch/s, loss=0.3908, val_loss=0.3424]

Lower model:  62%|██████▏   | 62/100 [00:05<00:02, 16.26epoch/s, loss=0.3858, val_loss=0.3421]

Lower model:  63%|██████▎   | 63/100 [00:05<00:02, 16.43epoch/s, loss=0.3858, val_loss=0.3421]

Lower model:  63%|██████▎   | 63/100 [00:06<00:02, 16.43epoch/s, loss=0.3880, val_loss=0.3414]

Lower model:  64%|██████▍   | 64/100 [00:06<00:02, 16.43epoch/s, loss=0.3867, val_loss=0.3409]

Lower model:  65%|██████▌   | 65/100 [00:06<00:02, 16.73epoch/s, loss=0.3867, val_loss=0.3409]

Lower model:  65%|██████▌   | 65/100 [00:06<00:02, 16.73epoch/s, loss=0.3857, val_loss=0.3404]

Lower model:  66%|██████▌   | 66/100 [00:06<00:02, 16.73epoch/s, loss=0.3910, val_loss=0.3406]

Lower model:  67%|██████▋   | 67/100 [00:06<00:01, 16.97epoch/s, loss=0.3910, val_loss=0.3406]

Lower model:  67%|██████▋   | 67/100 [00:06<00:01, 16.97epoch/s, loss=0.3853, val_loss=0.3407]

Lower model:  68%|██████▊   | 68/100 [00:06<00:01, 16.97epoch/s, loss=0.3872, val_loss=0.3406]

Lower model:  69%|██████▉   | 69/100 [00:06<00:01, 17.16epoch/s, loss=0.3872, val_loss=0.3406]

Lower model:  69%|██████▉   | 69/100 [00:06<00:01, 17.16epoch/s, loss=0.3916, val_loss=0.3403]

Lower model:  70%|███████   | 70/100 [00:06<00:01, 17.16epoch/s, loss=0.3849, val_loss=0.3409]

Lower model:  71%|███████   | 71/100 [00:06<00:01, 17.25epoch/s, loss=0.3849, val_loss=0.3409]

Lower model:  71%|███████   | 71/100 [00:06<00:01, 17.25epoch/s, loss=0.3871, val_loss=0.3410]

Lower model:  72%|███████▏  | 72/100 [00:06<00:01, 17.25epoch/s, loss=0.3895, val_loss=0.3407]

Lower model:  73%|███████▎  | 73/100 [00:06<00:01, 17.33epoch/s, loss=0.3895, val_loss=0.3407]

Lower model:  73%|███████▎  | 73/100 [00:06<00:01, 17.33epoch/s, loss=0.3845, val_loss=0.3399]

Lower model:  74%|███████▍  | 74/100 [00:06<00:01, 17.33epoch/s, loss=0.3872, val_loss=0.3391]

Lower model:  75%|███████▌  | 75/100 [00:06<00:01, 17.35epoch/s, loss=0.3872, val_loss=0.3391]

Lower model:  75%|███████▌  | 75/100 [00:06<00:01, 17.35epoch/s, loss=0.3847, val_loss=0.3389]

Lower model:  76%|███████▌  | 76/100 [00:06<00:01, 17.35epoch/s, loss=0.3865, val_loss=0.3384]

Lower model:  77%|███████▋  | 77/100 [00:06<00:01, 16.97epoch/s, loss=0.3865, val_loss=0.3384]

Lower model:  77%|███████▋  | 77/100 [00:06<00:01, 16.97epoch/s, loss=0.3857, val_loss=0.3381]

Lower model:  78%|███████▊  | 78/100 [00:06<00:01, 16.97epoch/s, loss=0.3826, val_loss=0.3374]

Lower model:  79%|███████▉  | 79/100 [00:06<00:01, 17.18epoch/s, loss=0.3826, val_loss=0.3374]

Lower model:  79%|███████▉  | 79/100 [00:06<00:01, 17.18epoch/s, loss=0.3874, val_loss=0.3369]

Lower model:  80%|████████  | 80/100 [00:06<00:01, 17.18epoch/s, loss=0.3838, val_loss=0.3367]

Lower model:  81%|████████  | 81/100 [00:06<00:01, 17.34epoch/s, loss=0.3838, val_loss=0.3367]

Lower model:  81%|████████  | 81/100 [00:07<00:01, 17.34epoch/s, loss=0.3882, val_loss=0.3371]

Lower model:  82%|████████▏ | 82/100 [00:07<00:01, 17.34epoch/s, loss=0.3855, val_loss=0.3375]

Lower model:  83%|████████▎ | 83/100 [00:07<00:00, 17.48epoch/s, loss=0.3855, val_loss=0.3375]

Lower model:  83%|████████▎ | 83/100 [00:07<00:00, 17.48epoch/s, loss=0.3849, val_loss=0.3378]

Lower model:  84%|████████▍ | 84/100 [00:07<00:00, 17.48epoch/s, loss=0.3846, val_loss=0.3367]

Lower model:  85%|████████▌ | 85/100 [00:07<00:00, 17.45epoch/s, loss=0.3846, val_loss=0.3367]

Lower model:  85%|████████▌ | 85/100 [00:07<00:00, 17.45epoch/s, loss=0.3813, val_loss=0.3351]

Lower model:  86%|████████▌ | 86/100 [00:07<00:00, 17.45epoch/s, loss=0.3799, val_loss=0.3344]

Lower model:  87%|████████▋ | 87/100 [00:07<00:00, 17.37epoch/s, loss=0.3799, val_loss=0.3344]

Lower model:  87%|████████▋ | 87/100 [00:07<00:00, 17.37epoch/s, loss=0.3841, val_loss=0.3344]

Lower model:  88%|████████▊ | 88/100 [00:07<00:00, 17.37epoch/s, loss=0.3831, val_loss=0.3348]

Lower model:  89%|████████▉ | 89/100 [00:07<00:00, 17.15epoch/s, loss=0.3831, val_loss=0.3348]

Lower model:  89%|████████▉ | 89/100 [00:07<00:00, 17.15epoch/s, loss=0.3829, val_loss=0.3351]

Lower model:  90%|█████████ | 90/100 [00:07<00:00, 17.15epoch/s, loss=0.3820, val_loss=0.3356]

Lower model:  91%|█████████ | 91/100 [00:07<00:00, 17.33epoch/s, loss=0.3820, val_loss=0.3356]

Lower model:  91%|█████████ | 91/100 [00:07<00:00, 17.33epoch/s, loss=0.3847, val_loss=0.3353]

Lower model:  92%|█████████▏| 92/100 [00:07<00:00, 17.33epoch/s, loss=0.3847, val_loss=0.3348]

Lower model:  93%|█████████▎| 93/100 [00:07<00:00, 17.20epoch/s, loss=0.3847, val_loss=0.3348]

Lower model:  93%|█████████▎| 93/100 [00:07<00:00, 17.20epoch/s, loss=0.3803, val_loss=0.3347]

Lower model:  94%|█████████▍| 94/100 [00:07<00:00, 17.20epoch/s, loss=0.3827, val_loss=0.3345]

Lower model:  95%|█████████▌| 95/100 [00:07<00:00, 17.31epoch/s, loss=0.3827, val_loss=0.3345]

Lower model:  95%|█████████▌| 95/100 [00:07<00:00, 17.31epoch/s, loss=0.3829, val_loss=0.3344]

Lower model:  96%|█████████▌| 96/100 [00:07<00:00, 17.31epoch/s, loss=0.3816, val_loss=0.3340]

Lower model:  97%|█████████▋| 97/100 [00:07<00:00, 17.32epoch/s, loss=0.3816, val_loss=0.3340]

Lower model:  97%|█████████▋| 97/100 [00:07<00:00, 17.32epoch/s, loss=0.3808, val_loss=0.3336]

Lower model:  98%|█████████▊| 98/100 [00:08<00:00, 17.32epoch/s, loss=0.3865, val_loss=0.3338]

Lower model:  99%|█████████▉| 99/100 [00:08<00:00, 16.99epoch/s, loss=0.3865, val_loss=0.3338]

Lower model:  99%|█████████▉| 99/100 [00:08<00:00, 16.99epoch/s, loss=0.3824, val_loss=0.3344]

Lower model: 100%|██████████| 100/100 [00:08<00:00, 12.37epoch/s, loss=0.3824, val_loss=0.3344]

1/6 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step

1/6 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step

1/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

1/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

  > CQR Calibration constant (Q): -0.4215

Running configuration: Low:0.03 - High:0.98

Upper model:   0%|          | 0/100 [00:00<?, ?epoch/s]

I0000 00:00:1778435112.154107 2605134 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_50214__.19

I0000 00:00:1778435112.914978 2605127 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_50214__.19

Upper model:   0%|          | 0/100 [00:02<?, ?epoch/s, loss=18.0490, val_loss=16.6089]

Upper model:   1%|          | 1/100 [00:02<03:30,  2.13s/epoch, loss=18.0490, val_loss=16.6089]

Upper model:   1%|          | 1/100 [00:02<03:30,  2.13s/epoch, loss=17.9963, val_loss=16.5588]

Upper model:   2%|▏         | 2/100 [00:02<03:28,  2.13s/epoch, loss=17.9463, val_loss=16.5114]

Upper model:   3%|▎         | 3/100 [00:02<00:58,  1.67epoch/s, loss=17.9463, val_loss=16.5114]

Upper model:   3%|▎         | 3/100 [00:02<00:58,  1.67epoch/s, loss=17.9006, val_loss=16.4696]

Upper model:   4%|▍         | 4/100 [00:02<00:57,  1.67epoch/s, loss=17.8603, val_loss=16.4363]

Upper model:   5%|▌         | 5/100 [00:02<00:30,  3.11epoch/s, loss=17.8603, val_loss=16.4363]

Upper model:   5%|▌         | 5/100 [00:02<00:30,  3.11epoch/s, loss=17.8297, val_loss=16.4107]

Upper model:   6%|▌         | 6/100 [00:02<00:30,  3.11epoch/s, loss=17.8041, val_loss=16.3859]

Upper model:   7%|▋         | 7/100 [00:02<00:19,  4.76epoch/s, loss=17.8041, val_loss=16.3859]

Upper model:   7%|▋         | 7/100 [00:02<00:19,  4.76epoch/s, loss=17.7722, val_loss=16.3571]

Upper model:   8%|▊         | 8/100 [00:02<00:19,  4.76epoch/s, loss=17.7426, val_loss=16.3230]

Upper model:   9%|▉         | 9/100 [00:02<00:13,  6.52epoch/s, loss=17.7426, val_loss=16.3230]

Upper model:   9%|▉         | 9/100 [00:02<00:13,  6.52epoch/s, loss=17.7078, val_loss=16.2811]

Upper model:  10%|█         | 10/100 [00:02<00:13,  6.52epoch/s, loss=17.6625, val_loss=16.2302]

Upper model:  11%|█         | 11/100 [00:02<00:10,  8.37epoch/s, loss=17.6625, val_loss=16.2302]

Upper model:  11%|█         | 11/100 [00:02<00:10,  8.37epoch/s, loss=17.6077, val_loss=16.1642]

Upper model:  12%|█▏        | 12/100 [00:02<00:10,  8.37epoch/s, loss=17.5315, val_loss=16.0832]

Upper model:  13%|█▎        | 13/100 [00:02<00:08, 10.10epoch/s, loss=17.5315, val_loss=16.0832]

Upper model:  13%|█▎        | 13/100 [00:02<00:08, 10.10epoch/s, loss=17.4488, val_loss=15.9917]

Upper model:  14%|█▍        | 14/100 [00:02<00:08, 10.10epoch/s, loss=17.3589, val_loss=15.8925]

Upper model:  15%|█▌        | 15/100 [00:02<00:07, 11.68epoch/s, loss=17.3589, val_loss=15.8925]

Upper model:  15%|█▌        | 15/100 [00:03<00:07, 11.68epoch/s, loss=17.2412, val_loss=15.7844]

Upper model:  16%|█▌        | 16/100 [00:03<00:07, 11.68epoch/s, loss=17.1298, val_loss=15.6664]

Upper model:  17%|█▋        | 17/100 [00:03<00:06, 12.85epoch/s, loss=17.1298, val_loss=15.6664]

Upper model:  17%|█▋        | 17/100 [00:03<00:06, 12.85epoch/s, loss=17.0048, val_loss=15.5373]

Upper model:  18%|█▊        | 18/100 [00:03<00:06, 12.85epoch/s, loss=16.8548, val_loss=15.3948]

Upper model:  19%|█▉        | 19/100 [00:03<00:05, 14.03epoch/s, loss=16.8548, val_loss=15.3948]

Upper model:  19%|█▉        | 19/100 [00:03<00:05, 14.03epoch/s, loss=16.7106, val_loss=15.2387]

Upper model:  20%|██        | 20/100 [00:03<00:05, 14.03epoch/s, loss=16.5538, val_loss=15.0682]

Upper model:  21%|██        | 21/100 [00:03<00:05, 14.97epoch/s, loss=16.5538, val_loss=15.0682]

Upper model:  21%|██        | 21/100 [00:03<00:05, 14.97epoch/s, loss=16.3504, val_loss=14.8803]

Upper model:  22%|██▏       | 22/100 [00:03<00:05, 14.97epoch/s, loss=16.1775, val_loss=14.6758]

Upper model:  23%|██▎       | 23/100 [00:03<00:05, 15.30epoch/s, loss=16.1775, val_loss=14.6758]

Upper model:  23%|██▎       | 23/100 [00:03<00:05, 15.30epoch/s, loss=15.9420, val_loss=14.4530]

Upper model:  24%|██▍       | 24/100 [00:03<00:04, 15.30epoch/s, loss=15.7250, val_loss=14.2124]

Upper model:  25%|██▌       | 25/100 [00:03<00:04, 15.76epoch/s, loss=15.7250, val_loss=14.2124]

Upper model:  25%|██▌       | 25/100 [00:03<00:04, 15.76epoch/s, loss=15.4580, val_loss=13.9529]

Upper model:  26%|██▌       | 26/100 [00:03<00:04, 15.76epoch/s, loss=15.1982, val_loss=13.6750]

Upper model:  27%|██▋       | 27/100 [00:03<00:04, 16.03epoch/s, loss=15.1982, val_loss=13.6750]

Upper model:  27%|██▋       | 27/100 [00:03<00:04, 16.03epoch/s, loss=14.8746, val_loss=13.3755]

Upper model:  28%|██▊       | 28/100 [00:03<00:04, 16.03epoch/s, loss=14.6156, val_loss=13.0528]

Upper model:  29%|██▉       | 29/100 [00:03<00:04, 16.27epoch/s, loss=14.6156, val_loss=13.0528]

Upper model:  29%|██▉       | 29/100 [00:03<00:04, 16.27epoch/s, loss=14.2898, val_loss=12.7083]

Upper model:  30%|███       | 30/100 [00:03<00:04, 16.27epoch/s, loss=13.8940, val_loss=12.3392]

Upper model:  31%|███       | 31/100 [00:03<00:04, 16.37epoch/s, loss=13.8940, val_loss=12.3392]

Upper model:  31%|███       | 31/100 [00:03<00:04, 16.37epoch/s, loss=13.4994, val_loss=11.9440]

Upper model:  32%|███▏      | 32/100 [00:04<00:04, 16.37epoch/s, loss=13.0653, val_loss=11.5295]

Upper model:  33%|███▎      | 33/100 [00:04<00:04, 16.58epoch/s, loss=13.0653, val_loss=11.5295]

Upper model:  33%|███▎      | 33/100 [00:04<00:04, 16.58epoch/s, loss=12.6877, val_loss=11.0951]

Upper model:  34%|███▍      | 34/100 [00:04<00:03, 16.58epoch/s, loss=12.2234, val_loss=10.6441]

Upper model:  35%|███▌      | 35/100 [00:04<00:03, 16.34epoch/s, loss=12.2234, val_loss=10.6441]

Upper model:  35%|███▌      | 35/100 [00:04<00:03, 16.34epoch/s, loss=11.7907, val_loss=10.1802]

Upper model:  36%|███▌      | 36/100 [00:04<00:03, 16.34epoch/s, loss=11.3261, val_loss=9.7021]

Upper model:  37%|███▋      | 37/100 [00:04<00:03, 16.42epoch/s, loss=11.3261, val_loss=9.7021]

Upper model:  37%|███▋      | 37/100 [00:04<00:03, 16.42epoch/s, loss=10.9112, val_loss=9.2245]

Upper model:  38%|███▊      | 38/100 [00:04<00:03, 16.42epoch/s, loss=10.3179, val_loss=8.7517]

Upper model:  39%|███▉      | 39/100 [00:04<00:03, 16.25epoch/s, loss=10.3179, val_loss=8.7517]

Upper model:  39%|███▉      | 39/100 [00:04<00:03, 16.25epoch/s, loss=9.9545, val_loss=8.2766]

Upper model:  40%|████      | 40/100 [00:04<00:03, 16.25epoch/s, loss=9.3409, val_loss=7.8014]

Upper model:  41%|████      | 41/100 [00:04<00:03, 16.48epoch/s, loss=9.3409, val_loss=7.8014]

Upper model:  41%|████      | 41/100 [00:04<00:03, 16.48epoch/s, loss=8.9744, val_loss=7.3247]

Upper model:  42%|████▏     | 42/100 [00:04<00:03, 16.48epoch/s, loss=8.4156, val_loss=6.8665]

Upper model:  43%|████▎     | 43/100 [00:04<00:03, 16.59epoch/s, loss=8.4156, val_loss=6.8665]

Upper model:  43%|████▎     | 43/100 [00:04<00:03, 16.59epoch/s, loss=8.1283, val_loss=6.4317]

Upper model:  44%|████▍     | 44/100 [00:04<00:03, 16.59epoch/s, loss=7.7490, val_loss=6.0126]

Upper model:  45%|████▌     | 45/100 [00:04<00:03, 16.42epoch/s, loss=7.7490, val_loss=6.0126]

Upper model:  45%|████▌     | 45/100 [00:04<00:03, 16.42epoch/s, loss=7.1581, val_loss=5.6020]

Upper model:  46%|████▌     | 46/100 [00:04<00:03, 16.42epoch/s, loss=6.8784, val_loss=5.2145]

Upper model:  47%|████▋     | 47/100 [00:04<00:03, 16.17epoch/s, loss=6.8784, val_loss=5.2145]

Upper model:  47%|████▋     | 47/100 [00:04<00:03, 16.17epoch/s, loss=6.3958, val_loss=4.8532]

Upper model:  48%|████▊     | 48/100 [00:05<00:03, 16.17epoch/s, loss=6.0996, val_loss=4.5032]

Upper model:  49%|████▉     | 49/100 [00:05<00:03, 16.19epoch/s, loss=6.0996, val_loss=4.5032]

Upper model:  49%|████▉     | 49/100 [00:05<00:03, 16.19epoch/s, loss=5.6850, val_loss=4.1667]

Upper model:  50%|█████     | 50/100 [00:05<00:03, 16.19epoch/s, loss=5.3179, val_loss=3.8386]

Upper model:  51%|█████     | 51/100 [00:05<00:02, 16.43epoch/s, loss=5.3179, val_loss=3.8386]

Upper model:  51%|█████     | 51/100 [00:05<00:02, 16.43epoch/s, loss=4.9749, val_loss=3.5355]

Upper model:  52%|█████▏    | 52/100 [00:05<00:02, 16.43epoch/s, loss=4.6095, val_loss=3.2593]

Upper model:  53%|█████▎    | 53/100 [00:05<00:02, 16.10epoch/s, loss=4.6095, val_loss=3.2593]

Upper model:  53%|█████▎    | 53/100 [00:05<00:02, 16.10epoch/s, loss=4.5304, val_loss=2.9877]

Upper model:  54%|█████▍    | 54/100 [00:05<00:02, 16.10epoch/s, loss=4.1001, val_loss=2.7204]

Upper model:  55%|█████▌    | 55/100 [00:05<00:02, 15.51epoch/s, loss=4.1001, val_loss=2.7204]

Upper model:  55%|█████▌    | 55/100 [00:05<00:02, 15.51epoch/s, loss=3.8025, val_loss=2.4637]

Upper model:  56%|█████▌    | 56/100 [00:05<00:02, 15.51epoch/s, loss=3.5503, val_loss=2.2171]

Upper model:  57%|█████▋    | 57/100 [00:05<00:02, 15.80epoch/s, loss=3.5503, val_loss=2.2171]

Upper model:  57%|█████▋    | 57/100 [00:05<00:02, 15.80epoch/s, loss=3.3294, val_loss=1.9916]

Upper model:  58%|█████▊    | 58/100 [00:05<00:02, 15.80epoch/s, loss=2.9261, val_loss=1.7938]

Upper model:  59%|█████▉    | 59/100 [00:05<00:02, 16.08epoch/s, loss=2.9261, val_loss=1.7938]

Upper model:  59%|█████▉    | 59/100 [00:05<00:02, 16.08epoch/s, loss=2.7501, val_loss=1.6126]

Upper model:  60%|██████    | 60/100 [00:05<00:02, 16.08epoch/s, loss=2.8107, val_loss=1.4592]

Upper model:  61%|██████    | 61/100 [00:05<00:02, 16.51epoch/s, loss=2.8107, val_loss=1.4592]

Upper model:  61%|██████    | 61/100 [00:05<00:02, 16.51epoch/s, loss=2.6477, val_loss=1.3253]

Upper model:  62%|██████▏   | 62/100 [00:05<00:02, 16.51epoch/s, loss=2.2838, val_loss=1.2000]

Upper model:  63%|██████▎   | 63/100 [00:05<00:02, 15.04epoch/s, loss=2.2838, val_loss=1.2000]

Upper model:  63%|██████▎   | 63/100 [00:05<00:02, 15.04epoch/s, loss=2.2457, val_loss=1.0849]

Upper model:  64%|██████▍   | 64/100 [00:06<00:02, 15.04epoch/s, loss=2.1014, val_loss=0.9797]

Upper model:  65%|██████▌   | 65/100 [00:06<00:02, 15.52epoch/s, loss=2.1014, val_loss=0.9797]

Upper model:  65%|██████▌   | 65/100 [00:06<00:02, 15.52epoch/s, loss=2.0541, val_loss=0.8968]

Upper model:  66%|██████▌   | 66/100 [00:06<00:02, 15.52epoch/s, loss=1.8989, val_loss=0.8313]

Upper model:  67%|██████▋   | 67/100 [00:06<00:02, 15.96epoch/s, loss=1.8989, val_loss=0.8313]

Upper model:  67%|██████▋   | 67/100 [00:06<00:02, 15.96epoch/s, loss=1.7913, val_loss=0.7760]

Upper model:  68%|██████▊   | 68/100 [00:06<00:02, 15.96epoch/s, loss=1.7071, val_loss=0.7313]

Upper model:  69%|██████▉   | 69/100 [00:06<00:01, 15.94epoch/s, loss=1.7071, val_loss=0.7313]

Upper model:  69%|██████▉   | 69/100 [00:06<00:01, 15.94epoch/s, loss=1.6790, val_loss=0.6951]

Upper model:  70%|███████   | 70/100 [00:06<00:01, 15.94epoch/s, loss=1.5566, val_loss=0.6610]

Upper model:  71%|███████   | 71/100 [00:06<00:01, 15.91epoch/s, loss=1.5566, val_loss=0.6610]

Upper model:  71%|███████   | 71/100 [00:06<00:01, 15.91epoch/s, loss=1.4465, val_loss=0.6285]

Upper model:  72%|███████▏  | 72/100 [00:06<00:01, 15.91epoch/s, loss=1.5545, val_loss=0.6048]

Upper model:  73%|███████▎  | 73/100 [00:06<00:01, 16.18epoch/s, loss=1.5545, val_loss=0.6048]

Upper model:  73%|███████▎  | 73/100 [00:06<00:01, 16.18epoch/s, loss=1.3477, val_loss=0.5859]

Upper model:  74%|███████▍  | 74/100 [00:06<00:01, 16.18epoch/s, loss=1.3984, val_loss=0.5699]

Upper model:  75%|███████▌  | 75/100 [00:06<00:01, 16.54epoch/s, loss=1.3984, val_loss=0.5699]

Upper model:  75%|███████▌  | 75/100 [00:06<00:01, 16.54epoch/s, loss=1.3972, val_loss=0.5565]

Upper model:  76%|███████▌  | 76/100 [00:06<00:01, 16.54epoch/s, loss=1.3175, val_loss=0.5470]

Upper model:  77%|███████▋  | 77/100 [00:06<00:01, 16.33epoch/s, loss=1.3175, val_loss=0.5470]

Upper model:  77%|███████▋  | 77/100 [00:06<00:01, 16.33epoch/s, loss=1.2651, val_loss=0.5408]

Upper model:  78%|███████▊  | 78/100 [00:06<00:01, 16.33epoch/s, loss=1.2441, val_loss=0.5347]

Upper model:  79%|███████▉  | 79/100 [00:06<00:01, 16.54epoch/s, loss=1.2441, val_loss=0.5347]

Upper model:  79%|███████▉  | 79/100 [00:06<00:01, 16.54epoch/s, loss=1.4064, val_loss=0.5302]

Upper model:  80%|████████  | 80/100 [00:07<00:01, 16.54epoch/s, loss=1.1389, val_loss=0.5264]

Upper model:  81%|████████  | 81/100 [00:07<00:01, 15.82epoch/s, loss=1.1389, val_loss=0.5264]

Upper model:  81%|████████  | 81/100 [00:07<00:01, 15.82epoch/s, loss=1.0168, val_loss=0.5230]

Upper model:  82%|████████▏ | 82/100 [00:07<00:01, 15.82epoch/s, loss=1.0792, val_loss=0.5197]

Upper model:  83%|████████▎ | 83/100 [00:07<00:01, 15.78epoch/s, loss=1.0792, val_loss=0.5197]

Upper model:  83%|████████▎ | 83/100 [00:07<00:01, 15.78epoch/s, loss=1.1221, val_loss=0.5189]

Upper model:  84%|████████▍ | 84/100 [00:07<00:01, 15.78epoch/s, loss=1.1070, val_loss=0.5181]

Upper model:  85%|████████▌ | 85/100 [00:07<00:00, 15.49epoch/s, loss=1.1070, val_loss=0.5181]

Upper model:  85%|████████▌ | 85/100 [00:07<00:00, 15.49epoch/s, loss=0.9874, val_loss=0.5175]

Upper model:  86%|████████▌ | 86/100 [00:07<00:00, 15.49epoch/s, loss=1.0475, val_loss=0.5168]

Upper model:  87%|████████▋ | 87/100 [00:07<00:00, 15.85epoch/s, loss=1.0475, val_loss=0.5168]

Upper model:  87%|████████▋ | 87/100 [00:07<00:00, 15.85epoch/s, loss=1.0252, val_loss=0.5175]

Upper model:  88%|████████▊ | 88/100 [00:07<00:00, 15.85epoch/s, loss=0.9855, val_loss=0.5186]

Upper model:  89%|████████▉ | 89/100 [00:07<00:00, 16.43epoch/s, loss=0.9855, val_loss=0.5186]

Upper model:  89%|████████▉ | 89/100 [00:07<00:00, 16.43epoch/s, loss=1.0938, val_loss=0.5196]

Upper model:  90%|█████████ | 90/100 [00:07<00:00, 16.43epoch/s, loss=1.0266, val_loss=0.5207]

Upper model:  91%|█████████ | 91/100 [00:07<00:00, 16.01epoch/s, loss=1.0266, val_loss=0.5207]

Upper model:  91%|█████████ | 91/100 [00:07<00:00, 16.01epoch/s, loss=1.0102, val_loss=0.5231]

Upper model:  92%|█████████▏| 92/100 [00:07<00:00, 16.01epoch/s, loss=0.9449, val_loss=0.5243]

Upper model:  93%|█████████▎| 93/100 [00:07<00:00, 16.03epoch/s, loss=0.9449, val_loss=0.5243]

Upper model:  93%|█████████▎| 93/100 [00:07<00:00, 16.03epoch/s, loss=1.0361, val_loss=0.5254]

Upper model:  94%|█████████▍| 94/100 [00:07<00:00, 16.03epoch/s, loss=1.0536, val_loss=0.5265]

Upper model:  95%|█████████▌| 95/100 [00:07<00:00, 16.02epoch/s, loss=1.0536, val_loss=0.5265]

Upper model:  95%|█████████▌| 95/100 [00:07<00:00, 16.02epoch/s, loss=0.9642, val_loss=0.5275]

Upper model:  96%|█████████▌| 96/100 [00:08<00:00, 16.02epoch/s, loss=1.0059, val_loss=0.5285]

Upper model:  97%|█████████▋| 97/100 [00:08<00:00, 16.32epoch/s, loss=1.0059, val_loss=0.5285]

Upper model:  97%|█████████▋| 97/100 [00:08<00:00, 12.12epoch/s, loss=1.0059, val_loss=0.5285]

Lower model:   0%|          | 0/100 [00:00<?, ?epoch/s]

I0000 00:00:1778435120.169073 2605134 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_57154__.19

I0000 00:00:1778435120.950967 2605134 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_57154__.19

Lower model:   0%|          | 0/100 [00:02<?, ?epoch/s, loss=0.5450, val_loss=0.5009]

Lower model:   1%|          | 1/100 [00:02<03:35,  2.18s/epoch, loss=0.5450, val_loss=0.5009]

Lower model:   1%|          | 1/100 [00:02<03:35,  2.18s/epoch, loss=0.5430, val_loss=0.4991]

Lower model:   2%|▏         | 2/100 [00:02<03:33,  2.18s/epoch, loss=0.5414, val_loss=0.4975]

Lower model:   3%|▎         | 3/100 [00:02<00:58,  1.65epoch/s, loss=0.5414, val_loss=0.4975]

Lower model:   3%|▎         | 3/100 [00:02<00:58,  1.65epoch/s, loss=0.5397, val_loss=0.4959]

Lower model:   4%|▍         | 4/100 [00:02<00:58,  1.65epoch/s, loss=0.5380, val_loss=0.4942]

Lower model:   5%|▌         | 5/100 [00:02<00:30,  3.08epoch/s, loss=0.5380, val_loss=0.4942]

Lower model:   5%|▌         | 5/100 [00:02<00:30,  3.08epoch/s, loss=0.5363, val_loss=0.4925]

Lower model:   6%|▌         | 6/100 [00:02<00:30,  3.08epoch/s, loss=0.5347, val_loss=0.4905]

Lower model:   7%|▋         | 7/100 [00:02<00:19,  4.72epoch/s, loss=0.5347, val_loss=0.4905]

Lower model:   7%|▋         | 7/100 [00:02<00:19,  4.72epoch/s, loss=0.5324, val_loss=0.4883]

Lower model:   8%|▊         | 8/100 [00:02<00:19,  4.72epoch/s, loss=0.5300, val_loss=0.4858]

Lower model:   9%|▉         | 9/100 [00:02<00:14,  6.38epoch/s, loss=0.5300, val_loss=0.4858]

Lower model:   9%|▉         | 9/100 [00:02<00:14,  6.38epoch/s, loss=0.5272, val_loss=0.4829]

Lower model:  10%|█         | 10/100 [00:02<00:14,  6.38epoch/s, loss=0.5242, val_loss=0.4796]

Lower model:  11%|█         | 11/100 [00:02<00:10,  8.13epoch/s, loss=0.5242, val_loss=0.4796]

Lower model:  11%|█         | 11/100 [00:02<00:10,  8.13epoch/s, loss=0.5204, val_loss=0.4759]

Lower model:  12%|█▏        | 12/100 [00:02<00:10,  8.13epoch/s, loss=0.5167, val_loss=0.4717]

Lower model:  13%|█▎        | 13/100 [00:02<00:09,  9.57epoch/s, loss=0.5167, val_loss=0.4717]

Lower model:  13%|█▎        | 13/100 [00:02<00:09,  9.57epoch/s, loss=0.5125, val_loss=0.4670]

Lower model:  14%|█▍        | 14/100 [00:03<00:08,  9.57epoch/s, loss=0.5076, val_loss=0.4619]

Lower model:  15%|█▌        | 15/100 [00:03<00:07, 11.13epoch/s, loss=0.5076, val_loss=0.4619]

Lower model:  15%|█▌        | 15/100 [00:03<00:07, 11.13epoch/s, loss=0.5028, val_loss=0.4563]

Lower model:  16%|█▌        | 16/100 [00:03<00:07, 11.13epoch/s, loss=0.4975, val_loss=0.4503]

Lower model:  17%|█▋        | 17/100 [00:03<00:06, 12.56epoch/s, loss=0.4975, val_loss=0.4503]

Lower model:  17%|█▋        | 17/100 [00:03<00:06, 12.56epoch/s, loss=0.4926, val_loss=0.4439]

Lower model:  18%|█▊        | 18/100 [00:03<00:06, 12.56epoch/s, loss=0.4876, val_loss=0.4374]

Lower model:  19%|█▉        | 19/100 [00:03<00:05, 13.69epoch/s, loss=0.4876, val_loss=0.4374]

Lower model:  19%|█▉        | 19/100 [00:03<00:05, 13.69epoch/s, loss=0.4827, val_loss=0.4308]

Lower model:  20%|██        | 20/100 [00:03<00:05, 13.69epoch/s, loss=0.4793, val_loss=0.4250]

Lower model:  21%|██        | 21/100 [00:03<00:05, 14.45epoch/s, loss=0.4793, val_loss=0.4250]

Lower model:  21%|██        | 21/100 [00:03<00:05, 14.45epoch/s, loss=0.4743, val_loss=0.4210]

Lower model:  22%|██▏       | 22/100 [00:03<00:05, 14.45epoch/s, loss=0.4726, val_loss=0.4175]

Lower model:  23%|██▎       | 23/100 [00:03<00:05, 14.90epoch/s, loss=0.4726, val_loss=0.4175]

Lower model:  23%|██▎       | 23/100 [00:03<00:05, 14.90epoch/s, loss=0.4742, val_loss=0.4151]

Lower model:  24%|██▍       | 24/100 [00:03<00:05, 14.90epoch/s, loss=0.4691, val_loss=0.4140]

Lower model:  25%|██▌       | 25/100 [00:03<00:05, 15.00epoch/s, loss=0.4691, val_loss=0.4140]

Lower model:  25%|██▌       | 25/100 [00:03<00:05, 15.00epoch/s, loss=0.4708, val_loss=0.4127]

Lower model:  26%|██▌       | 26/100 [00:03<00:04, 15.00epoch/s, loss=0.4704, val_loss=0.4117]

Lower model:  27%|██▋       | 27/100 [00:03<00:04, 15.75epoch/s, loss=0.4704, val_loss=0.4117]

Lower model:  27%|██▋       | 27/100 [00:03<00:04, 15.75epoch/s, loss=0.4727, val_loss=0.4114]

Lower model:  28%|██▊       | 28/100 [00:03<00:04, 15.75epoch/s, loss=0.4698, val_loss=0.4115]

Lower model:  29%|██▉       | 29/100 [00:03<00:04, 16.17epoch/s, loss=0.4698, val_loss=0.4115]

Lower model:  29%|██▉       | 29/100 [00:03<00:04, 16.17epoch/s, loss=0.4734, val_loss=0.4115]

Lower model:  30%|███       | 30/100 [00:04<00:04, 16.17epoch/s, loss=0.4706, val_loss=0.4116]

Lower model:  31%|███       | 31/100 [00:04<00:04, 15.30epoch/s, loss=0.4706, val_loss=0.4116]

Lower model:  31%|███       | 31/100 [00:04<00:04, 15.30epoch/s, loss=0.4708, val_loss=0.4118]

Lower model:  32%|███▏      | 32/100 [00:04<00:04, 15.30epoch/s, loss=0.4680, val_loss=0.4115]

Lower model:  33%|███▎      | 33/100 [00:04<00:04, 15.52epoch/s, loss=0.4680, val_loss=0.4115]

Lower model:  33%|███▎      | 33/100 [00:04<00:04, 15.52epoch/s, loss=0.4666, val_loss=0.4114]

Lower model:  34%|███▍      | 34/100 [00:04<00:04, 15.52epoch/s, loss=0.4687, val_loss=0.4111]

Lower model:  35%|███▌      | 35/100 [00:04<00:04, 15.71epoch/s, loss=0.4687, val_loss=0.4111]

Lower model:  35%|███▌      | 35/100 [00:04<00:04, 15.71epoch/s, loss=0.4685, val_loss=0.4109]

Lower model:  36%|███▌      | 36/100 [00:04<00:04, 15.71epoch/s, loss=0.4672, val_loss=0.4105]

Lower model:  37%|███▋      | 37/100 [00:04<00:03, 16.20epoch/s, loss=0.4672, val_loss=0.4105]

Lower model:  37%|███▋      | 37/100 [00:04<00:03, 16.20epoch/s, loss=0.4681, val_loss=0.4105]

Lower model:  38%|███▊      | 38/100 [00:04<00:03, 16.20epoch/s, loss=0.4671, val_loss=0.4104]

Lower model:  39%|███▉      | 39/100 [00:04<00:03, 16.56epoch/s, loss=0.4671, val_loss=0.4104]

Lower model:  39%|███▉      | 39/100 [00:04<00:03, 16.56epoch/s, loss=0.4653, val_loss=0.4103]

Lower model:  40%|████      | 40/100 [00:04<00:03, 16.56epoch/s, loss=0.4654, val_loss=0.4104]

Lower model:  41%|████      | 41/100 [00:04<00:03, 16.72epoch/s, loss=0.4654, val_loss=0.4104]

Lower model:  41%|████      | 41/100 [00:04<00:03, 16.72epoch/s, loss=0.4716, val_loss=0.4106]

Lower model:  42%|████▏     | 42/100 [00:04<00:03, 16.72epoch/s, loss=0.4665, val_loss=0.4106]

Lower model:  43%|████▎     | 43/100 [00:04<00:03, 16.98epoch/s, loss=0.4665, val_loss=0.4106]

Lower model:  43%|████▎     | 43/100 [00:04<00:03, 16.98epoch/s, loss=0.4657, val_loss=0.4105]

Lower model:  44%|████▍     | 44/100 [00:04<00:03, 16.98epoch/s, loss=0.4645, val_loss=0.4102]

Lower model:  45%|████▌     | 45/100 [00:04<00:03, 16.78epoch/s, loss=0.4645, val_loss=0.4102]

Lower model:  45%|████▌     | 45/100 [00:04<00:03, 16.78epoch/s, loss=0.4634, val_loss=0.4099]

Lower model:  46%|████▌     | 46/100 [00:04<00:03, 16.78epoch/s, loss=0.4662, val_loss=0.4097]

Lower model:  47%|████▋     | 47/100 [00:04<00:03, 17.00epoch/s, loss=0.4662, val_loss=0.4097]

Lower model:  47%|████▋     | 47/100 [00:05<00:03, 17.00epoch/s, loss=0.4690, val_loss=0.4096]

Lower model:  48%|████▊     | 48/100 [00:05<00:03, 17.00epoch/s, loss=0.4672, val_loss=0.4094]

Lower model:  49%|████▉     | 49/100 [00:05<00:02, 17.05epoch/s, loss=0.4672, val_loss=0.4094]

Lower model:  49%|████▉     | 49/100 [00:05<00:02, 17.05epoch/s, loss=0.4688, val_loss=0.4092]

Lower model:  50%|█████     | 50/100 [00:05<00:02, 17.05epoch/s, loss=0.4651, val_loss=0.4089]

Lower model:  51%|█████     | 51/100 [00:05<00:02, 17.12epoch/s, loss=0.4651, val_loss=0.4089]

Lower model:  51%|█████     | 51/100 [00:05<00:02, 17.12epoch/s, loss=0.4679, val_loss=0.4087]

Lower model:  52%|█████▏    | 52/100 [00:05<00:02, 17.12epoch/s, loss=0.4655, val_loss=0.4084]

Lower model:  53%|█████▎    | 53/100 [00:05<00:02, 17.14epoch/s, loss=0.4655, val_loss=0.4084]

Lower model:  53%|█████▎    | 53/100 [00:05<00:02, 17.14epoch/s, loss=0.4675, val_loss=0.4082]

Lower model:  54%|█████▍    | 54/100 [00:05<00:02, 17.14epoch/s, loss=0.4650, val_loss=0.4081]

Lower model:  55%|█████▌    | 55/100 [00:05<00:02, 16.49epoch/s, loss=0.4650, val_loss=0.4081]

Lower model:  55%|█████▌    | 55/100 [00:05<00:02, 16.49epoch/s, loss=0.4671, val_loss=0.4080]

Lower model:  56%|█████▌    | 56/100 [00:05<00:02, 16.49epoch/s, loss=0.4684, val_loss=0.4079]

Lower model:  57%|█████▋    | 57/100 [00:05<00:02, 16.81epoch/s, loss=0.4684, val_loss=0.4079]

Lower model:  57%|█████▋    | 57/100 [00:05<00:02, 16.81epoch/s, loss=0.4633, val_loss=0.4077]

Lower model:  58%|█████▊    | 58/100 [00:05<00:02, 16.81epoch/s, loss=0.4675, val_loss=0.4074]

Lower model:  59%|█████▉    | 59/100 [00:05<00:02, 17.06epoch/s, loss=0.4675, val_loss=0.4074]

Lower model:  59%|█████▉    | 59/100 [00:05<00:02, 17.06epoch/s, loss=0.4659, val_loss=0.4073]

Lower model:  60%|██████    | 60/100 [00:05<00:02, 17.06epoch/s, loss=0.4656, val_loss=0.4071]

Lower model:  61%|██████    | 61/100 [00:05<00:02, 17.16epoch/s, loss=0.4656, val_loss=0.4071]

Lower model:  61%|██████    | 61/100 [00:05<00:02, 17.16epoch/s, loss=0.4666, val_loss=0.4071]

Lower model:  62%|██████▏   | 62/100 [00:05<00:02, 17.16epoch/s, loss=0.4638, val_loss=0.4070]

Lower model:  63%|██████▎   | 63/100 [00:05<00:02, 17.05epoch/s, loss=0.4638, val_loss=0.4070]

Lower model:  63%|██████▎   | 63/100 [00:05<00:02, 17.05epoch/s, loss=0.4665, val_loss=0.4069]

Lower model:  64%|██████▍   | 64/100 [00:06<00:02, 17.05epoch/s, loss=0.4641, val_loss=0.4068]

Lower model:  65%|██████▌   | 65/100 [00:06<00:02, 16.95epoch/s, loss=0.4641, val_loss=0.4068]

Lower model:  65%|██████▌   | 65/100 [00:06<00:02, 16.95epoch/s, loss=0.4653, val_loss=0.4069]

Lower model:  66%|██████▌   | 66/100 [00:06<00:02, 16.95epoch/s, loss=0.4608, val_loss=0.4069]

Lower model:  67%|██████▋   | 67/100 [00:06<00:01, 17.19epoch/s, loss=0.4608, val_loss=0.4069]

Lower model:  67%|██████▋   | 67/100 [00:06<00:01, 17.19epoch/s, loss=0.4632, val_loss=0.4068]

Lower model:  68%|██████▊   | 68/100 [00:06<00:01, 17.19epoch/s, loss=0.4654, val_loss=0.4067]

Lower model:  69%|██████▉   | 69/100 [00:06<00:01, 17.35epoch/s, loss=0.4654, val_loss=0.4067]

Lower model:  69%|██████▉   | 69/100 [00:06<00:01, 17.35epoch/s, loss=0.4636, val_loss=0.4067]

Lower model:  70%|███████   | 70/100 [00:06<00:01, 17.35epoch/s, loss=0.4654, val_loss=0.4067]

Lower model:  71%|███████   | 71/100 [00:06<00:01, 17.20epoch/s, loss=0.4654, val_loss=0.4067]

Lower model:  71%|███████   | 71/100 [00:06<00:01, 17.20epoch/s, loss=0.4601, val_loss=0.4067]

Lower model:  72%|███████▏  | 72/100 [00:06<00:01, 17.20epoch/s, loss=0.4619, val_loss=0.4066]

Lower model:  73%|███████▎  | 73/100 [00:06<00:01, 16.94epoch/s, loss=0.4619, val_loss=0.4066]

Lower model:  73%|███████▎  | 73/100 [00:06<00:01, 16.94epoch/s, loss=0.4616, val_loss=0.4062]

Lower model:  74%|███████▍  | 74/100 [00:06<00:01, 16.94epoch/s, loss=0.4646, val_loss=0.4059]

Lower model:  75%|███████▌  | 75/100 [00:06<00:01, 16.82epoch/s, loss=0.4646, val_loss=0.4059]

Lower model:  75%|███████▌  | 75/100 [00:06<00:01, 16.82epoch/s, loss=0.4651, val_loss=0.4059]

Lower model:  76%|███████▌  | 76/100 [00:06<00:01, 16.82epoch/s, loss=0.4579, val_loss=0.4057]

Lower model:  77%|███████▋  | 77/100 [00:06<00:01, 17.03epoch/s, loss=0.4579, val_loss=0.4057]

Lower model:  77%|███████▋  | 77/100 [00:06<00:01, 17.03epoch/s, loss=0.4618, val_loss=0.4056]

Lower model:  78%|███████▊  | 78/100 [00:06<00:01, 17.03epoch/s, loss=0.4583, val_loss=0.4052]

Lower model:  79%|███████▉  | 79/100 [00:06<00:01, 17.22epoch/s, loss=0.4583, val_loss=0.4052]

Lower model:  79%|███████▉  | 79/100 [00:06<00:01, 17.22epoch/s, loss=0.4619, val_loss=0.4049]

Lower model:  80%|████████  | 80/100 [00:06<00:01, 17.22epoch/s, loss=0.4622, val_loss=0.4048]

Lower model:  81%|████████  | 81/100 [00:06<00:01, 17.38epoch/s, loss=0.4622, val_loss=0.4048]

Lower model:  81%|████████  | 81/100 [00:07<00:01, 17.38epoch/s, loss=0.4626, val_loss=0.4048]

Lower model:  82%|████████▏ | 82/100 [00:07<00:01, 17.38epoch/s, loss=0.4610, val_loss=0.4048]

Lower model:  83%|████████▎ | 83/100 [00:07<00:00, 17.41epoch/s, loss=0.4610, val_loss=0.4048]

Lower model:  83%|████████▎ | 83/100 [00:07<00:00, 17.41epoch/s, loss=0.4648, val_loss=0.4047]

Lower model:  84%|████████▍ | 84/100 [00:07<00:00, 17.41epoch/s, loss=0.4624, val_loss=0.4046]

Lower model:  85%|████████▌ | 85/100 [00:07<00:00, 17.47epoch/s, loss=0.4624, val_loss=0.4046]

Lower model:  85%|████████▌ | 85/100 [00:07<00:00, 17.47epoch/s, loss=0.4632, val_loss=0.4045]

Lower model:  86%|████████▌ | 86/100 [00:07<00:00, 17.47epoch/s, loss=0.4656, val_loss=0.4044]

Lower model:  87%|████████▋ | 87/100 [00:07<00:00, 17.26epoch/s, loss=0.4656, val_loss=0.4044]

Lower model:  87%|████████▋ | 87/100 [00:07<00:00, 17.26epoch/s, loss=0.4648, val_loss=0.4044]

Lower model:  88%|████████▊ | 88/100 [00:07<00:00, 17.26epoch/s, loss=0.4628, val_loss=0.4045]

Lower model:  89%|████████▉ | 89/100 [00:07<00:00, 17.16epoch/s, loss=0.4628, val_loss=0.4045]

Lower model:  89%|████████▉ | 89/100 [00:07<00:00, 17.16epoch/s, loss=0.4615, val_loss=0.4044]

Lower model:  90%|█████████ | 90/100 [00:07<00:00, 17.16epoch/s, loss=0.4571, val_loss=0.4043]

Lower model:  91%|█████████ | 91/100 [00:07<00:00, 16.79epoch/s, loss=0.4571, val_loss=0.4043]

Lower model:  91%|█████████ | 91/100 [00:07<00:00, 16.79epoch/s, loss=0.4608, val_loss=0.4041]

Lower model:  92%|█████████▏| 92/100 [00:07<00:00, 16.79epoch/s, loss=0.4615, val_loss=0.4039]

Lower model:  93%|█████████▎| 93/100 [00:07<00:00, 16.52epoch/s, loss=0.4615, val_loss=0.4039]

Lower model:  93%|█████████▎| 93/100 [00:07<00:00, 16.52epoch/s, loss=0.4663, val_loss=0.4038]

Lower model:  94%|█████████▍| 94/100 [00:07<00:00, 16.52epoch/s, loss=0.4597, val_loss=0.4037]

Lower model:  95%|█████████▌| 95/100 [00:07<00:00, 16.13epoch/s, loss=0.4597, val_loss=0.4037]

Lower model:  95%|█████████▌| 95/100 [00:07<00:00, 16.13epoch/s, loss=0.4639, val_loss=0.4037]

Lower model:  96%|█████████▌| 96/100 [00:07<00:00, 16.13epoch/s, loss=0.4642, val_loss=0.4038]

Lower model:  97%|█████████▋| 97/100 [00:07<00:00, 16.09epoch/s, loss=0.4642, val_loss=0.4038]

Lower model:  97%|█████████▋| 97/100 [00:07<00:00, 16.09epoch/s, loss=0.4610, val_loss=0.4038]

Lower model:  98%|█████████▊| 98/100 [00:08<00:00, 16.09epoch/s, loss=0.4593, val_loss=0.4037]

Lower model:  99%|█████████▉| 99/100 [00:08<00:00, 16.24epoch/s, loss=0.4593, val_loss=0.4037]

Lower model:  99%|█████████▉| 99/100 [00:08<00:00, 16.24epoch/s, loss=0.4650, val_loss=0.4037]

Lower model: 100%|██████████| 100/100 [00:08<00:00, 12.35epoch/s, loss=0.4650, val_loss=0.4037]

1/6 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step

1/6 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step

1/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

1/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

  > CQR Calibration constant (Q): -0.2576

Running configuration: Low:0.04 - High:0.99

Upper model:   0%|          | 0/100 [00:00<?, ?epoch/s]

I0000 00:00:1778435129.029440 2605127 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_64886__.19

I0000 00:00:1778435129.815604 2605127 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_64886__.19

Upper model:   0%|          | 0/100 [00:02<?, ?epoch/s, loss=18.3549, val_loss=16.8926]

Upper model:   1%|          | 1/100 [00:02<03:33,  2.16s/epoch, loss=18.3549, val_loss=16.8926]

Upper model:   1%|          | 1/100 [00:02<03:33,  2.16s/epoch, loss=18.2855, val_loss=16.8224]

Upper model:   2%|▏         | 2/100 [00:02<03:31,  2.16s/epoch, loss=18.2092, val_loss=16.7517]

Upper model:   3%|▎         | 3/100 [00:02<00:58,  1.65epoch/s, loss=18.2092, val_loss=16.7517]

Upper model:   3%|▎         | 3/100 [00:02<00:58,  1.65epoch/s, loss=18.1352, val_loss=16.6775]

Upper model:   4%|▍         | 4/100 [00:02<00:58,  1.65epoch/s, loss=18.0551, val_loss=16.5947]

Upper model:   5%|▌         | 5/100 [00:02<00:31,  3.05epoch/s, loss=18.0551, val_loss=16.5947]

Upper model:   5%|▌         | 5/100 [00:02<00:31,  3.05epoch/s, loss=17.9708, val_loss=16.5000]

Upper model:   6%|▌         | 6/100 [00:02<00:30,  3.05epoch/s, loss=17.8653, val_loss=16.3951]

Upper model:   7%|▋         | 7/100 [00:02<00:20,  4.59epoch/s, loss=17.8653, val_loss=16.3951]

Upper model:   7%|▋         | 7/100 [00:02<00:20,  4.59epoch/s, loss=17.7563, val_loss=16.2807]

Upper model:   8%|▊         | 8/100 [00:02<00:20,  4.59epoch/s, loss=17.6371, val_loss=16.1548]

Upper model:   9%|▉         | 9/100 [00:02<00:14,  6.33epoch/s, loss=17.6371, val_loss=16.1548]

Upper model:   9%|▉         | 9/100 [00:02<00:14,  6.33epoch/s, loss=17.5017, val_loss=16.0195]

Upper model:  10%|█         | 10/100 [00:02<00:14,  6.33epoch/s, loss=17.3587, val_loss=15.8730]

Upper model:  11%|█         | 11/100 [00:02<00:11,  7.99epoch/s, loss=17.3587, val_loss=15.8730]

Upper model:  11%|█         | 11/100 [00:02<00:11,  7.99epoch/s, loss=17.1997, val_loss=15.7139]

Upper model:  12%|█▏        | 12/100 [00:02<00:11,  7.99epoch/s, loss=17.0335, val_loss=15.5424]

Upper model:  13%|█▎        | 13/100 [00:02<00:09,  9.49epoch/s, loss=17.0335, val_loss=15.5424]

Upper model:  13%|█▎        | 13/100 [00:02<00:09,  9.49epoch/s, loss=16.8619, val_loss=15.3573]

Upper model:  14%|█▍        | 14/100 [00:03<00:09,  9.49epoch/s, loss=16.6523, val_loss=15.1565]

Upper model:  15%|█▌        | 15/100 [00:03<00:07, 10.88epoch/s, loss=16.6523, val_loss=15.1565]

Upper model:  15%|█▌        | 15/100 [00:03<00:07, 10.88epoch/s, loss=16.4447, val_loss=14.9373]

Upper model:  16%|█▌        | 16/100 [00:03<00:07, 10.88epoch/s, loss=16.2134, val_loss=14.6987]

Upper model:  17%|█▋        | 17/100 [00:03<00:06, 12.19epoch/s, loss=16.2134, val_loss=14.6987]

Upper model:  17%|█▋        | 17/100 [00:03<00:06, 12.19epoch/s, loss=15.9413, val_loss=14.4382]

Upper model:  18%|█▊        | 18/100 [00:03<00:06, 12.19epoch/s, loss=15.6634, val_loss=14.1546]

Upper model:  19%|█▉        | 19/100 [00:03<00:06, 13.50epoch/s, loss=15.6634, val_loss=14.1546]

Upper model:  19%|█▉        | 19/100 [00:03<00:06, 13.50epoch/s, loss=15.3567, val_loss=13.8486]

Upper model:  20%|██        | 20/100 [00:03<00:05, 13.50epoch/s, loss=15.0495, val_loss=13.5205]

Upper model:  21%|██        | 21/100 [00:03<00:05, 14.45epoch/s, loss=15.0495, val_loss=13.5205]

Upper model:  21%|██        | 21/100 [00:03<00:05, 14.45epoch/s, loss=14.7128, val_loss=13.1673]

Upper model:  22%|██▏       | 22/100 [00:03<00:05, 14.45epoch/s, loss=14.3233, val_loss=12.7910]

Upper model:  23%|██▎       | 23/100 [00:03<00:05, 14.94epoch/s, loss=14.3233, val_loss=12.7910]

Upper model:  23%|██▎       | 23/100 [00:03<00:05, 14.94epoch/s, loss=13.9761, val_loss=12.3919]

Upper model:  24%|██▍       | 24/100 [00:03<00:05, 14.94epoch/s, loss=13.4862, val_loss=11.9674]

Upper model:  25%|██▌       | 25/100 [00:03<00:04, 15.49epoch/s, loss=13.4862, val_loss=11.9674]

Upper model:  25%|██▌       | 25/100 [00:03<00:04, 15.49epoch/s, loss=13.1363, val_loss=11.5272]

Upper model:  26%|██▌       | 26/100 [00:03<00:04, 15.49epoch/s, loss=12.5964, val_loss=11.0685]

Upper model:  27%|██▋       | 27/100 [00:03<00:04, 15.55epoch/s, loss=12.5964, val_loss=11.0685]

Upper model:  27%|██▋       | 27/100 [00:03<00:04, 15.55epoch/s, loss=12.2165, val_loss=10.5967]

Upper model:  28%|██▊       | 28/100 [00:03<00:04, 15.55epoch/s, loss=11.6638, val_loss=10.1053]

Upper model:  29%|██▉       | 29/100 [00:03<00:04, 15.95epoch/s, loss=11.6638, val_loss=10.1053]

Upper model:  29%|██▉       | 29/100 [00:03<00:04, 15.95epoch/s, loss=11.1541, val_loss=9.5932]

Upper model:  30%|███       | 30/100 [00:04<00:04, 15.95epoch/s, loss=10.6907, val_loss=9.0691]

Upper model:  31%|███       | 31/100 [00:04<00:04, 15.11epoch/s, loss=10.6907, val_loss=9.0691]

Upper model:  31%|███       | 31/100 [00:04<00:04, 15.11epoch/s, loss=10.1157, val_loss=8.5584]

Upper model:  32%|███▏      | 32/100 [00:04<00:04, 15.11epoch/s, loss=9.5475, val_loss=8.0382]

Upper model:  33%|███▎      | 33/100 [00:04<00:04, 14.31epoch/s, loss=9.5475, val_loss=8.0382]

Upper model:  33%|███▎      | 33/100 [00:04<00:04, 14.31epoch/s, loss=9.0976, val_loss=7.5204]

Upper model:  34%|███▍      | 34/100 [00:04<00:04, 14.31epoch/s, loss=8.6694, val_loss=7.0091]

Upper model:  35%|███▌      | 35/100 [00:04<00:04, 14.73epoch/s, loss=8.6694, val_loss=7.0091]

Upper model:  35%|███▌      | 35/100 [00:04<00:04, 14.73epoch/s, loss=8.1139, val_loss=6.5056]

Upper model:  36%|███▌      | 36/100 [00:04<00:04, 14.73epoch/s, loss=7.6942, val_loss=6.0294]

Upper model:  37%|███▋      | 37/100 [00:04<00:04, 14.89epoch/s, loss=7.6942, val_loss=6.0294]

Upper model:  37%|███▋      | 37/100 [00:04<00:04, 14.89epoch/s, loss=7.1720, val_loss=5.5621]

Upper model:  38%|███▊      | 38/100 [00:04<00:04, 14.89epoch/s, loss=6.7300, val_loss=5.1034]

Upper model:  39%|███▉      | 39/100 [00:04<00:03, 15.49epoch/s, loss=6.7300, val_loss=5.1034]

Upper model:  39%|███▉      | 39/100 [00:04<00:03, 15.49epoch/s, loss=6.2207, val_loss=4.6781]

Upper model:  40%|████      | 40/100 [00:04<00:03, 15.49epoch/s, loss=5.8763, val_loss=4.2752]

Upper model:  41%|████      | 41/100 [00:04<00:03, 15.90epoch/s, loss=5.8763, val_loss=4.2752]

Upper model:  41%|████      | 41/100 [00:04<00:03, 15.90epoch/s, loss=5.4737, val_loss=3.8916]

Upper model:  42%|████▏     | 42/100 [00:04<00:03, 15.90epoch/s, loss=5.0140, val_loss=3.5307]

Upper model:  43%|████▎     | 43/100 [00:04<00:03, 16.20epoch/s, loss=5.0140, val_loss=3.5307]

Upper model:  43%|████▎     | 43/100 [00:04<00:03, 16.20epoch/s, loss=4.6417, val_loss=3.2088]

Upper model:  44%|████▍     | 44/100 [00:04<00:03, 16.20epoch/s, loss=4.2102, val_loss=2.8866]

Upper model:  45%|████▌     | 45/100 [00:04<00:03, 16.24epoch/s, loss=4.2102, val_loss=2.8866]

Upper model:  45%|████▌     | 45/100 [00:04<00:03, 16.24epoch/s, loss=3.9586, val_loss=2.5722]

Upper model:  46%|████▌     | 46/100 [00:05<00:03, 16.24epoch/s, loss=3.5102, val_loss=2.2708]

Upper model:  47%|████▋     | 47/100 [00:05<00:03, 16.29epoch/s, loss=3.5102, val_loss=2.2708]

Upper model:  47%|████▋     | 47/100 [00:05<00:03, 16.29epoch/s, loss=3.2967, val_loss=1.9910]

Upper model:  48%|████▊     | 48/100 [00:05<00:03, 16.29epoch/s, loss=3.1055, val_loss=1.7303]

Upper model:  49%|████▉     | 49/100 [00:05<00:03, 16.16epoch/s, loss=3.1055, val_loss=1.7303]

Upper model:  49%|████▉     | 49/100 [00:05<00:03, 16.16epoch/s, loss=2.7400, val_loss=1.5085]

Upper model:  50%|█████     | 50/100 [00:05<00:03, 16.16epoch/s, loss=2.5680, val_loss=1.3160]

Upper model:  51%|█████     | 51/100 [00:05<00:03, 16.20epoch/s, loss=2.5680, val_loss=1.3160]

Upper model:  51%|█████     | 51/100 [00:05<00:03, 16.20epoch/s, loss=2.3944, val_loss=1.1381]

Upper model:  52%|█████▏    | 52/100 [00:05<00:02, 16.20epoch/s, loss=2.0688, val_loss=0.9779]

Upper model:  53%|█████▎    | 53/100 [00:05<00:02, 16.10epoch/s, loss=2.0688, val_loss=0.9779]

Upper model:  53%|█████▎    | 53/100 [00:05<00:02, 16.10epoch/s, loss=1.9917, val_loss=0.8477]

Upper model:  54%|█████▍    | 54/100 [00:05<00:02, 16.10epoch/s, loss=1.7897, val_loss=0.7452]

Upper model:  55%|█████▌    | 55/100 [00:05<00:02, 16.42epoch/s, loss=1.7897, val_loss=0.7452]

Upper model:  55%|█████▌    | 55/100 [00:05<00:02, 16.42epoch/s, loss=1.6908, val_loss=0.6627]

Upper model:  56%|█████▌    | 56/100 [00:05<00:02, 16.42epoch/s, loss=1.5729, val_loss=0.5981]

Upper model:  57%|█████▋    | 57/100 [00:05<00:02, 15.44epoch/s, loss=1.5729, val_loss=0.5981]

Upper model:  57%|█████▋    | 57/100 [00:05<00:02, 15.44epoch/s, loss=1.4203, val_loss=0.5436]

Upper model:  58%|█████▊    | 58/100 [00:05<00:02, 15.44epoch/s, loss=1.2383, val_loss=0.4973]

Upper model:  59%|█████▉    | 59/100 [00:05<00:02, 15.51epoch/s, loss=1.2383, val_loss=0.4973]

Upper model:  59%|█████▉    | 59/100 [00:05<00:02, 15.51epoch/s, loss=1.2392, val_loss=0.4546]

Upper model:  60%|██████    | 60/100 [00:05<00:02, 15.51epoch/s, loss=1.1550, val_loss=0.4238]

Upper model:  61%|██████    | 61/100 [00:05<00:02, 15.66epoch/s, loss=1.1550, val_loss=0.4238]

Upper model:  61%|██████    | 61/100 [00:06<00:02, 15.66epoch/s, loss=1.1575, val_loss=0.3982]

Upper model:  62%|██████▏   | 62/100 [00:06<00:02, 15.66epoch/s, loss=1.0374, val_loss=0.3754]

Upper model:  63%|██████▎   | 63/100 [00:06<00:02, 15.54epoch/s, loss=1.0374, val_loss=0.3754]

Upper model:  63%|██████▎   | 63/100 [00:06<00:02, 15.54epoch/s, loss=0.9352, val_loss=0.3542]

Upper model:  64%|██████▍   | 64/100 [00:06<00:02, 15.54epoch/s, loss=0.9897, val_loss=0.3332]

Upper model:  65%|██████▌   | 65/100 [00:06<00:02, 15.84epoch/s, loss=0.9897, val_loss=0.3332]

Upper model:  65%|██████▌   | 65/100 [00:06<00:02, 15.84epoch/s, loss=0.8512, val_loss=0.3157]

Upper model:  66%|██████▌   | 66/100 [00:06<00:02, 15.84epoch/s, loss=0.9291, val_loss=0.3072]

Upper model:  67%|██████▋   | 67/100 [00:06<00:02, 16.03epoch/s, loss=0.9291, val_loss=0.3072]

Upper model:  67%|██████▋   | 67/100 [00:06<00:02, 16.03epoch/s, loss=0.8142, val_loss=0.3015]

Upper model:  68%|██████▊   | 68/100 [00:06<00:01, 16.03epoch/s, loss=0.6849, val_loss=0.2986]

Upper model:  69%|██████▉   | 69/100 [00:06<00:01, 16.17epoch/s, loss=0.6849, val_loss=0.2986]

Upper model:  69%|██████▉   | 69/100 [00:06<00:01, 16.17epoch/s, loss=0.7625, val_loss=0.2957]

Upper model:  70%|███████   | 70/100 [00:06<00:01, 16.17epoch/s, loss=0.7310, val_loss=0.2940]

Upper model:  71%|███████   | 71/100 [00:06<00:01, 14.96epoch/s, loss=0.7310, val_loss=0.2940]

Upper model:  71%|███████   | 71/100 [00:06<00:01, 14.96epoch/s, loss=0.7000, val_loss=0.2936]

Upper model:  72%|███████▏  | 72/100 [00:06<00:01, 14.96epoch/s, loss=0.6867, val_loss=0.2933]

Upper model:  73%|███████▎  | 73/100 [00:06<00:01, 15.21epoch/s, loss=0.6867, val_loss=0.2933]

Upper model:  73%|███████▎  | 73/100 [00:06<00:01, 15.21epoch/s, loss=0.7479, val_loss=0.2929]

Upper model:  74%|███████▍  | 74/100 [00:06<00:01, 15.21epoch/s, loss=0.7192, val_loss=0.2925]

Upper model:  75%|███████▌  | 75/100 [00:06<00:01, 15.54epoch/s, loss=0.7192, val_loss=0.2925]

Upper model:  75%|███████▌  | 75/100 [00:06<00:01, 15.54epoch/s, loss=0.7258, val_loss=0.2922]

Upper model:  76%|███████▌  | 76/100 [00:06<00:01, 15.54epoch/s, loss=0.5914, val_loss=0.2918]

Upper model:  77%|███████▋  | 77/100 [00:06<00:01, 15.68epoch/s, loss=0.5914, val_loss=0.2918]

Upper model:  77%|███████▋  | 77/100 [00:07<00:01, 15.68epoch/s, loss=0.6167, val_loss=0.2915]

Upper model:  78%|███████▊  | 78/100 [00:07<00:01, 15.68epoch/s, loss=0.5451, val_loss=0.2911]

Upper model:  79%|███████▉  | 79/100 [00:07<00:01, 16.07epoch/s, loss=0.5451, val_loss=0.2911]

Upper model:  79%|███████▉  | 79/100 [00:07<00:01, 16.07epoch/s, loss=0.5619, val_loss=0.2908]

Upper model:  80%|████████  | 80/100 [00:07<00:01, 16.07epoch/s, loss=0.5237, val_loss=0.2904]

Upper model:  81%|████████  | 81/100 [00:07<00:01, 16.32epoch/s, loss=0.5237, val_loss=0.2904]

Upper model:  81%|████████  | 81/100 [00:07<00:01, 16.32epoch/s, loss=0.5683, val_loss=0.2902]

Upper model:  82%|████████▏ | 82/100 [00:07<00:01, 16.32epoch/s, loss=0.5500, val_loss=0.2899]

Upper model:  83%|████████▎ | 83/100 [00:07<00:01, 16.24epoch/s, loss=0.5500, val_loss=0.2899]

Upper model:  83%|████████▎ | 83/100 [00:07<00:01, 16.24epoch/s, loss=0.5561, val_loss=0.2897]

Upper model:  84%|████████▍ | 84/100 [00:07<00:00, 16.24epoch/s, loss=0.5214, val_loss=0.2895]

Upper model:  85%|████████▌ | 85/100 [00:07<00:00, 16.46epoch/s, loss=0.5214, val_loss=0.2895]

Upper model:  85%|████████▌ | 85/100 [00:07<00:00, 16.46epoch/s, loss=0.5659, val_loss=0.2892]

Upper model:  86%|████████▌ | 86/100 [00:07<00:00, 16.46epoch/s, loss=0.4867, val_loss=0.2889]

Upper model:  87%|████████▋ | 87/100 [00:07<00:00, 16.45epoch/s, loss=0.4867, val_loss=0.2889]

Upper model:  87%|████████▋ | 87/100 [00:07<00:00, 16.45epoch/s, loss=0.6184, val_loss=0.2887]

Upper model:  88%|████████▊ | 88/100 [00:07<00:00, 16.45epoch/s, loss=0.4761, val_loss=0.2885]

Upper model:  89%|████████▉ | 89/100 [00:07<00:00, 16.78epoch/s, loss=0.4761, val_loss=0.2885]

Upper model:  89%|████████▉ | 89/100 [00:07<00:00, 16.78epoch/s, loss=0.5824, val_loss=0.2883]

Upper model:  90%|█████████ | 90/100 [00:07<00:00, 16.78epoch/s, loss=0.4848, val_loss=0.2881]

Upper model:  91%|█████████ | 91/100 [00:07<00:00, 16.33epoch/s, loss=0.4848, val_loss=0.2881]

Upper model:  91%|█████████ | 91/100 [00:07<00:00, 16.33epoch/s, loss=0.5588, val_loss=0.2878]

Upper model:  92%|█████████▏| 92/100 [00:07<00:00, 16.33epoch/s, loss=0.5709, val_loss=0.2876]

Upper model:  93%|█████████▎| 93/100 [00:07<00:00, 16.61epoch/s, loss=0.5709, val_loss=0.2876]

Upper model:  93%|█████████▎| 93/100 [00:07<00:00, 16.61epoch/s, loss=0.4229, val_loss=0.2873]

Upper model:  94%|█████████▍| 94/100 [00:08<00:00, 16.61epoch/s, loss=0.4856, val_loss=0.2871]

Upper model:  95%|█████████▌| 95/100 [00:08<00:00, 15.71epoch/s, loss=0.4856, val_loss=0.2871]

Upper model:  95%|█████████▌| 95/100 [00:08<00:00, 15.71epoch/s, loss=0.5585, val_loss=0.2869]

Upper model:  96%|█████████▌| 96/100 [00:08<00:00, 15.71epoch/s, loss=0.4931, val_loss=0.2868]

Upper model:  97%|█████████▋| 97/100 [00:08<00:00, 16.02epoch/s, loss=0.4931, val_loss=0.2868]

Upper model:  97%|█████████▋| 97/100 [00:08<00:00, 16.02epoch/s, loss=0.4976, val_loss=0.2866]

Upper model:  98%|█████████▊| 98/100 [00:08<00:00, 16.02epoch/s, loss=0.4885, val_loss=0.2864]

Upper model:  99%|█████████▉| 99/100 [00:08<00:00, 15.62epoch/s, loss=0.4885, val_loss=0.2864]

Upper model:  99%|█████████▉| 99/100 [00:08<00:00, 15.62epoch/s, loss=0.5177, val_loss=0.2862]

Upper model: 100%|██████████| 100/100 [00:08<00:00, 11.92epoch/s, loss=0.5177, val_loss=0.2862]

Lower model:   0%|          | 0/100 [00:00<?, ?epoch/s]

I0000 00:00:1778435137.413145 2605133 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_72105__.19

I0000 00:00:1778435138.168762 2605133 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_72105__.19

Lower model:   0%|          | 0/100 [00:02<?, ?epoch/s, loss=0.7271, val_loss=0.6693]

Lower model:   1%|          | 1/100 [00:02<03:30,  2.13s/epoch, loss=0.7271, val_loss=0.6693]

Lower model:   1%|          | 1/100 [00:02<03:30,  2.13s/epoch, loss=0.7250, val_loss=0.6670]

Lower model:   2%|▏         | 2/100 [00:02<03:28,  2.13s/epoch, loss=0.7226, val_loss=0.6647]

Lower model:   3%|▎         | 3/100 [00:02<00:57,  1.68epoch/s, loss=0.7226, val_loss=0.6647]

Lower model:   3%|▎         | 3/100 [00:02<00:57,  1.68epoch/s, loss=0.7205, val_loss=0.6624]

Lower model:   4%|▍         | 4/100 [00:02<00:57,  1.68epoch/s, loss=0.7183, val_loss=0.6599]

Lower model:   5%|▌         | 5/100 [00:02<00:30,  3.13epoch/s, loss=0.7183, val_loss=0.6599]

Lower model:   5%|▌         | 5/100 [00:02<00:30,  3.13epoch/s, loss=0.7153, val_loss=0.6573]

Lower model:   6%|▌         | 6/100 [00:02<00:30,  3.13epoch/s, loss=0.7127, val_loss=0.6545]

Lower model:   7%|▋         | 7/100 [00:02<00:19,  4.77epoch/s, loss=0.7127, val_loss=0.6545]

Lower model:   7%|▋         | 7/100 [00:02<00:19,  4.77epoch/s, loss=0.7097, val_loss=0.6516]

Lower model:   8%|▊         | 8/100 [00:02<00:19,  4.77epoch/s, loss=0.7067, val_loss=0.6484]

Lower model:   9%|▉         | 9/100 [00:02<00:14,  6.46epoch/s, loss=0.7067, val_loss=0.6484]

Lower model:   9%|▉         | 9/100 [00:02<00:14,  6.46epoch/s, loss=0.7031, val_loss=0.6450]

Lower model:  10%|█         | 10/100 [00:02<00:13,  6.46epoch/s, loss=0.7000, val_loss=0.6414]

Lower model:  11%|█         | 11/100 [00:02<00:10,  8.16epoch/s, loss=0.7000, val_loss=0.6414]

Lower model:  11%|█         | 11/100 [00:02<00:10,  8.16epoch/s, loss=0.6961, val_loss=0.6374]

Lower model:  12%|█▏        | 12/100 [00:02<00:10,  8.16epoch/s, loss=0.6915, val_loss=0.6332]

Lower model:  13%|█▎        | 13/100 [00:02<00:08,  9.81epoch/s, loss=0.6915, val_loss=0.6332]

Lower model:  13%|█▎        | 13/100 [00:02<00:08,  9.81epoch/s, loss=0.6876, val_loss=0.6286]

Lower model:  14%|█▍        | 14/100 [00:02<00:08,  9.81epoch/s, loss=0.6827, val_loss=0.6236]

Lower model:  15%|█▌        | 15/100 [00:02<00:07, 10.99epoch/s, loss=0.6827, val_loss=0.6236]

Lower model:  15%|█▌        | 15/100 [00:03<00:07, 10.99epoch/s, loss=0.6773, val_loss=0.6182]

Lower model:  16%|█▌        | 16/100 [00:03<00:07, 10.99epoch/s, loss=0.6715, val_loss=0.6123]

Lower model:  17%|█▋        | 17/100 [00:03<00:06, 12.25epoch/s, loss=0.6715, val_loss=0.6123]

Lower model:  17%|█▋        | 17/100 [00:03<00:06, 12.25epoch/s, loss=0.6662, val_loss=0.6059]

Lower model:  18%|█▊        | 18/100 [00:03<00:06, 12.25epoch/s, loss=0.6600, val_loss=0.5986]

Lower model:  19%|█▉        | 19/100 [00:03<00:06, 13.19epoch/s, loss=0.6600, val_loss=0.5986]

Lower model:  19%|█▉        | 19/100 [00:03<00:06, 13.19epoch/s, loss=0.6528, val_loss=0.5905]

Lower model:  20%|██        | 20/100 [00:03<00:06, 13.19epoch/s, loss=0.6436, val_loss=0.5806]

Lower model:  21%|██        | 21/100 [00:03<00:05, 14.16epoch/s, loss=0.6436, val_loss=0.5806]

Lower model:  21%|██        | 21/100 [00:03<00:05, 14.16epoch/s, loss=0.6392, val_loss=0.5688]

Lower model:  22%|██▏       | 22/100 [00:03<00:05, 14.16epoch/s, loss=0.6306, val_loss=0.5588]

Lower model:  23%|██▎       | 23/100 [00:03<00:05, 14.70epoch/s, loss=0.6306, val_loss=0.5588]

Lower model:  23%|██▎       | 23/100 [00:03<00:05, 14.70epoch/s, loss=0.6209, val_loss=0.5504]

Lower model:  24%|██▍       | 24/100 [00:03<00:05, 14.70epoch/s, loss=0.6240, val_loss=0.5443]

Lower model:  25%|██▌       | 25/100 [00:03<00:04, 15.21epoch/s, loss=0.6240, val_loss=0.5443]

Lower model:  25%|██▌       | 25/100 [00:03<00:04, 15.21epoch/s, loss=0.6198, val_loss=0.5410]

Lower model:  26%|██▌       | 26/100 [00:03<00:04, 15.21epoch/s, loss=0.6242, val_loss=0.5385]

Lower model:  27%|██▋       | 27/100 [00:03<00:04, 15.75epoch/s, loss=0.6242, val_loss=0.5385]

Lower model:  27%|██▋       | 27/100 [00:03<00:04, 15.75epoch/s, loss=0.6211, val_loss=0.5386]

Lower model:  28%|██▊       | 28/100 [00:03<00:04, 15.75epoch/s, loss=0.6095, val_loss=0.5381]

Lower model:  29%|██▉       | 29/100 [00:03<00:04, 16.09epoch/s, loss=0.6095, val_loss=0.5381]

Lower model:  29%|██▉       | 29/100 [00:03<00:04, 16.09epoch/s, loss=0.6137, val_loss=0.5369]

Lower model:  30%|███       | 30/100 [00:03<00:04, 16.09epoch/s, loss=0.6155, val_loss=0.5353]

Lower model:  31%|███       | 31/100 [00:03<00:04, 15.99epoch/s, loss=0.6155, val_loss=0.5353]

Lower model:  31%|███       | 31/100 [00:04<00:04, 15.99epoch/s, loss=0.6141, val_loss=0.5344]

Lower model:  32%|███▏      | 32/100 [00:04<00:04, 15.99epoch/s, loss=0.6086, val_loss=0.5332]

Lower model:  33%|███▎      | 33/100 [00:04<00:04, 16.36epoch/s, loss=0.6086, val_loss=0.5332]

Lower model:  33%|███▎      | 33/100 [00:04<00:04, 16.36epoch/s, loss=0.6108, val_loss=0.5326]

Lower model:  34%|███▍      | 34/100 [00:04<00:04, 16.36epoch/s, loss=0.6125, val_loss=0.5325]

Lower model:  35%|███▌      | 35/100 [00:04<00:04, 16.21epoch/s, loss=0.6125, val_loss=0.5325]

Lower model:  35%|███▌      | 35/100 [00:04<00:04, 16.21epoch/s, loss=0.6005, val_loss=0.5318]

Lower model:  36%|███▌      | 36/100 [00:04<00:03, 16.21epoch/s, loss=0.6057, val_loss=0.5304]

Lower model:  37%|███▋      | 37/100 [00:04<00:03, 16.29epoch/s, loss=0.6057, val_loss=0.5304]

Lower model:  37%|███▋      | 37/100 [00:04<00:03, 16.29epoch/s, loss=0.6099, val_loss=0.5296]

Lower model:  38%|███▊      | 38/100 [00:04<00:03, 16.29epoch/s, loss=0.6062, val_loss=0.5292]

Lower model:  39%|███▉      | 39/100 [00:04<00:03, 16.20epoch/s, loss=0.6062, val_loss=0.5292]

Lower model:  39%|███▉      | 39/100 [00:04<00:03, 16.20epoch/s, loss=0.5989, val_loss=0.5277]

Lower model:  40%|████      | 40/100 [00:04<00:03, 16.20epoch/s, loss=0.6064, val_loss=0.5265]

Lower model:  41%|████      | 41/100 [00:04<00:03, 16.04epoch/s, loss=0.6064, val_loss=0.5265]

Lower model:  41%|████      | 41/100 [00:04<00:03, 16.04epoch/s, loss=0.6064, val_loss=0.5260]

Lower model:  42%|████▏     | 42/100 [00:04<00:03, 16.04epoch/s, loss=0.6056, val_loss=0.5267]

Lower model:  43%|████▎     | 43/100 [00:04<00:03, 16.00epoch/s, loss=0.6056, val_loss=0.5267]

Lower model:  43%|████▎     | 43/100 [00:04<00:03, 16.00epoch/s, loss=0.6047, val_loss=0.5266]

Lower model:  44%|████▍     | 44/100 [00:04<00:03, 16.00epoch/s, loss=0.6062, val_loss=0.5254]

Lower model:  45%|████▌     | 45/100 [00:04<00:03, 15.83epoch/s, loss=0.6062, val_loss=0.5254]

Lower model:  45%|████▌     | 45/100 [00:04<00:03, 15.83epoch/s, loss=0.5940, val_loss=0.5242]

Lower model:  46%|████▌     | 46/100 [00:04<00:03, 15.83epoch/s, loss=0.6058, val_loss=0.5232]

Lower model:  47%|████▋     | 47/100 [00:04<00:03, 16.09epoch/s, loss=0.6058, val_loss=0.5232]

Lower model:  47%|████▋     | 47/100 [00:05<00:03, 16.09epoch/s, loss=0.6021, val_loss=0.5231]

Lower model:  48%|████▊     | 48/100 [00:05<00:03, 16.09epoch/s, loss=0.6017, val_loss=0.5223]

Lower model:  49%|████▉     | 49/100 [00:05<00:03, 16.14epoch/s, loss=0.6017, val_loss=0.5223]

Lower model:  49%|████▉     | 49/100 [00:05<00:03, 16.14epoch/s, loss=0.6022, val_loss=0.5224]

Lower model:  50%|█████     | 50/100 [00:05<00:03, 16.14epoch/s, loss=0.6005, val_loss=0.5225]

Lower model:  51%|█████     | 51/100 [00:05<00:03, 16.10epoch/s, loss=0.6005, val_loss=0.5225]

Lower model:  51%|█████     | 51/100 [00:05<00:03, 16.10epoch/s, loss=0.5990, val_loss=0.5225]

Lower model:  52%|█████▏    | 52/100 [00:05<00:02, 16.10epoch/s, loss=0.6002, val_loss=0.5221]

Lower model:  53%|█████▎    | 53/100 [00:05<00:02, 16.53epoch/s, loss=0.6002, val_loss=0.5221]

Lower model:  53%|█████▎    | 53/100 [00:05<00:02, 16.53epoch/s, loss=0.6004, val_loss=0.5217]

Lower model:  54%|█████▍    | 54/100 [00:05<00:02, 16.53epoch/s, loss=0.5978, val_loss=0.5203]

Lower model:  55%|█████▌    | 55/100 [00:05<00:02, 16.71epoch/s, loss=0.5978, val_loss=0.5203]

Lower model:  55%|█████▌    | 55/100 [00:05<00:02, 16.71epoch/s, loss=0.5944, val_loss=0.5183]

Lower model:  56%|█████▌    | 56/100 [00:05<00:02, 16.71epoch/s, loss=0.5967, val_loss=0.5170]

Lower model:  57%|█████▋    | 57/100 [00:05<00:02, 16.36epoch/s, loss=0.5967, val_loss=0.5170]

Lower model:  57%|█████▋    | 57/100 [00:05<00:02, 16.36epoch/s, loss=0.5979, val_loss=0.5159]

Lower model:  58%|█████▊    | 58/100 [00:05<00:02, 16.36epoch/s, loss=0.5959, val_loss=0.5159]

Lower model:  59%|█████▉    | 59/100 [00:05<00:02, 16.34epoch/s, loss=0.5959, val_loss=0.5159]

Lower model:  59%|█████▉    | 59/100 [00:05<00:02, 16.34epoch/s, loss=0.5906, val_loss=0.5153]

Lower model:  60%|██████    | 60/100 [00:05<00:02, 16.34epoch/s, loss=0.5993, val_loss=0.5151]

Lower model:  61%|██████    | 61/100 [00:05<00:02, 16.26epoch/s, loss=0.5993, val_loss=0.5151]

Lower model:  61%|██████    | 61/100 [00:05<00:02, 16.26epoch/s, loss=0.5910, val_loss=0.5148]

Lower model:  62%|██████▏   | 62/100 [00:05<00:02, 16.26epoch/s, loss=0.5951, val_loss=0.5136]

Lower model:  63%|██████▎   | 63/100 [00:05<00:02, 16.07epoch/s, loss=0.5951, val_loss=0.5136]

Lower model:  63%|██████▎   | 63/100 [00:06<00:02, 16.07epoch/s, loss=0.5958, val_loss=0.5127]

Lower model:  64%|██████▍   | 64/100 [00:06<00:02, 16.07epoch/s, loss=0.5967, val_loss=0.5129]

Lower model:  65%|██████▌   | 65/100 [00:06<00:02, 16.08epoch/s, loss=0.5967, val_loss=0.5129]

Lower model:  65%|██████▌   | 65/100 [00:06<00:02, 16.08epoch/s, loss=0.5918, val_loss=0.5127]

Lower model:  66%|██████▌   | 66/100 [00:06<00:02, 16.08epoch/s, loss=0.5908, val_loss=0.5127]

Lower model:  67%|██████▋   | 67/100 [00:06<00:02, 16.18epoch/s, loss=0.5908, val_loss=0.5127]

Lower model:  67%|██████▋   | 67/100 [00:06<00:02, 16.18epoch/s, loss=0.5960, val_loss=0.5118]

Lower model:  68%|██████▊   | 68/100 [00:06<00:01, 16.18epoch/s, loss=0.5968, val_loss=0.5123]

Lower model:  69%|██████▉   | 69/100 [00:06<00:01, 16.55epoch/s, loss=0.5968, val_loss=0.5123]

Lower model:  69%|██████▉   | 69/100 [00:06<00:01, 16.55epoch/s, loss=0.5939, val_loss=0.5124]

Lower model:  70%|███████   | 70/100 [00:06<00:01, 16.55epoch/s, loss=0.5898, val_loss=0.5132]

Lower model:  71%|███████   | 71/100 [00:06<00:01, 16.78epoch/s, loss=0.5898, val_loss=0.5132]

Lower model:  71%|███████   | 71/100 [00:06<00:01, 16.78epoch/s, loss=0.5863, val_loss=0.5126]

Lower model:  72%|███████▏  | 72/100 [00:06<00:01, 16.78epoch/s, loss=0.5965, val_loss=0.5114]

Lower model:  73%|███████▎  | 73/100 [00:06<00:01, 16.89epoch/s, loss=0.5965, val_loss=0.5114]

Lower model:  73%|███████▎  | 73/100 [00:06<00:01, 16.89epoch/s, loss=0.5923, val_loss=0.5101]

Lower model:  74%|███████▍  | 74/100 [00:06<00:01, 16.89epoch/s, loss=0.5832, val_loss=0.5103]

Lower model:  75%|███████▌  | 75/100 [00:06<00:01, 17.09epoch/s, loss=0.5832, val_loss=0.5103]

Lower model:  75%|███████▌  | 75/100 [00:06<00:01, 17.09epoch/s, loss=0.5906, val_loss=0.5093]

Lower model:  76%|███████▌  | 76/100 [00:06<00:01, 17.09epoch/s, loss=0.5821, val_loss=0.5076]

Lower model:  77%|███████▋  | 77/100 [00:06<00:01, 17.11epoch/s, loss=0.5821, val_loss=0.5076]

Lower model:  77%|███████▋  | 77/100 [00:06<00:01, 17.11epoch/s, loss=0.5876, val_loss=0.5061]

Lower model:  78%|███████▊  | 78/100 [00:06<00:01, 17.11epoch/s, loss=0.5919, val_loss=0.5072]

Lower model:  79%|███████▉  | 79/100 [00:06<00:01, 16.96epoch/s, loss=0.5919, val_loss=0.5072]

Lower model:  79%|███████▉  | 79/100 [00:06<00:01, 16.96epoch/s, loss=0.5933, val_loss=0.5097]

Lower model:  80%|████████  | 80/100 [00:06<00:01, 16.96epoch/s, loss=0.5869, val_loss=0.5108]

Lower model:  81%|████████  | 81/100 [00:06<00:01, 17.14epoch/s, loss=0.5869, val_loss=0.5108]

Lower model:  81%|████████  | 81/100 [00:07<00:01, 17.14epoch/s, loss=0.5905, val_loss=0.5098]

Lower model:  82%|████████▏ | 82/100 [00:07<00:01, 17.14epoch/s, loss=0.5920, val_loss=0.5081]

Lower model:  83%|████████▎ | 83/100 [00:07<00:01, 16.41epoch/s, loss=0.5920, val_loss=0.5081]

Lower model:  83%|████████▎ | 83/100 [00:07<00:01, 16.41epoch/s, loss=0.5878, val_loss=0.5076]

Lower model:  84%|████████▍ | 84/100 [00:07<00:00, 16.41epoch/s, loss=0.5871, val_loss=0.5065]

Lower model:  85%|████████▌ | 85/100 [00:07<00:00, 16.06epoch/s, loss=0.5871, val_loss=0.5065]

Lower model:  85%|████████▌ | 85/100 [00:07<00:00, 16.06epoch/s, loss=0.5863, val_loss=0.5053]

Lower model:  86%|████████▌ | 86/100 [00:07<00:00, 16.06epoch/s, loss=0.5789, val_loss=0.5040]

Lower model:  87%|████████▋ | 87/100 [00:07<00:00, 14.83epoch/s, loss=0.5789, val_loss=0.5040]

Lower model:  87%|████████▋ | 87/100 [00:07<00:00, 14.83epoch/s, loss=0.5870, val_loss=0.5035]

Lower model:  88%|████████▊ | 88/100 [00:07<00:00, 14.83epoch/s, loss=0.5914, val_loss=0.5037]

Lower model:  89%|████████▉ | 89/100 [00:07<00:00, 15.35epoch/s, loss=0.5914, val_loss=0.5037]

Lower model:  89%|████████▉ | 89/100 [00:07<00:00, 15.35epoch/s, loss=0.5903, val_loss=0.5042]

Lower model:  90%|█████████ | 90/100 [00:07<00:00, 15.35epoch/s, loss=0.5857, val_loss=0.5045]

Lower model:  91%|█████████ | 91/100 [00:07<00:00, 15.14epoch/s, loss=0.5857, val_loss=0.5045]

Lower model:  91%|█████████ | 91/100 [00:07<00:00, 15.14epoch/s, loss=0.5799, val_loss=0.5041]

Lower model:  92%|█████████▏| 92/100 [00:07<00:00, 15.14epoch/s, loss=0.5927, val_loss=0.5039]

Lower model:  93%|█████████▎| 93/100 [00:07<00:00, 14.14epoch/s, loss=0.5927, val_loss=0.5039]

Lower model:  93%|█████████▎| 93/100 [00:07<00:00, 14.14epoch/s, loss=0.5895, val_loss=0.5038]

Lower model:  94%|█████████▍| 94/100 [00:07<00:00, 14.14epoch/s, loss=0.5875, val_loss=0.5039]

Lower model:  95%|█████████▌| 95/100 [00:07<00:00, 13.76epoch/s, loss=0.5875, val_loss=0.5039]

Lower model:  95%|█████████▌| 95/100 [00:08<00:00, 13.76epoch/s, loss=0.5838, val_loss=0.5038]

Lower model:  96%|█████████▌| 96/100 [00:08<00:00, 13.76epoch/s, loss=0.5896, val_loss=0.5040]

Lower model:  97%|█████████▋| 97/100 [00:08<00:00, 14.23epoch/s, loss=0.5896, val_loss=0.5040]

Lower model:  97%|█████████▋| 97/100 [00:08<00:00, 14.23epoch/s, loss=0.5900, val_loss=0.5041]

Lower model:  98%|█████████▊| 98/100 [00:08<00:00, 11.94epoch/s, loss=0.5900, val_loss=0.5041]

1/6 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step

1/6 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step

1/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

1/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step

  > CQR Calibration constant (Q): -0.1819
Tuning metrics saved to /home/lmaosid/Desktop/major/experiments/classification_new_data/output/conformal_results_uncensored/EOS-04_tau_tuning_metrics.json

In [7]:
sentinel_exp = ConformalizedQuantileExperiment(X_sentinel, y_sentinel, satellite="Sentinel-1")

sentinel_results = sentinel_exp.run_ann_tuning_experiment(models['16, Dropout, 8, Dropout'])

Results → /home/lmaosid/Desktop/major/experiments/classification_new_data/output/pi_estimation_uncensored
Results → /home/lmaosid/Desktop/major/experiments/classification_new_data/output/conformal_results_uncensored

=== Starting Tau Hyperparameter Tuning for Sentinel-1 ===

Running configuration: Low:0.01 - High:0.96

Upper model:   0%|          | 0/100 [00:00<?, ?epoch/s]

I0000 00:00:1778435146.974089 2605134 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_79643__.19

I0000 00:00:1778435147.737197 2605131 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_79643__.19

Upper model:   0%|          | 0/100 [00:02<?, ?epoch/s, loss=19.4628, val_loss=19.1538]

Upper model:   1%|          | 1/100 [00:02<04:51,  2.95s/epoch, loss=19.4628, val_loss=19.1538]

Upper model:   1%|          | 1/100 [00:03<04:51,  2.95s/epoch, loss=19.3811, val_loss=19.0740]

Upper model:   2%|▏         | 2/100 [00:03<04:48,  2.95s/epoch, loss=19.2889, val_loss=18.9986]

Upper model:   3%|▎         | 3/100 [00:03<01:18,  1.24epoch/s, loss=19.2889, val_loss=18.9986]

Upper model:   3%|▎         | 3/100 [00:03<01:18,  1.24epoch/s, loss=19.2240, val_loss=18.9319]

Upper model:   4%|▍         | 4/100 [00:03<01:17,  1.24epoch/s, loss=19.1473, val_loss=18.8735]

Upper model:   5%|▌         | 5/100 [00:03<00:40,  2.36epoch/s, loss=19.1473, val_loss=18.8735]

Upper model:   5%|▌         | 5/100 [00:03<00:40,  2.36epoch/s, loss=19.0892, val_loss=18.8177]

Upper model:   6%|▌         | 6/100 [00:03<00:39,  2.36epoch/s, loss=19.0305, val_loss=18.7633]

Upper model:   7%|▋         | 7/100 [00:03<00:24,  3.72epoch/s, loss=19.0305, val_loss=18.7633]

Upper model:   7%|▋         | 7/100 [00:03<00:24,  3.72epoch/s, loss=18.9629, val_loss=18.7086]

Upper model:   8%|▊         | 8/100 [00:03<00:24,  3.72epoch/s, loss=18.9048, val_loss=18.6513]

Upper model:   9%|▉         | 9/100 [00:03<00:17,  5.28epoch/s, loss=18.9048, val_loss=18.6513]

Upper model:   9%|▉         | 9/100 [00:03<00:17,  5.28epoch/s, loss=18.8458, val_loss=18.5899]

Upper model:  10%|█         | 10/100 [00:03<00:17,  5.28epoch/s, loss=18.7655, val_loss=18.5179]

Upper model:  11%|█         | 11/100 [00:03<00:12,  6.97epoch/s, loss=18.7655, val_loss=18.5179]

Upper model:  11%|█         | 11/100 [00:03<00:12,  6.97epoch/s, loss=18.6801, val_loss=18.4255]

Upper model:  12%|█▏        | 12/100 [00:03<00:12,  6.97epoch/s, loss=18.5867, val_loss=18.3075]

Upper model:  13%|█▎        | 13/100 [00:03<00:10,  8.67epoch/s, loss=18.5867, val_loss=18.3075]

Upper model:  13%|█▎        | 13/100 [00:03<00:10,  8.67epoch/s, loss=18.4695, val_loss=18.1672]

Upper model:  14%|█▍        | 14/100 [00:03<00:09,  8.67epoch/s, loss=18.3070, val_loss=18.0059]

Upper model:  15%|█▌        | 15/100 [00:03<00:08, 10.09epoch/s, loss=18.3070, val_loss=18.0059]

Upper model:  15%|█▌        | 15/100 [00:03<00:08, 10.09epoch/s, loss=18.1358, val_loss=17.8286]

Upper model:  16%|█▌        | 16/100 [00:03<00:08, 10.09epoch/s, loss=17.9687, val_loss=17.6424]

Upper model:  17%|█▋        | 17/100 [00:03<00:07, 11.33epoch/s, loss=17.9687, val_loss=17.6424]

Upper model:  17%|█▋        | 17/100 [00:03<00:07, 11.33epoch/s, loss=17.7692, val_loss=17.4481]

Upper model:  18%|█▊        | 18/100 [00:04<00:07, 11.33epoch/s, loss=17.5450, val_loss=17.2430]

Upper model:  19%|█▉        | 19/100 [00:04<00:06, 12.63epoch/s, loss=17.5450, val_loss=17.2430]

Upper model:  19%|█▉        | 19/100 [00:04<00:06, 12.63epoch/s, loss=17.3428, val_loss=17.0178]

Upper model:  20%|██        | 20/100 [00:04<00:06, 12.63epoch/s, loss=17.0965, val_loss=16.7679]

Upper model:  21%|██        | 21/100 [00:04<00:05, 13.43epoch/s, loss=17.0965, val_loss=16.7679]

Upper model:  21%|██        | 21/100 [00:04<00:05, 13.43epoch/s, loss=16.8612, val_loss=16.5066]

Upper model:  22%|██▏       | 22/100 [00:04<00:05, 13.43epoch/s, loss=16.5731, val_loss=16.2372]

Upper model:  23%|██▎       | 23/100 [00:04<00:05, 14.46epoch/s, loss=16.5731, val_loss=16.2372]

Upper model:  23%|██▎       | 23/100 [00:04<00:05, 14.46epoch/s, loss=16.2931, val_loss=15.9584]

Upper model:  24%|██▍       | 24/100 [00:04<00:05, 14.46epoch/s, loss=16.0054, val_loss=15.6708]

Upper model:  25%|██▌       | 25/100 [00:04<00:05, 14.74epoch/s, loss=16.0054, val_loss=15.6708]

Upper model:  25%|██▌       | 25/100 [00:04<00:05, 14.74epoch/s, loss=15.7211, val_loss=15.3752]

Upper model:  26%|██▌       | 26/100 [00:04<00:05, 14.74epoch/s, loss=15.3974, val_loss=15.0691]

Upper model:  27%|██▋       | 27/100 [00:04<00:04, 15.29epoch/s, loss=15.3974, val_loss=15.0691]

Upper model:  27%|██▋       | 27/100 [00:04<00:04, 15.29epoch/s, loss=15.0784, val_loss=14.7550]

Upper model:  28%|██▊       | 28/100 [00:04<00:04, 15.29epoch/s, loss=14.7096, val_loss=14.4328]

Upper model:  29%|██▉       | 29/100 [00:04<00:04, 15.63epoch/s, loss=14.7096, val_loss=14.4328]

Upper model:  29%|██▉       | 29/100 [00:04<00:04, 15.63epoch/s, loss=14.3865, val_loss=14.1001]

Upper model:  30%|███       | 30/100 [00:04<00:04, 15.63epoch/s, loss=14.0571, val_loss=13.7565]

Upper model:  31%|███       | 31/100 [00:04<00:04, 15.29epoch/s, loss=14.0571, val_loss=13.7565]

Upper model:  31%|███       | 31/100 [00:04<00:04, 15.29epoch/s, loss=13.6644, val_loss=13.4005]

Upper model:  32%|███▏      | 32/100 [00:04<00:04, 15.29epoch/s, loss=13.3653, val_loss=13.0398]

Upper model:  33%|███▎      | 33/100 [00:04<00:04, 15.27epoch/s, loss=13.3653, val_loss=13.0398]

Upper model:  33%|███▎      | 33/100 [00:04<00:04, 15.27epoch/s, loss=12.9543, val_loss=12.6717]

Upper model:  34%|███▍      | 34/100 [00:05<00:04, 15.27epoch/s, loss=12.5241, val_loss=12.2978]

Upper model:  35%|███▌      | 35/100 [00:05<00:04, 15.70epoch/s, loss=12.5241, val_loss=12.2978]

Upper model:  35%|███▌      | 35/100 [00:05<00:04, 15.70epoch/s, loss=12.1574, val_loss=11.9155]

Upper model:  36%|███▌      | 36/100 [00:05<00:04, 15.70epoch/s, loss=11.7225, val_loss=11.5254]

Upper model:  37%|███▋      | 37/100 [00:05<00:03, 15.88epoch/s, loss=11.7225, val_loss=11.5254]

Upper model:  37%|███▋      | 37/100 [00:05<00:03, 15.88epoch/s, loss=11.2436, val_loss=11.1243]

Upper model:  38%|███▊      | 38/100 [00:05<00:03, 15.88epoch/s, loss=10.9550, val_loss=10.7149]

Upper model:  39%|███▉      | 39/100 [00:05<00:03, 15.65epoch/s, loss=10.9550, val_loss=10.7149]

Upper model:  39%|███▉      | 39/100 [00:05<00:03, 15.65epoch/s, loss=10.5261, val_loss=10.2968]

Upper model:  40%|████      | 40/100 [00:05<00:03, 15.65epoch/s, loss=9.8779, val_loss=9.8717]

Upper model:  41%|████      | 41/100 [00:05<00:03, 15.88epoch/s, loss=9.8779, val_loss=9.8717]

Upper model:  41%|████      | 41/100 [00:05<00:03, 15.88epoch/s, loss=9.4519, val_loss=9.4242]

Upper model:  42%|████▏     | 42/100 [00:05<00:03, 15.88epoch/s, loss=8.9360, val_loss=8.9615]

Upper model:  43%|████▎     | 43/100 [00:05<00:03, 16.34epoch/s, loss=8.9360, val_loss=8.9615]

Upper model:  43%|████▎     | 43/100 [00:05<00:03, 16.34epoch/s, loss=8.4927, val_loss=8.4891]

Upper model:  44%|████▍     | 44/100 [00:05<00:03, 16.34epoch/s, loss=8.0954, val_loss=8.0087]

Upper model:  45%|████▌     | 45/100 [00:05<00:03, 16.64epoch/s, loss=8.0954, val_loss=8.0087]

Upper model:  45%|████▌     | 45/100 [00:05<00:03, 16.64epoch/s, loss=7.6310, val_loss=7.5247]

Upper model:  46%|████▌     | 46/100 [00:05<00:03, 16.64epoch/s, loss=7.1585, val_loss=7.0415]

Upper model:  47%|████▋     | 47/100 [00:05<00:03, 16.59epoch/s, loss=7.1585, val_loss=7.0415]

Upper model:  47%|████▋     | 47/100 [00:05<00:03, 16.59epoch/s, loss=6.4765, val_loss=6.5741]

Upper model:  48%|████▊     | 48/100 [00:05<00:03, 16.59epoch/s, loss=6.1574, val_loss=6.1179]

Upper model:  49%|████▉     | 49/100 [00:05<00:03, 15.14epoch/s, loss=6.1574, val_loss=6.1179]

Upper model:  49%|████▉     | 49/100 [00:05<00:03, 15.14epoch/s, loss=5.8157, val_loss=5.6857]

Upper model:  50%|█████     | 50/100 [00:06<00:03, 15.14epoch/s, loss=5.2391, val_loss=5.2689]

Upper model:  51%|█████     | 51/100 [00:06<00:03, 14.37epoch/s, loss=5.2391, val_loss=5.2689]

Upper model:  51%|█████     | 51/100 [00:06<00:03, 14.37epoch/s, loss=5.1114, val_loss=4.8744]

Upper model:  52%|█████▏    | 52/100 [00:06<00:03, 14.37epoch/s, loss=4.6043, val_loss=4.4977]

Upper model:  53%|█████▎    | 53/100 [00:06<00:03, 14.73epoch/s, loss=4.6043, val_loss=4.4977]

Upper model:  53%|█████▎    | 53/100 [00:06<00:03, 14.73epoch/s, loss=4.3046, val_loss=4.1481]

Upper model:  54%|█████▍    | 54/100 [00:06<00:03, 14.73epoch/s, loss=4.0360, val_loss=3.8292]

Upper model:  55%|█████▌    | 55/100 [00:06<00:02, 15.02epoch/s, loss=4.0360, val_loss=3.8292]

Upper model:  55%|█████▌    | 55/100 [00:06<00:02, 15.02epoch/s, loss=3.8555, val_loss=3.5386]

Upper model:  56%|█████▌    | 56/100 [00:06<00:02, 15.02epoch/s, loss=3.2866, val_loss=3.2751]

Upper model:  57%|█████▋    | 57/100 [00:06<00:02, 15.30epoch/s, loss=3.2866, val_loss=3.2751]

Upper model:  57%|█████▋    | 57/100 [00:06<00:02, 15.30epoch/s, loss=3.2508, val_loss=3.0396]

Upper model:  58%|█████▊    | 58/100 [00:06<00:02, 15.30epoch/s, loss=2.8937, val_loss=2.8349]

Upper model:  59%|█████▉    | 59/100 [00:06<00:02, 15.32epoch/s, loss=2.8937, val_loss=2.8349]

Upper model:  59%|█████▉    | 59/100 [00:06<00:02, 15.32epoch/s, loss=2.6819, val_loss=2.6460]

Upper model:  60%|██████    | 60/100 [00:06<00:02, 15.32epoch/s, loss=2.6070, val_loss=2.4853]

Upper model:  61%|██████    | 61/100 [00:06<00:02, 15.51epoch/s, loss=2.6070, val_loss=2.4853]

Upper model:  61%|██████    | 61/100 [00:06<00:02, 15.51epoch/s, loss=2.4270, val_loss=2.3359]

Upper model:  62%|██████▏   | 62/100 [00:06<00:02, 15.51epoch/s, loss=2.3195, val_loss=2.1933]

Upper model:  63%|██████▎   | 63/100 [00:06<00:02, 15.21epoch/s, loss=2.3195, val_loss=2.1933]

Upper model:  63%|██████▎   | 63/100 [00:06<00:02, 15.21epoch/s, loss=2.0323, val_loss=2.0677]

Upper model:  64%|██████▍   | 64/100 [00:06<00:02, 15.21epoch/s, loss=2.1882, val_loss=1.9532]

Upper model:  65%|██████▌   | 65/100 [00:06<00:02, 15.02epoch/s, loss=2.1882, val_loss=1.9532]

Upper model:  65%|██████▌   | 65/100 [00:07<00:02, 15.02epoch/s, loss=1.9682, val_loss=1.8523]

Upper model:  66%|██████▌   | 66/100 [00:07<00:02, 15.02epoch/s, loss=1.9242, val_loss=1.7658]

Upper model:  67%|██████▋   | 67/100 [00:07<00:02, 14.85epoch/s, loss=1.9242, val_loss=1.7658]

Upper model:  67%|██████▋   | 67/100 [00:07<00:02, 14.85epoch/s, loss=1.9248, val_loss=1.6932]

Upper model:  68%|██████▊   | 68/100 [00:07<00:02, 14.85epoch/s, loss=1.8478, val_loss=1.6231]

Upper model:  69%|██████▉   | 69/100 [00:07<00:02, 14.98epoch/s, loss=1.8478, val_loss=1.6231]

Upper model:  69%|██████▉   | 69/100 [00:07<00:02, 14.98epoch/s, loss=1.6122, val_loss=1.5624]

Upper model:  70%|███████   | 70/100 [00:07<00:02, 14.98epoch/s, loss=1.7339, val_loss=1.5069]

Upper model:  71%|███████   | 71/100 [00:07<00:01, 15.33epoch/s, loss=1.7339, val_loss=1.5069]

Upper model:  71%|███████   | 71/100 [00:07<00:01, 15.33epoch/s, loss=1.5893, val_loss=1.4615]

Upper model:  72%|███████▏  | 72/100 [00:07<00:01, 15.33epoch/s, loss=1.6228, val_loss=1.4262]

Upper model:  73%|███████▎  | 73/100 [00:07<00:01, 15.50epoch/s, loss=1.6228, val_loss=1.4262]

Upper model:  73%|███████▎  | 73/100 [00:07<00:01, 15.50epoch/s, loss=1.4006, val_loss=1.3947]

Upper model:  74%|███████▍  | 74/100 [00:07<00:01, 15.50epoch/s, loss=1.5912, val_loss=1.3658]

Upper model:  75%|███████▌  | 75/100 [00:07<00:01, 15.97epoch/s, loss=1.5912, val_loss=1.3658]

Upper model:  75%|███████▌  | 75/100 [00:07<00:01, 15.97epoch/s, loss=1.4024, val_loss=1.3391]

Upper model:  76%|███████▌  | 76/100 [00:07<00:01, 15.97epoch/s, loss=1.3805, val_loss=1.3175]

Upper model:  77%|███████▋  | 77/100 [00:07<00:01, 16.35epoch/s, loss=1.3805, val_loss=1.3175]

Upper model:  77%|███████▋  | 77/100 [00:07<00:01, 16.35epoch/s, loss=1.4309, val_loss=1.2992]

Upper model:  78%|███████▊  | 78/100 [00:07<00:01, 16.35epoch/s, loss=1.4125, val_loss=1.2794]

Upper model:  79%|███████▉  | 79/100 [00:07<00:01, 16.14epoch/s, loss=1.4125, val_loss=1.2794]

Upper model:  79%|███████▉  | 79/100 [00:07<00:01, 16.14epoch/s, loss=1.3837, val_loss=1.2603]

Upper model:  80%|████████  | 80/100 [00:08<00:01, 16.14epoch/s, loss=1.3235, val_loss=1.2433]

Upper model:  81%|████████  | 81/100 [00:08<00:01, 15.11epoch/s, loss=1.3235, val_loss=1.2433]

Upper model:  81%|████████  | 81/100 [00:08<00:01, 15.11epoch/s, loss=1.3235, val_loss=1.2271]

Upper model:  82%|████████▏ | 82/100 [00:08<00:01, 15.11epoch/s, loss=1.3747, val_loss=1.2118]

Upper model:  83%|████████▎ | 83/100 [00:08<00:01, 15.64epoch/s, loss=1.3747, val_loss=1.2118]

Upper model:  83%|████████▎ | 83/100 [00:08<00:01, 15.64epoch/s, loss=1.2585, val_loss=1.1987]

Upper model:  84%|████████▍ | 84/100 [00:08<00:01, 15.64epoch/s, loss=1.3610, val_loss=1.1849]

Upper model:  85%|████████▌ | 85/100 [00:08<00:00, 15.90epoch/s, loss=1.3610, val_loss=1.1849]

Upper model:  85%|████████▌ | 85/100 [00:08<00:00, 15.90epoch/s, loss=1.3325, val_loss=1.1739]

Upper model:  86%|████████▌ | 86/100 [00:08<00:00, 15.90epoch/s, loss=1.3416, val_loss=1.1631]

Upper model:  87%|████████▋ | 87/100 [00:08<00:00, 16.23epoch/s, loss=1.3416, val_loss=1.1631]

Upper model:  87%|████████▋ | 87/100 [00:08<00:00, 16.23epoch/s, loss=1.2735, val_loss=1.1529]

Upper model:  88%|████████▊ | 88/100 [00:08<00:00, 16.23epoch/s, loss=1.3458, val_loss=1.1422]

Upper model:  89%|████████▉ | 89/100 [00:08<00:00, 15.16epoch/s, loss=1.3458, val_loss=1.1422]

Upper model:  89%|████████▉ | 89/100 [00:08<00:00, 15.16epoch/s, loss=1.2003, val_loss=1.1318]

Upper model:  90%|█████████ | 90/100 [00:08<00:00, 15.16epoch/s, loss=1.2093, val_loss=1.1224]

Upper model:  91%|█████████ | 91/100 [00:08<00:00, 13.95epoch/s, loss=1.2093, val_loss=1.1224]

Upper model:  91%|█████████ | 91/100 [00:08<00:00, 13.95epoch/s, loss=1.2610, val_loss=1.1148]

Upper model:  92%|█████████▏| 92/100 [00:08<00:00, 13.95epoch/s, loss=1.2168, val_loss=1.1084]

Upper model:  93%|█████████▎| 93/100 [00:08<00:00, 12.42epoch/s, loss=1.2168, val_loss=1.1084]

Upper model:  93%|█████████▎| 93/100 [00:08<00:00, 12.42epoch/s, loss=1.2157, val_loss=1.1022]

Upper model:  94%|█████████▍| 94/100 [00:09<00:00, 12.42epoch/s, loss=1.2930, val_loss=1.0954]

Upper model:  95%|█████████▌| 95/100 [00:09<00:00, 12.47epoch/s, loss=1.2930, val_loss=1.0954]

Upper model:  95%|█████████▌| 95/100 [00:09<00:00, 12.47epoch/s, loss=1.2175, val_loss=1.0889]

Upper model:  96%|█████████▌| 96/100 [00:09<00:00, 12.47epoch/s, loss=1.2764, val_loss=1.0809]

Upper model:  97%|█████████▋| 97/100 [00:09<00:00, 13.30epoch/s, loss=1.2764, val_loss=1.0809]

Upper model:  97%|█████████▋| 97/100 [00:09<00:00, 13.30epoch/s, loss=1.1640, val_loss=1.0739]

Upper model:  98%|█████████▊| 98/100 [00:09<00:00, 13.30epoch/s, loss=1.3175, val_loss=1.0675]

Upper model:  99%|█████████▉| 99/100 [00:09<00:00, 13.81epoch/s, loss=1.3175, val_loss=1.0675]

Upper model:  99%|█████████▉| 99/100 [00:09<00:00, 13.81epoch/s, loss=1.1804, val_loss=1.0634]

Upper model: 100%|██████████| 100/100 [00:09<00:00, 10.66epoch/s, loss=1.1804, val_loss=1.0634]

Lower model:   0%|          | 0/100 [00:00<?, ?epoch/s]

I0000 00:00:1778435156.353473 2605127 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_86562__.19

I0000 00:00:1778435157.152574 2605130 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_86562__.19

Lower model:   0%|          | 0/100 [00:02<?, ?epoch/s, loss=0.2022, val_loss=0.1996]

Lower model:   1%|          | 1/100 [00:02<03:42,  2.24s/epoch, loss=0.2022, val_loss=0.1996]

Lower model:   1%|          | 1/100 [00:02<03:42,  2.24s/epoch, loss=0.2018, val_loss=0.1992]

Lower model:   2%|▏         | 2/100 [00:02<03:39,  2.24s/epoch, loss=0.2014, val_loss=0.1988]

Lower model:   3%|▎         | 3/100 [00:02<01:02,  1.55epoch/s, loss=0.2014, val_loss=0.1988]

Lower model:   3%|▎         | 3/100 [00:02<01:02,  1.55epoch/s, loss=0.2010, val_loss=0.1983]

Lower model:   4%|▍         | 4/100 [00:02<01:01,  1.55epoch/s, loss=0.2006, val_loss=0.1979]

Lower model:   5%|▌         | 5/100 [00:02<00:33,  2.86epoch/s, loss=0.2006, val_loss=0.1979]

Lower model:   5%|▌         | 5/100 [00:02<00:33,  2.86epoch/s, loss=0.2001, val_loss=0.1974]

Lower model:   6%|▌         | 6/100 [00:02<00:32,  2.86epoch/s, loss=0.1996, val_loss=0.1968]

Lower model:   7%|▋         | 7/100 [00:02<00:21,  4.28epoch/s, loss=0.1996, val_loss=0.1968]

Lower model:   7%|▋         | 7/100 [00:02<00:21,  4.28epoch/s, loss=0.1990, val_loss=0.1962]

Lower model:   8%|▊         | 8/100 [00:02<00:21,  4.28epoch/s, loss=0.1984, val_loss=0.1956]

Lower model:   9%|▉         | 9/100 [00:02<00:15,  5.88epoch/s, loss=0.1984, val_loss=0.1956]

Lower model:   9%|▉         | 9/100 [00:02<00:15,  5.88epoch/s, loss=0.1977, val_loss=0.1949]

Lower model:  10%|█         | 10/100 [00:02<00:15,  5.88epoch/s, loss=0.1971, val_loss=0.1941]

Lower model:  11%|█         | 11/100 [00:02<00:11,  7.44epoch/s, loss=0.1971, val_loss=0.1941]

Lower model:  11%|█         | 11/100 [00:03<00:11,  7.44epoch/s, loss=0.1963, val_loss=0.1933]

Lower model:  12%|█▏        | 12/100 [00:03<00:11,  7.44epoch/s, loss=0.1954, val_loss=0.1923]

Lower model:  13%|█▎        | 13/100 [00:03<00:09,  9.15epoch/s, loss=0.1954, val_loss=0.1923]

Lower model:  13%|█▎        | 13/100 [00:03<00:09,  9.15epoch/s, loss=0.1944, val_loss=0.1913]

Lower model:  14%|█▍        | 14/100 [00:03<00:09,  9.15epoch/s, loss=0.1933, val_loss=0.1901]

Lower model:  15%|█▌        | 15/100 [00:03<00:08, 10.43epoch/s, loss=0.1933, val_loss=0.1901]

Lower model:  15%|█▌        | 15/100 [00:03<00:08, 10.43epoch/s, loss=0.1921, val_loss=0.1889]

Lower model:  16%|█▌        | 16/100 [00:03<00:08, 10.43epoch/s, loss=0.1908, val_loss=0.1881]

Lower model:  17%|█▋        | 17/100 [00:03<00:07, 11.55epoch/s, loss=0.1908, val_loss=0.1881]

Lower model:  17%|█▋        | 17/100 [00:03<00:07, 11.55epoch/s, loss=0.1898, val_loss=0.1877]

Lower model:  18%|█▊        | 18/100 [00:03<00:07, 11.55epoch/s, loss=0.1884, val_loss=0.1873]

Lower model:  19%|█▉        | 19/100 [00:03<00:06, 12.84epoch/s, loss=0.1884, val_loss=0.1873]

Lower model:  19%|█▉        | 19/100 [00:03<00:06, 12.84epoch/s, loss=0.1871, val_loss=0.1869]

Lower model:  20%|██        | 20/100 [00:03<00:06, 12.84epoch/s, loss=0.1857, val_loss=0.1865]

Lower model:  21%|██        | 21/100 [00:03<00:05, 13.85epoch/s, loss=0.1857, val_loss=0.1865]

Lower model:  21%|██        | 21/100 [00:03<00:05, 13.85epoch/s, loss=0.1846, val_loss=0.1862]

Lower model:  22%|██▏       | 22/100 [00:03<00:05, 13.85epoch/s, loss=0.1840, val_loss=0.1858]

Lower model:  23%|██▎       | 23/100 [00:03<00:05, 14.65epoch/s, loss=0.1840, val_loss=0.1858]

Lower model:  23%|██▎       | 23/100 [00:03<00:05, 14.65epoch/s, loss=0.1826, val_loss=0.1854]

Lower model:  24%|██▍       | 24/100 [00:03<00:05, 14.65epoch/s, loss=0.1821, val_loss=0.1863]

Lower model:  25%|██▌       | 25/100 [00:03<00:04, 15.23epoch/s, loss=0.1821, val_loss=0.1863]

Lower model:  25%|██▌       | 25/100 [00:03<00:04, 15.23epoch/s, loss=0.1824, val_loss=0.1884]

Lower model:  26%|██▌       | 26/100 [00:03<00:04, 15.23epoch/s, loss=0.1832, val_loss=0.1896]

Lower model:  27%|██▋       | 27/100 [00:03<00:04, 15.55epoch/s, loss=0.1832, val_loss=0.1896]

Lower model:  27%|██▋       | 27/100 [00:04<00:04, 15.55epoch/s, loss=0.1817, val_loss=0.1909]

Lower model:  28%|██▊       | 28/100 [00:04<00:04, 15.55epoch/s, loss=0.1807, val_loss=0.1929]

Lower model:  29%|██▉       | 29/100 [00:04<00:04, 15.90epoch/s, loss=0.1807, val_loss=0.1929]

Lower model:  29%|██▉       | 29/100 [00:04<00:04, 15.90epoch/s, loss=0.1824, val_loss=0.1936]

Lower model:  30%|███       | 30/100 [00:04<00:04, 15.90epoch/s, loss=0.1795, val_loss=0.1949]

Lower model:  31%|███       | 31/100 [00:04<00:04, 16.44epoch/s, loss=0.1795, val_loss=0.1949]

Lower model:  31%|███       | 31/100 [00:04<00:04, 16.44epoch/s, loss=0.1774, val_loss=0.1963]

Lower model:  32%|███▏      | 32/100 [00:04<00:04, 16.44epoch/s, loss=0.1792, val_loss=0.1980]

Lower model:  33%|███▎      | 33/100 [00:04<00:04, 16.62epoch/s, loss=0.1792, val_loss=0.1980]

Lower model:  33%|███▎      | 33/100 [00:04<00:04, 16.62epoch/s, loss=0.1806, val_loss=0.1990]

Lower model:  34%|███▍      | 34/100 [00:04<00:08,  7.77epoch/s, loss=0.1806, val_loss=0.1990]

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

WARNING:tensorflow:5 out of the last 23 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7f7e587642c0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

  > CQR Calibration constant (Q): 2.4050

Running configuration: Low:0.015 - High:0.965

Upper model:   0%|          | 0/100 [00:00<?, ?epoch/s]

I0000 00:00:1778435161.518072 2605131 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_90687__.19

I0000 00:00:1778435162.329559 2605131 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_90687__.19

Upper model:   0%|          | 0/100 [00:02<?, ?epoch/s, loss=19.7282, val_loss=19.4354]

Upper model:   1%|          | 1/100 [00:02<03:43,  2.26s/epoch, loss=19.7282, val_loss=19.4354]

Upper model:   1%|          | 1/100 [00:02<03:43,  2.26s/epoch, loss=19.6652, val_loss=19.3753]

Upper model:   2%|▏         | 2/100 [00:02<03:41,  2.26s/epoch, loss=19.6100, val_loss=19.3192]

Upper model:   3%|▎         | 3/100 [00:02<01:00,  1.59epoch/s, loss=19.6100, val_loss=19.3192]

Upper model:   3%|▎         | 3/100 [00:02<01:00,  1.59epoch/s, loss=19.5538, val_loss=19.2693]

Upper model:   4%|▍         | 4/100 [00:02<01:00,  1.59epoch/s, loss=19.5080, val_loss=19.2245]

Upper model:   5%|▌         | 5/100 [00:02<00:32,  2.96epoch/s, loss=19.5080, val_loss=19.2245]

Upper model:   5%|▌         | 5/100 [00:02<00:32,  2.96epoch/s, loss=19.4621, val_loss=19.1826]

Upper model:   6%|▌         | 6/100 [00:02<00:31,  2.96epoch/s, loss=19.4204, val_loss=19.1417]

Upper model:   7%|▋         | 7/100 [00:02<00:20,  4.53epoch/s, loss=19.4204, val_loss=19.1417]

Upper model:   7%|▋         | 7/100 [00:02<00:20,  4.53epoch/s, loss=19.3812, val_loss=19.1012]

Upper model:   8%|▊         | 8/100 [00:02<00:20,  4.53epoch/s, loss=19.3309, val_loss=19.0590]

Upper model:   9%|▉         | 9/100 [00:02<00:14,  6.24epoch/s, loss=19.3309, val_loss=19.0590]

Upper model:   9%|▉         | 9/100 [00:02<00:14,  6.24epoch/s, loss=19.2895, val_loss=19.0120]

Upper model:  10%|█         | 10/100 [00:02<00:14,  6.24epoch/s, loss=19.2431, val_loss=18.9560]

Upper model:  11%|█         | 11/100 [00:02<00:11,  7.78epoch/s, loss=19.2431, val_loss=18.9560]

Upper model:  11%|█         | 11/100 [00:02<00:11,  7.78epoch/s, loss=19.1757, val_loss=18.8890]

Upper model:  12%|█▏        | 12/100 [00:03<00:11,  7.78epoch/s, loss=19.1056, val_loss=18.8121]

Upper model:  13%|█▎        | 13/100 [00:03<00:09,  9.43epoch/s, loss=19.1056, val_loss=18.8121]

Upper model:  13%|█▎        | 13/100 [00:03<00:09,  9.43epoch/s, loss=19.0246, val_loss=18.7270]

Upper model:  14%|█▍        | 14/100 [00:03<00:09,  9.43epoch/s, loss=18.9312, val_loss=18.6337]

Upper model:  15%|█▌        | 15/100 [00:03<00:07, 10.97epoch/s, loss=18.9312, val_loss=18.6337]

Upper model:  15%|█▌        | 15/100 [00:03<00:07, 10.97epoch/s, loss=18.8281, val_loss=18.5319]

Upper model:  16%|█▌        | 16/100 [00:03<00:07, 10.97epoch/s, loss=18.7235, val_loss=18.4207]

Upper model:  17%|█▋        | 17/100 [00:03<00:06, 12.40epoch/s, loss=18.7235, val_loss=18.4207]

Upper model:  17%|█▋        | 17/100 [00:03<00:06, 12.40epoch/s, loss=18.6088, val_loss=18.3007]

Upper model:  18%|█▊        | 18/100 [00:03<00:06, 12.40epoch/s, loss=18.4862, val_loss=18.1708]

Upper model:  19%|█▉        | 19/100 [00:03<00:06, 13.38epoch/s, loss=18.4862, val_loss=18.1708]

Upper model:  19%|█▉        | 19/100 [00:03<00:06, 13.38epoch/s, loss=18.3544, val_loss=18.0300]

Upper model:  20%|██        | 20/100 [00:03<00:05, 13.38epoch/s, loss=18.1867, val_loss=17.8762]

Upper model:  21%|██        | 21/100 [00:03<00:05, 14.50epoch/s, loss=18.1867, val_loss=17.8762]

Upper model:  21%|██        | 21/100 [00:03<00:05, 14.50epoch/s, loss=18.0359, val_loss=17.7090]

Upper model:  22%|██▏       | 22/100 [00:03<00:05, 14.50epoch/s, loss=17.8501, val_loss=17.5271]

Upper model:  23%|██▎       | 23/100 [00:03<00:05, 15.21epoch/s, loss=17.8501, val_loss=17.5271]

Upper model:  23%|██▎       | 23/100 [00:03<00:05, 15.21epoch/s, loss=17.6862, val_loss=17.3298]

Upper model:  24%|██▍       | 24/100 [00:03<00:04, 15.21epoch/s, loss=17.4694, val_loss=17.1169]

Upper model:  25%|██▌       | 25/100 [00:03<00:04, 15.37epoch/s, loss=17.4694, val_loss=17.1169]

Upper model:  25%|██▌       | 25/100 [00:03<00:04, 15.37epoch/s, loss=17.2334, val_loss=16.8890]

Upper model:  26%|██▌       | 26/100 [00:03<00:04, 15.37epoch/s, loss=16.9931, val_loss=16.6454]

Upper model:  27%|██▋       | 27/100 [00:03<00:04, 15.02epoch/s, loss=16.9931, val_loss=16.6454]

Upper model:  27%|██▋       | 27/100 [00:03<00:04, 15.02epoch/s, loss=16.7250, val_loss=16.3848]

Upper model:  28%|██▊       | 28/100 [00:03<00:04, 15.02epoch/s, loss=16.4426, val_loss=16.1071]

Upper model:  29%|██▉       | 29/100 [00:03<00:04, 15.15epoch/s, loss=16.4426, val_loss=16.1071]

Upper model:  29%|██▉       | 29/100 [00:04<00:04, 15.15epoch/s, loss=16.1467, val_loss=15.8099]

Upper model:  30%|███       | 30/100 [00:04<00:04, 15.15epoch/s, loss=15.8526, val_loss=15.4930]

Upper model:  31%|███       | 31/100 [00:04<00:04, 15.51epoch/s, loss=15.8526, val_loss=15.4930]

Upper model:  31%|███       | 31/100 [00:04<00:04, 15.51epoch/s, loss=15.5105, val_loss=15.1585]

Upper model:  32%|███▏      | 32/100 [00:04<00:04, 15.51epoch/s, loss=15.1457, val_loss=14.8056]

Upper model:  33%|███▎      | 33/100 [00:04<00:04, 15.50epoch/s, loss=15.1457, val_loss=14.8056]

Upper model:  33%|███▎      | 33/100 [00:04<00:04, 15.50epoch/s, loss=14.7541, val_loss=14.4325]

Upper model:  34%|███▍      | 34/100 [00:04<00:04, 15.50epoch/s, loss=14.3386, val_loss=14.0399]

Upper model:  35%|███▌      | 35/100 [00:04<00:04, 15.65epoch/s, loss=14.3386, val_loss=14.0399]

Upper model:  35%|███▌      | 35/100 [00:04<00:04, 15.65epoch/s, loss=13.8883, val_loss=13.6276]

Upper model:  36%|███▌      | 36/100 [00:04<00:04, 15.65epoch/s, loss=13.4427, val_loss=13.1999]

Upper model:  37%|███▋      | 37/100 [00:04<00:03, 16.00epoch/s, loss=13.4427, val_loss=13.1999]

Upper model:  37%|███▋      | 37/100 [00:04<00:03, 16.00epoch/s, loss=12.9957, val_loss=12.7648]

Upper model:  38%|███▊      | 38/100 [00:04<00:03, 16.00epoch/s, loss=12.5588, val_loss=12.3196]

Upper model:  39%|███▉      | 39/100 [00:04<00:03, 16.17epoch/s, loss=12.5588, val_loss=12.3196]

Upper model:  39%|███▉      | 39/100 [00:04<00:03, 16.17epoch/s, loss=12.1124, val_loss=11.8658]

Upper model:  40%|████      | 40/100 [00:04<00:03, 16.17epoch/s, loss=11.5395, val_loss=11.3977]

Upper model:  41%|████      | 41/100 [00:04<00:03, 16.51epoch/s, loss=11.5395, val_loss=11.3977]

Upper model:  41%|████      | 41/100 [00:04<00:03, 16.51epoch/s, loss=11.1386, val_loss=10.9241]

Upper model:  42%|████▏     | 42/100 [00:04<00:03, 16.51epoch/s, loss=10.5460, val_loss=10.4468]

Upper model:  43%|████▎     | 43/100 [00:04<00:03, 16.83epoch/s, loss=10.5460, val_loss=10.4468]

Upper model:  43%|████▎     | 43/100 [00:04<00:03, 16.83epoch/s, loss=10.1377, val_loss=9.9671]

Upper model:  44%|████▍     | 44/100 [00:04<00:03, 16.83epoch/s, loss=9.5509, val_loss=9.4841]

Upper model:  45%|████▌     | 45/100 [00:04<00:03, 17.15epoch/s, loss=9.5509, val_loss=9.4841]

Upper model:  45%|████▌     | 45/100 [00:05<00:03, 17.15epoch/s, loss=9.1257, val_loss=9.0016]

Upper model:  46%|████▌     | 46/100 [00:05<00:03, 17.15epoch/s, loss=8.5257, val_loss=8.5262]

Upper model:  47%|████▋     | 47/100 [00:05<00:03, 17.03epoch/s, loss=8.5257, val_loss=8.5262]

Upper model:  47%|████▋     | 47/100 [00:05<00:03, 17.03epoch/s, loss=8.0343, val_loss=8.0541]

Upper model:  48%|████▊     | 48/100 [00:05<00:03, 17.03epoch/s, loss=7.6610, val_loss=7.5864]

Upper model:  49%|████▉     | 49/100 [00:05<00:02, 17.21epoch/s, loss=7.6610, val_loss=7.5864]

Upper model:  49%|████▉     | 49/100 [00:05<00:02, 17.21epoch/s, loss=7.2409, val_loss=7.1250]

Upper model:  50%|█████     | 50/100 [00:05<00:02, 17.21epoch/s, loss=6.7927, val_loss=6.6785]

Upper model:  51%|█████     | 51/100 [00:05<00:02, 16.84epoch/s, loss=6.7927, val_loss=6.6785]

Upper model:  51%|█████     | 51/100 [00:05<00:02, 16.84epoch/s, loss=6.2759, val_loss=6.2529]

Upper model:  52%|█████▏    | 52/100 [00:05<00:02, 16.84epoch/s, loss=5.7958, val_loss=5.8391]

Upper model:  53%|█████▎    | 53/100 [00:05<00:02, 16.62epoch/s, loss=5.7958, val_loss=5.8391]

Upper model:  53%|█████▎    | 53/100 [00:05<00:02, 16.62epoch/s, loss=5.4214, val_loss=5.4344]

Upper model:  54%|█████▍    | 54/100 [00:05<00:02, 16.62epoch/s, loss=5.1668, val_loss=5.0575]

Upper model:  55%|█████▌    | 55/100 [00:05<00:02, 16.88epoch/s, loss=5.1668, val_loss=5.0575]

Upper model:  55%|█████▌    | 55/100 [00:05<00:02, 16.88epoch/s, loss=4.8351, val_loss=4.6966]

Upper model:  56%|█████▌    | 56/100 [00:05<00:02, 16.88epoch/s, loss=4.4812, val_loss=4.3679]

Upper model:  57%|█████▋    | 57/100 [00:05<00:02, 16.65epoch/s, loss=4.4812, val_loss=4.3679]

Upper model:  57%|█████▋    | 57/100 [00:05<00:02, 16.65epoch/s, loss=4.1913, val_loss=4.0442]

Upper model:  58%|█████▊    | 58/100 [00:05<00:02, 16.65epoch/s, loss=3.7146, val_loss=3.7509]

Upper model:  59%|█████▉    | 59/100 [00:05<00:02, 16.49epoch/s, loss=3.7146, val_loss=3.7509]

Upper model:  59%|█████▉    | 59/100 [00:05<00:02, 16.49epoch/s, loss=3.6588, val_loss=3.4772]

Upper model:  60%|██████    | 60/100 [00:05<00:02, 16.49epoch/s, loss=3.3455, val_loss=3.2307]

Upper model:  61%|██████    | 61/100 [00:05<00:02, 16.51epoch/s, loss=3.3455, val_loss=3.2307]

Upper model:  61%|██████    | 61/100 [00:05<00:02, 16.51epoch/s, loss=3.2251, val_loss=3.0149]

Upper model:  62%|██████▏   | 62/100 [00:06<00:02, 16.51epoch/s, loss=2.9773, val_loss=2.8293]

Upper model:  63%|██████▎   | 63/100 [00:06<00:02, 16.87epoch/s, loss=2.9773, val_loss=2.8293]

Upper model:  63%|██████▎   | 63/100 [00:06<00:02, 16.87epoch/s, loss=2.7153, val_loss=2.6635]

Upper model:  64%|██████▍   | 64/100 [00:06<00:02, 16.87epoch/s, loss=2.5915, val_loss=2.5137]

Upper model:  65%|██████▌   | 65/100 [00:06<00:02, 17.12epoch/s, loss=2.5915, val_loss=2.5137]

Upper model:  65%|██████▌   | 65/100 [00:06<00:02, 17.12epoch/s, loss=2.4789, val_loss=2.3682]

Upper model:  66%|██████▌   | 66/100 [00:06<00:01, 17.12epoch/s, loss=2.3435, val_loss=2.2339]

Upper model:  67%|██████▋   | 67/100 [00:06<00:01, 17.15epoch/s, loss=2.3435, val_loss=2.2339]

Upper model:  67%|██████▋   | 67/100 [00:06<00:01, 17.15epoch/s, loss=2.3359, val_loss=2.1081]

Upper model:  68%|██████▊   | 68/100 [00:06<00:01, 17.15epoch/s, loss=2.1680, val_loss=2.0022]

Upper model:  69%|██████▉   | 69/100 [00:06<00:01, 17.13epoch/s, loss=2.1680, val_loss=2.0022]

Upper model:  69%|██████▉   | 69/100 [00:06<00:01, 17.13epoch/s, loss=1.9398, val_loss=1.9050]

Upper model:  70%|███████   | 70/100 [00:06<00:01, 17.13epoch/s, loss=2.1157, val_loss=1.8208]

Upper model:  71%|███████   | 71/100 [00:06<00:01, 17.37epoch/s, loss=2.1157, val_loss=1.8208]

Upper model:  71%|███████   | 71/100 [00:06<00:01, 17.37epoch/s, loss=1.8794, val_loss=1.7470]

Upper model:  72%|███████▏  | 72/100 [00:06<00:01, 17.37epoch/s, loss=2.0199, val_loss=1.6846]

Upper model:  73%|███████▎  | 73/100 [00:06<00:01, 17.57epoch/s, loss=2.0199, val_loss=1.6846]

Upper model:  73%|███████▎  | 73/100 [00:06<00:01, 17.57epoch/s, loss=1.7823, val_loss=1.6270]

Upper model:  74%|███████▍  | 74/100 [00:06<00:01, 17.57epoch/s, loss=1.6183, val_loss=1.5734]

Upper model:  75%|███████▌  | 75/100 [00:06<00:01, 17.63epoch/s, loss=1.6183, val_loss=1.5734]

Upper model:  75%|███████▌  | 75/100 [00:06<00:01, 17.63epoch/s, loss=1.6274, val_loss=1.5207]

Upper model:  76%|███████▌  | 76/100 [00:06<00:01, 17.63epoch/s, loss=1.5105, val_loss=1.4756]

Upper model:  77%|███████▋  | 77/100 [00:06<00:01, 17.28epoch/s, loss=1.5105, val_loss=1.4756]

Upper model:  77%|███████▋  | 77/100 [00:06<00:01, 17.28epoch/s, loss=1.5460, val_loss=1.4393]

Upper model:  78%|███████▊  | 78/100 [00:06<00:01, 17.28epoch/s, loss=1.4676, val_loss=1.4068]

Upper model:  79%|███████▉  | 79/100 [00:06<00:01, 17.31epoch/s, loss=1.4676, val_loss=1.4068]

Upper model:  79%|███████▉  | 79/100 [00:06<00:01, 17.31epoch/s, loss=1.4922, val_loss=1.3805]

Upper model:  80%|████████  | 80/100 [00:07<00:01, 17.31epoch/s, loss=1.5489, val_loss=1.3560]

Upper model:  81%|████████  | 81/100 [00:07<00:01, 17.35epoch/s, loss=1.5489, val_loss=1.3560]

Upper model:  81%|████████  | 81/100 [00:07<00:01, 17.35epoch/s, loss=1.3970, val_loss=1.3333]

Upper model:  82%|████████▏ | 82/100 [00:07<00:01, 17.35epoch/s, loss=1.4807, val_loss=1.3116]

Upper model:  83%|████████▎ | 83/100 [00:07<00:00, 17.44epoch/s, loss=1.4807, val_loss=1.3116]

Upper model:  83%|████████▎ | 83/100 [00:07<00:00, 17.44epoch/s, loss=1.4223, val_loss=1.2892]

Upper model:  84%|████████▍ | 84/100 [00:07<00:00, 17.44epoch/s, loss=1.3798, val_loss=1.2682]

Upper model:  85%|████████▌ | 85/100 [00:07<00:00, 17.16epoch/s, loss=1.3798, val_loss=1.2682]

Upper model:  85%|████████▌ | 85/100 [00:07<00:00, 17.16epoch/s, loss=1.3191, val_loss=1.2502]

Upper model:  86%|████████▌ | 86/100 [00:07<00:00, 17.16epoch/s, loss=1.3331, val_loss=1.2328]

Upper model:  87%|████████▋ | 87/100 [00:07<00:00, 17.32epoch/s, loss=1.3331, val_loss=1.2328]

Upper model:  87%|████████▋ | 87/100 [00:07<00:00, 17.32epoch/s, loss=1.2866, val_loss=1.2166]

Upper model:  88%|████████▊ | 88/100 [00:07<00:00, 17.32epoch/s, loss=1.3288, val_loss=1.2014]

Upper model:  89%|████████▉ | 89/100 [00:07<00:00, 17.45epoch/s, loss=1.3288, val_loss=1.2014]

Upper model:  89%|████████▉ | 89/100 [00:07<00:00, 17.45epoch/s, loss=1.1968, val_loss=1.1877]

Upper model:  90%|█████████ | 90/100 [00:07<00:00, 17.45epoch/s, loss=1.2942, val_loss=1.1740]

Upper model:  91%|█████████ | 91/100 [00:07<00:00, 17.43epoch/s, loss=1.2942, val_loss=1.1740]

Upper model:  91%|█████████ | 91/100 [00:07<00:00, 17.43epoch/s, loss=1.2647, val_loss=1.1599]

Upper model:  92%|█████████▏| 92/100 [00:07<00:00, 17.43epoch/s, loss=1.2593, val_loss=1.1484]

Upper model:  93%|█████████▎| 93/100 [00:07<00:00, 17.56epoch/s, loss=1.2593, val_loss=1.1484]

Upper model:  93%|█████████▎| 93/100 [00:07<00:00, 17.56epoch/s, loss=1.1678, val_loss=1.1367]

Upper model:  94%|█████████▍| 94/100 [00:07<00:00, 17.56epoch/s, loss=1.2034, val_loss=1.1252]

Upper model:  95%|█████████▌| 95/100 [00:07<00:00, 17.49epoch/s, loss=1.2034, val_loss=1.1252]

Upper model:  95%|█████████▌| 95/100 [00:07<00:00, 17.49epoch/s, loss=1.3550, val_loss=1.1149]

Upper model:  96%|█████████▌| 96/100 [00:07<00:00, 17.49epoch/s, loss=1.1342, val_loss=1.1060]

Upper model:  97%|█████████▋| 97/100 [00:07<00:00, 17.24epoch/s, loss=1.1342, val_loss=1.1060]

Upper model:  97%|█████████▋| 97/100 [00:08<00:00, 17.24epoch/s, loss=1.1654, val_loss=1.0976]

Upper model:  98%|█████████▊| 98/100 [00:08<00:00, 17.24epoch/s, loss=1.2696, val_loss=1.0896]

Upper model:  99%|█████████▉| 99/100 [00:08<00:00, 17.19epoch/s, loss=1.2696, val_loss=1.0896]

Upper model:  99%|█████████▉| 99/100 [00:08<00:00, 17.19epoch/s, loss=1.2973, val_loss=1.0808]

Upper model: 100%|██████████| 100/100 [00:08<00:00, 12.27epoch/s, loss=1.2973, val_loss=1.0808]

Lower model:   0%|          | 0/100 [00:00<?, ?epoch/s]

I0000 00:00:1778435169.618558 2605130 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_97606__.19

I0000 00:00:1778435170.425036 2605133 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_97606__.19

Lower model:   0%|          | 0/100 [00:02<?, ?epoch/s, loss=0.3059, val_loss=0.3018]

Lower model:   1%|          | 1/100 [00:02<03:34,  2.17s/epoch, loss=0.3059, val_loss=0.3018]

Lower model:   1%|          | 1/100 [00:02<03:34,  2.17s/epoch, loss=0.3051, val_loss=0.3009]

Lower model:   2%|▏         | 2/100 [00:02<03:32,  2.17s/epoch, loss=0.3041, val_loss=0.2998]

Lower model:   3%|▎         | 3/100 [00:02<00:58,  1.64epoch/s, loss=0.3041, val_loss=0.2998]

Lower model:   3%|▎         | 3/100 [00:02<00:58,  1.64epoch/s, loss=0.3031, val_loss=0.2986]

Lower model:   4%|▍         | 4/100 [00:02<00:58,  1.64epoch/s, loss=0.3018, val_loss=0.2973]

Lower model:   5%|▌         | 5/100 [00:02<00:31,  3.01epoch/s, loss=0.3018, val_loss=0.2973]

Lower model:   5%|▌         | 5/100 [00:02<00:31,  3.01epoch/s, loss=0.3005, val_loss=0.2960]

Lower model:   6%|▌         | 6/100 [00:02<00:31,  3.01epoch/s, loss=0.2992, val_loss=0.2947]

Lower model:   7%|▋         | 7/100 [00:02<00:20,  4.61epoch/s, loss=0.2992, val_loss=0.2947]

Lower model:   7%|▋         | 7/100 [00:02<00:20,  4.61epoch/s, loss=0.2980, val_loss=0.2934]

Lower model:   8%|▊         | 8/100 [00:02<00:19,  4.61epoch/s, loss=0.2964, val_loss=0.2919]

Lower model:   9%|▉         | 9/100 [00:02<00:14,  6.29epoch/s, loss=0.2964, val_loss=0.2919]

Lower model:   9%|▉         | 9/100 [00:02<00:14,  6.29epoch/s, loss=0.2949, val_loss=0.2905]

Lower model:  10%|█         | 10/100 [00:02<00:14,  6.29epoch/s, loss=0.2936, val_loss=0.2889]

Lower model:  11%|█         | 11/100 [00:02<00:10,  8.10epoch/s, loss=0.2936, val_loss=0.2889]

Lower model:  11%|█         | 11/100 [00:02<00:10,  8.10epoch/s, loss=0.2918, val_loss=0.2871]

Lower model:  12%|█▏        | 12/100 [00:02<00:10,  8.10epoch/s, loss=0.2900, val_loss=0.2852]

Lower model:  13%|█▎        | 13/100 [00:02<00:08,  9.80epoch/s, loss=0.2900, val_loss=0.2852]

Lower model:  13%|█▎        | 13/100 [00:02<00:08,  9.80epoch/s, loss=0.2878, val_loss=0.2829]

Lower model:  14%|█▍        | 14/100 [00:03<00:08,  9.80epoch/s, loss=0.2856, val_loss=0.2813]

Lower model:  15%|█▌        | 15/100 [00:03<00:07, 11.38epoch/s, loss=0.2856, val_loss=0.2813]

Lower model:  15%|█▌        | 15/100 [00:03<00:07, 11.38epoch/s, loss=0.2832, val_loss=0.2799]

Lower model:  16%|█▌        | 16/100 [00:03<00:07, 11.38epoch/s, loss=0.2807, val_loss=0.2785]

Lower model:  17%|█▋        | 17/100 [00:03<00:06, 12.52epoch/s, loss=0.2807, val_loss=0.2785]

Lower model:  17%|█▋        | 17/100 [00:03<00:06, 12.52epoch/s, loss=0.2780, val_loss=0.2770]

Lower model:  18%|█▊        | 18/100 [00:03<00:06, 12.52epoch/s, loss=0.2760, val_loss=0.2757]

Lower model:  19%|█▉        | 19/100 [00:03<00:05, 13.64epoch/s, loss=0.2760, val_loss=0.2757]

Lower model:  19%|█▉        | 19/100 [00:03<00:05, 13.64epoch/s, loss=0.2749, val_loss=0.2744]

Lower model:  20%|██        | 20/100 [00:03<00:05, 13.64epoch/s, loss=0.2723, val_loss=0.2731]

Lower model:  21%|██        | 21/100 [00:03<00:05, 14.45epoch/s, loss=0.2723, val_loss=0.2731]

Lower model:  21%|██        | 21/100 [00:03<00:05, 14.45epoch/s, loss=0.2700, val_loss=0.2738]

Lower model:  22%|██▏       | 22/100 [00:03<00:05, 14.45epoch/s, loss=0.2688, val_loss=0.2773]

Lower model:  23%|██▎       | 23/100 [00:03<00:05, 14.96epoch/s, loss=0.2688, val_loss=0.2773]

Lower model:  23%|██▎       | 23/100 [00:03<00:05, 14.96epoch/s, loss=0.2661, val_loss=0.2819]

Lower model:  24%|██▍       | 24/100 [00:03<00:05, 14.96epoch/s, loss=0.2612, val_loss=0.2873]

Lower model:  25%|██▌       | 25/100 [00:03<00:04, 15.30epoch/s, loss=0.2612, val_loss=0.2873]

Lower model:  25%|██▌       | 25/100 [00:03<00:04, 15.30epoch/s, loss=0.2618, val_loss=0.2932]

Lower model:  26%|██▌       | 26/100 [00:03<00:04, 15.30epoch/s, loss=0.2609, val_loss=0.2962]

Lower model:  27%|██▋       | 27/100 [00:03<00:04, 15.85epoch/s, loss=0.2609, val_loss=0.2962]

Lower model:  27%|██▋       | 27/100 [00:03<00:04, 15.85epoch/s, loss=0.2620, val_loss=0.2987]

Lower model:  28%|██▊       | 28/100 [00:03<00:04, 15.85epoch/s, loss=0.2618, val_loss=0.3005]

Lower model:  29%|██▉       | 29/100 [00:03<00:04, 15.79epoch/s, loss=0.2618, val_loss=0.3005]

Lower model:  29%|██▉       | 29/100 [00:03<00:04, 15.79epoch/s, loss=0.2613, val_loss=0.3026]

Lower model:  30%|███       | 30/100 [00:04<00:04, 15.79epoch/s, loss=0.2621, val_loss=0.3044]

Lower model:  31%|███       | 31/100 [00:04<00:04, 15.90epoch/s, loss=0.2621, val_loss=0.3044]

Lower model:  31%|███       | 31/100 [00:04<00:08,  7.73epoch/s, loss=0.2621, val_loss=0.3044]

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

WARNING:tensorflow:5 out of the last 21 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7f7ef05be700> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

  > CQR Calibration constant (Q): 5.5699

Running configuration: Low:0.02 - High:0.97

Upper model:   0%|          | 0/100 [00:00<?, ?epoch/s]

I0000 00:00:1778435174.330731 2605131 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_101575__.19

I0000 00:00:1778435175.136794 2605131 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_101575__.19

Upper model:   0%|          | 0/100 [00:02<?, ?epoch/s, loss=19.6759, val_loss=19.4209]

Upper model:   1%|          | 1/100 [00:02<03:45,  2.28s/epoch, loss=19.6759, val_loss=19.4209]

Upper model:   1%|          | 1/100 [00:02<03:45,  2.28s/epoch, loss=19.6394, val_loss=19.3810]

Upper model:   2%|▏         | 2/100 [00:02<03:43,  2.28s/epoch, loss=19.6020, val_loss=19.3352]

Upper model:   3%|▎         | 3/100 [00:02<01:01,  1.57epoch/s, loss=19.6020, val_loss=19.3352]

Upper model:   3%|▎         | 3/100 [00:02<01:01,  1.57epoch/s, loss=19.5545, val_loss=19.2870]

Upper model:   4%|▍         | 4/100 [00:02<01:01,  1.57epoch/s, loss=19.5104, val_loss=19.2384]

Upper model:   5%|▌         | 5/100 [00:02<00:32,  2.96epoch/s, loss=19.5104, val_loss=19.2384]

Upper model:   5%|▌         | 5/100 [00:02<00:32,  2.96epoch/s, loss=19.4616, val_loss=19.1903]

Upper model:   6%|▌         | 6/100 [00:02<00:31,  2.96epoch/s, loss=19.4147, val_loss=19.1418]

Upper model:   7%|▋         | 7/100 [00:02<00:20,  4.56epoch/s, loss=19.4147, val_loss=19.1418]

Upper model:   7%|▋         | 7/100 [00:02<00:20,  4.56epoch/s, loss=19.3589, val_loss=19.0915]

Upper model:   8%|▊         | 8/100 [00:02<00:20,  4.56epoch/s, loss=19.3102, val_loss=19.0386]

Upper model:   9%|▉         | 9/100 [00:02<00:14,  6.34epoch/s, loss=19.3102, val_loss=19.0386]

Upper model:   9%|▉         | 9/100 [00:02<00:14,  6.34epoch/s, loss=19.2582, val_loss=18.9829]

Upper model:  10%|█         | 10/100 [00:02<00:14,  6.34epoch/s, loss=19.1962, val_loss=18.9234]

Upper model:  11%|█         | 11/100 [00:02<00:10,  8.15epoch/s, loss=19.1962, val_loss=18.9234]

Upper model:  11%|█         | 11/100 [00:02<00:10,  8.15epoch/s, loss=19.1370, val_loss=18.8599]

Upper model:  12%|█▏        | 12/100 [00:02<00:10,  8.15epoch/s, loss=19.0719, val_loss=18.7915]

Upper model:  13%|█▎        | 13/100 [00:02<00:08,  9.71epoch/s, loss=19.0719, val_loss=18.7915]

Upper model:  13%|█▎        | 13/100 [00:03<00:08,  9.71epoch/s, loss=18.9933, val_loss=18.7172]

Upper model:  14%|█▍        | 14/100 [00:03<00:08,  9.71epoch/s, loss=18.9165, val_loss=18.6369]

Upper model:  15%|█▌        | 15/100 [00:03<00:07, 10.98epoch/s, loss=18.9165, val_loss=18.6369]

Upper model:  15%|█▌        | 15/100 [00:03<00:07, 10.98epoch/s, loss=18.8333, val_loss=18.5491]

Upper model:  16%|█▌        | 16/100 [00:03<00:07, 10.98epoch/s, loss=18.7422, val_loss=18.4535]

Upper model:  17%|█▋        | 17/100 [00:03<00:06, 12.32epoch/s, loss=18.7422, val_loss=18.4535]

Upper model:  17%|█▋        | 17/100 [00:03<00:06, 12.32epoch/s, loss=18.6323, val_loss=18.3493]

Upper model:  18%|█▊        | 18/100 [00:03<00:06, 12.32epoch/s, loss=18.5386, val_loss=18.2362]

Upper model:  19%|█▉        | 19/100 [00:03<00:05, 13.66epoch/s, loss=18.5386, val_loss=18.2362]

Upper model:  19%|█▉        | 19/100 [00:03<00:05, 13.66epoch/s, loss=18.3948, val_loss=18.1141]

Upper model:  20%|██        | 20/100 [00:03<00:05, 13.66epoch/s, loss=18.2921, val_loss=17.9809]

Upper model:  21%|██        | 21/100 [00:03<00:05, 14.70epoch/s, loss=18.2921, val_loss=17.9809]

Upper model:  21%|██        | 21/100 [00:03<00:05, 14.70epoch/s, loss=18.1539, val_loss=17.8367]

Upper model:  22%|██▏       | 22/100 [00:03<00:05, 14.70epoch/s, loss=17.9906, val_loss=17.6803]

Upper model:  23%|██▎       | 23/100 [00:03<00:05, 15.10epoch/s, loss=17.9906, val_loss=17.6803]

Upper model:  23%|██▎       | 23/100 [00:03<00:05, 15.10epoch/s, loss=17.8057, val_loss=17.5102]

Upper model:  24%|██▍       | 24/100 [00:03<00:05, 15.10epoch/s, loss=17.6654, val_loss=17.3273]

Upper model:  25%|██▌       | 25/100 [00:03<00:04, 15.64epoch/s, loss=17.6654, val_loss=17.3273]

Upper model:  25%|██▌       | 25/100 [00:03<00:04, 15.64epoch/s, loss=17.4618, val_loss=17.1305]

Upper model:  26%|██▌       | 26/100 [00:03<00:04, 15.64epoch/s, loss=17.2677, val_loss=16.9199]

Upper model:  27%|██▋       | 27/100 [00:03<00:04, 16.26epoch/s, loss=17.2677, val_loss=16.9199]

Upper model:  27%|██▋       | 27/100 [00:03<00:04, 16.26epoch/s, loss=17.0090, val_loss=16.6944]

Upper model:  28%|██▊       | 28/100 [00:03<00:04, 16.26epoch/s, loss=16.7696, val_loss=16.4530]

Upper model:  29%|██▉       | 29/100 [00:03<00:04, 16.75epoch/s, loss=16.7696, val_loss=16.4530]

Upper model:  29%|██▉       | 29/100 [00:03<00:04, 16.75epoch/s, loss=16.5016, val_loss=16.1942]

Upper model:  30%|███       | 30/100 [00:04<00:04, 16.75epoch/s, loss=16.2484, val_loss=15.9159]

Upper model:  31%|███       | 31/100 [00:04<00:04, 16.77epoch/s, loss=16.2484, val_loss=15.9159]

Upper model:  31%|███       | 31/100 [00:04<00:04, 16.77epoch/s, loss=15.8951, val_loss=15.6205]

Upper model:  32%|███▏      | 32/100 [00:04<00:04, 16.77epoch/s, loss=15.6336, val_loss=15.3065]

Upper model:  33%|███▎      | 33/100 [00:04<00:04, 16.41epoch/s, loss=15.6336, val_loss=15.3065]

Upper model:  33%|███▎      | 33/100 [00:04<00:04, 16.41epoch/s, loss=15.2964, val_loss=14.9755]

Upper model:  34%|███▍      | 34/100 [00:04<00:04, 16.41epoch/s, loss=14.9183, val_loss=14.6254]

Upper model:  35%|███▌      | 35/100 [00:04<00:03, 16.34epoch/s, loss=14.9183, val_loss=14.6254]

Upper model:  35%|███▌      | 35/100 [00:04<00:03, 16.34epoch/s, loss=14.5452, val_loss=14.2564]

Upper model:  36%|███▌      | 36/100 [00:04<00:03, 16.34epoch/s, loss=14.2167, val_loss=13.8679]

Upper model:  37%|███▋      | 37/100 [00:04<00:03, 16.53epoch/s, loss=14.2167, val_loss=13.8679]

Upper model:  37%|███▋      | 37/100 [00:04<00:03, 16.53epoch/s, loss=13.7037, val_loss=13.4688]

Upper model:  38%|███▊      | 38/100 [00:04<00:03, 16.53epoch/s, loss=13.2282, val_loss=13.0491]

Upper model:  39%|███▉      | 39/100 [00:04<00:03, 16.50epoch/s, loss=13.2282, val_loss=13.0491]

Upper model:  39%|███▉      | 39/100 [00:04<00:03, 16.50epoch/s, loss=12.9009, val_loss=12.6181]

Upper model:  40%|████      | 40/100 [00:04<00:03, 16.50epoch/s, loss=12.4299, val_loss=12.1785]

Upper model:  41%|████      | 41/100 [00:04<00:03, 16.33epoch/s, loss=12.4299, val_loss=12.1785]

Upper model:  41%|████      | 41/100 [00:04<00:03, 16.33epoch/s, loss=11.9260, val_loss=11.7365]

Upper model:  42%|████▏     | 42/100 [00:04<00:03, 16.33epoch/s, loss=11.5146, val_loss=11.2838]

Upper model:  43%|████▎     | 43/100 [00:04<00:03, 16.10epoch/s, loss=11.5146, val_loss=11.2838]

Upper model:  43%|████▎     | 43/100 [00:04<00:03, 16.10epoch/s, loss=11.0646, val_loss=10.8252]

Upper model:  44%|████▍     | 44/100 [00:04<00:03, 16.10epoch/s, loss=10.5940, val_loss=10.3617]

Upper model:  45%|████▌     | 45/100 [00:04<00:03, 15.78epoch/s, loss=10.5940, val_loss=10.3617]

Upper model:  45%|████▌     | 45/100 [00:04<00:03, 15.78epoch/s, loss=9.9930, val_loss=9.8940]

Upper model:  46%|████▌     | 46/100 [00:05<00:03, 15.78epoch/s, loss=9.5573, val_loss=9.4332]

Upper model:  47%|████▋     | 47/100 [00:05<00:03, 15.91epoch/s, loss=9.5573, val_loss=9.4332]

Upper model:  47%|████▋     | 47/100 [00:05<00:03, 15.91epoch/s, loss=9.1756, val_loss=8.9702]

Upper model:  48%|████▊     | 48/100 [00:05<00:03, 15.91epoch/s, loss=8.5141, val_loss=8.4994]

Upper model:  49%|████▉     | 49/100 [00:05<00:03, 15.41epoch/s, loss=8.5141, val_loss=8.4994]

Upper model:  49%|████▉     | 49/100 [00:05<00:03, 15.41epoch/s, loss=8.0887, val_loss=8.0325]

Upper model:  50%|█████     | 50/100 [00:05<00:03, 15.41epoch/s, loss=7.6898, val_loss=7.5736]

Upper model:  51%|█████     | 51/100 [00:05<00:03, 15.74epoch/s, loss=7.6898, val_loss=7.5736]

Upper model:  51%|█████     | 51/100 [00:05<00:03, 15.74epoch/s, loss=7.2715, val_loss=7.1324]

Upper model:  52%|█████▏    | 52/100 [00:05<00:03, 15.74epoch/s, loss=6.7036, val_loss=6.7004]

Upper model:  53%|█████▎    | 53/100 [00:05<00:02, 16.36epoch/s, loss=6.7036, val_loss=6.7004]

Upper model:  53%|█████▎    | 53/100 [00:05<00:02, 16.36epoch/s, loss=6.3960, val_loss=6.2821]

Upper model:  54%|█████▍    | 54/100 [00:05<00:02, 16.36epoch/s, loss=6.0029, val_loss=5.8706]

Upper model:  55%|█████▌    | 55/100 [00:05<00:02, 16.77epoch/s, loss=6.0029, val_loss=5.8706]

Upper model:  55%|█████▌    | 55/100 [00:05<00:02, 16.77epoch/s, loss=5.5242, val_loss=5.4655]

Upper model:  56%|█████▌    | 56/100 [00:05<00:02, 16.77epoch/s, loss=5.2556, val_loss=5.0783]

Upper model:  57%|█████▋    | 57/100 [00:05<00:02, 16.48epoch/s, loss=5.2556, val_loss=5.0783]

Upper model:  57%|█████▋    | 57/100 [00:05<00:02, 16.48epoch/s, loss=4.9469, val_loss=4.7278]

Upper model:  58%|█████▊    | 58/100 [00:05<00:02, 16.48epoch/s, loss=4.5432, val_loss=4.3983]

Upper model:  59%|█████▉    | 59/100 [00:05<00:02, 16.25epoch/s, loss=4.5432, val_loss=4.3983]

Upper model:  59%|█████▉    | 59/100 [00:05<00:02, 16.25epoch/s, loss=4.2732, val_loss=4.0939]

Upper model:  60%|██████    | 60/100 [00:05<00:02, 16.25epoch/s, loss=4.0045, val_loss=3.7962]

Upper model:  61%|██████    | 61/100 [00:05<00:02, 16.67epoch/s, loss=4.0045, val_loss=3.7962]

Upper model:  61%|██████    | 61/100 [00:05<00:02, 16.67epoch/s, loss=3.6640, val_loss=3.5136]

Upper model:  62%|██████▏   | 62/100 [00:06<00:02, 16.67epoch/s, loss=3.4279, val_loss=3.2732]

Upper model:  63%|██████▎   | 63/100 [00:06<00:02, 16.88epoch/s, loss=3.4279, val_loss=3.2732]

Upper model:  63%|██████▎   | 63/100 [00:06<00:02, 16.88epoch/s, loss=3.3503, val_loss=3.0694]

Upper model:  64%|██████▍   | 64/100 [00:06<00:02, 16.88epoch/s, loss=3.1681, val_loss=2.8784]

Upper model:  65%|██████▌   | 65/100 [00:06<00:02, 16.10epoch/s, loss=3.1681, val_loss=2.8784]

Upper model:  65%|██████▌   | 65/100 [00:06<00:02, 16.10epoch/s, loss=2.9066, val_loss=2.7022]

Upper model:  66%|██████▌   | 66/100 [00:06<00:02, 16.10epoch/s, loss=2.6813, val_loss=2.5426]

Upper model:  67%|██████▋   | 67/100 [00:06<00:02, 16.21epoch/s, loss=2.6813, val_loss=2.5426]

Upper model:  67%|██████▋   | 67/100 [00:06<00:02, 16.21epoch/s, loss=2.5121, val_loss=2.3878]

Upper model:  68%|██████▊   | 68/100 [00:06<00:01, 16.21epoch/s, loss=2.3583, val_loss=2.2442]

Upper model:  69%|██████▉   | 69/100 [00:06<00:01, 16.53epoch/s, loss=2.3583, val_loss=2.2442]

Upper model:  69%|██████▉   | 69/100 [00:06<00:01, 16.53epoch/s, loss=2.3307, val_loss=2.1159]

Upper model:  70%|███████   | 70/100 [00:06<00:01, 16.53epoch/s, loss=2.4300, val_loss=2.0046]

Upper model:  71%|███████   | 71/100 [00:06<00:01, 16.94epoch/s, loss=2.4300, val_loss=2.0046]

Upper model:  71%|███████   | 71/100 [00:06<00:01, 16.94epoch/s, loss=2.1647, val_loss=1.9088]

Upper model:  72%|███████▏  | 72/100 [00:06<00:01, 16.94epoch/s, loss=2.0951, val_loss=1.8277]

Upper model:  73%|███████▎  | 73/100 [00:06<00:01, 16.78epoch/s, loss=2.0951, val_loss=1.8277]

Upper model:  73%|███████▎  | 73/100 [00:06<00:01, 16.78epoch/s, loss=2.0027, val_loss=1.7497]

Upper model:  74%|███████▍  | 74/100 [00:06<00:01, 16.78epoch/s, loss=2.0129, val_loss=1.6839]

Upper model:  75%|███████▌  | 75/100 [00:06<00:01, 17.06epoch/s, loss=2.0129, val_loss=1.6839]

Upper model:  75%|███████▌  | 75/100 [00:06<00:01, 17.06epoch/s, loss=1.9042, val_loss=1.6231]

Upper model:  76%|███████▌  | 76/100 [00:06<00:01, 17.06epoch/s, loss=1.7473, val_loss=1.5658]

Upper model:  77%|███████▋  | 77/100 [00:06<00:01, 16.95epoch/s, loss=1.7473, val_loss=1.5658]

Upper model:  77%|███████▋  | 77/100 [00:06<00:01, 16.95epoch/s, loss=1.6996, val_loss=1.5177]

Upper model:  78%|███████▊  | 78/100 [00:06<00:01, 16.95epoch/s, loss=1.6323, val_loss=1.4721]

Upper model:  79%|███████▉  | 79/100 [00:06<00:01, 16.68epoch/s, loss=1.6323, val_loss=1.4721]

Upper model:  79%|███████▉  | 79/100 [00:07<00:01, 16.68epoch/s, loss=1.6972, val_loss=1.4291]

Upper model:  80%|████████  | 80/100 [00:07<00:01, 16.68epoch/s, loss=1.5449, val_loss=1.3905]

Upper model:  81%|████████  | 81/100 [00:07<00:01, 16.95epoch/s, loss=1.5449, val_loss=1.3905]

Upper model:  81%|████████  | 81/100 [00:07<00:01, 16.95epoch/s, loss=1.3953, val_loss=1.3543]

Upper model:  82%|████████▏ | 82/100 [00:07<00:01, 16.95epoch/s, loss=1.4337, val_loss=1.3227]

Upper model:  83%|████████▎ | 83/100 [00:07<00:00, 17.13epoch/s, loss=1.4337, val_loss=1.3227]

Upper model:  83%|████████▎ | 83/100 [00:07<00:00, 17.13epoch/s, loss=1.3951, val_loss=1.2936]

Upper model:  84%|████████▍ | 84/100 [00:07<00:00, 17.13epoch/s, loss=1.4551, val_loss=1.2644]

Upper model:  85%|████████▌ | 85/100 [00:07<00:00, 16.11epoch/s, loss=1.4551, val_loss=1.2644]

Upper model:  85%|████████▌ | 85/100 [00:07<00:00, 16.11epoch/s, loss=1.3400, val_loss=1.2375]

Upper model:  86%|████████▌ | 86/100 [00:07<00:00, 16.11epoch/s, loss=1.4152, val_loss=1.2146]

Upper model:  87%|████████▋ | 87/100 [00:07<00:00, 15.96epoch/s, loss=1.4152, val_loss=1.2146]

Upper model:  87%|████████▋ | 87/100 [00:07<00:00, 15.96epoch/s, loss=1.2850, val_loss=1.1938]

Upper model:  88%|████████▊ | 88/100 [00:07<00:00, 15.96epoch/s, loss=1.3034, val_loss=1.1736]

Upper model:  89%|████████▉ | 89/100 [00:07<00:00, 15.82epoch/s, loss=1.3034, val_loss=1.1736]

Upper model:  89%|████████▉ | 89/100 [00:07<00:00, 15.82epoch/s, loss=1.1497, val_loss=1.1526]

Upper model:  90%|█████████ | 90/100 [00:07<00:00, 15.82epoch/s, loss=1.3191, val_loss=1.1334]

Upper model:  91%|█████████ | 91/100 [00:07<00:00, 15.60epoch/s, loss=1.3191, val_loss=1.1334]

Upper model:  91%|█████████ | 91/100 [00:07<00:00, 15.60epoch/s, loss=1.1159, val_loss=1.1167]

Upper model:  92%|█████████▏| 92/100 [00:07<00:00, 15.60epoch/s, loss=1.2078, val_loss=1.1019]

Upper model:  93%|█████████▎| 93/100 [00:07<00:00, 16.19epoch/s, loss=1.2078, val_loss=1.1019]

Upper model:  93%|█████████▎| 93/100 [00:07<00:00, 16.19epoch/s, loss=1.2134, val_loss=1.0892]

Upper model:  94%|█████████▍| 94/100 [00:07<00:00, 16.19epoch/s, loss=1.1661, val_loss=1.0767]

Upper model:  95%|█████████▌| 95/100 [00:07<00:00, 16.19epoch/s, loss=1.1661, val_loss=1.0767]

Upper model:  95%|█████████▌| 95/100 [00:08<00:00, 16.19epoch/s, loss=1.2282, val_loss=1.0666]

Upper model:  96%|█████████▌| 96/100 [00:08<00:00, 16.19epoch/s, loss=1.1973, val_loss=1.0568]

Upper model:  97%|█████████▋| 97/100 [00:08<00:00, 16.62epoch/s, loss=1.1973, val_loss=1.0568]

Upper model:  97%|█████████▋| 97/100 [00:08<00:00, 16.62epoch/s, loss=1.0953, val_loss=1.0469]

Upper model:  98%|█████████▊| 98/100 [00:08<00:00, 16.62epoch/s, loss=1.2595, val_loss=1.0375]

Upper model:  99%|█████████▉| 99/100 [00:08<00:00, 16.79epoch/s, loss=1.2595, val_loss=1.0375]

Upper model:  99%|█████████▉| 99/100 [00:08<00:00, 16.79epoch/s, loss=1.2131, val_loss=1.0284]

Upper model: 100%|██████████| 100/100 [00:08<00:00, 12.12epoch/s, loss=1.2131, val_loss=1.0284]

Lower model:   0%|          | 0/100 [00:00<?, ?epoch/s]

I0000 00:00:1778435182.535296 2605130 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_108494__.19

I0000 00:00:1778435183.358399 2605133 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_108494__.19

Lower model:   0%|          | 0/100 [00:02<?, ?epoch/s, loss=0.4005, val_loss=0.3948]

Lower model:   1%|          | 1/100 [00:02<03:37,  2.20s/epoch, loss=0.4005, val_loss=0.3948]

Lower model:   1%|          | 1/100 [00:02<03:37,  2.20s/epoch, loss=0.3989, val_loss=0.3932]

Lower model:   2%|▏         | 2/100 [00:02<03:35,  2.20s/epoch, loss=0.3972, val_loss=0.3915]

Lower model:   3%|▎         | 3/100 [00:02<00:59,  1.63epoch/s, loss=0.3972, val_loss=0.3915]

Lower model:   3%|▎         | 3/100 [00:02<00:59,  1.63epoch/s, loss=0.3955, val_loss=0.3896]

Lower model:   4%|▍         | 4/100 [00:02<00:58,  1.63epoch/s, loss=0.3936, val_loss=0.3876]

Lower model:   5%|▌         | 5/100 [00:02<00:31,  3.02epoch/s, loss=0.3936, val_loss=0.3876]

Lower model:   5%|▌         | 5/100 [00:02<00:31,  3.02epoch/s, loss=0.3913, val_loss=0.3855]

Lower model:   6%|▌         | 6/100 [00:02<00:31,  3.02epoch/s, loss=0.3891, val_loss=0.3831]

Lower model:   7%|▋         | 7/100 [00:02<00:20,  4.61epoch/s, loss=0.3891, val_loss=0.3831]

Lower model:   7%|▋         | 7/100 [00:02<00:20,  4.61epoch/s, loss=0.3864, val_loss=0.3805]

Lower model:   8%|▊         | 8/100 [00:02<00:19,  4.61epoch/s, loss=0.3840, val_loss=0.3777]

Lower model:   9%|▉         | 9/100 [00:02<00:14,  6.39epoch/s, loss=0.3840, val_loss=0.3777]

Lower model:   9%|▉         | 9/100 [00:02<00:14,  6.39epoch/s, loss=0.3811, val_loss=0.3752]

Lower model:  10%|█         | 10/100 [00:02<00:14,  6.39epoch/s, loss=0.3786, val_loss=0.3733]

Lower model:  11%|█         | 11/100 [00:02<00:10,  8.26epoch/s, loss=0.3786, val_loss=0.3733]

Lower model:  11%|█         | 11/100 [00:02<00:10,  8.26epoch/s, loss=0.3751, val_loss=0.3712]

Lower model:  12%|█▏        | 12/100 [00:02<00:10,  8.26epoch/s, loss=0.3717, val_loss=0.3691]

Lower model:  13%|█▎        | 13/100 [00:02<00:08,  9.98epoch/s, loss=0.3717, val_loss=0.3691]

Lower model:  13%|█▎        | 13/100 [00:02<00:08,  9.98epoch/s, loss=0.3686, val_loss=0.3667]

Lower model:  14%|█▍        | 14/100 [00:03<00:08,  9.98epoch/s, loss=0.3651, val_loss=0.3643]

Lower model:  15%|█▌        | 15/100 [00:03<00:07, 11.34epoch/s, loss=0.3651, val_loss=0.3643]

Lower model:  15%|█▌        | 15/100 [00:03<00:07, 11.34epoch/s, loss=0.3620, val_loss=0.3618]

Lower model:  16%|█▌        | 16/100 [00:03<00:07, 11.34epoch/s, loss=0.3597, val_loss=0.3605]

Lower model:  17%|█▋        | 17/100 [00:03<00:06, 12.16epoch/s, loss=0.3597, val_loss=0.3605]

Lower model:  17%|█▋        | 17/100 [00:03<00:06, 12.16epoch/s, loss=0.3570, val_loss=0.3603]

Lower model:  18%|█▊        | 18/100 [00:03<00:06, 12.16epoch/s, loss=0.3554, val_loss=0.3604]

Lower model:  19%|█▉        | 19/100 [00:03<00:06, 13.16epoch/s, loss=0.3554, val_loss=0.3604]

Lower model:  19%|█▉        | 19/100 [00:03<00:06, 13.16epoch/s, loss=0.3520, val_loss=0.3618]

Lower model:  20%|██        | 20/100 [00:03<00:06, 13.16epoch/s, loss=0.3491, val_loss=0.3652]

Lower model:  21%|██        | 21/100 [00:03<00:05, 14.37epoch/s, loss=0.3491, val_loss=0.3652]

Lower model:  21%|██        | 21/100 [00:03<00:05, 14.37epoch/s, loss=0.3486, val_loss=0.3685]

Lower model:  22%|██▏       | 22/100 [00:03<00:05, 14.37epoch/s, loss=0.3458, val_loss=0.3718]

Lower model:  23%|██▎       | 23/100 [00:03<00:05, 15.34epoch/s, loss=0.3458, val_loss=0.3718]

Lower model:  23%|██▎       | 23/100 [00:03<00:05, 15.34epoch/s, loss=0.3427, val_loss=0.3734]

Lower model:  24%|██▍       | 24/100 [00:03<00:04, 15.34epoch/s, loss=0.3402, val_loss=0.3749]

Lower model:  25%|██▌       | 25/100 [00:03<00:04, 15.60epoch/s, loss=0.3402, val_loss=0.3749]

Lower model:  25%|██▌       | 25/100 [00:03<00:04, 15.60epoch/s, loss=0.3436, val_loss=0.3760]

Lower model:  26%|██▌       | 26/100 [00:03<00:04, 15.60epoch/s, loss=0.3428, val_loss=0.3762]

Lower model:  27%|██▋       | 27/100 [00:03<00:04, 16.08epoch/s, loss=0.3428, val_loss=0.3762]

Lower model:  27%|██▋       | 27/100 [00:03<00:04, 16.08epoch/s, loss=0.3435, val_loss=0.3765]

Lower model:  28%|██▊       | 28/100 [00:03<00:09,  7.32epoch/s, loss=0.3435, val_loss=0.3765]

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

  > CQR Calibration constant (Q): 4.0297

Running configuration: Low:0.025 - High:0.975

Upper model:   0%|          | 0/100 [00:00<?, ?epoch/s]

I0000 00:00:1778435187.001707 2605130 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_112307__.19

I0000 00:00:1778435187.761705 2605127 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_112307__.19

Upper model:   0%|          | 0/100 [00:02<?, ?epoch/s, loss=19.8659, val_loss=19.5950]

Upper model:   1%|          | 1/100 [00:02<03:28,  2.11s/epoch, loss=19.8659, val_loss=19.5950]

Upper model:   1%|          | 1/100 [00:02<03:28,  2.11s/epoch, loss=19.8101, val_loss=19.5406]

Upper model:   2%|▏         | 2/100 [00:02<03:26,  2.11s/epoch, loss=19.7582, val_loss=19.4882]

Upper model:   3%|▎         | 3/100 [00:02<00:57,  1.70epoch/s, loss=19.7582, val_loss=19.4882]

Upper model:   3%|▎         | 3/100 [00:02<00:57,  1.70epoch/s, loss=19.7075, val_loss=19.4383]

Upper model:   4%|▍         | 4/100 [00:02<00:56,  1.70epoch/s, loss=19.6528, val_loss=19.3892]

Upper model:   5%|▌         | 5/100 [00:02<00:29,  3.17epoch/s, loss=19.6528, val_loss=19.3892]

Upper model:   5%|▌         | 5/100 [00:02<00:29,  3.17epoch/s, loss=19.6026, val_loss=19.3395]

Upper model:   6%|▌         | 6/100 [00:02<00:29,  3.17epoch/s, loss=19.5494, val_loss=19.2883]

Upper model:   7%|▋         | 7/100 [00:02<00:19,  4.77epoch/s, loss=19.5494, val_loss=19.2883]

Upper model:   7%|▋         | 7/100 [00:02<00:19,  4.77epoch/s, loss=19.4985, val_loss=19.2345]

Upper model:   8%|▊         | 8/100 [00:02<00:19,  4.77epoch/s, loss=19.4351, val_loss=19.1769]

Upper model:   9%|▉         | 9/100 [00:02<00:14,  6.38epoch/s, loss=19.4351, val_loss=19.1769]

Upper model:   9%|▉         | 9/100 [00:02<00:14,  6.38epoch/s, loss=19.3761, val_loss=19.1135]

Upper model:  10%|█         | 10/100 [00:02<00:14,  6.38epoch/s, loss=19.3133, val_loss=19.0430]

Upper model:  11%|█         | 11/100 [00:02<00:11,  8.05epoch/s, loss=19.3133, val_loss=19.0430]

Upper model:  11%|█         | 11/100 [00:02<00:11,  8.05epoch/s, loss=19.2367, val_loss=18.9646]

Upper model:  12%|█▏        | 12/100 [00:02<00:10,  8.05epoch/s, loss=19.1649, val_loss=18.8784]

Upper model:  13%|█▎        | 13/100 [00:02<00:09,  9.57epoch/s, loss=19.1649, val_loss=18.8784]

Upper model:  13%|█▎        | 13/100 [00:02<00:09,  9.57epoch/s, loss=19.0768, val_loss=18.7819]

Upper model:  14%|█▍        | 14/100 [00:02<00:08,  9.57epoch/s, loss=18.9642, val_loss=18.6760]

Upper model:  15%|█▌        | 15/100 [00:02<00:07, 10.89epoch/s, loss=18.9642, val_loss=18.6760]

Upper model:  15%|█▌        | 15/100 [00:03<00:07, 10.89epoch/s, loss=18.8519, val_loss=18.5599]

Upper model:  16%|█▌        | 16/100 [00:03<00:07, 10.89epoch/s, loss=18.7358, val_loss=18.4330]

Upper model:  17%|█▋        | 17/100 [00:03<00:07, 11.75epoch/s, loss=18.7358, val_loss=18.4330]

Upper model:  17%|█▋        | 17/100 [00:03<00:07, 11.75epoch/s, loss=18.5857, val_loss=18.2932]

Upper model:  18%|█▊        | 18/100 [00:03<00:06, 11.75epoch/s, loss=18.4576, val_loss=18.1374]

Upper model:  19%|█▉        | 19/100 [00:03<00:06, 13.04epoch/s, loss=18.4576, val_loss=18.1374]

Upper model:  19%|█▉        | 19/100 [00:03<00:06, 13.04epoch/s, loss=18.2810, val_loss=17.9703]

Upper model:  20%|██        | 20/100 [00:03<00:06, 13.04epoch/s, loss=18.1098, val_loss=17.7939]

Upper model:  21%|██        | 21/100 [00:03<00:05, 13.93epoch/s, loss=18.1098, val_loss=17.7939]

Upper model:  21%|██        | 21/100 [00:03<00:05, 13.93epoch/s, loss=17.9126, val_loss=17.6092]

Upper model:  22%|██▏       | 22/100 [00:03<00:05, 13.93epoch/s, loss=17.7317, val_loss=17.4166]

Upper model:  23%|██▎       | 23/100 [00:03<00:05, 14.79epoch/s, loss=17.7317, val_loss=17.4166]

Upper model:  23%|██▎       | 23/100 [00:03<00:05, 14.79epoch/s, loss=17.5417, val_loss=17.2165]

Upper model:  24%|██▍       | 24/100 [00:03<00:05, 14.79epoch/s, loss=17.3306, val_loss=17.0096]

Upper model:  25%|██▌       | 25/100 [00:03<00:05, 14.70epoch/s, loss=17.3306, val_loss=17.0096]

Upper model:  25%|██▌       | 25/100 [00:03<00:05, 14.70epoch/s, loss=17.1307, val_loss=16.7966]

Upper model:  26%|██▌       | 26/100 [00:03<00:05, 14.70epoch/s, loss=16.8794, val_loss=16.5741]

Upper model:  27%|██▋       | 27/100 [00:03<00:04, 15.16epoch/s, loss=16.8794, val_loss=16.5741]

Upper model:  27%|██▋       | 27/100 [00:03<00:04, 15.16epoch/s, loss=16.6541, val_loss=16.3412]

Upper model:  28%|██▊       | 28/100 [00:03<00:04, 15.16epoch/s, loss=16.4310, val_loss=16.0975]

Upper model:  29%|██▉       | 29/100 [00:03<00:04, 15.63epoch/s, loss=16.4310, val_loss=16.0975]

Upper model:  29%|██▉       | 29/100 [00:03<00:04, 15.63epoch/s, loss=16.1410, val_loss=15.8430]

Upper model:  30%|███       | 30/100 [00:03<00:04, 15.63epoch/s, loss=15.8653, val_loss=15.5772]

Upper model:  31%|███       | 31/100 [00:03<00:04, 15.87epoch/s, loss=15.8653, val_loss=15.5772]

Upper model:  31%|███       | 31/100 [00:04<00:04, 15.87epoch/s, loss=15.5748, val_loss=15.3019]

Upper model:  32%|███▏      | 32/100 [00:04<00:04, 15.87epoch/s, loss=15.2173, val_loss=15.0134]

Upper model:  33%|███▎      | 33/100 [00:04<00:04, 16.27epoch/s, loss=15.2173, val_loss=15.0134]

Upper model:  33%|███▎      | 33/100 [00:04<00:04, 16.27epoch/s, loss=14.9298, val_loss=14.7114]

Upper model:  34%|███▍      | 34/100 [00:04<00:04, 16.27epoch/s, loss=14.6166, val_loss=14.3961]

Upper model:  35%|███▌      | 35/100 [00:04<00:04, 16.21epoch/s, loss=14.6166, val_loss=14.3961]

Upper model:  35%|███▌      | 35/100 [00:04<00:04, 16.21epoch/s, loss=14.2828, val_loss=14.0734]

Upper model:  36%|███▌      | 36/100 [00:04<00:03, 16.21epoch/s, loss=13.9835, val_loss=13.7385]

Upper model:  37%|███▋      | 37/100 [00:04<00:03, 15.90epoch/s, loss=13.9835, val_loss=13.7385]

Upper model:  37%|███▋      | 37/100 [00:04<00:03, 15.90epoch/s, loss=13.5818, val_loss=13.3968]

Upper model:  38%|███▊      | 38/100 [00:04<00:03, 15.90epoch/s, loss=13.2924, val_loss=13.0513]

Upper model:  39%|███▉      | 39/100 [00:04<00:03, 16.10epoch/s, loss=13.2924, val_loss=13.0513]

Upper model:  39%|███▉      | 39/100 [00:04<00:03, 16.10epoch/s, loss=12.8413, val_loss=12.7009]

Upper model:  40%|████      | 40/100 [00:04<00:03, 16.10epoch/s, loss=12.4976, val_loss=12.3408]

Upper model:  41%|████      | 41/100 [00:04<00:03, 16.28epoch/s, loss=12.4976, val_loss=12.3408]

Upper model:  41%|████      | 41/100 [00:04<00:03, 16.28epoch/s, loss=12.1045, val_loss=11.9744]

Upper model:  42%|████▏     | 42/100 [00:04<00:03, 16.28epoch/s, loss=11.7112, val_loss=11.5997]

Upper model:  43%|████▎     | 43/100 [00:04<00:03, 16.24epoch/s, loss=11.7112, val_loss=11.5997]

Upper model:  43%|████▎     | 43/100 [00:04<00:03, 16.24epoch/s, loss=11.4146, val_loss=11.2227]

Upper model:  44%|████▍     | 44/100 [00:04<00:03, 16.24epoch/s, loss=10.8589, val_loss=10.8389]

Upper model:  45%|████▌     | 45/100 [00:04<00:03, 15.93epoch/s, loss=10.8589, val_loss=10.8389]

Upper model:  45%|████▌     | 45/100 [00:04<00:03, 15.93epoch/s, loss=10.5061, val_loss=10.4476]

Upper model:  46%|████▌     | 46/100 [00:04<00:03, 15.93epoch/s, loss=10.0378, val_loss=10.0584]

Upper model:  47%|████▋     | 47/100 [00:04<00:03, 15.98epoch/s, loss=10.0378, val_loss=10.0584]

Upper model:  47%|████▋     | 47/100 [00:05<00:03, 15.98epoch/s, loss=9.7646, val_loss=9.6664]

Upper model:  48%|████▊     | 48/100 [00:05<00:03, 15.98epoch/s, loss=9.2550, val_loss=9.2705]

Upper model:  49%|████▉     | 49/100 [00:05<00:03, 16.07epoch/s, loss=9.2550, val_loss=9.2705]

Upper model:  49%|████▉     | 49/100 [00:05<00:03, 16.07epoch/s, loss=8.8093, val_loss=8.8743]

Upper model:  50%|█████     | 50/100 [00:05<00:03, 16.07epoch/s, loss=8.3887, val_loss=8.4810]

Upper model:  51%|█████     | 51/100 [00:05<00:02, 16.60epoch/s, loss=8.3887, val_loss=8.4810]

Upper model:  51%|█████     | 51/100 [00:05<00:02, 16.60epoch/s, loss=8.0138, val_loss=8.0846]

Upper model:  52%|█████▏    | 52/100 [00:05<00:02, 16.60epoch/s, loss=7.8220, val_loss=7.6909]

Upper model:  53%|█████▎    | 53/100 [00:05<00:02, 16.99epoch/s, loss=7.8220, val_loss=7.6909]

Upper model:  53%|█████▎    | 53/100 [00:05<00:02, 16.99epoch/s, loss=7.4047, val_loss=7.3069]

Upper model:  54%|█████▍    | 54/100 [00:05<00:02, 16.99epoch/s, loss=6.9984, val_loss=6.9302]

Upper model:  55%|█████▌    | 55/100 [00:05<00:02, 16.97epoch/s, loss=6.9984, val_loss=6.9302]

Upper model:  55%|█████▌    | 55/100 [00:05<00:02, 16.97epoch/s, loss=6.5376, val_loss=6.5643]

Upper model:  56%|█████▌    | 56/100 [00:05<00:02, 16.97epoch/s, loss=6.1790, val_loss=6.2021]

Upper model:  57%|█████▋    | 57/100 [00:05<00:02, 17.17epoch/s, loss=6.1790, val_loss=6.2021]

Upper model:  57%|█████▋    | 57/100 [00:05<00:02, 17.17epoch/s, loss=5.8493, val_loss=5.8506]

Upper model:  58%|█████▊    | 58/100 [00:05<00:02, 17.17epoch/s, loss=5.5197, val_loss=5.5076]

Upper model:  59%|█████▉    | 59/100 [00:05<00:02, 17.21epoch/s, loss=5.5197, val_loss=5.5076]

Upper model:  59%|█████▉    | 59/100 [00:05<00:02, 17.21epoch/s, loss=5.3715, val_loss=5.1896]

Upper model:  60%|██████    | 60/100 [00:05<00:02, 17.21epoch/s, loss=4.9411, val_loss=4.8770]

Upper model:  61%|██████    | 61/100 [00:05<00:02, 16.76epoch/s, loss=4.9411, val_loss=4.8770]

Upper model:  61%|██████    | 61/100 [00:05<00:02, 16.76epoch/s, loss=4.6483, val_loss=4.5796]

Upper model:  62%|██████▏   | 62/100 [00:05<00:02, 16.76epoch/s, loss=4.2518, val_loss=4.2911]

Upper model:  63%|██████▎   | 63/100 [00:05<00:02, 16.94epoch/s, loss=4.2518, val_loss=4.2911]

Upper model:  63%|██████▎   | 63/100 [00:05<00:02, 16.94epoch/s, loss=4.1112, val_loss=4.0153]

Upper model:  64%|██████▍   | 64/100 [00:06<00:02, 16.94epoch/s, loss=3.9251, val_loss=3.7646]

Upper model:  65%|██████▌   | 65/100 [00:06<00:02, 16.75epoch/s, loss=3.9251, val_loss=3.7646]

Upper model:  65%|██████▌   | 65/100 [00:06<00:02, 16.75epoch/s, loss=3.7452, val_loss=3.5259]

Upper model:  66%|██████▌   | 66/100 [00:06<00:02, 16.75epoch/s, loss=3.4613, val_loss=3.3057]

Upper model:  67%|██████▋   | 67/100 [00:06<00:01, 16.73epoch/s, loss=3.4613, val_loss=3.3057]

Upper model:  67%|██████▋   | 67/100 [00:06<00:01, 16.73epoch/s, loss=3.4293, val_loss=3.0989]

Upper model:  68%|██████▊   | 68/100 [00:06<00:01, 16.73epoch/s, loss=3.1908, val_loss=2.9197]

Upper model:  69%|██████▉   | 69/100 [00:06<00:01, 16.58epoch/s, loss=3.1908, val_loss=2.9197]

Upper model:  69%|██████▉   | 69/100 [00:06<00:01, 16.58epoch/s, loss=3.0187, val_loss=2.7644]

Upper model:  70%|███████   | 70/100 [00:06<00:01, 16.58epoch/s, loss=2.7593, val_loss=2.6161]

Upper model:  71%|███████   | 71/100 [00:06<00:01, 16.65epoch/s, loss=2.7593, val_loss=2.6161]

Upper model:  71%|███████   | 71/100 [00:06<00:01, 16.65epoch/s, loss=2.8435, val_loss=2.4788]

Upper model:  72%|███████▏  | 72/100 [00:06<00:01, 16.65epoch/s, loss=2.4960, val_loss=2.3502]

Upper model:  73%|███████▎  | 73/100 [00:06<00:01, 16.63epoch/s, loss=2.4960, val_loss=2.3502]

Upper model:  73%|███████▎  | 73/100 [00:06<00:01, 16.63epoch/s, loss=2.4427, val_loss=2.2205]

Upper model:  74%|███████▍  | 74/100 [00:06<00:01, 16.63epoch/s, loss=2.2762, val_loss=2.1031]

Upper model:  75%|███████▌  | 75/100 [00:06<00:01, 15.58epoch/s, loss=2.2762, val_loss=2.1031]

Upper model:  75%|███████▌  | 75/100 [00:06<00:01, 15.58epoch/s, loss=2.2856, val_loss=1.9954]

Upper model:  76%|███████▌  | 76/100 [00:06<00:01, 15.58epoch/s, loss=2.2013, val_loss=1.9032]

Upper model:  77%|███████▋  | 77/100 [00:06<00:01, 15.91epoch/s, loss=2.2013, val_loss=1.9032]

Upper model:  77%|███████▋  | 77/100 [00:06<00:01, 15.91epoch/s, loss=1.9665, val_loss=1.8201]

Upper model:  78%|███████▊  | 78/100 [00:06<00:01, 15.91epoch/s, loss=2.0788, val_loss=1.7446]

Upper model:  79%|███████▉  | 79/100 [00:06<00:01, 15.85epoch/s, loss=2.0788, val_loss=1.7446]

Upper model:  79%|███████▉  | 79/100 [00:06<00:01, 15.85epoch/s, loss=1.8820, val_loss=1.6696]

Upper model:  80%|████████  | 80/100 [00:07<00:01, 15.85epoch/s, loss=1.7339, val_loss=1.6055]

Upper model:  81%|████████  | 81/100 [00:07<00:01, 15.72epoch/s, loss=1.7339, val_loss=1.6055]

Upper model:  81%|████████  | 81/100 [00:07<00:01, 15.72epoch/s, loss=1.9562, val_loss=1.5471]

Upper model:  82%|████████▏ | 82/100 [00:07<00:01, 15.72epoch/s, loss=1.9006, val_loss=1.4911]

Upper model:  83%|████████▎ | 83/100 [00:07<00:01, 15.61epoch/s, loss=1.9006, val_loss=1.4911]

Upper model:  83%|████████▎ | 83/100 [00:07<00:01, 15.61epoch/s, loss=1.6483, val_loss=1.4409]

Upper model:  84%|████████▍ | 84/100 [00:07<00:01, 15.61epoch/s, loss=1.6221, val_loss=1.3923]

Upper model:  85%|████████▌ | 85/100 [00:07<00:00, 15.71epoch/s, loss=1.6221, val_loss=1.3923]

Upper model:  85%|████████▌ | 85/100 [00:07<00:00, 15.71epoch/s, loss=1.4683, val_loss=1.3481]

Upper model:  86%|████████▌ | 86/100 [00:07<00:00, 15.71epoch/s, loss=1.6169, val_loss=1.3107]

Upper model:  87%|████████▋ | 87/100 [00:07<00:00, 15.55epoch/s, loss=1.6169, val_loss=1.3107]

Upper model:  87%|████████▋ | 87/100 [00:07<00:00, 15.55epoch/s, loss=1.5249, val_loss=1.2765]

Upper model:  88%|████████▊ | 88/100 [00:07<00:00, 15.55epoch/s, loss=1.5049, val_loss=1.2461]

Upper model:  89%|████████▉ | 89/100 [00:07<00:00, 14.62epoch/s, loss=1.5049, val_loss=1.2461]

Upper model:  89%|████████▉ | 89/100 [00:07<00:00, 14.62epoch/s, loss=1.5005, val_loss=1.2168]

Upper model:  90%|█████████ | 90/100 [00:07<00:00, 14.62epoch/s, loss=1.4144, val_loss=1.1889]

Upper model:  91%|█████████ | 91/100 [00:07<00:00, 15.37epoch/s, loss=1.4144, val_loss=1.1889]

Upper model:  91%|█████████ | 91/100 [00:07<00:00, 15.37epoch/s, loss=1.4627, val_loss=1.1623]

Upper model:  92%|█████████▏| 92/100 [00:07<00:00, 15.37epoch/s, loss=1.3348, val_loss=1.1361]

Upper model:  93%|█████████▎| 93/100 [00:07<00:00, 15.61epoch/s, loss=1.3348, val_loss=1.1361]

Upper model:  93%|█████████▎| 93/100 [00:07<00:00, 15.61epoch/s, loss=1.3840, val_loss=1.1119]

Upper model:  94%|█████████▍| 94/100 [00:07<00:00, 15.61epoch/s, loss=1.1868, val_loss=1.0913]

Upper model:  95%|█████████▌| 95/100 [00:07<00:00, 15.77epoch/s, loss=1.1868, val_loss=1.0913]

Upper model:  95%|█████████▌| 95/100 [00:08<00:00, 15.77epoch/s, loss=1.2542, val_loss=1.0719]

Upper model:  96%|█████████▌| 96/100 [00:08<00:00, 15.77epoch/s, loss=1.3192, val_loss=1.0536]

Upper model:  97%|█████████▋| 97/100 [00:08<00:00, 15.56epoch/s, loss=1.3192, val_loss=1.0536]

Upper model:  97%|█████████▋| 97/100 [00:08<00:00, 15.56epoch/s, loss=1.2519, val_loss=1.0346]

Upper model:  98%|█████████▊| 98/100 [00:08<00:00, 15.56epoch/s, loss=1.2748, val_loss=1.0168]

Upper model:  99%|█████████▉| 99/100 [00:08<00:00, 15.64epoch/s, loss=1.2748, val_loss=1.0168]

Upper model:  99%|█████████▉| 99/100 [00:08<00:00, 15.64epoch/s, loss=1.2213, val_loss=0.9994]

Upper model: 100%|██████████| 100/100 [00:08<00:00, 12.08epoch/s, loss=1.2213, val_loss=0.9994]

Lower model:   0%|          | 0/100 [00:00<?, ?epoch/s]

I0000 00:00:1778435195.276741 2605127 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_119226__.19

I0000 00:00:1778435196.036131 2605134 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_119226__.19

Lower model:   0%|          | 0/100 [00:02<?, ?epoch/s, loss=0.5034, val_loss=0.4967]

Lower model:   1%|          | 1/100 [00:02<03:28,  2.10s/epoch, loss=0.5034, val_loss=0.4967]

Lower model:   1%|          | 1/100 [00:02<03:28,  2.10s/epoch, loss=0.5024, val_loss=0.4959]

Lower model:   2%|▏         | 2/100 [00:02<03:25,  2.10s/epoch, loss=0.5016, val_loss=0.4950]

Lower model:   3%|▎         | 3/100 [00:02<00:57,  1.69epoch/s, loss=0.5016, val_loss=0.4950]

Lower model:   3%|▎         | 3/100 [00:02<00:57,  1.69epoch/s, loss=0.5006, val_loss=0.4940]

Lower model:   4%|▍         | 4/100 [00:02<00:56,  1.69epoch/s, loss=0.4996, val_loss=0.4929]

Lower model:   5%|▌         | 5/100 [00:02<00:30,  3.16epoch/s, loss=0.4996, val_loss=0.4929]

Lower model:   5%|▌         | 5/100 [00:02<00:30,  3.16epoch/s, loss=0.4983, val_loss=0.4917]

Lower model:   6%|▌         | 6/100 [00:02<00:29,  3.16epoch/s, loss=0.4967, val_loss=0.4901]

Lower model:   7%|▋         | 7/100 [00:02<00:19,  4.85epoch/s, loss=0.4967, val_loss=0.4901]

Lower model:   7%|▋         | 7/100 [00:02<00:19,  4.85epoch/s, loss=0.4952, val_loss=0.4881]

Lower model:   8%|▊         | 8/100 [00:02<00:18,  4.85epoch/s, loss=0.4930, val_loss=0.4860]

Lower model:   9%|▉         | 9/100 [00:02<00:13,  6.69epoch/s, loss=0.4930, val_loss=0.4860]

Lower model:   9%|▉         | 9/100 [00:02<00:13,  6.69epoch/s, loss=0.4911, val_loss=0.4837]

Lower model:  10%|█         | 10/100 [00:02<00:13,  6.69epoch/s, loss=0.4885, val_loss=0.4814]

Lower model:  11%|█         | 11/100 [00:02<00:10,  8.51epoch/s, loss=0.4885, val_loss=0.4814]

Lower model:  11%|█         | 11/100 [00:02<00:10,  8.51epoch/s, loss=0.4862, val_loss=0.4789]

Lower model:  12%|█▏        | 12/100 [00:02<00:10,  8.51epoch/s, loss=0.4839, val_loss=0.4763]

Lower model:  13%|█▎        | 13/100 [00:02<00:08, 10.19epoch/s, loss=0.4839, val_loss=0.4763]

Lower model:  13%|█▎        | 13/100 [00:02<00:08, 10.19epoch/s, loss=0.4812, val_loss=0.4737]

Lower model:  14%|█▍        | 14/100 [00:02<00:08, 10.19epoch/s, loss=0.4782, val_loss=0.4712]

Lower model:  15%|█▌        | 15/100 [00:02<00:07, 11.59epoch/s, loss=0.4782, val_loss=0.4712]

Lower model:  15%|█▌        | 15/100 [00:02<00:07, 11.59epoch/s, loss=0.4755, val_loss=0.4692]

Lower model:  16%|█▌        | 16/100 [00:03<00:07, 11.59epoch/s, loss=0.4729, val_loss=0.4672]

Lower model:  17%|█▋        | 17/100 [00:03<00:06, 12.53epoch/s, loss=0.4729, val_loss=0.4672]

Lower model:  17%|█▋        | 17/100 [00:03<00:06, 12.53epoch/s, loss=0.4698, val_loss=0.4650]

Lower model:  18%|█▊        | 18/100 [00:03<00:06, 12.53epoch/s, loss=0.4674, val_loss=0.4628]

Lower model:  19%|█▉        | 19/100 [00:03<00:06, 13.36epoch/s, loss=0.4674, val_loss=0.4628]

Lower model:  19%|█▉        | 19/100 [00:03<00:06, 13.36epoch/s, loss=0.4636, val_loss=0.4605]

Lower model:  20%|██        | 20/100 [00:03<00:05, 13.36epoch/s, loss=0.4611, val_loss=0.4582]

Lower model:  21%|██        | 21/100 [00:03<00:05, 14.15epoch/s, loss=0.4611, val_loss=0.4582]

Lower model:  21%|██        | 21/100 [00:03<00:05, 14.15epoch/s, loss=0.4585, val_loss=0.4558]

Lower model:  22%|██▏       | 22/100 [00:03<00:05, 14.15epoch/s, loss=0.4563, val_loss=0.4534]

Lower model:  23%|██▎       | 23/100 [00:03<00:05, 14.59epoch/s, loss=0.4563, val_loss=0.4534]

Lower model:  23%|██▎       | 23/100 [00:03<00:05, 14.59epoch/s, loss=0.4533, val_loss=0.4519]

Lower model:  24%|██▍       | 24/100 [00:03<00:05, 14.59epoch/s, loss=0.4497, val_loss=0.4514]

Lower model:  25%|██▌       | 25/100 [00:03<00:05, 14.90epoch/s, loss=0.4497, val_loss=0.4514]

Lower model:  25%|██▌       | 25/100 [00:03<00:05, 14.90epoch/s, loss=0.4489, val_loss=0.4513]

Lower model:  26%|██▌       | 26/100 [00:03<00:04, 14.90epoch/s, loss=0.4460, val_loss=0.4518]

Lower model:  27%|██▋       | 27/100 [00:03<00:04, 15.17epoch/s, loss=0.4460, val_loss=0.4518]

Lower model:  27%|██▋       | 27/100 [00:03<00:04, 15.17epoch/s, loss=0.4438, val_loss=0.4536]

Lower model:  28%|██▊       | 28/100 [00:03<00:04, 15.17epoch/s, loss=0.4395, val_loss=0.4556]

Lower model:  29%|██▉       | 29/100 [00:03<00:04, 15.40epoch/s, loss=0.4395, val_loss=0.4556]

Lower model:  29%|██▉       | 29/100 [00:03<00:04, 15.40epoch/s, loss=0.4362, val_loss=0.4580]

Lower model:  30%|███       | 30/100 [00:03<00:04, 15.40epoch/s, loss=0.4370, val_loss=0.4604]

Lower model:  31%|███       | 31/100 [00:03<00:04, 15.62epoch/s, loss=0.4370, val_loss=0.4604]

Lower model:  31%|███       | 31/100 [00:03<00:04, 15.62epoch/s, loss=0.4353, val_loss=0.4619]

Lower model:  32%|███▏      | 32/100 [00:04<00:04, 15.62epoch/s, loss=0.4343, val_loss=0.4631]

Lower model:  33%|███▎      | 33/100 [00:04<00:04, 15.99epoch/s, loss=0.4343, val_loss=0.4631]

Lower model:  33%|███▎      | 33/100 [00:04<00:04, 15.99epoch/s, loss=0.4282, val_loss=0.4644]

Lower model:  34%|███▍      | 34/100 [00:04<00:04, 15.99epoch/s, loss=0.4281, val_loss=0.4657]

Lower model:  35%|███▌      | 35/100 [00:04<00:03, 16.29epoch/s, loss=0.4281, val_loss=0.4657]

Lower model:  35%|███▌      | 35/100 [00:04<00:03, 16.29epoch/s, loss=0.4295, val_loss=0.4668]

Lower model:  36%|███▌      | 36/100 [00:04<00:07,  8.52epoch/s, loss=0.4295, val_loss=0.4668]

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

  > CQR Calibration constant (Q): 6.3445

Running configuration: Low:0.03 - High:0.98

Upper model:   0%|          | 0/100 [00:00<?, ?epoch/s]

I0000 00:00:1778435200.173030 2605133 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_123455__.19

I0000 00:00:1778435200.983402 2605131 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_123455__.19

Upper model:   0%|          | 0/100 [00:02<?, ?epoch/s, loss=19.3955, val_loss=19.1479]

Upper model:   1%|          | 1/100 [00:02<03:41,  2.24s/epoch, loss=19.3955, val_loss=19.1479]

Upper model:   1%|          | 1/100 [00:02<03:41,  2.24s/epoch, loss=19.3152, val_loss=19.0689]

Upper model:   2%|▏         | 2/100 [00:02<03:39,  2.24s/epoch, loss=19.2318, val_loss=18.9816]

Upper model:   3%|▎         | 3/100 [00:02<01:00,  1.60epoch/s, loss=19.2318, val_loss=18.9816]

Upper model:   3%|▎         | 3/100 [00:02<01:00,  1.60epoch/s, loss=19.1503, val_loss=18.8856]

Upper model:   4%|▍         | 4/100 [00:02<00:59,  1.60epoch/s, loss=19.0533, val_loss=18.7788]

Upper model:   5%|▌         | 5/100 [00:02<00:31,  2.98epoch/s, loss=19.0533, val_loss=18.7788]

Upper model:   5%|▌         | 5/100 [00:02<00:31,  2.98epoch/s, loss=18.9336, val_loss=18.6588]

Upper model:   6%|▌         | 6/100 [00:02<00:31,  2.98epoch/s, loss=18.8137, val_loss=18.5246]

Upper model:   7%|▋         | 7/100 [00:02<00:20,  4.56epoch/s, loss=18.8137, val_loss=18.5246]

Upper model:   7%|▋         | 7/100 [00:02<00:20,  4.56epoch/s, loss=18.6693, val_loss=18.3749]

Upper model:   8%|▊         | 8/100 [00:02<00:20,  4.56epoch/s, loss=18.5227, val_loss=18.2085]

Upper model:   9%|▉         | 9/100 [00:02<00:14,  6.19epoch/s, loss=18.5227, val_loss=18.2085]

Upper model:   9%|▉         | 9/100 [00:02<00:14,  6.19epoch/s, loss=18.3450, val_loss=18.0250]

Upper model:  10%|█         | 10/100 [00:02<00:14,  6.19epoch/s, loss=18.1717, val_loss=17.8196]

Upper model:  11%|█         | 11/100 [00:02<00:11,  7.75epoch/s, loss=18.1717, val_loss=17.8196]

Upper model:  11%|█         | 11/100 [00:02<00:11,  7.75epoch/s, loss=17.9777, val_loss=17.5927]

Upper model:  12%|█▏        | 12/100 [00:02<00:11,  7.75epoch/s, loss=17.7002, val_loss=17.3440]

Upper model:  13%|█▎        | 13/100 [00:02<00:09,  9.46epoch/s, loss=17.7002, val_loss=17.3440]

Upper model:  13%|█▎        | 13/100 [00:03<00:09,  9.46epoch/s, loss=17.4362, val_loss=17.0758]

Upper model:  14%|█▍        | 14/100 [00:03<00:09,  9.46epoch/s, loss=17.1348, val_loss=16.7840]

Upper model:  15%|█▌        | 15/100 [00:03<00:07, 11.03epoch/s, loss=17.1348, val_loss=16.7840]

Upper model:  15%|█▌        | 15/100 [00:03<00:07, 11.03epoch/s, loss=16.8309, val_loss=16.4704]

Upper model:  16%|█▌        | 16/100 [00:03<00:07, 11.03epoch/s, loss=16.5147, val_loss=16.1323]

Upper model:  17%|█▋        | 17/100 [00:03<00:06, 12.21epoch/s, loss=16.5147, val_loss=16.1323]

Upper model:  17%|█▋        | 17/100 [00:03<00:06, 12.21epoch/s, loss=16.1186, val_loss=15.7744]

Upper model:  18%|█▊        | 18/100 [00:03<00:06, 12.21epoch/s, loss=15.7277, val_loss=15.3928]

Upper model:  19%|█▉        | 19/100 [00:03<00:05, 13.52epoch/s, loss=15.7277, val_loss=15.3928]

Upper model:  19%|█▉        | 19/100 [00:03<00:05, 13.52epoch/s, loss=15.3190, val_loss=14.9851]

Upper model:  20%|██        | 20/100 [00:03<00:05, 13.52epoch/s, loss=14.8506, val_loss=14.5533]

Upper model:  21%|██        | 21/100 [00:03<00:05, 14.49epoch/s, loss=14.8506, val_loss=14.5533]

Upper model:  21%|██        | 21/100 [00:03<00:05, 14.49epoch/s, loss=14.4835, val_loss=14.0996]

Upper model:  22%|██▏       | 22/100 [00:03<00:05, 14.49epoch/s, loss=13.9771, val_loss=13.6311]

Upper model:  23%|██▎       | 23/100 [00:03<00:05, 14.98epoch/s, loss=13.9771, val_loss=13.6311]

Upper model:  23%|██▎       | 23/100 [00:03<00:05, 14.98epoch/s, loss=13.4913, val_loss=13.1433]

Upper model:  24%|██▍       | 24/100 [00:03<00:05, 14.98epoch/s, loss=12.9520, val_loss=12.6470]

Upper model:  25%|██▌       | 25/100 [00:03<00:04, 15.15epoch/s, loss=12.9520, val_loss=12.6470]

Upper model:  25%|██▌       | 25/100 [00:03<00:04, 15.15epoch/s, loss=12.3776, val_loss=12.1392]

Upper model:  26%|██▌       | 26/100 [00:03<00:04, 15.15epoch/s, loss=11.8346, val_loss=11.6142]

Upper model:  27%|██▋       | 27/100 [00:03<00:04, 15.39epoch/s, loss=11.8346, val_loss=11.6142]

Upper model:  27%|██▋       | 27/100 [00:03<00:04, 15.39epoch/s, loss=11.2762, val_loss=11.0852]

Upper model:  28%|██▊       | 28/100 [00:03<00:04, 15.39epoch/s, loss=10.6882, val_loss=10.5448]

Upper model:  29%|██▉       | 29/100 [00:03<00:04, 15.77epoch/s, loss=10.6882, val_loss=10.5448]

Upper model:  29%|██▉       | 29/100 [00:04<00:04, 15.77epoch/s, loss=10.1237, val_loss=9.9991]

Upper model:  30%|███       | 30/100 [00:04<00:04, 15.77epoch/s, loss=9.5562, val_loss=9.4520]

Upper model:  31%|███       | 31/100 [00:04<00:04, 15.26epoch/s, loss=9.5562, val_loss=9.4520]

Upper model:  31%|███       | 31/100 [00:04<00:04, 15.26epoch/s, loss=8.9840, val_loss=8.9025]

Upper model:  32%|███▏      | 32/100 [00:04<00:04, 15.26epoch/s, loss=8.4733, val_loss=8.3490]

Upper model:  33%|███▎      | 33/100 [00:04<00:04, 15.23epoch/s, loss=8.4733, val_loss=8.3490]

Upper model:  33%|███▎      | 33/100 [00:04<00:04, 15.23epoch/s, loss=7.8568, val_loss=7.8033]

Upper model:  34%|███▍      | 34/100 [00:04<00:04, 15.23epoch/s, loss=7.3338, val_loss=7.2708]

Upper model:  35%|███▌      | 35/100 [00:04<00:04, 15.54epoch/s, loss=7.3338, val_loss=7.2708]

Upper model:  35%|███▌      | 35/100 [00:04<00:04, 15.54epoch/s, loss=6.8166, val_loss=6.7551]

Upper model:  36%|███▌      | 36/100 [00:04<00:04, 15.54epoch/s, loss=6.2479, val_loss=6.2508]

Upper model:  37%|███▋      | 37/100 [00:04<00:04, 15.46epoch/s, loss=6.2479, val_loss=6.2508]

Upper model:  37%|███▋      | 37/100 [00:04<00:04, 15.46epoch/s, loss=5.8892, val_loss=5.7566]

Upper model:  38%|███▊      | 38/100 [00:04<00:04, 15.46epoch/s, loss=5.2766, val_loss=5.2909]

Upper model:  39%|███▉      | 39/100 [00:04<00:03, 15.72epoch/s, loss=5.2766, val_loss=5.2909]

Upper model:  39%|███▉      | 39/100 [00:04<00:03, 15.72epoch/s, loss=4.8896, val_loss=4.8576]

Upper model:  40%|████      | 40/100 [00:04<00:03, 15.72epoch/s, loss=4.5240, val_loss=4.4465]

Upper model:  41%|████      | 41/100 [00:04<00:03, 15.58epoch/s, loss=4.5240, val_loss=4.4465]

Upper model:  41%|████      | 41/100 [00:04<00:03, 15.58epoch/s, loss=4.1311, val_loss=4.0565]

Upper model:  42%|████▏     | 42/100 [00:04<00:03, 15.58epoch/s, loss=3.7951, val_loss=3.6920]

Upper model:  43%|████▎     | 43/100 [00:04<00:03, 15.89epoch/s, loss=3.7951, val_loss=3.6920]

Upper model:  43%|████▎     | 43/100 [00:04<00:03, 15.89epoch/s, loss=3.5061, val_loss=3.3458]

Upper model:  44%|████▍     | 44/100 [00:04<00:03, 15.89epoch/s, loss=3.2025, val_loss=3.0706]

Upper model:  45%|████▌     | 45/100 [00:04<00:03, 15.82epoch/s, loss=3.2025, val_loss=3.0706]

Upper model:  45%|████▌     | 45/100 [00:05<00:03, 15.82epoch/s, loss=2.9226, val_loss=2.8265]

Upper model:  46%|████▌     | 46/100 [00:05<00:03, 15.82epoch/s, loss=2.6451, val_loss=2.6014]

Upper model:  47%|████▋     | 47/100 [00:05<00:03, 16.02epoch/s, loss=2.6451, val_loss=2.6014]

Upper model:  47%|████▋     | 47/100 [00:05<00:03, 16.02epoch/s, loss=2.5442, val_loss=2.3873]

Upper model:  48%|████▊     | 48/100 [00:05<00:03, 16.02epoch/s, loss=2.3144, val_loss=2.1799]

Upper model:  49%|████▉     | 49/100 [00:05<00:03, 16.11epoch/s, loss=2.3144, val_loss=2.1799]

Upper model:  49%|████▉     | 49/100 [00:05<00:03, 16.11epoch/s, loss=2.1828, val_loss=1.9939]

Upper model:  50%|█████     | 50/100 [00:05<00:03, 16.11epoch/s, loss=1.9072, val_loss=1.8347]

Upper model:  51%|█████     | 51/100 [00:05<00:03, 16.02epoch/s, loss=1.9072, val_loss=1.8347]

Upper model:  51%|█████     | 51/100 [00:05<00:03, 16.02epoch/s, loss=1.8571, val_loss=1.7036]

Upper model:  52%|█████▏    | 52/100 [00:05<00:02, 16.02epoch/s, loss=1.6417, val_loss=1.5913]

Upper model:  53%|█████▎    | 53/100 [00:05<00:02, 15.81epoch/s, loss=1.6417, val_loss=1.5913]

Upper model:  53%|█████▎    | 53/100 [00:05<00:02, 15.81epoch/s, loss=1.6074, val_loss=1.4932]

Upper model:  54%|█████▍    | 54/100 [00:05<00:02, 15.81epoch/s, loss=1.4328, val_loss=1.4119]

Upper model:  55%|█████▌    | 55/100 [00:05<00:02, 16.00epoch/s, loss=1.4328, val_loss=1.4119]

Upper model:  55%|█████▌    | 55/100 [00:05<00:02, 16.00epoch/s, loss=1.3723, val_loss=1.3355]

Upper model:  56%|█████▌    | 56/100 [00:05<00:02, 16.00epoch/s, loss=1.3808, val_loss=1.2700]

Upper model:  57%|█████▋    | 57/100 [00:05<00:02, 16.16epoch/s, loss=1.3808, val_loss=1.2700]

Upper model:  57%|█████▋    | 57/100 [00:05<00:02, 16.16epoch/s, loss=1.1728, val_loss=1.2128]

Upper model:  58%|█████▊    | 58/100 [00:05<00:02, 16.16epoch/s, loss=1.2515, val_loss=1.1622]

Upper model:  59%|█████▉    | 59/100 [00:05<00:02, 16.36epoch/s, loss=1.2515, val_loss=1.1622]

Upper model:  59%|█████▉    | 59/100 [00:05<00:02, 16.36epoch/s, loss=1.1165, val_loss=1.1151]

Upper model:  60%|██████    | 60/100 [00:05<00:02, 16.36epoch/s, loss=0.9809, val_loss=1.0732]

Upper model:  61%|██████    | 61/100 [00:05<00:02, 16.43epoch/s, loss=0.9809, val_loss=1.0732]

Upper model:  61%|██████    | 61/100 [00:06<00:02, 16.43epoch/s, loss=1.0976, val_loss=1.0384]

Upper model:  62%|██████▏   | 62/100 [00:06<00:02, 16.43epoch/s, loss=1.0151, val_loss=1.0069]

Upper model:  63%|██████▎   | 63/100 [00:06<00:02, 16.52epoch/s, loss=1.0151, val_loss=1.0069]

Upper model:  63%|██████▎   | 63/100 [00:06<00:02, 16.52epoch/s, loss=1.0024, val_loss=0.9755]

Upper model:  64%|██████▍   | 64/100 [00:06<00:02, 16.52epoch/s, loss=0.9801, val_loss=0.9446]

Upper model:  65%|██████▌   | 65/100 [00:06<00:02, 16.26epoch/s, loss=0.9801, val_loss=0.9446]

Upper model:  65%|██████▌   | 65/100 [00:06<00:02, 16.26epoch/s, loss=0.8569, val_loss=0.9151]

Upper model:  66%|██████▌   | 66/100 [00:06<00:02, 16.26epoch/s, loss=0.8865, val_loss=0.8907]

Upper model:  67%|██████▋   | 67/100 [00:06<00:02, 15.77epoch/s, loss=0.8865, val_loss=0.8907]

Upper model:  67%|██████▋   | 67/100 [00:06<00:02, 15.77epoch/s, loss=0.9341, val_loss=0.8690]

Upper model:  68%|██████▊   | 68/100 [00:06<00:02, 15.77epoch/s, loss=0.8656, val_loss=0.8495]

Upper model:  69%|██████▉   | 69/100 [00:06<00:01, 15.93epoch/s, loss=0.8656, val_loss=0.8495]

Upper model:  69%|██████▉   | 69/100 [00:06<00:01, 15.93epoch/s, loss=0.7858, val_loss=0.8318]

Upper model:  70%|███████   | 70/100 [00:06<00:01, 15.93epoch/s, loss=0.7543, val_loss=0.8169]

Upper model:  71%|███████   | 71/100 [00:06<00:01, 15.96epoch/s, loss=0.7543, val_loss=0.8169]

Upper model:  71%|███████   | 71/100 [00:06<00:01, 15.96epoch/s, loss=0.8245, val_loss=0.8019]

Upper model:  72%|███████▏  | 72/100 [00:06<00:01, 15.96epoch/s, loss=0.8491, val_loss=0.7877]

Upper model:  73%|███████▎  | 73/100 [00:06<00:01, 16.38epoch/s, loss=0.8491, val_loss=0.7877]

Upper model:  73%|███████▎  | 73/100 [00:06<00:01, 16.38epoch/s, loss=0.8651, val_loss=0.7740]

Upper model:  74%|███████▍  | 74/100 [00:06<00:01, 16.38epoch/s, loss=0.7328, val_loss=0.7608]

Upper model:  75%|███████▌  | 75/100 [00:06<00:01, 16.76epoch/s, loss=0.7328, val_loss=0.7608]

Upper model:  75%|███████▌  | 75/100 [00:06<00:01, 16.76epoch/s, loss=0.7518, val_loss=0.7486]

Upper model:  76%|███████▌  | 76/100 [00:06<00:01, 16.76epoch/s, loss=0.7826, val_loss=0.7369]

Upper model:  77%|███████▋  | 77/100 [00:06<00:01, 16.61epoch/s, loss=0.7826, val_loss=0.7369]

Upper model:  77%|███████▋  | 77/100 [00:07<00:01, 16.61epoch/s, loss=0.8031, val_loss=0.7274]

Upper model:  78%|███████▊  | 78/100 [00:07<00:01, 16.61epoch/s, loss=0.8117, val_loss=0.7185]

Upper model:  79%|███████▉  | 79/100 [00:07<00:01, 16.99epoch/s, loss=0.8117, val_loss=0.7185]

Upper model:  79%|███████▉  | 79/100 [00:07<00:01, 16.99epoch/s, loss=0.8165, val_loss=0.7097]

Upper model:  80%|████████  | 80/100 [00:07<00:01, 16.99epoch/s, loss=0.7152, val_loss=0.7026]

Upper model:  81%|████████  | 81/100 [00:07<00:01, 16.96epoch/s, loss=0.7152, val_loss=0.7026]

Upper model:  81%|████████  | 81/100 [00:07<00:01, 16.96epoch/s, loss=0.7610, val_loss=0.6967]

Upper model:  82%|████████▏ | 82/100 [00:07<00:01, 16.96epoch/s, loss=0.7559, val_loss=0.6922]

Upper model:  83%|████████▎ | 83/100 [00:07<00:01, 16.91epoch/s, loss=0.7559, val_loss=0.6922]

Upper model:  83%|████████▎ | 83/100 [00:07<00:01, 16.91epoch/s, loss=0.6976, val_loss=0.6876]

Upper model:  84%|████████▍ | 84/100 [00:07<00:00, 16.91epoch/s, loss=0.7469, val_loss=0.6843]

Upper model:  85%|████████▌ | 85/100 [00:07<00:00, 17.16epoch/s, loss=0.7469, val_loss=0.6843]

Upper model:  85%|████████▌ | 85/100 [00:07<00:00, 17.16epoch/s, loss=0.7599, val_loss=0.6822]

Upper model:  86%|████████▌ | 86/100 [00:07<00:00, 17.16epoch/s, loss=0.7507, val_loss=0.6803]

Upper model:  87%|████████▋ | 87/100 [00:07<00:00, 17.41epoch/s, loss=0.7507, val_loss=0.6803]

Upper model:  87%|████████▋ | 87/100 [00:07<00:00, 17.41epoch/s, loss=0.6889, val_loss=0.6787]

Upper model:  88%|████████▊ | 88/100 [00:07<00:00, 17.41epoch/s, loss=0.7570, val_loss=0.6771]

Upper model:  89%|████████▉ | 89/100 [00:07<00:00, 17.17epoch/s, loss=0.7570, val_loss=0.6771]

Upper model:  89%|████████▉ | 89/100 [00:07<00:00, 17.17epoch/s, loss=0.7140, val_loss=0.6757]

Upper model:  90%|█████████ | 90/100 [00:07<00:00, 17.17epoch/s, loss=0.6921, val_loss=0.6744]

Upper model:  91%|█████████ | 91/100 [00:07<00:00, 16.50epoch/s, loss=0.6921, val_loss=0.6744]

Upper model:  91%|█████████ | 91/100 [00:07<00:00, 16.50epoch/s, loss=0.6984, val_loss=0.6731]

Upper model:  92%|█████████▏| 92/100 [00:07<00:00, 16.50epoch/s, loss=0.6951, val_loss=0.6721]

Upper model:  93%|█████████▎| 93/100 [00:07<00:00, 15.99epoch/s, loss=0.6951, val_loss=0.6721]

Upper model:  93%|█████████▎| 93/100 [00:07<00:00, 15.99epoch/s, loss=0.6997, val_loss=0.6711]

Upper model:  94%|█████████▍| 94/100 [00:08<00:00, 15.99epoch/s, loss=0.7438, val_loss=0.6699]

Upper model:  95%|█████████▌| 95/100 [00:08<00:00, 16.48epoch/s, loss=0.7438, val_loss=0.6699]

Upper model:  95%|█████████▌| 95/100 [00:08<00:00, 16.48epoch/s, loss=0.7559, val_loss=0.6686]

Upper model:  96%|█████████▌| 96/100 [00:08<00:00, 16.48epoch/s, loss=0.7390, val_loss=0.6673]

Upper model:  97%|█████████▋| 97/100 [00:08<00:00, 16.90epoch/s, loss=0.7390, val_loss=0.6673]

Upper model:  97%|█████████▋| 97/100 [00:08<00:00, 16.90epoch/s, loss=0.7744, val_loss=0.6660]

Upper model:  98%|█████████▊| 98/100 [00:08<00:00, 16.90epoch/s, loss=0.7347, val_loss=0.6644]

Upper model:  99%|█████████▉| 99/100 [00:08<00:00, 17.12epoch/s, loss=0.7347, val_loss=0.6644]

Upper model:  99%|█████████▉| 99/100 [00:08<00:00, 17.12epoch/s, loss=0.6622, val_loss=0.6630]

Upper model: 100%|██████████| 100/100 [00:08<00:00, 12.02epoch/s, loss=0.6622, val_loss=0.6630]

Lower model:   0%|          | 0/100 [00:00<?, ?epoch/s]

I0000 00:00:1778435208.680350 2605133 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_130374__.19

I0000 00:00:1778435209.437716 2605133 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_130374__.19

Lower model:   0%|          | 0/100 [00:02<?, ?epoch/s, loss=0.5954, val_loss=0.5876]

Lower model:   1%|          | 1/100 [00:02<03:54,  2.37s/epoch, loss=0.5954, val_loss=0.5876]

Lower model:   1%|          | 1/100 [00:02<03:54,  2.37s/epoch, loss=0.5934, val_loss=0.5855]

Lower model:   2%|▏         | 2/100 [00:02<03:52,  2.37s/epoch, loss=0.5911, val_loss=0.5832]

Lower model:   3%|▎         | 3/100 [00:02<01:04,  1.51epoch/s, loss=0.5911, val_loss=0.5832]

Lower model:   3%|▎         | 3/100 [00:02<01:04,  1.51epoch/s, loss=0.5886, val_loss=0.5808]

Lower model:   4%|▍         | 4/100 [00:02<01:03,  1.51epoch/s, loss=0.5863, val_loss=0.5782]

Lower model:   5%|▌         | 5/100 [00:02<00:33,  2.82epoch/s, loss=0.5863, val_loss=0.5782]

Lower model:   5%|▌         | 5/100 [00:02<00:33,  2.82epoch/s, loss=0.5835, val_loss=0.5753]

Lower model:   6%|▌         | 6/100 [00:02<00:33,  2.82epoch/s, loss=0.5800, val_loss=0.5719]

Lower model:   7%|▋         | 7/100 [00:02<00:21,  4.37epoch/s, loss=0.5800, val_loss=0.5719]

Lower model:   7%|▋         | 7/100 [00:02<00:21,  4.37epoch/s, loss=0.5765, val_loss=0.5682]

Lower model:   8%|▊         | 8/100 [00:02<00:21,  4.37epoch/s, loss=0.5729, val_loss=0.5640]

Lower model:   9%|▉         | 9/100 [00:02<00:14,  6.10epoch/s, loss=0.5729, val_loss=0.5640]

Lower model:   9%|▉         | 9/100 [00:02<00:14,  6.10epoch/s, loss=0.5686, val_loss=0.5603]

Lower model:  10%|█         | 10/100 [00:02<00:14,  6.10epoch/s, loss=0.5636, val_loss=0.5564]

Lower model:  11%|█         | 11/100 [00:02<00:11,  7.86epoch/s, loss=0.5636, val_loss=0.5564]

Lower model:  11%|█         | 11/100 [00:03<00:11,  7.86epoch/s, loss=0.5583, val_loss=0.5520]

Lower model:  12%|█▏        | 12/100 [00:03<00:11,  7.86epoch/s, loss=0.5528, val_loss=0.5475]

Lower model:  13%|█▎        | 13/100 [00:03<00:09,  9.64epoch/s, loss=0.5528, val_loss=0.5475]

Lower model:  13%|█▎        | 13/100 [00:03<00:09,  9.64epoch/s, loss=0.5468, val_loss=0.5426]

Lower model:  14%|█▍        | 14/100 [00:03<00:08,  9.64epoch/s, loss=0.5422, val_loss=0.5381]

Lower model:  15%|█▌        | 15/100 [00:03<00:07, 11.17epoch/s, loss=0.5422, val_loss=0.5381]

Lower model:  15%|█▌        | 15/100 [00:03<00:07, 11.17epoch/s, loss=0.5349, val_loss=0.5375]

Lower model:  16%|█▌        | 16/100 [00:03<00:07, 11.17epoch/s, loss=0.5304, val_loss=0.5383]

Lower model:  17%|█▋        | 17/100 [00:03<00:06, 12.62epoch/s, loss=0.5304, val_loss=0.5383]

Lower model:  17%|█▋        | 17/100 [00:03<00:06, 12.62epoch/s, loss=0.5268, val_loss=0.5416]

Lower model:  18%|█▊        | 18/100 [00:03<00:06, 12.62epoch/s, loss=0.5167, val_loss=0.5453]

Lower model:  19%|█▉        | 19/100 [00:03<00:05, 13.61epoch/s, loss=0.5167, val_loss=0.5453]

Lower model:  19%|█▉        | 19/100 [00:03<00:05, 13.61epoch/s, loss=0.5131, val_loss=0.5490]

Lower model:  20%|██        | 20/100 [00:03<00:05, 13.61epoch/s, loss=0.5058, val_loss=0.5529]

Lower model:  21%|██        | 21/100 [00:03<00:05, 14.38epoch/s, loss=0.5058, val_loss=0.5529]

Lower model:  21%|██        | 21/100 [00:03<00:05, 14.38epoch/s, loss=0.5057, val_loss=0.5554]

Lower model:  22%|██▏       | 22/100 [00:03<00:05, 14.38epoch/s, loss=0.5019, val_loss=0.5577]

Lower model:  23%|██▎       | 23/100 [00:03<00:05, 15.00epoch/s, loss=0.5019, val_loss=0.5577]

Lower model:  23%|██▎       | 23/100 [00:03<00:05, 15.00epoch/s, loss=0.5046, val_loss=0.5602]

Lower model:  24%|██▍       | 24/100 [00:03<00:05, 15.00epoch/s, loss=0.5043, val_loss=0.5632]

Lower model:  25%|██▌       | 25/100 [00:03<00:05, 14.91epoch/s, loss=0.5043, val_loss=0.5632]

Lower model:  25%|██▌       | 25/100 [00:03<00:05, 14.91epoch/s, loss=0.4994, val_loss=0.5661]

Lower model:  26%|██▌       | 26/100 [00:03<00:11,  6.71epoch/s, loss=0.4994, val_loss=0.5661]

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

  > CQR Calibration constant (Q): 1.4850

Running configuration: Low:0.04 - High:0.99

Upper model:   0%|          | 0/100 [00:00<?, ?epoch/s]

I0000 00:00:1778435212.936023 2605131 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_134083__.19

I0000 00:00:1778435213.702581 2605131 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_134083__.19

Upper model:   0%|          | 0/100 [00:02<?, ?epoch/s, loss=20.1035, val_loss=19.8097]

Upper model:   1%|          | 1/100 [00:02<03:30,  2.13s/epoch, loss=20.1035, val_loss=19.8097]

Upper model:   1%|          | 1/100 [00:02<03:30,  2.13s/epoch, loss=20.0428, val_loss=19.7590]

Upper model:   2%|▏         | 2/100 [00:02<03:28,  2.13s/epoch, loss=20.0002, val_loss=19.7083]

Upper model:   3%|▎         | 3/100 [00:02<00:59,  1.64epoch/s, loss=20.0002, val_loss=19.7083]

Upper model:   3%|▎         | 3/100 [00:02<00:59,  1.64epoch/s, loss=19.9464, val_loss=19.6576]

Upper model:   4%|▍         | 4/100 [00:02<00:58,  1.64epoch/s, loss=19.8886, val_loss=19.6060]

Upper model:   5%|▌         | 5/100 [00:02<00:32,  2.97epoch/s, loss=19.8886, val_loss=19.6060]

Upper model:   5%|▌         | 5/100 [00:02<00:32,  2.97epoch/s, loss=19.8353, val_loss=19.5531]

Upper model:   6%|▌         | 6/100 [00:02<00:31,  2.97epoch/s, loss=19.7715, val_loss=19.4936]

Upper model:   7%|▋         | 7/100 [00:02<00:20,  4.58epoch/s, loss=19.7715, val_loss=19.4936]

Upper model:   7%|▋         | 7/100 [00:02<00:20,  4.58epoch/s, loss=19.7094, val_loss=19.4226]

Upper model:   8%|▊         | 8/100 [00:02<00:20,  4.58epoch/s, loss=19.6356, val_loss=19.3452]

Upper model:   9%|▉         | 9/100 [00:02<00:14,  6.25epoch/s, loss=19.6356, val_loss=19.3452]

Upper model:   9%|▉         | 9/100 [00:02<00:14,  6.25epoch/s, loss=19.5585, val_loss=19.2635]

Upper model:  10%|█         | 10/100 [00:02<00:14,  6.25epoch/s, loss=19.4753, val_loss=19.1787]

Upper model:  11%|█         | 11/100 [00:02<00:11,  7.99epoch/s, loss=19.4753, val_loss=19.1787]

Upper model:  11%|█         | 11/100 [00:02<00:11,  7.99epoch/s, loss=19.3922, val_loss=19.0905]

Upper model:  12%|█▏        | 12/100 [00:02<00:11,  7.99epoch/s, loss=19.3053, val_loss=18.9979]

Upper model:  13%|█▎        | 13/100 [00:02<00:08,  9.74epoch/s, loss=19.3053, val_loss=18.9979]

Upper model:  13%|█▎        | 13/100 [00:02<00:08,  9.74epoch/s, loss=19.2007, val_loss=18.8995]

Upper model:  14%|█▍        | 14/100 [00:03<00:08,  9.74epoch/s, loss=19.1079, val_loss=18.7947]

Upper model:  15%|█▌        | 15/100 [00:03<00:07, 10.87epoch/s, loss=19.1079, val_loss=18.7947]

Upper model:  15%|█▌        | 15/100 [00:03<00:07, 10.87epoch/s, loss=19.0146, val_loss=18.6818]

Upper model:  16%|█▌        | 16/100 [00:03<00:07, 10.87epoch/s, loss=18.8639, val_loss=18.5612]

Upper model:  17%|█▋        | 17/100 [00:03<00:06, 12.24epoch/s, loss=18.8639, val_loss=18.5612]

Upper model:  17%|█▋        | 17/100 [00:03<00:06, 12.24epoch/s, loss=18.7406, val_loss=18.4338]

Upper model:  18%|█▊        | 18/100 [00:03<00:06, 12.24epoch/s, loss=18.6269, val_loss=18.3006]

Upper model:  19%|█▉        | 19/100 [00:03<00:05, 13.53epoch/s, loss=18.6269, val_loss=18.3006]

Upper model:  19%|█▉        | 19/100 [00:03<00:05, 13.53epoch/s, loss=18.4832, val_loss=18.1598]

Upper model:  20%|██        | 20/100 [00:03<00:05, 13.53epoch/s, loss=18.3184, val_loss=17.9945]

Upper model:  21%|██        | 21/100 [00:03<00:05, 14.57epoch/s, loss=18.3184, val_loss=17.9945]

Upper model:  21%|██        | 21/100 [00:03<00:05, 14.57epoch/s, loss=18.1362, val_loss=17.8008]

Upper model:  22%|██▏       | 22/100 [00:03<00:05, 14.57epoch/s, loss=17.9019, val_loss=17.5913]

Upper model:  23%|██▎       | 23/100 [00:03<00:04, 15.44epoch/s, loss=17.9019, val_loss=17.5913]

Upper model:  23%|██▎       | 23/100 [00:03<00:04, 15.44epoch/s, loss=17.7245, val_loss=17.3712]

Upper model:  24%|██▍       | 24/100 [00:03<00:04, 15.44epoch/s, loss=17.5072, val_loss=17.1400]

Upper model:  25%|██▌       | 25/100 [00:03<00:04, 16.08epoch/s, loss=17.5072, val_loss=17.1400]

Upper model:  25%|██▌       | 25/100 [00:03<00:04, 16.08epoch/s, loss=17.2248, val_loss=16.8977]

Upper model:  26%|██▌       | 26/100 [00:03<00:04, 16.08epoch/s, loss=16.9664, val_loss=16.6449]

Upper model:  27%|██▋       | 27/100 [00:03<00:04, 15.59epoch/s, loss=16.9664, val_loss=16.6449]

Upper model:  27%|██▋       | 27/100 [00:03<00:04, 15.59epoch/s, loss=16.7132, val_loss=16.3778]

Upper model:  28%|██▊       | 28/100 [00:03<00:04, 15.59epoch/s, loss=16.4754, val_loss=16.0997]

Upper model:  29%|██▉       | 29/100 [00:03<00:04, 15.88epoch/s, loss=16.4754, val_loss=16.0997]

Upper model:  29%|██▉       | 29/100 [00:03<00:04, 15.88epoch/s, loss=16.1345, val_loss=15.8107]

Upper model:  30%|███       | 30/100 [00:04<00:04, 15.88epoch/s, loss=15.8206, val_loss=15.5121]

Upper model:  31%|███       | 31/100 [00:04<00:04, 16.46epoch/s, loss=15.8206, val_loss=15.5121]

Upper model:  31%|███       | 31/100 [00:04<00:04, 16.46epoch/s, loss=15.4776, val_loss=15.2010]

Upper model:  32%|███▏      | 32/100 [00:04<00:04, 16.46epoch/s, loss=15.1398, val_loss=14.8794]

Upper model:  33%|███▎      | 33/100 [00:04<00:03, 16.86epoch/s, loss=15.1398, val_loss=14.8794]

Upper model:  33%|███▎      | 33/100 [00:04<00:03, 16.86epoch/s, loss=14.8469, val_loss=14.5429]

Upper model:  34%|███▍      | 34/100 [00:04<00:03, 16.86epoch/s, loss=14.4944, val_loss=14.1959]

Upper model:  35%|███▌      | 35/100 [00:04<00:03, 16.87epoch/s, loss=14.4944, val_loss=14.1959]

Upper model:  35%|███▌      | 35/100 [00:04<00:03, 16.87epoch/s, loss=14.1372, val_loss=13.8374]

Upper model:  36%|███▌      | 36/100 [00:04<00:03, 16.87epoch/s, loss=13.6735, val_loss=13.4731]

Upper model:  37%|███▋      | 37/100 [00:04<00:03, 17.19epoch/s, loss=13.6735, val_loss=13.4731]

Upper model:  37%|███▋      | 37/100 [00:04<00:03, 17.19epoch/s, loss=13.2979, val_loss=13.1003]

Upper model:  38%|███▊      | 38/100 [00:04<00:03, 17.19epoch/s, loss=12.8900, val_loss=12.7187]

Upper model:  39%|███▉      | 39/100 [00:04<00:03, 17.36epoch/s, loss=12.8900, val_loss=12.7187]

Upper model:  39%|███▉      | 39/100 [00:04<00:03, 17.36epoch/s, loss=12.6151, val_loss=12.3382]

Upper model:  40%|████      | 40/100 [00:04<00:03, 17.36epoch/s, loss=12.1120, val_loss=11.9506]

Upper model:  41%|████      | 41/100 [00:04<00:03, 17.11epoch/s, loss=12.1120, val_loss=11.9506]

Upper model:  41%|████      | 41/100 [00:04<00:03, 17.11epoch/s, loss=11.7346, val_loss=11.5568]

Upper model:  42%|████▏     | 42/100 [00:04<00:03, 17.11epoch/s, loss=11.3270, val_loss=11.1580]

Upper model:  43%|████▎     | 43/100 [00:04<00:03, 17.08epoch/s, loss=11.3270, val_loss=11.1580]

Upper model:  43%|████▎     | 43/100 [00:04<00:03, 17.08epoch/s, loss=10.9104, val_loss=10.7577]

Upper model:  44%|████▍     | 44/100 [00:04<00:03, 17.08epoch/s, loss=10.4385, val_loss=10.3479]

Upper model:  45%|████▌     | 45/100 [00:04<00:03, 16.50epoch/s, loss=10.4385, val_loss=10.3479]

Upper model:  45%|████▌     | 45/100 [00:04<00:03, 16.50epoch/s, loss=9.9887, val_loss=9.9446]

Upper model:  46%|████▌     | 46/100 [00:04<00:03, 16.50epoch/s, loss=9.5982, val_loss=9.5401]

Upper model:  47%|████▋     | 47/100 [00:04<00:03, 16.70epoch/s, loss=9.5982, val_loss=9.5401]

Upper model:  47%|████▋     | 47/100 [00:04<00:03, 16.70epoch/s, loss=9.1373, val_loss=9.1359]

Upper model:  48%|████▊     | 48/100 [00:05<00:03, 16.70epoch/s, loss=8.7285, val_loss=8.7368]

Upper model:  49%|████▉     | 49/100 [00:05<00:03, 16.94epoch/s, loss=8.7285, val_loss=8.7368]

Upper model:  49%|████▉     | 49/100 [00:05<00:03, 16.94epoch/s, loss=8.4163, val_loss=8.3371]

Upper model:  50%|█████     | 50/100 [00:05<00:02, 16.94epoch/s, loss=7.8981, val_loss=7.9396]

Upper model:  51%|█████     | 51/100 [00:05<00:02, 16.71epoch/s, loss=7.8981, val_loss=7.9396]

Upper model:  51%|█████     | 51/100 [00:05<00:02, 16.71epoch/s, loss=7.6733, val_loss=7.5431]

Upper model:  52%|█████▏    | 52/100 [00:05<00:02, 16.71epoch/s, loss=7.1798, val_loss=7.1605]

Upper model:  53%|█████▎    | 53/100 [00:05<00:02, 16.14epoch/s, loss=7.1798, val_loss=7.1605]

Upper model:  53%|█████▎    | 53/100 [00:05<00:02, 16.14epoch/s, loss=6.7830, val_loss=6.7789]

Upper model:  54%|█████▍    | 54/100 [00:05<00:02, 16.14epoch/s, loss=6.5335, val_loss=6.4135]

Upper model:  55%|█████▌    | 55/100 [00:05<00:02, 15.87epoch/s, loss=6.5335, val_loss=6.4135]

Upper model:  55%|█████▌    | 55/100 [00:05<00:02, 15.87epoch/s, loss=6.2191, val_loss=6.0599]

Upper model:  56%|█████▌    | 56/100 [00:05<00:02, 15.87epoch/s, loss=5.8267, val_loss=5.7192]

Upper model:  57%|█████▋    | 57/100 [00:05<00:02, 15.90epoch/s, loss=5.8267, val_loss=5.7192]

Upper model:  57%|█████▋    | 57/100 [00:05<00:02, 15.90epoch/s, loss=5.5484, val_loss=5.3849]

Upper model:  58%|█████▊    | 58/100 [00:05<00:02, 15.90epoch/s, loss=5.2360, val_loss=5.0703]

Upper model:  59%|█████▉    | 59/100 [00:05<00:02, 15.85epoch/s, loss=5.2360, val_loss=5.0703]

Upper model:  59%|█████▉    | 59/100 [00:05<00:02, 15.85epoch/s, loss=4.8529, val_loss=4.7717]

Upper model:  60%|██████    | 60/100 [00:05<00:02, 15.85epoch/s, loss=4.6294, val_loss=4.4947]

Upper model:  61%|██████    | 61/100 [00:05<00:02, 16.24epoch/s, loss=4.6294, val_loss=4.4947]

Upper model:  61%|██████    | 61/100 [00:05<00:02, 16.24epoch/s, loss=4.3302, val_loss=4.2266]

Upper model:  62%|██████▏   | 62/100 [00:05<00:02, 16.24epoch/s, loss=4.1835, val_loss=3.9768]

Upper model:  63%|██████▎   | 63/100 [00:05<00:02, 16.44epoch/s, loss=4.1835, val_loss=3.9768]

Upper model:  63%|██████▎   | 63/100 [00:05<00:02, 16.44epoch/s, loss=3.9476, val_loss=3.7284]

Upper model:  64%|██████▍   | 64/100 [00:06<00:02, 16.44epoch/s, loss=3.6175, val_loss=3.4931]

Upper model:  65%|██████▌   | 65/100 [00:06<00:02, 16.27epoch/s, loss=3.6175, val_loss=3.4931]

Upper model:  65%|██████▌   | 65/100 [00:06<00:02, 16.27epoch/s, loss=3.5375, val_loss=3.2767]

Upper model:  66%|██████▌   | 66/100 [00:06<00:02, 16.27epoch/s, loss=3.2822, val_loss=3.0843]

Upper model:  67%|██████▋   | 67/100 [00:06<00:01, 16.62epoch/s, loss=3.2822, val_loss=3.0843]

Upper model:  67%|██████▋   | 67/100 [00:06<00:01, 16.62epoch/s, loss=3.0878, val_loss=2.9077]

Upper model:  68%|██████▊   | 68/100 [00:06<00:01, 16.62epoch/s, loss=3.0818, val_loss=2.7495]

Upper model:  69%|██████▉   | 69/100 [00:06<00:01, 16.40epoch/s, loss=3.0818, val_loss=2.7495]

Upper model:  69%|██████▉   | 69/100 [00:06<00:01, 16.40epoch/s, loss=2.8658, val_loss=2.6004]

Upper model:  70%|███████   | 70/100 [00:06<00:01, 16.40epoch/s, loss=2.5723, val_loss=2.4548]

Upper model:  71%|███████   | 71/100 [00:06<00:01, 16.31epoch/s, loss=2.5723, val_loss=2.4548]

Upper model:  71%|███████   | 71/100 [00:06<00:01, 16.31epoch/s, loss=2.5462, val_loss=2.3102]

Upper model:  72%|███████▏  | 72/100 [00:06<00:01, 16.31epoch/s, loss=2.4323, val_loss=2.1721]

Upper model:  73%|███████▎  | 73/100 [00:06<00:01, 15.83epoch/s, loss=2.4323, val_loss=2.1721]

Upper model:  73%|███████▎  | 73/100 [00:06<00:01, 15.83epoch/s, loss=2.2906, val_loss=2.0392]

Upper model:  74%|███████▍  | 74/100 [00:06<00:01, 15.83epoch/s, loss=2.0652, val_loss=1.9109]

Upper model:  75%|███████▌  | 75/100 [00:06<00:01, 16.02epoch/s, loss=2.0652, val_loss=1.9109]

Upper model:  75%|███████▌  | 75/100 [00:06<00:01, 16.02epoch/s, loss=1.9059, val_loss=1.7907]

Upper model:  76%|███████▌  | 76/100 [00:06<00:01, 16.02epoch/s, loss=1.8817, val_loss=1.6878]

Upper model:  77%|███████▋  | 77/100 [00:06<00:01, 16.06epoch/s, loss=1.8817, val_loss=1.6878]

Upper model:  77%|███████▋  | 77/100 [00:06<00:01, 16.06epoch/s, loss=1.7330, val_loss=1.6011]

Upper model:  78%|███████▊  | 78/100 [00:06<00:01, 16.06epoch/s, loss=1.8675, val_loss=1.5222]

Upper model:  79%|███████▉  | 79/100 [00:06<00:01, 15.78epoch/s, loss=1.8675, val_loss=1.5222]

Upper model:  79%|███████▉  | 79/100 [00:06<00:01, 15.78epoch/s, loss=1.6943, val_loss=1.4479]

Upper model:  80%|████████  | 80/100 [00:07<00:01, 15.78epoch/s, loss=1.5927, val_loss=1.3760]

Upper model:  81%|████████  | 81/100 [00:07<00:01, 14.86epoch/s, loss=1.5927, val_loss=1.3760]

Upper model:  81%|████████  | 81/100 [00:07<00:01, 14.86epoch/s, loss=1.6546, val_loss=1.3115]

Upper model:  82%|████████▏ | 82/100 [00:07<00:01, 14.86epoch/s, loss=1.5498, val_loss=1.2543]

Upper model:  83%|████████▎ | 83/100 [00:07<00:01, 15.22epoch/s, loss=1.5498, val_loss=1.2543]

Upper model:  83%|████████▎ | 83/100 [00:07<00:01, 15.22epoch/s, loss=1.3505, val_loss=1.1992]

Upper model:  84%|████████▍ | 84/100 [00:07<00:01, 15.22epoch/s, loss=1.4620, val_loss=1.1490]

Upper model:  85%|████████▌ | 85/100 [00:07<00:00, 15.41epoch/s, loss=1.4620, val_loss=1.1490]

Upper model:  85%|████████▌ | 85/100 [00:07<00:00, 15.41epoch/s, loss=1.3391, val_loss=1.1046]

Upper model:  86%|████████▌ | 86/100 [00:07<00:00, 15.41epoch/s, loss=1.2365, val_loss=1.0620]

Upper model:  87%|████████▋ | 87/100 [00:07<00:00, 15.35epoch/s, loss=1.2365, val_loss=1.0620]

Upper model:  87%|████████▋ | 87/100 [00:07<00:00, 15.35epoch/s, loss=1.2756, val_loss=1.0236]

Upper model:  88%|████████▊ | 88/100 [00:07<00:00, 15.35epoch/s, loss=1.2385, val_loss=0.9837]

Upper model:  89%|████████▉ | 89/100 [00:07<00:00, 15.21epoch/s, loss=1.2385, val_loss=0.9837]

Upper model:  89%|████████▉ | 89/100 [00:07<00:00, 15.21epoch/s, loss=1.2814, val_loss=0.9426]

Upper model:  90%|█████████ | 90/100 [00:07<00:00, 15.21epoch/s, loss=1.2037, val_loss=0.9063]

Upper model:  91%|█████████ | 91/100 [00:07<00:00, 15.54epoch/s, loss=1.2037, val_loss=0.9063]

Upper model:  91%|█████████ | 91/100 [00:07<00:00, 15.54epoch/s, loss=1.1423, val_loss=0.8737]

Upper model:  92%|█████████▏| 92/100 [00:07<00:00, 15.54epoch/s, loss=1.1314, val_loss=0.8437]

Upper model:  93%|█████████▎| 93/100 [00:07<00:00, 15.75epoch/s, loss=1.1314, val_loss=0.8437]

Upper model:  93%|█████████▎| 93/100 [00:07<00:00, 15.75epoch/s, loss=1.0921, val_loss=0.8120]

Upper model:  94%|█████████▍| 94/100 [00:07<00:00, 15.75epoch/s, loss=0.8390, val_loss=0.7819]

Upper model:  95%|█████████▌| 95/100 [00:07<00:00, 16.05epoch/s, loss=0.8390, val_loss=0.7819]

Upper model:  95%|█████████▌| 95/100 [00:08<00:00, 16.05epoch/s, loss=1.0395, val_loss=0.7523]

Upper model:  96%|█████████▌| 96/100 [00:08<00:00, 16.05epoch/s, loss=0.9642, val_loss=0.7264]

Upper model:  97%|█████████▋| 97/100 [00:08<00:00, 16.13epoch/s, loss=0.9642, val_loss=0.7264]

Upper model:  97%|█████████▋| 97/100 [00:08<00:00, 16.13epoch/s, loss=0.9490, val_loss=0.7049]

Upper model:  98%|█████████▊| 98/100 [00:08<00:00, 16.13epoch/s, loss=0.8798, val_loss=0.6840]

Upper model:  99%|█████████▉| 99/100 [00:08<00:00, 16.36epoch/s, loss=0.8798, val_loss=0.6840]

Upper model:  99%|█████████▉| 99/100 [00:08<00:00, 16.36epoch/s, loss=0.8618, val_loss=0.6639]

Upper model: 100%|██████████| 100/100 [00:08<00:00, 12.09epoch/s, loss=0.8618, val_loss=0.6639]

Lower model:   0%|          | 0/100 [00:00<?, ?epoch/s]

I0000 00:00:1778435221.235742 2605131 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_141002__.19

I0000 00:00:1778435222.035977 2605133 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_141002__.19

Lower model:   0%|          | 0/100 [00:02<?, ?epoch/s, loss=0.8116, val_loss=0.8014]

Lower model:   1%|          | 1/100 [00:02<03:39,  2.22s/epoch, loss=0.8116, val_loss=0.8014]

Lower model:   1%|          | 1/100 [00:02<03:39,  2.22s/epoch, loss=0.8108, val_loss=0.8004]

Lower model:   2%|▏         | 2/100 [00:02<03:37,  2.22s/epoch, loss=0.8098, val_loss=0.7994]

Lower model:   3%|▎         | 3/100 [00:02<01:00,  1.61epoch/s, loss=0.8098, val_loss=0.7994]

Lower model:   3%|▎         | 3/100 [00:02<01:00,  1.61epoch/s, loss=0.8087, val_loss=0.7983]

Lower model:   4%|▍         | 4/100 [00:02<00:59,  1.61epoch/s, loss=0.8075, val_loss=0.7969]

Lower model:   5%|▌         | 5/100 [00:02<00:31,  3.01epoch/s, loss=0.8075, val_loss=0.7969]

Lower model:   5%|▌         | 5/100 [00:02<00:31,  3.01epoch/s, loss=0.8062, val_loss=0.7954]

Lower model:   6%|▌         | 6/100 [00:02<00:31,  3.01epoch/s, loss=0.8046, val_loss=0.7937]

Lower model:   7%|▋         | 7/100 [00:02<00:20,  4.63epoch/s, loss=0.8046, val_loss=0.7937]

Lower model:   7%|▋         | 7/100 [00:02<00:20,  4.63epoch/s, loss=0.8027, val_loss=0.7918]

Lower model:   8%|▊         | 8/100 [00:02<00:19,  4.63epoch/s, loss=0.8008, val_loss=0.7897]

Lower model:   9%|▉         | 9/100 [00:02<00:14,  6.35epoch/s, loss=0.8008, val_loss=0.7897]

Lower model:   9%|▉         | 9/100 [00:02<00:14,  6.35epoch/s, loss=0.7986, val_loss=0.7874]

Lower model:  10%|█         | 10/100 [00:02<00:14,  6.35epoch/s, loss=0.7964, val_loss=0.7849]

Lower model:  11%|█         | 11/100 [00:02<00:10,  8.12epoch/s, loss=0.7964, val_loss=0.7849]

Lower model:  11%|█         | 11/100 [00:02<00:10,  8.12epoch/s, loss=0.7937, val_loss=0.7822]

Lower model:  12%|█▏        | 12/100 [00:02<00:10,  8.12epoch/s, loss=0.7909, val_loss=0.7792]

Lower model:  13%|█▎        | 13/100 [00:02<00:08,  9.84epoch/s, loss=0.7909, val_loss=0.7792]

Lower model:  13%|█▎        | 13/100 [00:02<00:08,  9.84epoch/s, loss=0.7878, val_loss=0.7759]

Lower model:  14%|█▍        | 14/100 [00:03<00:08,  9.84epoch/s, loss=0.7843, val_loss=0.7722]

Lower model:  15%|█▌        | 15/100 [00:03<00:07, 11.38epoch/s, loss=0.7843, val_loss=0.7722]

Lower model:  15%|█▌        | 15/100 [00:03<00:07, 11.38epoch/s, loss=0.7802, val_loss=0.7680]

Lower model:  16%|█▌        | 16/100 [00:03<00:07, 11.38epoch/s, loss=0.7759, val_loss=0.7633]

Lower model:  17%|█▋        | 17/100 [00:03<00:06, 12.82epoch/s, loss=0.7759, val_loss=0.7633]

Lower model:  17%|█▋        | 17/100 [00:03<00:06, 12.82epoch/s, loss=0.7707, val_loss=0.7581]

Lower model:  18%|█▊        | 18/100 [00:03<00:06, 12.82epoch/s, loss=0.7655, val_loss=0.7523]

Lower model:  19%|█▉        | 19/100 [00:03<00:05, 13.97epoch/s, loss=0.7655, val_loss=0.7523]

Lower model:  19%|█▉        | 19/100 [00:03<00:05, 13.97epoch/s, loss=0.7594, val_loss=0.7471]

Lower model:  20%|██        | 20/100 [00:03<00:05, 13.97epoch/s, loss=0.7520, val_loss=0.7414]

Lower model:  21%|██        | 21/100 [00:03<00:05, 14.79epoch/s, loss=0.7520, val_loss=0.7414]

Lower model:  21%|██        | 21/100 [00:03<00:05, 14.79epoch/s, loss=0.7456, val_loss=0.7351]

Lower model:  22%|██▏       | 22/100 [00:03<00:05, 14.79epoch/s, loss=0.7380, val_loss=0.7282]

Lower model:  23%|██▎       | 23/100 [00:03<00:04, 15.56epoch/s, loss=0.7380, val_loss=0.7282]

Lower model:  23%|██▎       | 23/100 [00:03<00:04, 15.56epoch/s, loss=0.7301, val_loss=0.7205]

Lower model:  24%|██▍       | 24/100 [00:03<00:04, 15.56epoch/s, loss=0.7219, val_loss=0.7162]

Lower model:  25%|██▌       | 25/100 [00:03<00:04, 15.97epoch/s, loss=0.7219, val_loss=0.7162]

Lower model:  25%|██▌       | 25/100 [00:03<00:04, 15.97epoch/s, loss=0.7120, val_loss=0.7161]

Lower model:  26%|██▌       | 26/100 [00:03<00:04, 15.97epoch/s, loss=0.7009, val_loss=0.7169]

Lower model:  27%|██▋       | 27/100 [00:03<00:04, 16.29epoch/s, loss=0.7009, val_loss=0.7169]

Lower model:  27%|██▋       | 27/100 [00:03<00:04, 16.29epoch/s, loss=0.6880, val_loss=0.7192]

Lower model:  28%|██▊       | 28/100 [00:03<00:04, 16.29epoch/s, loss=0.6802, val_loss=0.7222]

Lower model:  29%|██▉       | 29/100 [00:03<00:04, 16.57epoch/s, loss=0.6802, val_loss=0.7222]

Lower model:  29%|██▉       | 29/100 [00:03<00:04, 16.57epoch/s, loss=0.6713, val_loss=0.7271]

Lower model:  30%|███       | 30/100 [00:03<00:04, 16.57epoch/s, loss=0.6634, val_loss=0.7299]

Lower model:  31%|███       | 31/100 [00:03<00:04, 16.56epoch/s, loss=0.6634, val_loss=0.7299]

Lower model:  31%|███       | 31/100 [00:04<00:04, 16.56epoch/s, loss=0.6590, val_loss=0.7325]

Lower model:  32%|███▏      | 32/100 [00:04<00:04, 16.56epoch/s, loss=0.6604, val_loss=0.7345]

Lower model:  33%|███▎      | 33/100 [00:04<00:04, 16.73epoch/s, loss=0.6604, val_loss=0.7345]

Lower model:  33%|███▎      | 33/100 [00:04<00:04, 16.73epoch/s, loss=0.6599, val_loss=0.7363]

Lower model:  34%|███▍      | 34/100 [00:04<00:03, 16.73epoch/s, loss=0.6519, val_loss=0.7385]

Lower model:  35%|███▌      | 35/100 [00:04<00:03, 17.11epoch/s, loss=0.6519, val_loss=0.7385]

Lower model:  35%|███▌      | 35/100 [00:04<00:03, 17.11epoch/s, loss=0.6542, val_loss=0.7393]

Lower model:  36%|███▌      | 36/100 [00:04<00:07,  8.43epoch/s, loss=0.6542, val_loss=0.7393]

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

  > CQR Calibration constant (Q): 5.1873
Tuning metrics saved to /home/lmaosid/Desktop/major/experiments/classification_new_data/output/conformal_results_uncensored/Sentinel-1_tau_tuning_metrics.json

In [8]:
eos_results

                 Tau_Pair  Raw_PICP   Raw_MPIW  CQR_PICP   CQR_MPIW
0    Low:0.01 - High:0.96  0.921788  31.894760  0.921788  31.617267
1  Low:0.015 - High:0.965  0.938547  32.880219  0.938547  32.757247
2    Low:0.02 - High:0.97  0.932961  32.078392  0.916201  31.647921
3  Low:0.025 - High:0.975  0.949721  32.646286  0.944134  31.803221
4    Low:0.03 - High:0.98  0.938547  34.581764  0.927374  34.066471
5    Low:0.04 - High:0.99  0.938547  40.114269  0.921788  39.750510

In [9]:
sentinel_results

                 Tau_Pair  Raw_PICP   Raw_MPIW  CQR_PICP   CQR_MPIW
0    Low:0.01 - High:0.96  0.948905  37.708244  0.978102  42.518270
1  Low:0.015 - High:0.965  0.948905  35.194904  0.978102  46.334665
2    Low:0.02 - High:0.97  0.948905  35.237068  0.963504  43.296373
3  Low:0.025 - High:0.975  0.934307  33.306107  0.970803  45.995024
4    Low:0.03 - High:0.98  0.963504  40.617153  0.978102  43.587098
5    Low:0.04 - High:0.99  0.948905  34.754604  0.978102  45.129263