# Driver Code

In [1]:
from sklearn.model_selection import train_test_split

class Experiment:
    def __init__(self, X, y, train_size=0.8, test_size=0.1, val_size=0.1, split_type='train-val-test', print_stats=None):
        self.X = X
        self.y = y

        self.X_train = None
        self.y_train = None
        self.X_val = None
        self.y_val = None
        self.X_test = None
        self.y_test = None

        self.__split_data(train_size, test_size, val_size, split_type)
        if print_stats:
            self.__print_data_summary(train_size, test_size, val_size, split_type)

    def __split_data(self, train_size, test_size, val_size, split_type):
        if split_type == 'train-val-test':
            if not np.isclose(train_size + test_size + val_size, 1.0):
                raise ValueError("train_size, test_size, and val_size must sum to 1.0")

            if train_size == 1.0:
                self.X_train, self.y_train = self.X, self.y
                return

            X_train, X_temp, y_train, y_temp = train_test_split(
                self.X, self.y, train_size=train_size, random_state=42
            )

            self.X_train, self.y_train = X_train, y_train

            remaining_size = val_size + test_size
            if np.isclose(remaining_size, 0.0):
                return

            relative_test_size = test_size / remaining_size

            if np.isclose(relative_test_size, 1.0):
                self.X_test, self.y_test = X_temp, y_temp
            elif np.isclose(relative_test_size, 0.0):
                self.X_val, self.y_val = X_temp, y_temp
            else:
                self.X_val, self.X_test, self.y_val, self.y_test = train_test_split(
                    X_temp, y_temp, test_size=relative_test_size, random_state=42
                )

        elif split_type == 'train-test':
            if not np.isclose(train_size + test_size, 1.0):
                raise ValueError("train_size and test_size must sum to 1.0")

            if train_size == 1.0:
                self.X_train, self.y_train = self.X, self.y
            elif test_size == 1.0:
                self.X_test, self.y_test = self.X, self.y
            else:
                self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(
                    self.X, self.y, train_size=train_size, random_state=42
                )

        else:
            raise ValueError(f"Unknown split_type: {split_type}. Must be 'train-val-test' or 'train-test'.")

    def __print_data_summary(self, train_size, test_size, val_size, split_type):
        total_samples = len(self.X)
        train_samples = len(self.X_train) if self.X_train is not None else 0
        val_samples = len(self.X_val) if self.X_val is not None else 0
        test_samples = len(self.X_test) if self.X_test is not None else 0

        print(f"\n--- Experiment Data Initialized ---")
        print(f"Total Samples: {total_samples}")
        print(f"Split Type:    '{split_type}'")

        if split_type == 'train-val-test':
            print(f"  - Train: {train_size*100:>6.1f}% ({train_samples} samples)")
            print(f"  - Val:   {val_size*100:>6.1f}% ({val_samples} samples)")
            print(f"  - Test:  {test_size*100:>6.1f}% ({test_samples} samples)")
        elif split_type == 'train-test':
            print(f"  - Train: {train_size*100:>6.1f}% ({train_samples} samples)")
            print(f"  - Test:  {test_size*100:>6.1f}% ({test_samples} samples)")

        print(f"Total in splits: {train_samples + val_samples + test_samples}")
        print("-----------------------------------\n")

In [2]:
import time
from scipy.spatial.distance import cdist
from cvxopt import matrix, solvers

from sklearn.preprocessing import MinMaxScaler
import os
import numpy as np
import json
import matplotlib.pyplot as plt
from pathlib import Path

solvers.options['show_progress'] = False
OUTPUT_PATH = Path("results_qsvr")


class QuantileSVRExperiment(Experiment):
    def __init__(self, X, y, satellite, train_size=0.8, test_size=0.1, val_size=0.1,
                 split_type='train-val-test', print_stats=None, type='censored'):
        super().__init__(X, y, train_size, test_size, val_size, split_type, print_stats)
        self.satellite = satellite
        self.results_path = OUTPUT_PATH / f"qsvr_pi_estimation_{type}"
        os.makedirs(self.results_path, exist_ok=True)

        self.__scale_data()

    def __scale_data(self):
        """Scales X and Y data, storing the scalers."""
        self.x_scaler = MinMaxScaler()
        self.y_scaler = MinMaxScaler()


        self.X_train_scaled = self.x_scaler.fit_transform(self.X_train)
        self.X_val_scaled = self.x_scaler.transform(self.X_val)
        self.X_test_scaled = self.x_scaler.transform(self.X_test)


        self.y_train = self.y_train.reshape(-1, 1)
        self.y_val = self.y_val.reshape(-1, 1)
        self.y_test = self.y_test.reshape(-1, 1)


        self.y_train_scaled = self.y_scaler.fit_transform(self.y_train)
        self.y_val_scaled = self.y_scaler.transform(self.y_val)
        self.y_test_scaled = self.y_scaler.transform(self.y_test)


        self.y_train = self.y_train.ravel()
        self.y_val = self.y_val.ravel()
        self.y_test = self.y_test.ravel()
        self.y_train_scaled = self.y_train_scaled.ravel()
        self.y_val_scaled = self.y_val_scaled.ravel()
        self.y_test_scaled = self.y_test_scaled.ravel()



    @staticmethod
    def kernelfun(X, kerfPara, Y=None):
        """Evaluate the RBF kernel."""
        if Y is None:
            Y = X
        if kerfPara['type'] == 'rbf':
            gamma = kerfPara['pars']
            sqdist = cdist(X, Y, 'sqeuclidean')
            return np.exp(-gamma * sqdist)
        else:
            raise ValueError("Unknown kernel function")

    @staticmethod
    def svtol(C):
        """A helper function to set a tolerance based on C."""
        return 1e-5

    @staticmethod
    def nobias(kerfType):
        """For this demonstration we simply disable the bias-computation by returning 0."""
        return 0

    @staticmethod
    def fit_quantile_svr(X, Y, kerfPara, C, tau, eps1=0.0):
        """
        Trains the Quantile SVR model by solving the Quadratic Program.

        Returns:
          beta (np.array): The learned model coefficients.
          bias (float): The learned model bias.
        """
        epsilon = QuantileSVRExperiment.svtol(C)
        n = X.shape[0]
        H = QuantileSVRExperiment.kernelfun(X, kerfPara)  # shape: (n,n)


        Hb_top = np.hstack([H, -H])
        Hb_bottom = np.hstack([-H, H])
        Hb = np.vstack([Hb_top, Hb_bottom])



        Y_col = Y.reshape(-1, 1)
        c_part1 = ((1 - tau) * eps1 * np.ones((n, 1)) - Y_col)
        c_part2 = (tau * eps1 * np.ones((n, 1)) + Y_col)
        c_vec = np.vstack([c_part1, c_part2]).flatten()


        vlb = np.zeros(2 * n)
        vub = np.concatenate([tau * C * np.ones(n), (1 - tau) * C * np.ones(n)])

        A = None
        b_eq = None



        P = matrix(Hb)
        q = matrix(c_vec)
        I = np.eye(2 * n)
        G1 = -I
        h1 = np.zeros(2 * n)
        G2 = I
        h2 = vub
        G = matrix(np.vstack([G1, G2]))
        h = matrix(np.hstack([h1, h2]))

        sol = solvers.qp(P, q, G, h)

        alpha = np.array(sol['x']).flatten()
        alpha1 = alpha[:n]
        beta1 = alpha[n:2*n]
        beta = alpha1 - beta1


        bias = 0

        return beta, bias, H

    @staticmethod
    def predict_quantile_svr(X_train, X_predict, kerfPara, beta, bias):
        """
        Generates predictions on new data using a trained Q-SVR model.
        """
        H_test = QuantileSVRExperiment.kernelfun(X_predict, kerfPara, X_train)
        PredictY = H_test.dot(beta) + bias
        return PredictY

    def evaluate_model(self, y_true, y_pred_lower, y_pred_upper):
        """
        Evaluates the prediction interval using PICP and MPIW.
        (Adapted from your PredictionIntervalEstimation class)
        """
        y_true_flat = y_true.flatten()
        y_lower_flat = y_pred_lower.flatten()
        y_upper_flat = y_pred_upper.flatten()

        def picp(y_true_vals, y_pred_lower_vals, y_pred_upper_vals):
            """Prediction Interval Coverage Probability"""
            covered = np.sum((y_true_vals >= y_pred_lower_vals) & (y_true_vals <= y_pred_upper_vals))
            return covered / len(y_true_vals)

        def mpiw(y_pred_lower_vals, y_pred_upper_vals):
            """Mean Prediction Interval Width"""
            return np.mean(y_pred_upper_vals - y_pred_lower_vals)

        return {
            'PICP': float(picp(y_true_flat, y_lower_flat, y_upper_flat)),
            'MPIW': float(mpiw(y_lower_flat, y_upper_flat))
        }

    def plot_prediction_interval(self, y_pred_lower_test, y_pred_upper_test,
                                 y_pred_lower_val, y_pred_upper_val, model_param_string):
        """
        Plots the prediction intervals for the test set.
        (Adapted from your PredictionIntervalEstimation class)
        """
        indices = range(len(self.y_test))

        test_eval_dict = self.evaluate_model(self.y_test, y_pred_lower_test, y_pred_upper_test)
        val_eval_dict = self.evaluate_model(self.y_val, y_pred_lower_val, y_pred_upper_val)

        plt.figure(figsize=(14, 7))
        plt.plot(indices, self.y_test, 'o', color='blue', label='Actual Soil Moisture (Test Set)', markersize=4)
        plt.plot(indices, y_pred_lower_test, color='red', linestyle='--', label='Lower Bound')
        plt.plot(indices, y_pred_upper_test, color='orange', linestyle='--', label='Upper Bound')

        plt.fill_between(indices, y_pred_lower_test, y_pred_upper_test, color='gray', alpha=0.2, label='95% Prediction Interval')

        test_metrics = f"Test  | PICP: {test_eval_dict['PICP']*100:5.2f}% | MPIW: {test_eval_dict['MPIW']:.4f}"
        val_metrics =  f"Valid | PICP: {val_eval_dict['PICP']*100:5.2f}% | MPIW: {val_eval_dict['MPIW']:.4f}"
        metrics_text = f"{test_metrics}\n{val_metrics}"

        plt.annotate(metrics_text, xy=(0.02, 0.98), xycoords='axes fraction',
                    bbox=dict(boxstyle="round,pad=0.5", facecolor="white", alpha=0.8),
                    verticalalignment='top', fontsize=12, fontname='monospace')

        plot_dir = self.results_path / "plots"
        os.makedirs(plot_dir, exist_ok=True)

        plt.xlabel('Sample Index')
        plt.ylabel('Soil Moisture')
        plt.title(f'{self.satellite}: {model_param_string}\nQ-SVR Prediction Interval')
        plt.legend()
        plt.grid(True, alpha=0.3)
        plot_save_path = plot_dir / f"{self.satellite}_{model_param_string}.png"
        plt.savefig(plot_save_path, dpi=300)
        print(f"Plot saved to {plot_save_path}")
        plt.close()

    def run_experiment(self, C_value, gamma, q_lower=0.025, q_upper=0.975, eps1=0.0):
        """
        Runs the full experiment for training and evaluating the Q-SVR.
        """
        model_param_string = f"C={C_value}_gamma={gamma}"
        print(f"\n--- Running Quantile SVR for {self.satellite} ---")
        print(f"Params: {model_param_string}")


        kerfPara = {'type': 'rbf', 'pars': gamma}


        print(f"Training lower quantile ({q_lower}) model...")
        start_time = time.time()

        beta_lower, bias_lower, _ = self.fit_quantile_svr(
            self.X_train_scaled, self.y_train, kerfPara, C_value, q_lower, eps1
        )
        print(f"Done in {time.time() - start_time:.2f}s")


        print(f"Training upper quantile ({q_upper}) model...")
        start_time = time.time()
        beta_upper, bias_upper, _ = self.fit_quantile_svr(
            self.X_train_scaled, self.y_train, kerfPara, C_value, q_upper, eps1
        )
        print(f"Done in {time.time() - start_time:.2f}s")


        print("Generating predictions...")

        y_preds_lower_val = self.predict_quantile_svr(
            self.X_train_scaled, self.X_val_scaled, kerfPara, beta_lower, bias_lower
        )
        y_preds_upper_val = self.predict_quantile_svr(
            self.X_train_scaled, self.X_val_scaled, kerfPara, beta_upper, bias_upper
        )


        y_preds_lower_test = self.predict_quantile_svr(
            self.X_train_scaled, self.X_test_scaled, kerfPara, beta_lower, bias_lower
        )
        y_preds_upper_test = self.predict_quantile_svr(
            self.X_train_scaled, self.X_test_scaled, kerfPara, beta_upper, bias_upper
        )


        print("Evaluating and plotting results...")
        self.plot_prediction_interval(
            y_preds_lower_test, y_preds_upper_test,
            y_preds_lower_val, y_preds_upper_val,
            model_param_string
        )

        results_val = self.evaluate_model(self.y_val, y_preds_lower_val, y_preds_upper_val)
        results_test = self.evaluate_model(self.y_test, y_preds_lower_test, y_preds_upper_test)

        results = {
            "params": {"C": C_value, "gamma": gamma, "q_lower": q_lower, "q_upper": q_upper},
            "val": results_val,
            "test": results_test
        }

        print(f"Results for {model_param_string}:")
        print(json.dumps(results, indent=4))


        metrics_filename = self.results_path / f"{self.satellite}_metrics_{model_param_string}.json"
        # with open(metrics_filename, "w") as f:
        #     json.dump(results, f, indent=4)
        # print(f"Metrics saved to {metrics_filename}")

        return results

# Experiment Code

In [3]:
from constants import DATA_PATH
import pandas as pd

eos = pd.read_csv(DATA_PATH / "eos-04-processed.csv")
sentinel = pd.read_csv(DATA_PATH / "sentinel-1-processed.csv")

In [4]:
sentinel = sentinel[sentinel['SM1 (%)'] != 50]
eos = eos[eos['SM1 (%)'] != 50]

In [5]:
X_cols_eos = ['HH-pol', 'HV-pol']
X_cols_sentinel = ['VH-pol', 'VV-pol']

y_col = ['SM1 (%)']

X_sentinel = sentinel[X_cols_sentinel].values
X_eos = eos[X_cols_eos].values

y_sentinel = sentinel[y_col].values
y_eos = eos[y_col].values

In [6]:
C_VALUE = 2**6
GAMMA_VALUES = [2 ** i for i in range(-15, 16)]

GAMMA_VALUES

[3.0517578125e-05,
 6.103515625e-05,
 0.0001220703125,
 0.000244140625,
 0.00048828125,
 0.0009765625,
 0.001953125,
 0.00390625,
 0.0078125,
 0.015625,
 0.03125,
 0.0625,
 0.125,
 0.25,
 0.5,
 1,
 2,
 4,
 8,
 16,
 32,
 64,
 128,
 256,
 512,
 1024,
 2048,
 4096,
 8192,
 16384,
 32768]

In [7]:
from joblib import Parallel, delayed

def _run_sentinel_gamma(gamma, C_VALUE):
    exp = QuantileSVRExperiment(
        X=X_sentinel,
        y=y_sentinel,
        satellite="Sentinel-1",
        print_stats=False,
        type="uncensored"
    )
    try:
        results = exp.run_experiment(C_value=C_VALUE, gamma=gamma)
        print(f"Sentinel-1 Gamma={gamma:.6f} done — PICP={results['test']['PICP']:.4f}")
        return results
    except Exception as e:
        print(f"ERROR Gamma={gamma}: {e}")
        return {"params": {"C": C_VALUE, "gamma": gamma}, "val": {"PICP": None, "MPIW": None}, "test": {"PICP": None, "MPIW": None}, "error": str(e)}

all_results = Parallel(n_jobs=-1, prefer="threads")(
    delayed(_run_sentinel_gamma)(gamma, C_VALUE) for gamma in GAMMA_VALUES
)
all_results = sorted(all_results, key=lambda r: r["params"]["gamma"])

[RUN 1/31]
Testing Gamma = 3.0517578125e-05 (2^-15)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=3.0517578125e-05
Training lower quantile (0.025) model...

Done in 28.29s
Training upper quantile (0.975) model...

Done in 20.53s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=3.0517578125e-05.png
Results for C=64_gamma=3.0517578125e-05:
{
    "params": {
        "C": 64,
        "gamma": 3.0517578125e-05,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.8905109489051095,
        "MPIW": 42.198326431248006
    },
    "test": {
        "PICP": 0.9562043795620438,
        "MPIW": 42.198136574413326
    }
}

[RUN 2/31]
Testing Gamma = 6.103515625e-05 (2^-14)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=6.103515625e-05
Training lower quantile (0.025) model...

Done in 24.47s
Training upper quantile (0.975) model...

Done in 21.38s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=6.103515625e-05.png
Results for C=64_gamma=6.103515625e-05:
{
    "params": {
        "C": 64,
        "gamma": 6.103515625e-05,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.8905109489051095,
        "MPIW": 42.196653635357585
    },
    "test": {
        "PICP": 0.9562043795620438,
        "MPIW": 42.19627392232664
    }
}

[RUN 3/31]
Testing Gamma = 0.0001220703125 (2^-13)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=0.0001220703125
Training lower quantile (0.025) model...

Done in 24.28s
Training upper quantile (0.975) model...

Done in 20.10s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=0.0001220703125.png
Results for C=64_gamma=0.0001220703125:
{
    "params": {
        "C": 64,
        "gamma": 0.0001220703125,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.8905109489051095,
        "MPIW": 42.193306124500296
    },
    "test": {
        "PICP": 0.9562043795620438,
        "MPIW": 42.19254670346945
    }
}

[RUN 4/31]
Testing Gamma = 0.000244140625 (2^-12)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=0.000244140625
Training lower quantile (0.025) model...

Done in 23.31s
Training upper quantile (0.975) model...

Done in 19.26s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=0.000244140625.png
Results for C=64_gamma=0.000244140625:
{
    "params": {
        "C": 64,
        "gamma": 0.000244140625,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.8905109489051095,
        "MPIW": 42.186613020749434
    },
    "test": {
        "PICP": 0.9562043795620438,
        "MPIW": 42.18509419626314
    }
}

[RUN 5/31]
Testing Gamma = 0.00048828125 (2^-11)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=0.00048828125
Training lower quantile (0.025) model...

Done in 24.25s
Training upper quantile (0.975) model...

Done in 19.33s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=0.00048828125.png
Results for C=64_gamma=0.00048828125:
{
    "params": {
        "C": 64,
        "gamma": 0.00048828125,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.8905109489051095,
        "MPIW": 42.1732275188307
    },
    "test": {
        "PICP": 0.9562043795620438,
        "MPIW": 42.17018995541457
    }
}

[RUN 6/31]
Testing Gamma = 0.0009765625 (2^-10)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=0.0009765625
Training lower quantile (0.025) model...

Done in 26.53s
Training upper quantile (0.975) model...

Done in 20.72s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=0.0009765625.png
Results for C=64_gamma=0.0009765625:
{
    "params": {
        "C": 64,
        "gamma": 0.0009765625,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.8905109489051095,
        "MPIW": 42.08677477050294
    },
    "test": {
        "PICP": 0.9562043795620438,
        "MPIW": 42.081203129405225
    }
}

[RUN 7/31]
Testing Gamma = 0.001953125 (2^-9)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=0.001953125
Training lower quantile (0.025) model...

Done in 27.92s
Training upper quantile (0.975) model...

Done in 21.49s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=0.001953125.png
Results for C=64_gamma=0.001953125:
{
    "params": {
        "C": 64,
        "gamma": 0.001953125,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.8905109489051095,
        "MPIW": 42.022182319048135
    },
    "test": {
        "PICP": 0.9562043795620438,
        "MPIW": 42.01282427895715
    }
}

[RUN 8/31]
Testing Gamma = 0.00390625 (2^-8)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=0.00390625
Training lower quantile (0.025) model...

Done in 27.24s
Training upper quantile (0.975) model...

Done in 20.23s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=0.00390625.png
Results for C=64_gamma=0.00390625:
{
    "params": {
        "C": 64,
        "gamma": 0.00390625,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.8905109489051095,
        "MPIW": 41.98904911045959
    },
    "test": {
        "PICP": 0.9562043795620438,
        "MPIW": 41.975730801056386
    }
}

[RUN 9/31]
Testing Gamma = 0.0078125 (2^-7)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=0.0078125
Training lower quantile (0.025) model...

Done in 26.16s
Training upper quantile (0.975) model...

Done in 17.17s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=0.0078125.png
Results for C=64_gamma=0.0078125:
{
    "params": {
        "C": 64,
        "gamma": 0.0078125,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.8832116788321168,
        "MPIW": 41.88923561089912
    },
    "test": {
        "PICP": 0.9562043795620438,
        "MPIW": 41.8694144726557
    }
}

[RUN 10/31]
Testing Gamma = 0.015625 (2^-6)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=0.015625
Training lower quantile (0.025) model...

Done in 26.27s
Training upper quantile (0.975) model...

Done in 18.41s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=0.015625.png
Results for C=64_gamma=0.015625:
{
    "params": {
        "C": 64,
        "gamma": 0.015625,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.8832116788321168,
        "MPIW": 41.61891370200807
    },
    "test": {
        "PICP": 0.9562043795620438,
        "MPIW": 41.59994979608963
    }
}

[RUN 11/31]
Testing Gamma = 0.03125 (2^-5)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=0.03125
Training lower quantile (0.025) model...

Done in 24.44s
Training upper quantile (0.975) model...

Done in 21.50s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=0.03125.png
Results for C=64_gamma=0.03125:
{
    "params": {
        "C": 64,
        "gamma": 0.03125,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.8832116788321168,
        "MPIW": 40.99659766795501
    },
    "test": {
        "PICP": 0.9562043795620438,
        "MPIW": 41.000171403958575
    }
}

[RUN 12/31]
Testing Gamma = 0.0625 (2^-4)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=0.0625
Training lower quantile (0.025) model...

Done in 27.51s
Training upper quantile (0.975) model...

Done in 19.38s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=0.0625.png
Results for C=64_gamma=0.0625:
{
    "params": {
        "C": 64,
        "gamma": 0.0625,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.8832116788321168,
        "MPIW": 40.57248581446881
    },
    "test": {
        "PICP": 0.9635036496350365,
        "MPIW": 40.595741358522744
    }
}

[RUN 13/31]
Testing Gamma = 0.125 (2^-3)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=0.125
Training lower quantile (0.025) model...

Done in 23.36s
Training upper quantile (0.975) model...

Done in 17.38s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=0.125.png
Results for C=64_gamma=0.125:
{
    "params": {
        "C": 64,
        "gamma": 0.125,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.8832116788321168,
        "MPIW": 40.37988598356607
    },
    "test": {
        "PICP": 0.9635036496350365,
        "MPIW": 40.404443286207645
    }
}

[RUN 14/31]
Testing Gamma = 0.25 (2^-2)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=0.25
Training lower quantile (0.025) model...

Done in 23.20s
Training upper quantile (0.975) model...

Done in 19.26s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=0.25.png
Results for C=64_gamma=0.25:
{
    "params": {
        "C": 64,
        "gamma": 0.25,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.9051094890510949,
        "MPIW": 38.82689957212828
    },
    "test": {
        "PICP": 0.9635036496350365,
        "MPIW": 38.913592899863104
    }
}

[RUN 15/31]
Testing Gamma = 0.5 (2^-1)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=0.5
Training lower quantile (0.025) model...

Done in 21.79s
Training upper quantile (0.975) model...

Done in 19.85s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=0.5.png
Results for C=64_gamma=0.5:
{
    "params": {
        "C": 64,
        "gamma": 0.5,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.8978102189781022,
        "MPIW": 37.83248303442167
    },
    "test": {
        "PICP": 0.9562043795620438,
        "MPIW": 37.75421016110096
    }
}

[RUN 16/31]
Testing Gamma = 1 (2^0)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=1
Training lower quantile (0.025) model...

Done in 22.04s
Training upper quantile (0.975) model...

Done in 18.27s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=1.png
Results for C=64_gamma=1:
{
    "params": {
        "C": 64,
        "gamma": 1,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.9051094890510949,
        "MPIW": 37.33006564169088
    },
    "test": {
        "PICP": 0.9635036496350365,
        "MPIW": 37.16415079362586
    }
}

[RUN 17/31]
Testing Gamma = 2 (2^1)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=2
Training lower quantile (0.025) model...

Done in 23.27s
Training upper quantile (0.975) model...

Done in 18.32s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=2.png
Results for C=64_gamma=2:
{
    "params": {
        "C": 64,
        "gamma": 2,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.8905109489051095,
        "MPIW": 37.00726114452016
    },
    "test": {
        "PICP": 0.9416058394160584,
        "MPIW": 36.66185685325858
    }
}

[RUN 18/31]
Testing Gamma = 4 (2^2)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=4
Training lower quantile (0.025) model...

Done in 21.19s
Training upper quantile (0.975) model...

Done in 16.15s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=4.png
Results for C=64_gamma=4:
{
    "params": {
        "C": 64,
        "gamma": 4,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.8978102189781022,
        "MPIW": 37.068764639420806
    },
    "test": {
        "PICP": 0.948905109489051,
        "MPIW": 36.53999847717253
    }
}

[RUN 19/31]
Testing Gamma = 8 (2^3)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=8
Training lower quantile (0.025) model...

Done in 21.03s
Training upper quantile (0.975) model...

Done in 17.97s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=8.png
Results for C=64_gamma=8:
{
    "params": {
        "C": 64,
        "gamma": 8,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.8759124087591241,
        "MPIW": 35.608678932647784
    },
    "test": {
        "PICP": 0.948905109489051,
        "MPIW": 35.03922540263502
    }
}

[RUN 20/31]
Testing Gamma = 16 (2^4)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=16
Training lower quantile (0.025) model...

Done in 19.85s
Training upper quantile (0.975) model...

Done in 18.04s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=16.png
Results for C=64_gamma=16:
{
    "params": {
        "C": 64,
        "gamma": 16,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.8905109489051095,
        "MPIW": 35.17148215671303
    },
    "test": {
        "PICP": 0.948905109489051,
        "MPIW": 34.603669265481344
    }
}

[RUN 21/31]
Testing Gamma = 32 (2^5)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=32
Training lower quantile (0.025) model...

Done in 18.02s
Training upper quantile (0.975) model...

Done in 16.98s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=32.png
Results for C=64_gamma=32:
{
    "params": {
        "C": 64,
        "gamma": 32,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.8905109489051095,
        "MPIW": 34.60642771475907
    },
    "test": {
        "PICP": 0.9416058394160584,
        "MPIW": 33.679429246647075
    }
}

[RUN 22/31]
Testing Gamma = 64 (2^6)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=64
Training lower quantile (0.025) model...

Done in 17.02s
Training upper quantile (0.975) model...

Done in 14.06s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=64.png
Results for C=64_gamma=64:
{
    "params": {
        "C": 64,
        "gamma": 64,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.8613138686131386,
        "MPIW": 33.60075885351858
    },
    "test": {
        "PICP": 0.9124087591240876,
        "MPIW": 32.78253296544232
    }
}

[RUN 23/31]
Testing Gamma = 128 (2^7)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=128
Training lower quantile (0.025) model...

Done in 16.05s
Training upper quantile (0.975) model...

Done in 15.14s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=128.png
Results for C=64_gamma=128:
{
    "params": {
        "C": 64,
        "gamma": 128,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.8248175182481752,
        "MPIW": 31.92676955004655
    },
    "test": {
        "PICP": 0.8686131386861314,
        "MPIW": 30.966207511469758
    }
}

[RUN 24/31]
Testing Gamma = 256 (2^8)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=256
Training lower quantile (0.025) model...

Done in 13.06s
Training upper quantile (0.975) model...

Done in 12.07s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=256.png
Results for C=64_gamma=256:
{
    "params": {
        "C": 64,
        "gamma": 256,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.8029197080291971,
        "MPIW": 29.180326345888833
    },
    "test": {
        "PICP": 0.8321167883211679,
        "MPIW": 28.453161839605176
    }
}

[RUN 25/31]
Testing Gamma = 512 (2^9)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=512
Training lower quantile (0.025) model...

Done in 11.06s
Training upper quantile (0.975) model...

Done in 11.09s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=512.png
Results for C=64_gamma=512:
{
    "params": {
        "C": 64,
        "gamma": 512,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.7299270072992701,
        "MPIW": 26.150881027998174
    },
    "test": {
        "PICP": 0.7518248175182481,
        "MPIW": 25.710653029077786
    }
}

[RUN 26/31]
Testing Gamma = 1024 (2^10)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=1024
Training lower quantile (0.025) model...

Done in 10.01s
Training upper quantile (0.975) model...

Done in 10.06s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=1024.png
Results for C=64_gamma=1024:
{
    "params": {
        "C": 64,
        "gamma": 1024,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.6496350364963503,
        "MPIW": 22.91021097861077
    },
    "test": {
        "PICP": 0.6423357664233577,
        "MPIW": 21.897297693636283
    }
}

[RUN 27/31]
Testing Gamma = 2048 (2^11)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=2048
Training lower quantile (0.025) model...

Done in 11.04s
Training upper quantile (0.975) model...

Done in 10.12s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=2048.png
Results for C=64_gamma=2048:
{
    "params": {
        "C": 64,
        "gamma": 2048,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.5766423357664233,
        "MPIW": 20.010045376665868
    },
    "test": {
        "PICP": 0.5182481751824818,
        "MPIW": 17.719714957172013
    }
}

[RUN 28/31]
Testing Gamma = 4096 (2^12)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=4096
Training lower quantile (0.025) model...

Done in 10.50s
Training upper quantile (0.975) model...

Done in 10.21s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=4096.png
Results for C=64_gamma=4096:
{
    "params": {
        "C": 64,
        "gamma": 4096,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.48905109489051096,
        "MPIW": 17.26083237495792
    },
    "test": {
        "PICP": 0.43795620437956206,
        "MPIW": 14.513890413216458
    }
}

[RUN 29/31]
Testing Gamma = 8192 (2^13)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=8192
Training lower quantile (0.025) model...

Done in 11.30s
Training upper quantile (0.975) model...

Done in 9.82s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=8192.png
Results for C=64_gamma=8192:
{
    "params": {
        "C": 64,
        "gamma": 8192,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.40875912408759124,
        "MPIW": 14.582229451742288
    },
    "test": {
        "PICP": 0.36496350364963503,
        "MPIW": 11.784971185982586
    }
}

[RUN 30/31]
Testing Gamma = 16384 (2^14)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=16384
Training lower quantile (0.025) model...

Done in 12.25s
Training upper quantile (0.975) model...

Done in 10.74s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=16384.png
Results for C=64_gamma=16384:
{
    "params": {
        "C": 64,
        "gamma": 16384,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.291970802919708,
        "MPIW": 11.117035382039923
    },
    "test": {
        "PICP": 0.2846715328467153,
        "MPIW": 8.9753090190378
    }
}

[RUN 31/31]
Testing Gamma = 32768 (2^15)

--- Running Quantile SVR for Sentinel-1 ---
Params: C=64_gamma=32768
Training lower quantile (0.025) model...

Done in 13.85s
Training upper quantile (0.975) model...

Done in 11.59s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\Sentinel-1_C=64_gamma=32768.png
Results for C=64_gamma=32768:
{
    "params": {
        "C": 64,
        "gamma": 32768,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.1678832116788321,
        "MPIW": 7.524342583013413
    },
    "test": {
        "PICP": 0.18248175182481752,
        "MPIW": 5.960930853378389
    }
}

In [8]:
results_df = pd.json_normalize(all_results)
results_df.columns = results_df.columns.str.replace('params.', 'param_')

try:
    # Calculate the exponent (e.g., 11 from 2048)
    gamma_exponents = np.log2(results_df['param_gamma']).astype(int)
    # Create the new string column (e.g., "2^11")
    results_df['param_gamma_str'] = '2^' + gamma_exponents.astype(str)
except Exception as e:
    print(f"Could not create 'param_gamma_str': {e}")
    results_df['param_gamma_str'] = results_df['param_gamma'] # Fallback
# --- END NEW CODE ---

# Save the full summary to a CSV
summary_filename = sentinel_exp.results_path / f"tuning_summary_C={C_VALUE}.csv"
results_df.to_csv(summary_filename, index=False)
print(f"\nFull tuning summary saved to:\n{summary_filename}")

# --- Analysis ---
acceptable_coverage_df = results_df[
    (results_df['test.PICP'] > 0.90) & (results_df['test.PICP'] <= 0.97)
].copy()

if not acceptable_coverage_df.empty:
    acceptable_coverage_df = acceptable_coverage_df.sort_values(by="test.MPIW", ascending=True)
    print("\n--- Top Models with 90-97% Test PICP (sorted by width) ---")
    print(acceptable_coverage_df[['param_gamma_str', 'test.PICP', 'test.MPIW']].head())
else:
    print("\nNo models achieved acceptable test PICP (90-97%).")

print("\n--- Top Models (sorted by Test PICP) ---")
print(results_df.sort_values(by="test.PICP", ascending=False)[['param_gamma_str', 'test.PICP', 'test.MPIW']].head(5))

Full tuning summary saved to:
results_qsvr\qsvr_pi_estimation_uncensored\tuning_summary_C=64.csv

--- Top Models with 90-97% Test PICP (sorted by width) ---
   param_gamma_str  test.PICP  test.MPIW
21             2^6   0.912409  32.782533
20             2^5   0.941606  33.679429
19             2^4   0.948905  34.603669
18             2^3   0.948905  35.039225
17             2^2   0.948905  36.539998

--- Top Models (sorted by Test PICP) ---
   param_gamma_str  test.PICP  test.MPIW
11            2^-4   0.963504  40.595741
13            2^-2   0.963504  38.913593
12            2^-3   0.963504  40.404443
15             2^0   0.963504  37.164151
3            2^-12   0.956204  42.185094

In [9]:
results_df.sort_values(by="test.PICP", ascending=False)[['param_gamma_str', 'test.PICP', 'test.MPIW']]

   param_gamma_str  test.PICP  test.MPIW
11            2^-4   0.963504  40.595741
13            2^-2   0.963504  38.913593
12            2^-3   0.963504  40.404443
15             2^0   0.963504  37.164151
3            2^-12   0.956204  42.185094
1            2^-14   0.956204  42.196274
0            2^-15   0.956204  42.198137
6             2^-9   0.956204  42.012824
5            2^-10   0.956204  42.081203
4            2^-11   0.956204  42.170190
7             2^-8   0.956204  41.975731
10            2^-5   0.956204  41.000171
9             2^-6   0.956204  41.599950
8             2^-7   0.956204  41.869414
2            2^-13   0.956204  42.192547
14            2^-1   0.956204  37.754210
17             2^2   0.948905  36.539998
18             2^3   0.948905  35.039225
19             2^4   0.948905  34.603669
16             2^1   0.941606  36.661857
20             2^5   0.941606  33.679429
21             2^6   0.912409  32.782533
22             2^7   0.868613  30.966208
23             2^8   0.832117  28.453162
24             2^9   0.751825  25.710653
25            2^10   0.642336  21.897298
26            2^11   0.518248  17.719715
27            2^12   0.437956  14.513890
28            2^13   0.364964  11.784971
29            2^14   0.284672   8.975309
30            2^15   0.182482   5.960931

## EOS

In [10]:
def _run_eos_gamma(gamma, C_VALUE):
    exp = QuantileSVRExperiment(
        X=X_eos,
        y=y_eos,
        satellite="EOS-04",
        print_stats=False,
        type="uncensored"
    )
    try:
        results = exp.run_experiment(C_value=C_VALUE, gamma=gamma)
        print(f"EOS-04 Gamma={gamma:.6f} done — PICP={results['test']['PICP']:.4f}")
        return results
    except Exception as e:
        print(f"ERROR Gamma={gamma}: {e}")
        return {"params": {"C": C_VALUE, "gamma": gamma}, "val": {"PICP": None, "MPIW": None}, "test": {"PICP": None, "MPIW": None}, "error": str(e)}

all_results = Parallel(n_jobs=-1, prefer="threads")(
    delayed(_run_eos_gamma)(gamma, C_VALUE) for gamma in GAMMA_VALUES
)
all_results = sorted(all_results, key=lambda r: r["params"]["gamma"])

[RUN 1/31]
Testing Gamma = 3.0517578125e-05 (2^-15)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=3.0517578125e-05
Training lower quantile (0.025) model...

Done in 50.83s
Training upper quantile (0.975) model...

Done in 40.80s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=3.0517578125e-05.png
Results for C=64_gamma=3.0517578125e-05:
{
    "params": {
        "C": 64,
        "gamma": 3.0517578125e-05,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.9775280898876404,
        "MPIW": 41.99333015112254
    },
    "test": {
        "PICP": 0.9608938547486033,
        "MPIW": 41.9935533665447
    }
}

[RUN 2/31]
Testing Gamma = 6.103515625e-05 (2^-14)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=6.103515625e-05
Training lower quantile (0.025) model...

Done in 53.22s
Training upper quantile (0.975) model...

Done in 40.23s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=6.103515625e-05.png
Results for C=64_gamma=6.103515625e-05:
{
    "params": {
        "C": 64,
        "gamma": 6.103515625e-05,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.9775280898876404,
        "MPIW": 41.98665967096754
    },
    "test": {
        "PICP": 0.9608938547486033,
        "MPIW": 41.98710609802213
    }
}

[RUN 3/31]
Testing Gamma = 0.0001220703125 (2^-13)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=0.0001220703125
Training lower quantile (0.025) model...

Done in 50.49s
Training upper quantile (0.975) model...

Done in 40.22s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=0.0001220703125.png
Results for C=64_gamma=0.0001220703125:
{
    "params": {
        "C": 64,
        "gamma": 0.0001220703125,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.9775280898876404,
        "MPIW": 41.97332022663838
    },
    "test": {
        "PICP": 0.9608938547486033,
        "MPIW": 41.974213048551874
    }
}

[RUN 4/31]
Testing Gamma = 0.000244140625 (2^-12)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=0.000244140625
Training lower quantile (0.025) model...

Done in 52.93s
Training upper quantile (0.975) model...

Done in 40.63s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=0.000244140625.png
Results for C=64_gamma=0.000244140625:
{
    "params": {
        "C": 64,
        "gamma": 0.000244140625,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.9775280898876404,
        "MPIW": 41.94664049774857
    },
    "test": {
        "PICP": 0.9608938547486033,
        "MPIW": 41.94842602667624
    }
}

[RUN 5/31]
Testing Gamma = 0.00048828125 (2^-11)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=0.00048828125
Training lower quantile (0.025) model...

Done in 50.77s
Training upper quantile (0.975) model...

Done in 44.66s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=0.00048828125.png
Results for C=64_gamma=0.00048828125:
{
    "params": {
        "C": 64,
        "gamma": 0.00048828125,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.9775280898876404,
        "MPIW": 41.89328504491112
    },
    "test": {
        "PICP": 0.9608938547486033,
        "MPIW": 41.89685563887024
    }
}

[RUN 6/31]
Testing Gamma = 0.0009765625 (2^-10)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=0.0009765625
Training lower quantile (0.025) model...

Done in 52.50s
Training upper quantile (0.975) model...

Done in 41.86s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=0.0009765625.png
Results for C=64_gamma=0.0009765625:
{
    "params": {
        "C": 64,
        "gamma": 0.0009765625,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.9775280898876404,
        "MPIW": 41.85281271700268
    },
    "test": {
        "PICP": 0.9608938547486033,
        "MPIW": 41.85949251581473
    }
}

[RUN 7/31]
Testing Gamma = 0.001953125 (2^-9)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=0.001953125
Training lower quantile (0.025) model...

Done in 50.58s
Training upper quantile (0.975) model...

Done in 40.27s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=0.001953125.png
Results for C=64_gamma=0.001953125:
{
    "params": {
        "C": 64,
        "gamma": 0.001953125,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.9775280898876404,
        "MPIW": 41.93093997053137
    },
    "test": {
        "PICP": 0.9608938547486033,
        "MPIW": 41.94657518754628
    }
}

[RUN 8/31]
Testing Gamma = 0.00390625 (2^-8)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=0.00390625
Training lower quantile (0.025) model...

Done in 52.93s
Training upper quantile (0.975) model...

Done in 38.05s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=0.00390625.png
Results for C=64_gamma=0.00390625:
{
    "params": {
        "C": 64,
        "gamma": 0.00390625,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.9775280898876404,
        "MPIW": 41.696317385890765
    },
    "test": {
        "PICP": 0.9608938547486033,
        "MPIW": 41.724160138346086
    }
}

[RUN 9/31]
Testing Gamma = 0.0078125 (2^-7)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=0.0078125
Training lower quantile (0.025) model...

Done in 53.43s
Training upper quantile (0.975) model...

Done in 51.02s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=0.0078125.png
Results for C=64_gamma=0.0078125:
{
    "params": {
        "C": 64,
        "gamma": 0.0078125,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.9775280898876404,
        "MPIW": 41.4001814714981
    },
    "test": {
        "PICP": 0.9664804469273743,
        "MPIW": 41.4545699741724
    }
}

[RUN 10/31]
Testing Gamma = 0.015625 (2^-6)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=0.015625
Training lower quantile (0.025) model...

Done in 52.90s
Training upper quantile (0.975) model...

Done in 42.38s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=0.015625.png
Results for C=64_gamma=0.015625:
{
    "params": {
        "C": 64,
        "gamma": 0.015625,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.9831460674157303,
        "MPIW": 40.71050856560156
    },
    "test": {
        "PICP": 0.9720670391061452,
        "MPIW": 40.82534810111594
    }
}

[RUN 11/31]
Testing Gamma = 0.03125 (2^-5)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=0.03125
Training lower quantile (0.025) model...

Done in 54.88s
Training upper quantile (0.975) model...

Done in 50.17s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=0.03125.png
Results for C=64_gamma=0.03125:
{
    "params": {
        "C": 64,
        "gamma": 0.03125,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.9831460674157303,
        "MPIW": 40.02999250666413
    },
    "test": {
        "PICP": 0.9720670391061452,
        "MPIW": 40.24864178604936
    }
}

[RUN 12/31]
Testing Gamma = 0.0625 (2^-4)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=0.0625
Training lower quantile (0.025) model...

Done in 52.50s
Training upper quantile (0.975) model...

Done in 42.21s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=0.0625.png
Results for C=64_gamma=0.0625:
{
    "params": {
        "C": 64,
        "gamma": 0.0625,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.9775280898876404,
        "MPIW": 39.20011493221919
    },
    "test": {
        "PICP": 0.9720670391061452,
        "MPIW": 39.557997183764115
    }
}

[RUN 13/31]
Testing Gamma = 0.125 (2^-3)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=0.125
Training lower quantile (0.025) model...

Done in 50.60s
Training upper quantile (0.975) model...

Done in 42.19s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=0.125.png
Results for C=64_gamma=0.125:
{
    "params": {
        "C": 64,
        "gamma": 0.125,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.9775280898876404,
        "MPIW": 38.42352460507432
    },
    "test": {
        "PICP": 0.9664804469273743,
        "MPIW": 38.9052762323878
    }
}

[RUN 14/31]
Testing Gamma = 0.25 (2^-2)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=0.25
Training lower quantile (0.025) model...

Done in 46.37s
Training upper quantile (0.975) model...

Done in 42.15s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=0.25.png
Results for C=64_gamma=0.25:
{
    "params": {
        "C": 64,
        "gamma": 0.25,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.9775280898876404,
        "MPIW": 37.891636228966185
    },
    "test": {
        "PICP": 0.9608938547486033,
        "MPIW": 38.467873184858995
    }
}

[RUN 15/31]
Testing Gamma = 0.5 (2^-1)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=0.5
Training lower quantile (0.025) model...

Done in 50.18s
Training upper quantile (0.975) model...

Done in 35.63s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=0.5.png
Results for C=64_gamma=0.5:
{
    "params": {
        "C": 64,
        "gamma": 0.5,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.9831460674157303,
        "MPIW": 37.8552177468389
    },
    "test": {
        "PICP": 0.9608938547486033,
        "MPIW": 38.349804605548606
    }
}

[RUN 16/31]
Testing Gamma = 1 (2^0)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=1
Training lower quantile (0.025) model...

Done in 50.35s
Training upper quantile (0.975) model...

Done in 40.47s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=1.png
Results for C=64_gamma=1:
{
    "params": {
        "C": 64,
        "gamma": 1,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.9775280898876404,
        "MPIW": 36.62904892911791
    },
    "test": {
        "PICP": 0.9497206703910615,
        "MPIW": 36.9931465134315
    }
}

[RUN 17/31]
Testing Gamma = 2 (2^1)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=2
Training lower quantile (0.025) model...

Done in 44.33s
Training upper quantile (0.975) model...

Done in 46.29s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=2.png
Results for C=64_gamma=2:
{
    "params": {
        "C": 64,
        "gamma": 2,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.9775280898876404,
        "MPIW": 36.767527884926054
    },
    "test": {
        "PICP": 0.9553072625698324,
        "MPIW": 37.02368805216316
    }
}

[RUN 18/31]
Testing Gamma = 4 (2^2)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=4
Training lower quantile (0.025) model...

Done in 42.39s
Training upper quantile (0.975) model...

Done in 44.36s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=4.png
Results for C=64_gamma=4:
{
    "params": {
        "C": 64,
        "gamma": 4,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.9775280898876404,
        "MPIW": 36.23016084987025
    },
    "test": {
        "PICP": 0.9441340782122905,
        "MPIW": 36.44881684563808
    }
}

[RUN 19/31]
Testing Gamma = 8 (2^3)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=8
Training lower quantile (0.025) model...

Done in 42.12s
Training upper quantile (0.975) model...

Done in 35.76s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=8.png
Results for C=64_gamma=8:
{
    "params": {
        "C": 64,
        "gamma": 8,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.9662921348314607,
        "MPIW": 36.684056380929405
    },
    "test": {
        "PICP": 0.9329608938547486,
        "MPIW": 36.90953399712493
    }
}

[RUN 20/31]
Testing Gamma = 16 (2^4)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=16
Training lower quantile (0.025) model...

Done in 40.08s
Training upper quantile (0.975) model...

Done in 36.36s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=16.png
Results for C=64_gamma=16:
{
    "params": {
        "C": 64,
        "gamma": 16,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.9606741573033708,
        "MPIW": 36.568059725626206
    },
    "test": {
        "PICP": 0.9329608938547486,
        "MPIW": 36.89303510612542
    }
}

[RUN 21/31]
Testing Gamma = 32 (2^5)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=32
Training lower quantile (0.025) model...

Done in 38.17s
Training upper quantile (0.975) model...

Done in 29.78s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=32.png
Results for C=64_gamma=32:
{
    "params": {
        "C": 64,
        "gamma": 32,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.9606741573033708,
        "MPIW": 35.80467002796139
    },
    "test": {
        "PICP": 0.9162011173184358,
        "MPIW": 35.95743097200735
    }
}

[RUN 22/31]
Testing Gamma = 64 (2^6)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=64
Training lower quantile (0.025) model...

Done in 33.82s
Training upper quantile (0.975) model...

Done in 29.68s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=64.png
Results for C=64_gamma=64:
{
    "params": {
        "C": 64,
        "gamma": 64,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.9550561797752809,
        "MPIW": 34.98734952824786
    },
    "test": {
        "PICP": 0.8715083798882681,
        "MPIW": 34.165340155581994
    }
}

[RUN 23/31]
Testing Gamma = 128 (2^7)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=128
Training lower quantile (0.025) model...

Done in 31.51s
Training upper quantile (0.975) model...

Done in 25.44s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=128.png
Results for C=64_gamma=128:
{
    "params": {
        "C": 64,
        "gamma": 128,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.9213483146067416,
        "MPIW": 33.635754633248
    },
    "test": {
        "PICP": 0.8435754189944135,
        "MPIW": 33.20912972052305
    }
}

[RUN 24/31]
Testing Gamma = 256 (2^8)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=256
Training lower quantile (0.025) model...

Done in 27.37s
Training upper quantile (0.975) model...

Done in 25.41s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=256.png
Results for C=64_gamma=256:
{
    "params": {
        "C": 64,
        "gamma": 256,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.8876404494382022,
        "MPIW": 31.263863517563315
    },
    "test": {
        "PICP": 0.8044692737430168,
        "MPIW": 30.655098160099005
    }
}

[RUN 25/31]
Testing Gamma = 512 (2^9)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=512
Training lower quantile (0.025) model...

Done in 25.17s
Training upper quantile (0.975) model...

Done in 23.16s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=512.png
Results for C=64_gamma=512:
{
    "params": {
        "C": 64,
        "gamma": 512,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.8089887640449438,
        "MPIW": 28.17932050445007
    },
    "test": {
        "PICP": 0.7430167597765364,
        "MPIW": 27.69042668229402
    }
}

[RUN 26/31]
Testing Gamma = 1024 (2^10)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=1024
Training lower quantile (0.025) model...

Done in 23.31s
Training upper quantile (0.975) model...

Done in 21.17s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=1024.png
Results for C=64_gamma=1024:
{
    "params": {
        "C": 64,
        "gamma": 1024,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.6966292134831461,
        "MPIW": 24.41511424010662
    },
    "test": {
        "PICP": 0.6536312849162011,
        "MPIW": 24.101938512899405
    }
}

[RUN 27/31]
Testing Gamma = 2048 (2^11)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=2048
Training lower quantile (0.025) model...

Done in 23.57s
Training upper quantile (0.975) model...

Done in 21.33s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=2048.png
Results for C=64_gamma=2048:
{
    "params": {
        "C": 64,
        "gamma": 2048,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.6179775280898876,
        "MPIW": 19.930209837988336
    },
    "test": {
        "PICP": 0.6201117318435754,
        "MPIW": 20.41428155392016
    }
}

[RUN 28/31]
Testing Gamma = 4096 (2^12)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=4096
Training lower quantile (0.025) model...

Done in 23.71s
Training upper quantile (0.975) model...

Done in 19.76s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=4096.png
Results for C=64_gamma=4096:
{
    "params": {
        "C": 64,
        "gamma": 4096,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.5280898876404494,
        "MPIW": 15.534880444463882
    },
    "test": {
        "PICP": 0.4860335195530726,
        "MPIW": 16.30204816542952
    }
}

[RUN 29/31]
Testing Gamma = 8192 (2^13)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=8192
Training lower quantile (0.025) model...

Done in 22.98s
Training upper quantile (0.975) model...

Done in 20.09s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=8192.png
Results for C=64_gamma=8192:
{
    "params": {
        "C": 64,
        "gamma": 8192,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.43820224719101125,
        "MPIW": 12.42049609730711
    },
    "test": {
        "PICP": 0.3687150837988827,
        "MPIW": 12.198893301326875
    }
}

[RUN 30/31]
Testing Gamma = 16384 (2^14)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=16384
Training lower quantile (0.025) model...

Done in 30.03s
Training upper quantile (0.975) model...

Done in 22.95s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=16384.png
Results for C=64_gamma=16384:
{
    "params": {
        "C": 64,
        "gamma": 16384,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.2752808988764045,
        "MPIW": 9.127218271509896
    },
    "test": {
        "PICP": 0.22346368715083798,
        "MPIW": 8.678781094157703
    }
}

[RUN 31/31]
Testing Gamma = 32768 (2^15)

--- Running Quantile SVR for EOS-04 ---
Params: C=64_gamma=32768
Training lower quantile (0.025) model...

Done in 34.82s
Training upper quantile (0.975) model...

Done in 25.36s
Generating predictions...
Evaluating and plotting results...

Plot saved to results_qsvr\qsvr_pi_estimation_uncensored\plots\EOS-04_C=64_gamma=32768.png
Results for C=64_gamma=32768:
{
    "params": {
        "C": 64,
        "gamma": 32768,
        "q_lower": 0.025,
        "q_upper": 0.975
    },
    "val": {
        "PICP": 0.17415730337078653,
        "MPIW": 5.886499952117966
    },
    "test": {
        "PICP": 0.13966480446927373,
        "MPIW": 5.7691515709661925
    }
}

In [11]:
results_df = pd.json_normalize(all_results)
results_df.columns = results_df.columns.str.replace('params.', 'param_')

try:
    # Calculate the exponent (e.g., 11 from 2048)
    gamma_exponents = np.log2(results_df['param_gamma']).astype(int)
    # Create the new string column (e.g., "2^11")
    results_df['param_gamma_str'] = '2^' + gamma_exponents.astype(str)
except Exception as e:
    print(f"Could not create 'param_gamma_str': {e}")
    results_df['param_gamma_str'] = results_df['param_gamma'] # Fallback
# --- END NEW CODE ---

# Save the full summary to a CSV
summary_filename = eos_exp.results_path / f"eos-04-tuning_summary_C={C_VALUE}.csv"
results_df.to_csv(summary_filename, index=False)
print(f"\nFull tuning summary saved to:\n{summary_filename}")

# --- Analysis ---
acceptable_coverage_df = results_df[
    (results_df['test.PICP'] > 0.90) & (results_df['test.PICP'] <= 0.97)
].copy()

if not acceptable_coverage_df.empty:
    acceptable_coverage_df = acceptable_coverage_df.sort_values(by="test.MPIW", ascending=True)
    print("\n--- Top Models with 90-97% Test PICP (sorted by width) ---")
    print(acceptable_coverage_df[['param_gamma_str', 'test.PICP', 'test.MPIW']].head())
else:
    print("\nNo models achieved acceptable test PICP (90-97%).")

print("\n--- Top Models (sorted by Test PICP) ---")
results_df.sort_values(by="test.PICP", ascending=False)[['param_gamma_str', 'test.PICP', 'test.MPIW']].head(5)

Full tuning summary saved to:
results_qsvr\qsvr_pi_estimation_uncensored\eos-04-tuning_summary_C=64.csv

--- Top Models with 90-97% Test PICP (sorted by width) ---
   param_gamma_str  test.PICP  test.MPIW
20             2^5   0.916201  35.957431
17             2^2   0.944134  36.448817
19             2^4   0.932961  36.893035
18             2^3   0.932961  36.909534
15             2^0   0.949721  36.993147

--- Top Models (sorted by Test PICP) ---

   param_gamma_str  test.PICP  test.MPIW
11            2^-4   0.972067  39.557997
9             2^-6   0.972067  40.825348
10            2^-5   0.972067  40.248642
8             2^-7   0.966480  41.454570
12            2^-3   0.966480  38.905276

In [12]:
results_df.sort_values(by="test.PICP", ascending=False)[['param_gamma_str', 'test.PICP', 'test.MPIW']]

   param_gamma_str  test.PICP  test.MPIW
11            2^-4   0.972067  39.557997
9             2^-6   0.972067  40.825348
10            2^-5   0.972067  40.248642
8             2^-7   0.966480  41.454570
12            2^-3   0.966480  38.905276
1            2^-14   0.960894  41.987106
0            2^-15   0.960894  41.993553
6             2^-9   0.960894  41.946575
5            2^-10   0.960894  41.859493
4            2^-11   0.960894  41.896856
3            2^-12   0.960894  41.948426
2            2^-13   0.960894  41.974213
7             2^-8   0.960894  41.724160
13            2^-2   0.960894  38.467873
14            2^-1   0.960894  38.349805
16             2^1   0.955307  37.023688
15             2^0   0.949721  36.993147
17             2^2   0.944134  36.448817
18             2^3   0.932961  36.909534
19             2^4   0.932961  36.893035
20             2^5   0.916201  35.957431
21             2^6   0.871508  34.165340
22             2^7   0.843575  33.209130
23             2^8   0.804469  30.655098
24             2^9   0.743017  27.690427
25            2^10   0.653631  24.101939
26            2^11   0.620112  20.414282
27            2^12   0.486034  16.302048
28            2^13   0.368715  12.198893
29            2^14   0.223464   8.678781
30            2^15   0.139665   5.769152